### ISSUE TITLE
[6.8] Dynamic columns

### ISSUE THREAD

**Issue by Nks** [orchidsoftware/platform#1003]
Sometimes we have a lot of columns on the table list but we not needed to show it for all of the users and it will be good dynamically (without reload page and without saving this in the database) show or hide columns. 
Nice example: https://datatables.net/examples/api/show_hide.html
I think we can do something like this

**Comment by tabuna** [comment]
The `TD` class has `CanSee` trate and you can set visibility in advance depending on the role or perrmission:

```php
TD::set('show_column')->canSee(true);
or

TD::set('hidden_column')->canSee(false);
```

**Comment by Nks** [comment]
I mean do this without canSee, but with javascript only

**Comment by tabuna** [comment]
I think it is possible to add. In the form of a dropdown list next to the pagination table, where all column names and options for inclusion / hide would be listed.
I think it’s worth storing these values in the localstorage of the browser.

**Comment by tabuna** [comment]
A few more points that may be interesting are the default hiding on the server side. And also a ban on hiding some columns, so that the table does not appear empty.

**Comment by Nks** [comment]
Confirm. Can be done with server side operations.

**Comment by tabuna** [comment]
Why is it closed? Did you do it differently? (Session?)

**Comment by Nks** [comment]
I forgot that I already did something similar with the vue.js and store selected columns to the local storage. It's enough for me. But if we need save it to the user forever it can be done with setup modal screen where user can select which columns to hide and then on the tables we can get this information from cache store and use "canSee" as you mentioned before.

**Comment by tabuna** [comment]
I worked a little on this, it still has some problems, but I think we can support it natively.

![screencast-localhost_8000-2019 10 30-00_15_14](https://user-images.githubusercontent.com/5102591/68236959-3c0db300-0017-11ea-968c-d6bb9d0dc08d.gif)

**Comment by tabuna** [comment]
Could you help me find a suitable place to locate it?

![screenshot-localhost_8000-2019 11 07-11_46_25](https://user-images.githubusercontent.com/5102591/68373694-72048180-0154-11ea-9f1d-1b530761fe9d.png)

**Comment by PSalador** [comment]
Top, in the filters.

**Comment by tabuna** [comment]
I also suggest adding a new method that prevents the user from hiding the column:
```php
TD::set('email')->cannotHide()
```


@PSalador Can you give an example?

**Comment by Nks** [comment]
Maybe instead or "cannotHide()" method we can add "canHide()" and then developer can choose what to hide or show for already existing columns?

Also I suggest to have something like this:
```php
TD::set('email'),
TD::set('name')->canHide(),
TD::set('created_at')->canHide()->defaultVisible(),
TD::set('updated_at')->canHide()->defaultHidden(),
```

What do you think?

**Comment by tabuna** [comment]
I think we should decide whether by default it will be possible to hide them or not.

For example, by default, all are allowed to turn off:

```php
TD::set('id')->cantHide(), //The column cannot be hidden
TD::set('email'),
TD::set('name'),
TD::set('created_at')->defaultVisible(),
TD::set('updated_at')->defaultHidden(),
```

In theory, you should have much fewer columns that can be hidden, so this might make sense. What do you think of it?

-----

As for placement, we cannot place it on top. There is simply no place for this.

**Comment by tabuna** [comment]
Documented both methods.
