### ISSUE TITLE
Биндинг экземплара модели в метод query экрана

### ISSUE THREAD

**Issue by mavsan** [orchidsoftware/platform#1016]
Выскакивает исключение, если модель "мягко удалена":

Argument 1 passed to App\Orchid\Screens\Offers\OffersEditScreen::query() must be an instance of App\Offer, null given

Модель дожна быть "мягко удалена", т.е. иметь трейт `SoftDeletes` и, соответственно, поле `deleted_at` не должно быть `null`.

Метод query экрана (отрабатывает прекрасно, если модель не помечена, как удаленная):

`public function query(Offer $offer): array`

Кстати, про фильтры, я понимаю, что это другая штука, но чтобы не плодить issue. Чекбокс в фильтре выглядит вот так:

![image](https://user-images.githubusercontent.com/5114650/68537707-57304800-03b4-11ea-9ace-0f376627ac21.png)

**Comment by tabuna** [comment]
> Выскакивает исключение, если модель "мягко удалена":

Это не является проблемой, так работает биндинг. При выборке удалённых значений необходимо явно указывать `Offer::withTrashed()` или `Offer::onlyTrashed()`. Вы можете [определить свой биндинг, либо в модели, либо в роуте](https://laravel.com/docs/6.x/routing#explicit-binding), например:


```php
/**
 * Retrieve the model for a bound value.
 *
 * @param  mixed  $value
 * @return \Illuminate\Database\Eloquent\Model|null
 */
public function resolveRouteBinding($value)
{
    return $this->withTrashed()->findOrFail($value);
}
```

Или в роутинге:

```php
Route::bind('offer', function ($value) {
    return App\Offer::withTrashed()->findOrFail($value);
});
```

> Кстати, про фильтры, я понимаю, что это другая штука, но чтобы не плодить issue. Чекбокс в фильтре выглядит вот так:

Вы указали только `title` который всегда располагаться выше элемента формы, за пояснение отвечает `placeholder`, вы можете увидеть пример [тут](https://github.com/orchidsoftware/platform/blob/master/install-stubs/Orchid/Layouts/Examples/RowExample.php#L71-L75).


```php
CheckBox::make('trash')
    ->sendTrueOrFalse()
    ->title('Только удалённые кейсы')
     ->placeholder('Отобразить');
```


Не стесняйтесь задавать вопросы и отрывать это обращение снова.
