### ISSUE TITLE
Поле Upload

### ISSUE THREAD

**Issue by mavsan** [orchidsoftware/platform#1019]
Если пытаться загрузить файл большего размера, чем это позволяют настройки сервера, то ошибки ни какой не появится. Т.е. административная панель ни как не уведомляет об неудаче. Сервер возвращает код ошибки 415.

Если значение `maxFileSize` установить в 1, то файл (файл - 8Мб, максимально разрешенный размер на сервере - 2 Мб) в Dropzone появляется, но ни каких действий с сервером не происходит, т.е. ничего никуда не отсылается. 

В любом случае, может произойти что угодно, надо что-то выводить если вернулось что-то кроме 200.

Как выполнять валидацию загружаемых файлов, например, надо убедиться, что файлы не больше определенных размеров? Я сейчас делаю так - сохраняю все, потом читаю attachments, создаю их них объект `Symfony\Component\HttpFoundation\File\File`, потом создаю экземпляр валидатора, передаю туда правила и полученные экземпляры объекта и провожу валидацию, но, кажется мне, что это не совсем правильно.

Думал добавить в  Upload метод, например - validate, чтобы туда можно было передать стандартные правила валидации, а уже при сохранении - проверять (правила думал предавать вместе с файлом при загрузке), но это не совсем то, т.к. валидацию необходимо выполнять в любом случае и при создании/обновлении данных редактируемой модели.

Надеяться, что тот, кто загружает файл - умеет читать (и прочел инструкцию) и подготовил файл нужного размера/объема... даже не знаю.

**Comment by tabuna** [comment]
Очень интересные мысли, предлогаю попробовать реализовать следующие действия:

- Установить в `Dropzone` максимальный вес файла, равным upload_max_filesize/post_max_size (самое маленькое значение из них), по умолчанию.
- При попытке явного указания значения которое превышает `upload_max_filesize/post_max_size` выбрасывать исключение.
- Уведомлять пользователя тостем, при любом отличном от 200 ответе сервера (при загрузке)


По поводу валидации.

Загрузка и отображение поля независимые части, по сути мы имеем одну единственную точку входа, по этому установить ей правила можно только для всех загрузок (если это вообще нужно), предлогаю валидировать в [событии](https://orchid.software/ru/docs/attachments/#podpiska-na-zagruzku) и при ошибке информировать пользователя.

**Comment by tabuna** [comment]
Добавил класс для определния настроект PHP, для уведомления https://github.com/orchidsoftware/platform/commit/f8c9ba20a63e69e18419d5ca0fadf35c47a00dca

Но ещё не во всех местах существует оповещение об ошибки при загрузке, так как загрузка файлов может быть как в wysing  редакторах, так и в различных полях. Вы можете помочь мне проверить это?

**Comment by Leshkens** [comment]
Закину сюда тоже возможный баг с аплоадом:

![UDGuH7MIaF](https://user-images.githubusercontent.com/8939383/70712570-e14a3400-1d05-11ea-8e07-473550d5dcd8.gif)

При **обновлении** аттачей в модели все хорошо, но при **удалении модели** с аттачами, эти аттачи физически не удаляются, хотя все ссылки из базы (таблицы `attachements` и `attachmentable`) пропадают.

Поле upload:
```
Upload::make('product.images')
    ->title(__('Images'))
    ->storage('images')
    ->groups('products')
    ->value($this->product->attachment()->where('group', 'products')->get())
    ->help(__('...'))
    ->acceptedFiles('.jpg,.jpeg,.png'),
```

Метод boot модели:

```
public static function boot()
{
    parent::boot();

    self::deleting(function ($model) {
        /**
         * @var Product $model
         */
        $model->attachment()->delete();
    });
}
```

Orchid: 6.7.5
Laravel: 6.7.0
OC: Windows 10
PHP: 7.3.5

**Comment by Leshkens** [comment]
@tabuna Получается удалять файлы (физически) вот таким образом:

Метод boot модели:

```
public static function boot()
{
    parent::boot();

    self::deleting(function ($model) {
        /**
         * @var Product $model
         */
        $attach = $model->attachment();

        if ($attach->exists()) {
            $ids = $attach->get()->pluck('id');
            foreach ($ids as $id) {
                Attachment::find($id)->delete();
            }
        }
    });
}
```

То есть, если метод `delete()` вызвать прямо из объекта `Attachment`. 

Через трейт `Attachable` унаследованный метод `delete()` в объекте `Attachment` не срабатывает:
```
public static function boot()
{
    parent::boot();

    self::deleting(function ($model) {
        /**
         * @var Product $model
         */
        $model->attachment()->delete();
    });
}
```

Такого не должно быть? Или все правильно?

**Comment by tabuna** [comment]
@Leshkens Так и должно [быть](https://github.com/laravel/framework/issues/2536#issuecomment-26770667). Из вариантов, либо каскадное удаление на уровне БД, либо удаление по одной модели. Пример, что работает не очень оптимален, вам не обязательно заново загружать модель, достаточно будет:

```php
$model->attachment()->each(function (Attachment $attachment) {
    $attachment->delete();
});
```

**Comment by tabuna** [comment]
> Но ещё не во всех местах существует оповещение об ошибки при загрузке, так как загрузка файлов может быть как в wysing редакторах, так и в различных полях. Вы можете помочь мне проверить это?
Добавил оповещения во wysing редакторы и поля Picture/Cropper
