### ISSUE TITLE
Как загрузить один файл без использования attachements?

### ISSUE THREAD

**Issue by ivan-cc** [orchidsoftware/platform#1020]
Мне нужно к сущностям прикрепить по одной картинке. Думаю, что использование для этого Attachements - излишне. Как можно загрузить одну картинку и сохранить её адрес в нужном поле (например logo_url) модели?

**Comment by tabuna** [comment]
Вы можете воспользоваться другими полями, например, [Picture](https://orchid.software/ru/docs/field/#picture-field)  или [Cropper](https://orchid.software/ru/docs/field/#cropper-field), более подробно можно посмотреть [тут](https://orchid.software/ru/docs/quickstart-files/)

**Comment by ivan-cc** [comment]
Блин, да я пробовал ими, но поле указывал без названия модели. Тупил. 
Спасибо за быстрый ответ.
