### ISSUE TITLE
I can't set the id of the textarea

### ISSUE THREAD

**Issue by Hrache** [orchidsoftware/platform#1022]
How to add attribute to the field? I need to assign custom **id** to the **TextArea** field, but the available set and id methods ain't working.

**Comment by tabuna** [comment]
We define a unique identifier on our own in order to avoid problems when building forms. But you can redefine the field, and in it the principle of formation of this value:

```php
declare(strict_types=1);

namespace App;

class TextArea extends \Orchid\Screen\Fields\TextArea
{
    /**
     * @return string
     */
    public function getId(): string
    {
        return 'custom id';
    }
}

```

**Comment by tabuna** [comment]
Also in version `6.7.2` it is now allowed to specify them yourself

```php
TextArea::make('description')->set('id','custom-my-id');
```

Please note that in both cases, you will need to monitor their uniqueness yourself.
