### ISSUE TITLE
Is it possible to not use permissions?

### ISSUE THREAD

**Issue by Arcesilas** [orchidsoftware/platform#1023]
I'm considering using this package, but before I install it and face problems, I'd like to know if it's possible to not use the permissions system it provides?

I'm using another package with roles and abilities, I don't want to have another package that makes the same thing with methods name that may collide.

**Comment by tabuna** [comment]
Hi @Arcesilas, yes, you can use your own rules or even make the project public

To do this, disable the `middleware` check in the configuration (remove platform)

https://github.com/orchidsoftware/platform/blob/a495238ff3e54c69cac59574335879214d26ff72/config/platform.php#L32-L45

As for the user model, we can[ override methods](https://www.php.net/manual/ru/language.oop5.traits.php) if they conflict:
```php
trait A {
    public function smallTalk() {
        echo 'a';
    }
    public function bigTalk() {
        echo 'A';
    }
}

trait B {
    public function smallTalk() {
        echo 'b';
    }
    public function bigTalk() {
        echo 'B';
    }
}

class Talker {
    use A, B {
        B::smallTalk insteadof A;
        A::bigTalk insteadof B;
    }
}

class Aliased_Talker {
    use A, B {
        B::smallTalk insteadof A;
        A::bigTalk insteadof B;
        B::bigTalk as talk;
    }
}

```

In general, the package does not prohibit the use of other solutions, but will not help with them. For example, it will lose the ability to set permissions on the screen:

```php
use Orchid\Screen\Screen;

class Example extends Screen
{
    public $permission = 'myRules';
}
```

Instead, you have to do:

```php
use Orchid\Screen\Screen;

class Example extends Screen
{
    public function query() 
    {
       // your code 
       $user->yorMethodCheck('myRules') // Or any other rules
    }
}
```

Good luck.

**Comment by Arcesilas** [comment]
Thanks for your quick reply. I'll give it a chance!

BTW, I consider that permissions should be handled only by specialized packages. Packages that require permissions should only rely on Laravel Gate. Packages like Entrust, Laratrust, Bouncer configure the Gate. Any package requiring the use of permissions should only ask the Gate: `$user->can('access-admin')`.

Anyway, thanks again!

**Comment by tabuna** [comment]
The built-in rights system is not a replacement for the Gate, this is also indicated in the description.

I successfully combine both approaches in one project
