### ISSUE TITLE
removeMaskOnSubmit в фильтрах

### ISSUE THREAD

**Issue by Leshkens** [orchidsoftware/platform#1028]
Не работает удаление маски при применении фильтра:

![eiRHGQ8EEU](https://user-images.githubusercontent.com/8939383/70849732-653a2280-1ea4-11ea-9287-9df7f31abfe2.gif)

`removeMaskOnSubmit` конечно же стоит у поля.

**Comment by tabuna** [comment]
Пожалуйста проверьте версию [6.7.6](https://github.com/orchidsoftware/platform/releases/tag/6.7.6)

**Comment by Leshkens** [comment]
Да, вроде все хорошо
