### ISSUE TITLE
Как сделать форму редактирования сущности с редактирования связанных hasMany данных?

### ISSUE THREAD

**Issue by ivan-cc** [orchidsoftware/platform#1029]
Например, хочу на странице редактирования юзера сделать добавление/редактирование телефонов, которые хранятся в отдельной таблице и связаны с таблицей юзеров через user_id.

Пока вижу решение это всё сделать через отдельную страницу, где будут редактироваться записи только телефонов, но хочется прям на одной форме.

**Comment by tabuna** [comment]
Вы можете добавить, например, таблицу с номерами телефонов и добавлять/редактировать через модальные окна. 

Условный пример/илюстрация:

![image](https://user-images.githubusercontent.com/5102591/70888174-be16d180-1ff0-11ea-8863-83a192b17f0c.png)

![image](https://user-images.githubusercontent.com/5102591/70888203-d0910b00-1ff0-11ea-83a9-9bbd8f94f779.png)

Допустим, что мы создали миграцию:

```php
Schema::create('phones', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->bigInteger('user_id');
    $table->string('description');
    $table->string('number');
    $table->foreign('user_id')
        ->references('id')
        ->on('users')
        ->onUpdate('cascade')
        ->onDelete('cascade');
    $table->timestamps();
});
```

Создали модель:

```php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Orchid\Screen\AsSource;

class Phone extends Model
{
    use AsSource;

    /**
     * @var array
     */
    protected $fillable = [
        'user_id',
        'description',
        'number',
    ];

    /**
     * @var array
     */
    protected $casts = [
        'description' => 'string',
        'number'      => 'string',
    ];
}
```

И добавили связь в базового пользователя:

```php
namespace App;

use Orchid\Platform\Models\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function phones()
    {
        return $this->hasMany(Phone::class);
    }
}
```

Тогда, возьмём уже существующий экран `UserEditScreen` и внесём в него некоторые правки:

```php
$user->load(['roles', 'phones']);
```
До загрузим к нашему пользователю номера телефонов.

Для вывода воспользуемся таблицей в разделе `layouts`:

```php
Layout::table('user.phones', [
    TD::set('number', 'Номер телефона')->render(function (Phone $phone) {
            return ModalToggle::make($phone->number)
                ->modal('editPhone')
                ->modalTitle($phone->number)
                ->method('savePhone')
                ->asyncParameters($phone->id);
        }),
    TD::set('description', 'Описание'),
]),
```

В колонку таблицы, мы добавили кнопку по которой будет загружено модельное окно (Вы можете посмотреть пример, в списке пользователей, нажав на email).

Опишем его:

```php
Layout:: modal ('editPhone', [
    Layout::rows([
        Input::make('phone.number')->title('Номер телефона'),
        Input::make('phone.description')->title('Описание'),
    ])
])->async ('asyncGetPhone'),
```

Так как асинхронное окно должно получать данные, то определим метод `asyncGetPhone` в этом классе:

```php
/**
 * @param \App\Phone $phone
 *
 * @return array
 */
public function asyncGetPhone(Phone $phone) : array
{
    return [
        'phone' => $phone,
    ];
}
```

Остаться только определить метод 'savePhone' для сохранения номера телефона для вашего пользователя.

-----
Пример такого подхода вы можете посмотреть на странице списка пользователей, где в модальном окне можно быстро редактировать не переходя на страницу.

Постарался достаточно подробно описать как это можно сделать, но если остались вопросы не стесняйтесь.
