### ISSUE TITLE
Permissions and cache

### ISSUE THREAD

**Issue by Hrache** [orchidsoftware/platform#1030]
Hi there. I deployed my website to some sub-domain which's doc-root is in the directory of the main domain. Then I required to move files of the project into the domain doc-root, now I'm getting error number **500** - the question is may it be because of the permissions of storage and bootstrap/cache folders and if yes how can I fix it (by using shell_exec instead of terminals, because of absence of the terminal/s, if it needs any terminal of course)? Thank you for your attention and as a note the first time project was deployed it run after we removed cache config file from the bootstrap folder's cache folder.

**Comment by tabuna** [comment]
Yes, it is quite possible, the package relies completely on the framework and you should refer to its recommendations on the bootstrap cache.

For starters, you can clear all:

```php
php artisan optimize:clear
```

Also set `chmod -R o + w` for `storage ` and `bootstrap/cache` directories

Not sure you can do it through `shell_exec`. If you use hosting, there should be a graphical interface where you could do this. If this is someone else’s environment where you do not have rights, then the best option would be to ask for it.

**Comment by Hrache** [comment]
Thank you for a quick answer, I'll try and will leave some sign at least :)

**Comment by Hrache** [comment]
Hey, good day. So tried to do something asked but didn't get any answer, I hope it concerns to the upcoming Christmas events, but however. There is a way to change permission through right click menu item by the name Change permissions, it is kinda you need to chose read write execute permissions to the user, group, world, so is there any number combination, or maybe you could provide read, write, execute options combinations for each of user, group, world types or something?

**Comment by tabuna** [comment]
> or maybe you could provide read, write, execute option's combinations for each of user, group, world types or something?

775

**Comment by Hrache** [comment]
Thank you, I'll try it
