### ISSUE TITLE
How does Orchid deals with table relations?

### ISSUE THREAD

**Issue by FreddyCrugger** [orchidsoftware/platform#1032]
Hello,

I did not know where to post this question sorry as the Telegram group seems empty.
But how does Orchid deals with Table relations please?

I would like to pass data from one table into the dropdown menu of a form for example.

Thank you,

**Comment by tabuna** [comment]
Hi, there is nothing wrong with asking a question here.
 

This is a normal requirement that you can implement using the “Select” and “Relation” elements, please see:
http://orchid.software/en/docs/field#relations
