### ISSUE TITLE
[6.8] Combine available color modifiers into one class

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#1037]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when colors must be specified. Because constants are scattered across base classes. For instance:

```php
// Notification
new \Orchid\Platform\Notifications\DashboardNotification([
    'title'   => 'Hello Word',
    'message' => 'New post!',
    'action'  => 'http://orchid.software/',
    'type'    =>  DashboardNotification::INFO,
]);

// Alert
Alert::message('Welcome Aboard!', Alert::INFO);

// Notice
Toast::message('Welcome Aboard!', Toast::INFO);

// Button
Button::make('Delete')->type(Button::DANGER)
```
This is repeated too many times.

**Describe the solution you'd like**
Create a single class containing all colors as constants.
Which I could indicate in any objects

```php
class Color
{
    /**
     * Visual style.
     */
    public const INFO = 'info';
    public const SUCCESS = 'success';
    public const WARNING = 'warning';
    public const DEFAULT = 'default';
    public const DANGER = 'danger';
    public const PRIMARY = 'primary';
    public const SECONDARY = 'secondary';
    public const LIGHT = 'light';
    public const DARK = 'dark';
    public const LINK = 'link';
    public const ERROR = self::DANGER;
}
```

**Comment by tabuna** [comment]
It would be even better if the class was enum.

**Comment by Nks** [comment]
Color::DANGER() возвращает по-умолчанию объект вместо строки. Из-за этого, например, может упать код ```$message['type'] = $message['type'] ?? Color::INFO();``` из DashboardNotification

**Comment by Nks** [comment]
Остальные методы, как уже понятно, так же возвращают объект. Вообще не проще ли было просто создать ColorEnum со списком указанных констант и избавиться от непонятных методов и дополнительной библиотеки? Мы используем какой-то другой функционал из этой библиотеки?

**Comment by tabuna** [comment]
> Остальные методы, как уже понятно, так же возвращают объект. Вообще не проще ли было просто создать ColorEnum со списком указанных констант и избавиться от непонятных методов и дополнительной библиотеки? Мы используем какой-то другой функционал из этой библиотеки?

В большей степени для определения типов агрументов:

```php
public function brand(Color $color) {
    // ...
}

public function status():Color {
    // ...
}
```
Чего нельзя достигруть с помощью простых констант
