### ISSUE TITLE
Нужен произвольный width и height в Cropper

### ISSUE THREAD

**Issue by ivan-cc** [orchidsoftware/platform#1041]
Сейчас в Cropper обязательно нужно указывать размер картинки (соотношение сторон), хотя это не всегда необходимо.

Предлагаю сделать указание `width` и `height` адаптивным, чуть исправив шаблон `resources/views/fields/cropper.blade.php`:
```
         data-fields--cropper-storage="{{ $storage ?? 'public' }}"
         @if (isset($width))data-fields--cropper-width="{{ $width }}"@endif
         @if (isset($height))data-fields--cropper-height="{{ $height }}"@endif
         data-fields--cropper-target="{{ $target }}"
```

**Comment by tabuna** [comment]
Ширина и высота больше не обязательны с версии 6.8.1 (2020-01-12)
