### ISSUE TITLE
Not working filter reset

### ISSUE THREAD

**Issue by unzippo** [orchidsoftware/platform#1042]
**Describe the bug**
Not working filter reset

**To Reproduce**

  1. Goto users page
  2. Set filter by name
  3. Try to reset filter by click on badge

**Expected behavior**
Page reloaded without filtration

**Screenshots**
![image](https://user-images.githubusercontent.com/11323261/72603960-12cca580-392b-11ea-8dbe-ff3442de2489.png)

**Server (please complete the following information):**
  - Platfrom Version: 6.8.3

**Comment by tabuna** [comment]
Hey @unzippo. 

Is there any additional information? Can the error output in the console?
I can not reproduce the problem:

![screencast](https://user-images.githubusercontent.com/5102591/72605165-4f010580-392d-11ea-9a60-43e7670ece17.gif)

**Comment by unzippo** [comment]
There are no errors in the console. 
I installed a clean version from the repository.
I replace vendor\orchid\platform\public\js\orchid.js from platform version 6.7.1, all works.

**Comment by unzippo** [comment]
After firs setting filter:
![image](https://user-images.githubusercontent.com/11323261/72606902-8d4bf400-3930-11ea-9159-8d69d8946723.png)

Then i press "Roles:"
![image](https://user-images.githubusercontent.com/11323261/72606946-a6ed3b80-3930-11ea-8814-9d06d29c46bb.png)

Then i press "admin", page refreshes. The same result.

**Comment by tabuna** [comment]
I just checked under different browsers:
- Chrome 79.0.3945.117
- Firefox 72.0.1
- Safari 13.0.4 

None of them had problems. Can you disable extensions and check it again?

**Comment by tabuna** [comment]
> I replace vendor\orchid\platform\public\js\orchid.js from platform version 6.7.1, all works.

You can check a later release, for example 6.8.2? js/css resources collected automatically.

**Comment by unzippo** [comment]
Checked without extensions in mozilla and chrome in private mode. Not working.

**Comment by tabuna** [comment]
Hi @unzippo 

The problem should be fixed in the next release.
You can try it now or wait for the release of 6.8.4

**Comment by unzippo** [comment]
Thanks, everything works now.
