### ISSUE TITLE
Remove

### ISSUE THREAD

**Issue by lopika99** [orchidsoftware/platform#1043]
Hi, I'd like to remove the all Orchid package.
What's the method for that??
Thx

**Comment by tabuna** [comment]
Hey. To do this, you must:

1. Clear all cache
2. Roll back migrations until creation.
3. Delete the app/orchid directory
4. Return user model code from https://github.com/laravel/laravel/blob/master/app/User.php
5. Remove composer run `composer remove vendor/package`
