### ISSUE TITLE
Changing base layout for web views 

### ISSUE THREAD

**Issue by anushkamds** [orchidsoftware/platform#1048]
Base layout of the application stay same for `web` and `platform` views. In some cases, we are required to change the way user see things rather than showing actual view. Consider an example like running a blog.

**Describe the solution you'd like**
I would like, if there is setting that we can change base of the application by giving a particular resource file

Thank you.

**Comment by tabuna** [comment]
Hey @anushkamds .

Sorry, I don’t really understand what exactly do you want to see? 
Can I have more descriptions or examples?

**Comment by anushkamds** [comment]
Hey @tabuna,
It's like this. I have defined some routes in `routes/platform.php` and some in `routes/web.php` file. For the routes in `web.php`, user must not see the side panel and other stuff which generated by Orchid. I want to add a custom view for the routes which is define in `web.php`

**Comment by tabuna** [comment]
This can be done in the menu itself.
For example, by using roles or explicit indication:

```php
ItemMenu::label('Example')->permission('my.rules');

// or
$isAuth= Auth::check();

ItemMenu::label('Example')->canSee($isAuth);
```

**Comment by anushkamds** [comment]
Hi @tabuna,
this is to hide menu item. What i want, to hide side menu completely and show only `body-right` part in the view

**Comment by tabuna** [comment]
Hey @anushkamds .
The goal of the project is to solve non-public things.
Therefore, there is no setting to hide the menu.

But you can do this in several ways:

#### Add custom css code and add a rule in which the menu will be hidden;

In `config/platform.php`
```php
'resource' => [
    'stylesheets' => [ '/path/for/your/file.css' ],
    'scripts'     => [],
],
```
It is also possible to specify resources through the `Dashboard` object, for example, in a service provider:

```php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Orchid\Platform\Dashboard;

class AppServiceProvider extends ServiceProvider
{
    public function boot(Dashboard $dashboard)
    {
        $dashboard->registerResource('stylesheets', '/path/for/your/file.css' );
    }
}
```


#### Publish resources to the application


You can use the artisan command to publish all resources in the `html/blade` view. 

```php
php artisan vendor:publish
```
They will be in the directory `view/vendor/platform` and package updates will not affect these files.
You can explicitly make changes, for example by deleting or adding your own rule to show/hide this
