### ISSUE TITLE
Upload

### ISSUE THREAD

**Issue by mavsan** [orchidsoftware/platform#1050]
**Describe the bug**
Экран редактирования записи (запись уже создана). У экрана имеются несколько полей с валидацией при сохранении (любые правила, добавлены могут быть в любой момент). После сохранения какое-то из полей не проходит валидацию, форма перезагружается, файлов в Upload нет, просто пустые квадратики.

Анализ привел к пониманию, что поле Upload требует особого подхода к формированию своего атрибута value. Это особое value формируется вот тут: [$this->addBeforeRender(...)](https://github.com/orchidsoftware/platform/blob/2fe5c101f1da109ff61d9b474d313b681dd54c95/src/Screen/Fields/Upload.php#L143) (не получается нормально код вставить, поэтому ссылка).

Затем, в методе [Field::render](https://github.com/orchidsoftware/platform/blob/2fe5c101f1da109ff61d9b474d313b681dd54c95/src/Screen/Field.php#L181) происходит вызов этого `runBeforeRender`, который устанавливает верное value, затем, ниже происходит вызов метода `modifyValue()`, который смотрит - есть ли "старые данные", а они там есть - идентификаторы записей файлов из таблицы `attachments`.

Вот как выглядит "нормальный" экран:

![image](https://user-images.githubusercontent.com/5114650/73908669-2baaf400-48f6-11ea-97ff-1028d2cbd20b.png)

Потом я установил для validation ограничение по кол-ву символов для поля "Город":

![image](https://user-images.githubusercontent.com/5114650/73908758-69a81800-48f6-11ea-9041-572d324d004b.png)

Дальше происходят еще более интересные вещи. Вот так выглядят input для этого Uoload (к стати, их почему-то много стало):

![image](https://user-images.githubusercontent.com/5114650/73909457-6e6dcb80-48f8-11ea-8572-4cf09f8752eb.png)

И, соответственно, радостный человек получив ошибку, исправляет её, отправляет данные, и получает следующую ошибку:

![image](https://user-images.githubusercontent.com/5114650/73909616-d7edda00-48f8-11ea-8948-427c9931cf62.png)

**Comment by mavsan** [comment]
А, и вот еще что. У меня там несколько групп файлов - логотипы, письма, файлы. Если в качестве имени поля указать `review.attachment` то `Upload` загружает все в одно поле, даже, если groups разные, поэтому id файлов хранятся в записи отзыва. Не знаю, может не правильный подход, но работает, позволяет понять что-за файл - прайс, или логотип, или скан письма (в данном случае). После сохранения записи (отзыва) вместо ID картинок там сохраняются вот эти undefined, и потом, при повторном открытии записи (просто перезагрузив страницу) получается вот такое:

![image](https://user-images.githubusercontent.com/5114650/73910239-7dee1400-48fa-11ea-9af3-927d81dde82d.png)

Вот как базе, обычный json:

![image](https://user-images.githubusercontent.com/5114650/73910467-2e5c1800-48fb-11ea-87b0-af39cbef7859.png)

Лежу в больничке, ограничен в более глубоком анализе, инет почти не работает, да и не удобно одной рукой, вторая под капельницей еще пару часов точно.

**Comment by tabuna** [comment]
Привет @mavsan  
Проверь релиз 6.10.0, такая ошибка должна быть исправлена

**Comment by mavsan** [comment]
Возможности протестировать хорошо сейчас нет (не повлияло ли на что-то другое это исправление), но проблема, которую я описывал - пропала. Все сохраняется, картинки не теряются.

**Comment by tabuna** [comment]
@mavsan Отлично.
