### ISSUE TITLE
Required fields are not validating on hidden tab

### ISSUE THREAD

**Issue by CodingJediKnight** [orchidsoftware/platform#1052]
If you have several tabs on edit screen, required fields will be validated only on the first tab. So empty fields on other tab won't stop save method.

1. Create several tabs.
2. Add required fields to the first and other tab.
3. Fill required fields on the first tab and hit save button.

  - Platfrom Version: 6.10.1
  - Laravel Version: 6.15.1
  - PHP Version:  7.3
  - Database:  MySql
  - Database Version:  5.7

**Comment by tabuna** [comment]
Hi @CodingJediKnight 

I created a screen and added the following information to it:

```php
public function commandBar(): array
{
    return [
        Button::make('Submit form')
            ->method('checkIssue')
    ];
}

public function layout(): array
{
    return [
        Layout::tabs([
            'Example Tab 1' => Layout::rows([
                Input::make('required_field_1')->required()
            ]),
            'Example Tab 2' =>  Layout::rows([
                Input::make('required_field_2')->required()
            ]),
        ]),
    ];
}
```

After that, I filled out the first tab and clicked send. 
And I get an error about sending. In google chrome, firefox, safari.
What do I need to do in order to reproduce this behavior?

**Comment by tabuna** [comment]
I will close this issue.
If you are still experiencing such a problem, please feel free to open it again.
