### ISSUE TITLE
Laravel medialibrary support

### ISSUE THREAD

**Issue by jseparovic1** [orchidsoftware/platform#1055]
**Is your feature request related to a problem? Please describe.**
I would like to use [spatie/laravel-media-library](https://github.com/spatie/laravel-medialibrary) package in order to manipulate uploaded images and make them responsive.

**Describe the solution you'd like**
Ideally I would like to use `Media` field
```php
 Media::make('post.gallery')
                ->help('Post gallery')
                ->multiple(true)
                 ->acceptedFiles('image/*')
                ->title('Post gallery'),
```

Media library  uses `Media` entity which is almost similar to `Attachment` with some added fields so implementation could be similar. 

**Describe alternatives you've considered**
I have tried to manually add files to media collection on `createOrUpdate`, but there are issues with deleting and loading existing files.

Are there any examples on how this integration is done and would you like to have this feature in core?

**Comment by tabuna** [comment]
Hi @jseparovic1 

I think this is a great idea for a package.

Regarding adaptability, I am achieving this [using the library]( https://github.com/Intervention/imagecache)

Let me know if you want to make a package for this and you will need help.
