### ISSUE TITLE
Как фильтровать сразу по двум колонкам - first_name & last_name?

### ISSUE THREAD

**Issue by ivan-cc** [orchidsoftware/platform#1062]
Вывожу имя и фамилию одной колонкой, нужно иметь фильтрацию, которая будет работать одновременно по двум колонкам таблицы (first_name OR last_name).

Как можно расширить встроенный фильтр на такое использование?

**Comment by tabuna** [comment]
> Как можно расширить встроенный фильтр на такое использование?

Используйте фильтр созданный командой artisan:
```bash
php artisan orchid:filter
```

После этого вы можете сделать нужный запрос, например
```php
/**
 * @param Builder $builder
 *
 * @return Builder
 */
public function run(Builder $builder): Builder
{
     $query = $this->request->get('query');

     return $builder->where('first_name', $query)
                    ->orWhere('last_name', $query);
}

```
