### ISSUE TITLE
The modal window does not open after server validation

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#1064]
**Describe the bug**

If you create a modal window and send data from it that will be validated on the screen, there will be an error. That modal window needs to be opened again

**To Reproduce**

  1. Create a modal window
  1. Submit failed validation data
  1. Modal is not open

**Comment by Velisariy** [comment]
Если в модалку добавить поле DateRange и  добавить на него валидацию, то модалка будет закрываться при неверном вводе.

Например 

```
public function layout(): iterable
    {
        return [
            Layout::modal('test-modal', Layout::rows([
                DateRange::make('dates')
            ])),
        ];
    }
```

```
class DateRequest extends FormRequest
{
...
    public function rules()
    {
        return [
            'dates' => 'required|array',
            'dates.start' => 'required|date|after:today',
            'dates.end' => 'required|date|after:dates.start',
        ];
    }
}

```
