### ISSUE TITLE
Frontend validation: Max file size null MB

### ISSUE THREAD

**Issue by adxin** [orchidsoftware/platform#1068]
Laravel 6.10 
Orchid 6.11
php.ini: 
- memory_limit=1536M
- post_max_size=1024M
- upload_max_filesize=1024M

```php
Cropper::make('post.picture')
->maxFileSize(100)
->width(500)
->height(300);

Picture::make('post.picture')
->maxFileSize(100);
```
При попытке загрузить изображение размером 20кб
появляется toast: Validation error 
The downloaded file is too large. Max size: **null** MB

![Скриншот](https://user-images.githubusercontent.com/46772040/76855445-f9849e80-6872-11ea-82fd-3483cfcaffe2.png)
Метод Init::convertBytesTo поправил, pull request отправил, на фронте не знаю как проверить

**Comment by tabuna** [comment]
> Метод Init::convertBytesTo поправил, pull request отправил, на фронте не знаю как проверить

Ошибка на фронте осталось после изменения из PR ?
