### ISSUE TITLE
Badge-success background-color is grey

### ISSUE THREAD

**Issue by G3z** [orchidsoftware/platform#1076]
**Describe the bug**
when using bootstrap `.badge` the color (badge-success, badge-danger,...) class is shadowed by badge class background-color

**To Reproduce**

  1. print a `<span class="badge badge-success">Active</span>`
**Expected behavior**
![Schermata 2020-04-20 alle 11 46 11](https://user-images.githubusercontent.com/875086/79738066-8d2b0e00-82fc-11ea-8b3b-10cbf3bc8cc9.png)

**Screenshots**
![Schermata 2020-04-20 alle 11 44 22](https://user-images.githubusercontent.com/875086/79737893-4b9a6300-82fc-11ea-88e9-ec9520dc0d8f.png)

![Schermata 2020-04-20 alle 11 40 46](https://user-images.githubusercontent.com/875086/79737613-dcbd0a00-82fb-11ea-8ba0-5f3de3f088de.png)

**Context**
i'm using this in a `TD`
```php
TD::set('active', 'Status')
     ->render(function ($product) {
         if ($product->active) {
             return '<span class="badge badge-success">Active</span>';
         }
         return '<span class="badge badge-danger">Inactive</span>';
     }),
```

**Comment by G3z** [comment]
i should use `<span class="badge bg-success">Active</span`, closing!

**Comment by hellodit** [comment]
It's bug or error? 
Why have to use `bg-color` instead of `badge-status`

According to bootstrap documentation to change the color we've to use  `badge-status`
[Badge documentation](https://getbootstrap.com/docs/4.0/components/badge)

**Comment by tabuna** [comment]
I think this is a style error. Which would be good to fix.

**Comment by tabuna** [comment]
Please check this release: https://github.com/orchidsoftware/platform/releases/tag/9.19.5

**Comment by hellodit** [comment]
thanks for your update, appreciate it!
