### ISSUE TITLE
Filters URL parameters bug

### ISSUE THREAD

**Issue by Leshkens** [orchidsoftware/platform#1081]
При применении фильтра удаляются параметры фильтров после загрузки страницы. То есть страница загружается с параметром, но потом он из URL просто исчезает.

### Гифка:
![isr4ba48h8](https://user-images.githubusercontent.com/8939383/80290513-e9f45180-875e-11ea-9c55-5e0e98b91c33.gif)

Orchid 7.1.1
Chrome 81
Firefox 75

**Comment by tabuna** [comment]
Должно быть исправлено с выпуском 7.1.2
