### ISSUE TITLE
Bad upload image url

### ISSUE THREAD

**Issue by alecz2303** [orchidsoftware/platform#1089]
I'm trying to upload an image on a new Orchid Platform Implementation, doing the Manage attachments tutorial.

When I click in the "Upload File" button I am getting a 404 response because the POST URL http://orchid.test/dashboardsystems/files, I'm pretty sure an **/** is missing between dashboard and systems. 

Please help!

**Comment by tabuna** [comment]
Hey. I’m sorry you came across this.
We fixed a bug with a missing slash in the version [7.2.4](https://github.com/orchidsoftware/platform/releases/tag/7.2.4)
Just do `composer update` and the problem should be resolved

**Comment by alecz2303** [comment]
> Hey. I’m sorry you came across this.
> We fixed a bug with a missing slash in the version [7.2.4](https://github.com/orchidsoftware/platform/releases/tag/7.2.4)
> Just do `composer update` and the problem should be resolved

Tnak you very much, it resolved the issue.
