### ISSUE TITLE
Removing "Apply" button from modal

### ISSUE THREAD

**Issue by alash3al** [orchidsoftware/platform#1095]
my use case is:

"I want a user to click on a click, then show him a modal with some info about the clicked item"

When I read the source code of the modal resource "blade file", I noticed that there must be an apply button.

Any idea to do that without hacking the core?

**Comment by tabuna** [comment]
Hey @a13hander . I moved this question to a more suitable repository. 
The easiest way is to write your own view:

```blade
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
    </div>
  </div>
</div>
```

We use [bootstrap](https://getbootstrap.com/docs/4.5/components/modal/) for styles. On your screen you will need to call:

```php
<?php

Layout::view('your.blade.template');
```
All screen variables will be available in this template. 

Or `Layout::wrapper` if you want to transfer other layers there

-----

A slightly more complicated way is to really inherit from the base class and change its template to your needs.

----

The third way to come up with a scheme in which it would be a universal way to use, share it and make PR in the main repository.

**Comment by alash3al** [comment]
@tabuna I think you mentioned another person, mine is @alash3al
