### ISSUE TITLE
Package davejamesmiller/laravel-breadcrumbs is abandoned

### ISSUE THREAD

**Issue by gioacchinopoletto** [orchidsoftware/platform#1097]
This is only a composer warning. 
Don't worry, but we still using it?

**Comment by tabuna** [comment]
Hi @gioacchinopoletto , yes, the author of the package decided to stop developing it.

We have already created an issue #1073 on this subject.
Moreover, I prepared an [implementation](https://github.com/tabuna/breadcrumbs) that will replace this in the next version. We have time to fully prepare the new release until August when this package turns into a pumpkin
