### ISSUE TITLE
Request for change UX\UI

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#1105]
**Introduction**
A couple of times a month I get messages that the design sucks. I am not a professional designer and do not have a high sense of taste, so it is difficult for me to do this the first time. Especially when you work in it for a long time, you stop noticing errors.

This task is designed to work out various concepts of design-related changes. 
I think we can make significant changes for the next major version (8.0?).

I would really like to build this in the form of some problematic queries, and then try to solve them with the help of demonstrations and discussions.

_Possible problems:_

**Dark background for the logo**

Many small companies or projects do not have a suitable logo that looks good against a dark background. :rage: Sometimes this leads to sad things like:

![Снимок экрана 2020-05-25 в 18 28 58](https://user-images.githubusercontent.com/5102591/82826375-ab64ca80-9eb5-11ea-91b2-716c015f12be.png)

This logo was taken by chance, but I saw real projects that use similar things.  

**Screen width**

Another of the things that I have seen many times is a complaint about the size of the width of the workspace. In most cases, extra width was needed for "large" tables. But in reality, for those projects there was no need for the width of the entire screen. For example:

![image](https://user-images.githubusercontent.com/5102591/82826776-6ee59e80-9eb6-11ea-99cf-9a7a62f9c95a.png)

It seems that there is already no place and the information is presented extremely poorly. But it depends on the developer and how he will build his columns. This example can be easily changed to the following view :wink: without losing any data:

![image](https://user-images.githubusercontent.com/5102591/82826965-b9ffb180-9eb6-11ea-8d88-58840bb182fa.png)

_This example was taken from [my Russian-language blog](https://medium.com/@tabuna/8083996736b5), where you can see the whole process of change._

**Too much dark color**

Because of the container, a quarter of the screen is dark in color, which is not very like. (I do not know why :anguished:)

**Comment by tabuna** [comment]
One of the simplest solutions that I see is simply to remove the container. This will make the workspace almost full width.

_Before:_
![image](https://user-images.githubusercontent.com/5102591/82828258-4f9c4080-9eb9-11ea-9d9b-003003b3883b.png)

_After:_

![image](https://user-images.githubusercontent.com/5102591/82828309-6e9ad280-9eb9-11ea-8b79-12d19f26ac9d.png)

Metrics and graphs, of course, began to look a little ridiculous. But if you go in this direction, then you can improve them.

**Comment by tabuna** [comment]
To solve problems with the perception of dark color, as well as the placement of the logo. Сan changes the color scheme:

![image](https://user-images.githubusercontent.com/5102591/82829013-f6351100-9eba-11ea-93b7-cdb7a1e790f7.png)

This loses some contrast. In this style, it is difficult for me to focus my eyes. (Maybe it's just my habit).

**Comment by tabuna** [comment]
If you go further, you can remove the container for this option, then it will look like this:

![image](https://user-images.githubusercontent.com/5102591/82829418-dfdb8500-9ebb-11ea-8043-ca9f4b347b4e.png)

**Comment by pontmerci** [comment]
Excellent idea, you can take https://adminlte.io as a base, there are also many administration panel designs that can be taken as a base, they have already analyzed the characteristics of UX.

**Comment by tabuna** [comment]
You can take completely radical measures and strongly attribute the style. 
For example, this:
![Снимок экрана 2020-05-25 в 19 49 56](https://user-images.githubusercontent.com/5102591/82831538-5929a680-9ec1-11ea-9ab6-cd191437eb58.png)

**Comment by tabuna** [comment]
This issue did not lead to any discussion.
I suggest returning to it when more people are interested.

**Comment by talcual** [comment]
for the full with of right content remove workspace-limit but i dont found this code XD

**Comment by tabuna** [comment]
@talcual I assume that's what you're looking for:

https://github.com/orchidsoftware/platform/blob/1d232452289950366322e77a9d079cebc305a906/config/platform.php#L280-L293
