### ISSUE TITLE
При загрузке attachment добавлять кастомный путь в request

### ISSUE THREAD

**Issue by agoalofalife** [orchidsoftware/platform#1106]
**Is your feature request related to a problem? Please describe.**
Предлагаю в `AttachmentController` добавить получение `$request->path`
Это здесь в методе `createModel`
```php
    $model = app()->make(File::class, [
            'file'  => $file,
            'disk'  => $request->get('storage'),
            'group' => $request->get('group'),
        ])->load();
```

**Describe the solution you'd like**
В свою очередь это надо изменить upload_controller.js, class Upload
Надо добавить получение в контролере, в основном классе File, добавить получение path из __construct и в методе по-умолчанию

**Describe alternatives you've considered**
При случае если я не хочу использывать навязанный путь из класса File, надо будет делать дополнительные Generators и как то протаскивать свою логику генерации путей

**UPD** Если добро могу кинуть PR

**Comment by tabuna** [comment]
Генератор, специально был создан и вынесен в конфиг, для того, что бы можно было менять пути сохранения, определение mime, определения хэша и так далее. Возможно он всё таки вам подойдёт. А если нет - 

> UPD Если добро могу кинуть PR

Отлично, давай добавим. Только не только для поля `Upload`, но и для `Picture/Cropper`

**Comment by agoalofalife** [comment]
@tabuna да я могу создать новый Generator, но у меня задача, динамический path.
Часть пути состоит из данных пользователя.
Как я посмотрел, в Generator я не могу пробросить данные.
Наверное надо менять так же сlass File

**Comment by tabuna** [comment]
@agoalofalife Можете привести пример?

Можно указать в генераторе, префикс пути или подобные вещи.
Так же можно выбирать хранилища явно:

```php
Upload::make('files')
    ->storage('s3');
```

Разве, что просто нельзя указать путь у поля, но тогда давайте добавим это:

```php
Upload::make('files')
    ->path('/my-photos/holiday');
```
Который бы заменял значение метода:

https://github.com/orchidsoftware/platform/blob/62ba0fa539ff1c1e78f9c5f8229a10b0c4ccfb53/src/Attachment/Engines/Generator.php#L69

**Comment by agoalofalife** [comment]
@tabuna да про storage я знаю
Ну пример такой, я хочу в колонке path такой путь `{user_id}/nameFile.extension`
Теперь в screen я могу написать что - то вроде 
```php
 Upload::make('taxPayer.attachment')
                    ->title('All files')
                    ->storage('cutsonDisk');
```
Но путь будет именно с датой, я хочу туда подставить user_id или как- то еще

**Comment by tabuna** [comment]
> Ну пример такой, я хочу в колонке path такой путь {user_id}/nameFile.extension
```php
<?php

use Illuminate\Support\Facades\Auth;

class UserGenerator implements Generator
{
    /**
     * Returns the relative file path.
     *
     * @return string
     */
    public function path(): string
    {
        return Auth::id() ?? 'guest';
    }
}
```

**Comment by agoalofalife** [comment]
@tabuna да забыл добавить, не аутентифицированного конечно
сейчас понял, что можно его из Request в принципе получить, если будет машрут такой
`user/edit/{id}`
Но по необходимости в screen это конечно делать удобнее)

**Comment by tabuna** [comment]
Как я уже говорил ранее, это возможно и хороший функционал и будет замечательно если вы поработаете над этим. Но мне больше всего не очень ясно, для чего это? 

- Если это для определения какой пользователь загрузил файл, то мы уже имеем эту информацию в базе данных. 

- Если это для "приватных" файлов для каждого пользователя, то должен быть использован не публичное хранилище (storage) и отдача этих файлов через контроллер. Где вы можете поставить любой маршрут.

- Если это для ресайзера, то так же решается собственным контроллером, как пример можно привести пакет image/cache с небольшой выдержкой его [конфига](https://github.com/Intervention/imagecache/blob/2fae78a3f299597c5179740f9e70b4f5e367b350/src/config/config.php#L5-L19)

**Comment by agoalofalife** [comment]
@tabuna хорошо я подумаю как смогу изменить логику загрузки или изменить пути
если что я вернусь с PR

**Comment by agoalofalife** [comment]
@tabuna я подстроился под платформу и сделал пути по дате
в процессе уже возникли некоторые идеи по расширение
по-возможности будут писать и помогать)
куда лучше сюда или в telegram?

**Comment by tabuna** [comment]
Если вопрос быстрый то лучше в телегу. 
Если более или менее сформированная концепция по изменениям, то лучше на github.
