### ISSUE TITLE
More flexibility with Cropper

### ISSUE THREAD

**Issue by G3z** [orchidsoftware/platform#1108]
**Is your feature request related to a problem? Please describe.**
At the moment, if I'm not mistaken, only with and height are settable on Cropper but i noticed Cropper.js has a few more options https://github.com/fengyuanchen/cropperjs#getcroppedcanvasoptions

**Describe the solution you'd like**
I believe it would be easy to implement `minWidth` `minHeight` `maxWidth` `maxHeight` (and also `max` and `min` shortcuts).
If this makes sense to you I will make a PR

**Comment by tabuna** [comment]
Hi @G3z . I fully support the idea of expanding the existing capabilities to existing fields, especially when their js allow and you just need to throw a call.
