### ISSUE TITLE
UserPresenter not found

### ISSUE THREAD

**Issue by mwkcoding** [orchidsoftware/platform#1129]
**Describe the bug**
After updating from Laravel 6 -> 7 and therefore Orchid 6 -> 7, I'm getting an error.
`Class 'App\Orchid\Presenters\UserPresenter' not found`

**To Reproduce**

  1. Make a new laravel project (version 6) and install orchid
  1. Upgrade project to Laravel 7 and update Orchid.
  1.  Attempt to access dashboard

**Expected behavior**
Either an upgrade guide of some sort, or no errors when updating.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.5 
 - Browser: Chrome
 - Version 83

**Server (please complete the following information):**
  - Platform Version: 7.7.1
  - Laravel Version: 7.14.1
  - PHP Version:  7.4
  - Database:  MySQL
  - Database Version:  5.7

**Additional context**
I would like to see some upgrade guides when making new major versions instead of having that box on the dashboard "shouting" at users to update your package...

**Comment by tabuna** [comment]
Hey @mwkcoding .


> Class 'App\Orchid\Presenters\UserPresenter' not found

You need to add this class yourself. You can take it from the [standard delivery](https://github.com/orchidsoftware/platform/blob/db746dd6c30c4f005e166b8be5228bf5ddfb3a42/install-stubs/Orchid/Presenters/UserPresenter.php#L12) and change as you wish. The work of the presentation classes can be found at the [following link](https://orchid.software/en/docs/presenters).

> Either an upgrade guide of some sort, or no errors when updating.

Thanks for this suggestion. I think we will definitely do it for 8.0

> I would like to see some upgrade guides when making new major versions instead of having that box on the dashboard "shouting" at users to update your package...

I hope this was said with good intentions. Notification that a new version has been released is not intended for your users. It is intended only for you as a developer! (Suddenly you installed the old version of laravel/orchid) The output of this die is on [your screen and you can remove it](https://github.com/orchidsoftware/platform/blob/db746dd6c30c4f005e166b8be5228bf5ddfb3a42/install-stubs/Orchid/Screens/PlatformScreen.php#L70).

**Comment by tabuna** [comment]
This question has remained unanswered for a long time. 
I hope that all is well with you. Feel free to rediscover it.
