### ISSUE TITLE
Repeatable fields and Conditional fields ?

### ISSUE THREAD

**Issue by jehanf** [orchidsoftware/platform#1158]
**Describe the solution you'd like**
A conditional form fields : check a box and some others fields are appearing
A repeatable form fields : the possibility of adding dynamic inputs or textarea as array with a little "+" button as often seen in many admin dashboards

And by the way, your solution is really awesome and super smooth, I was really impressed :)

**Comment by tabuna** [comment]
Hey @jehanf .  
We have a matrix field that allows us to add new rows. 
For example, to fill out an account. Can be used as follows:

```php
Matrix::make('users')
    ->title('Users list')
    ->columns(['id', 'name', 'email', 'created_at', 'uses_two_factor_auth'])
    ->fields([
        'id'                   => Input::make()->type('number'),
        'name'                 => TextArea::make(),
        'email'                => Select::make()->fromModel(User::class, 'name'),
        'created_at'           => DateTimer::make()->format('Y-m-d'),
        'uses_two_factor_auth' => CheckBox::make()->placeholder('Включена'),
    ]),
```


Screenshots:

![image](https://user-images.githubusercontent.com/5102591/84595664-d19cdb00-ae61-11ea-9664-90fba604347b.png)


Also, note the existing extensions for this. 
For example, here is a package that adds a similar implementation: https://github.com/Nks/orchid-repeater-field

**Comment by tabuna** [comment]
> A conditional form fields : check a box and some others fields are appearing

This request also already exists.
 It is provided immediately and [described here](https://orchid.software/en/docs/layouts/listener/). There is also a [short video on how to use](https://www.youtube.com/watch?v=mXFPooGSqs4)

**Comment by jehanf** [comment]
Then I'm sorry for the duplicates, I should have done my research better !

Thanks for the really precise answer !

**Comment by tabuna** [comment]
Feel free to ask here on github or in general chat

**Comment by RaiserWeb** [comment]
Can I just say this is really awesome! Thanks @tabuna , got up and running with this in no time - I thought it might be tricky, but this solution is great.
