### ISSUE TITLE
Delete row for Matrix field does not work in Firefox

### ISSUE THREAD

**Issue by jehanf** [orchidsoftware/platform#1166]
**Describe the bug**
The delete row button in a Matrix field is behaving weirdly in Firefox, doing an api call and refreshing the view with no change

**To Reproduce**
Just try to delete a row after adding content in Advanced Forms element provided as an example 

**Expected behavior**
Well, just delete the row :)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Browser 1: Firefox 77
 - Browser 2: Firefox Developer 78
 - Note: seems to work as it should in webkit-based browsers

**Comment by tabuna** [comment]
This should be fixed in https://github.com/orchidsoftware/platform/releases/tag/7.11.2

**Comment by jehanf** [comment]
It seems to work perfectly indeed :)

**Comment by tabuna** [comment]
Fine. Then I close this issue.
Feel free to open it again.
