### ISSUE TITLE
Password Resets migration is missing

### ISSUE THREAD

**Issue by MunGell** [orchidsoftware/platform#1175]
**Describe the bug**

Migration for table `password_resets` is missing in the standard pack of the platform. This leads to Error 500 on password reset action.

**Steps to reproduce**

  1. Open platform application the browser
  1. On login screen click "Forgot your password?"
  1. Enter email of an *existing* user and click "Send Password Reset Link" button

**Expected behavior**

System should show a successful screen and send email with password reset instructions to the user

**Actual behavior**

System shows Error 500:

```
Illuminate\Database\QueryException
SQLSTATE[HY000]: General error: 1 no such table: password_resets (SQL: select * from "password_resets" where "email" = user@example.com limit 1)
```

**Comment by tabuna** [comment]
Hi, this migration comes with the installation of the framework:
[https://github.com/laravel/laravel/](https://github.com/laravel/laravel/blob/311c3f823a6f09df5e9b882906456e9caa02132c/database/migrations/2014_10_12_100000_create_password_resets_table.php#L1)

At some point, he was removed, and then returned again. 
Only users who have installed applications in the past may encounter this.

**Comment by MunGell** [comment]
Yeah, looks like I was unlucky to setup it between Dec 2019 and May 2020.

Thanks!
