### ISSUE TITLE
Inputs that in group don't serialize in filter

### ISSUE THREAD

**Issue by fozbek** [orchidsoftware/platform#1181]
**Describe the bug**
I have a list screen that includes filter. Filter contains a lot of inputs and i need to group them. When i put them in a group and i submit, inputs values dont append to url.

**To Reproduce**

  1. Add filter to page
  2. Add a group and put inputs 
  3. Click submit

**Expected behavior**
go to: Describe the bug;

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - Browser Chrome 
 - Version 83.0.4103.116

**Server (please complete the following information):**
  - Platfrom Version: 7.13.0
  - Laravel Version: v7.20.0
  - PHP Version:  7.4.8
  - Database:  Mysql
  - Database Version:  5.7.29

**Comment by tabuna** [comment]
Hey @fozbek .

This should already be fixed.
I recommend using a group of several filters, and not one large one, which will need to be grouped later.

For example:

```php
class FiltersLayout extends Selection
{
    /**
     * @return Filter[]
     */
    public function filters(): array
    {
        return [
            ExampleFilter::class,
            AnotherFilter::class,
            SomethingElseHereFilter::class,
        ];
    }
}
```

**Comment by fozbek** [comment]
Thank you for your answer.

Im grouping inputs not the filters. Filter width is enough for two switchers for a line. But inputs dont work properly in a group.

Before;
![Screenshot from 2020-07-17 13-17-12](https://user-images.githubusercontent.com/17993880/87776155-010f8080-c830-11ea-918d-730ea335549a.png)

After;
![Screenshot from 2020-07-17 13-17-46](https://user-images.githubusercontent.com/17993880/87776163-040a7100-c830-11ea-8020-5390281e33be.png)

**Comment by tabuna** [comment]
I agree. It looks much better and is suitable.
Upgrade to [7.14.0](https://github.com/orchidsoftware/platform/releases/tag/7.14.0)

**Comment by fozbek** [comment]
@tabuna 
Wow, you are fast. Thank you so much.
