### ISSUE TITLE
Search Page: label is overlays help text

### ISSUE THREAD

**Issue by grigoriy-ivanov** [orchidsoftware/platform#1185]
**Describe the bug**
Label is overlays help text at the global search page.

**To Reproduce**

  1. Use a short name for label: Docs, Test, etc.

**Screenshots**

![изображение](https://user-images.githubusercontent.com/13166748/87974114-36d39400-cad2-11ea-8d7e-64abcd8dc9a3.png)

**Expected behavior**
![изображение](https://user-images.githubusercontent.com/13166748/87974407-b4979f80-cad2-11ea-93a1-09f560c2f165.png)

**Comment by tabuna** [comment]
Hi @grigoriy-ivanov  this should be fixed in [7.14.1](https://github.com/orchidsoftware/platform/releases/tag/7.14.1)

**Comment by grigoriy-ivanov** [comment]
@tabuna Thank you.
