### ISSUE TITLE
Alert not visible after redirect back

### ISSUE THREAD

**Issue by cdupasquier** [orchidsoftware/platform#1186]
Describe the bug
The Alert info message is not visible after a redirect back from a Screen.

To Reproduce

Create a Screen class;
Define a Button that points to a method;
Define a method that contains a code like this:
public function sendMessage(Request $request) { Alert::info('Your e-mail has been sent successfully!'); return back(); }

Expected behavior
A redirect to the previous page with a visible Alert message.

Desktop (please complete the following information):

OS: Windows
Browser: Chrome, Firefox, Safari
Dev : Laragon

Server (please complete the following information):

Platform Version: 7.14
Laravel Version: 7
PHP Version: 7.3.20

I have read the threads already present but none of them allow me to solve this problem. Do you have a solution? 
In third-party developments, alerts work without any problem with the same configuration as mentioned above.

Thank you for your attention 

Best regards

**Comment by tabuna** [comment]
Hey @cdupasquier .

Most likely you have a second redirect. For example, you have a page:

```
https://example.dev/screen
```
And the redirect goes like this
```
-> http://example.dev/screen
-> https://example.dev/screen
```

Look at the `.env` file to make sure the address matches the real one you are referring to.
It would also help to see the actual behavior of the request in the 'Network' tab in the browser.

**Comment by cdupasquier** [comment]
hey @tabuna 

Thank you for your prompt response
here is my env file 

APP_NAME=Laravel
APP_ENV=local
APP_KEY=MyKey
APP_DEBUG=true
APP_URL=http://localhost/orchid/public

My Email Page route : http://localhost/orchid/public/dashboard/email

All requests in tab network are sending from http://localhost/orchid/public/...

I don't understand where is the second redirect ?

**Comment by tabuna** [comment]
> I don't understand where is the second redirect ?

This is just a guess.

> APP_URL=http://localhost/orchid/public

Why do you have a call to public?
It feels like the environment is not set up correctly.

**Comment by cdupasquier** [comment]
I have this public appeal because I've tried several options.
If I only put http://localhost in APP_URL like I do when I develop in local mode, it doesn't work either.

**Comment by tabuna** [comment]
I mean, you actually go to the browser at `http://localhost/orchid/public/...`
It shouldn't be like that. In this mode, your web server rules do not work.

The normal view would be the address `http://localhost`. 
Without any `orchid` (unless it is specifically configured) and even more so `public`

**Comment by cdupasquier** [comment]
Excuse me for the problem, using a virtualhost everything works perfectly !

thank you for your help !
