### ISSUE TITLE
Matrix fields with Listeners

### ISSUE THREAD

**Issue by apatronilha** [orchidsoftware/platform#1212]
I'm trying to do a Master detail for invoices and I can't calculate the total from Matrix fields of items (Quantity, Price, Discount, etc).
Is there a way to get this done? Following the documentation I was able to get the value from a normal Input. I used the same logic for Matrix field but without success.

Thanks

**Comment by tabuna** [comment]
The listener connects to a specific field. On the other hand, Matrix consists of many fields, so it is now necessary to explicitly indicate its full name. If you are interested in a listener for such fields, then I think it's worth doing a PR where the target name could apply a mask `field.*`

**Comment by plamenradev** [comment]
Since the last comment - is there a solution for listener layout with matrix fields?
Thanks!

**Comment by HichemBenali** [comment]
@plamenradev Well you can try this, it works well for me.
use this as a target
`anything"], [data-controller^="matrix`

this will make the querySelector target be: 
`[name="anything"], [data-controller^="matrix"]`

Which allows you to use any selector, in this case the matrix table.
Meanwhile allowing the developer to use a custom query selector would be better @tabuna.
