### ISSUE TITLE
[9.0] Change logo

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#1231]
I think since we have already started working on a serious change in appearance, then we cannot ignore the project logo. It's a little rough and proportional, but I remember how he was [born in the distant 23 Feb 2016:](https://user-images.githubusercontent.com/5102591/93106669-411ca380-f6b9-11ea-88f5-1c8b8eadc78d.png) Most don't care, but it's a [personal memory for me](https://user-images.githubusercontent.com/5102591/93107108-d28c1580-f6b9-11ea-8033-05a9325bce80.png).  But now, a new, more professional logo has been prepared for me, which is made in the style of laravel projects: [Jetstream](https://user-images.githubusercontent.com/5102591/93107649-91483580-f6ba-11ea-9a62-b0bb58f4910a.png), [Nova](https://user-images.githubusercontent.com/5102591/93108035-0451ac00-f6bb-11ea-9eb3-6527687a2366.png).

Ta-dam :tophat: . It's him:

![Color](https://user-images.githubusercontent.com/5102591/93109608-f866e980-f6bc-11ea-911d-800e219d9bae.png)

What do you think about this?

**Comment by astersnake** [comment]
I like the current logo, has its personality, but I can agree that a logo more in the line of Laravel branding could be more appropriated for the project.

**Comment by tabuna** [comment]
This is just a suggestion. 
Objectively, the stylistics will be more pleasant, but it has become absolutely not memorable.

**Comment by tabuna** [comment]
The new logo has already been installed on many resources and on the platform.
If you still see the last one, I advise you to run the commands:

```bash
composer update
php artisan cache:clear
```
