### ISSUE TITLE
Example App

### ISSUE THREAD

**Issue by Wulfheart** [orchidsoftware/platform#1251]
Hello,

is there a simple example app to discover the possibilities of Orchid?

**Comment by tabuna** [comment]
Hey @Wulfheart.

Examples of many of the components will be published during installation.
Also in the documentation, there are [4 small step-by-step tutorials](https://orchid.software/en/docs/quickstart/) that will show you how to work with the package.

**Comment by Wulfheart** [comment]
I hoped for an example for evaluation purposes.

**Comment by tabuna** [comment]
The admin panel is specific and usually unique for each project. Not everyone shares their work. You can see the [repositories that are open](https://github.com/orchidsoftware/platform/network/dependents) (this organization or I have nothing to do with them)

We do not currently have an application specifically for training or assessment. But we are open and if you have a desire to learn and make a demo application, then I am ready to support you.
