### ISSUE TITLE
AdminCommand add user class

### ISSUE THREAD

**Issue by RaiserWeb** [orchidsoftware/platform#1261]
**Is your feature request related to a problem? Please describe.**
I want to use a custom guard with a model called Admin for user auth. I cannot seem to change the User model used by the AdminCommand orchid:admin when creating a user. 

**Describe the solution you'd like**
The command should use config/platform.php models array setting to map User model

**Comment by tabuna** [comment]
Hi, we are [using class override](https://orchid.software/en/docs/configuration/#model-classes), have you tried that?

```php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Orchid\Support\Facades\Dashboard;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Dashboard::useModel(\Orchid\Platform\Models\User::class, \App\User::class);
    }
}
```

**Comment by RaiserWeb** [comment]
Hi @tabuna thanks for your fast response. Perfect, the above solution has resolved my request and works perfectly.

Cheers

**Comment by RaiserWeb** [comment]
Hi @tabuna, to update, there is a slight issue when logging in standard Users to the web application (and not the Orchid Dashboard).

The standard User model does not have the last_login field. But the Orchid package is registering an event listener that tries to update the last_login field on the user model Orchid\Platform\Listeners\LogSuccessfulLogin which causes it to fail.

I can fix this by adding the last_login field to the standard User model, but its an event that ideally wouldn't be firing as a user login to the web application via a different model and guard (not the dashboard) isn't related to this package.

**Comment by tabuna** [comment]
@RaiserWeb, it is not related to the subject.
Unfortunately, I don't know a way to disable the listener.
You might be helped by an update coming out today where this field is no longer used, and this listener is missing.

**Comment by Vladjen** [comment]
Hi @RaiserWeb @tabuna , I am trying to accomplish using the custom Model

I have added `Dashboard::useModel(\Orchid\Platform\Models\User::class, \App\Admin::class);` to my `AppServiceProvider`, however an Error is thrown

```php
 Error

  Call to a member function createAdmin() on string

  at C:\xampp\htdocs\project\vendor\orchid\platform\src\Platform\Commands\AdminCommand.php:55
     51▕
     52▕     protected function createNewUser(): void
     53▕     {
     54▕         Dashboard::modelClass(User::class)
  ➜  55▕             ->createAdmin(
     56▕                 $this->argument('name') ?? $this->ask('What is your name?', 'admin'),
     57▕                 $this->argument('email') ?? $this->ask('What is your email?', 'admin@admin.com'),
     58▕                 $this->argument('password') ?? $this->secret('What is the password?')
     59▕             );

  1   C:\xampp\htdocs\project\vendor\orchid\platform\src\Platform\Commands\AdminCommand.php:45
      Orchid\Platform\Commands\AdminCommand::createNewUser()

  2   C:\xampp\htdocs\project\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
      Orchid\Platform\Commands\AdminCommand::handle()

```

My Model

```php
class Admin extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'email',
        'password',
        'permissions',
    ];
}
```

migration file
```php
 Schema::create('admins', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('email')->unique();            
            $table->string('password')->nullable();
            $table->jsonb('permissions')->nullable();
            $table->timestamps();
        });
```

What would be the possible cause of this ?

**Comment by tabuna** [comment]
Hey @Vladjen. The string is returned only when the model is not found. Check the correctness of the namespace and the directories that you specified here: `\App\Admin::class`
