### ISSUE TITLE
orchid_mix should respect MIX_ASSET_URL env variable

### ISSUE THREAD

**Issue by G3z** [orchidsoftware/platform#1267]
**Is your feature request related to a problem? Please describe.**
When using a different server for assets orchid assets are not loaded

**Describe the solution you'd like**
`orchid_mix` should use `MIX_ASSET_URL` or `ASSET_URL` if set up

**Comment by tabuna** [comment]
Hey @G3z . 

Following the [documentation](https://laravel.com/docs/8.x/mix#url-processing), we should listen to the configuration `mix_url ` in `app.php`.

![image](https://user-images.githubusercontent.com/5102591/95127209-5046bc80-0760-11eb-8a4a-e285f6564a51.png)


I think we could easily fix the wrong behavior.

**Comment by tabuna** [comment]
And so I did this order:

1. If there is a setting for `app.mix_url`, we will use it.
2. If the setting for `app.asset` is set and the files have been published, then we also send from its URL
3. We return with the controller with the full cache and headers.

**Comment by tabuna** [comment]
I just released 9.1.0, where this is resolved. Can you confirm?

**Comment by G3z** [comment]
It does, thanks!
