### ISSUE TITLE
Access source items in Screen class commandBar and layout methods

### ISSUE THREAD

**Issue by RaiserWeb** [orchidsoftware/platform#1277]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to access model data inside commandBar or layout methods. Eg In layout, for show/hide conditions on form elements based on model data, or in commandBar, to add an attribute to a button eg
```
Link::make(__('Edit'))
   ->route('platform.classes.edit', $model->id)
   ->icon('pencil'),
```

**Describe the solution you'd like**
Is making the private $source var a solution? 

**Describe alternatives you've considered**
An alternative to the commandBar issue is using a method call instead, and then a redirect. I don't know of an alternative to the layout issue.

Thanks

**Comment by tabuna** [comment]
I am using class properties to define

```php
public function query(): array
{
    $this->model = $model;
    // ...
}
```

Then you can use this data in the `commandBar` too

```php
Link::make(__('Edit'))
   ->route('platform.classes.edit', $this->model->id)
   ->icon('pencil'),
```

I think we could change the visibility of the `$source` property. 
But it is important to understand that then you will not receive IDE hints, and also the value may be empty for some calls

**Comment by RaiserWeb** [comment]
Hi @tabuna , thanks for the above, this does give me a solution to use.
