### ISSUE TITLE
Wrapping class to all layouts

### ISSUE THREAD

**Issue by RaiserWeb** [orchidsoftware/platform#1278]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to add a class to the parent of a layout. Either to give it distinct styling, or to add a until class such as border or margin.

**Describe the solution you'd like**
It would be great if all layouts were able to accept a cutom class string (like the Link layout) that inserted the class string into the parent div of the layout

**Describe alternatives you've considered**
Making my own custom layouts that have specific classes added to the view, but this adds lots of extra files

**Comment by tabuna** [comment]
Hi, I'm not sure if writing CSS code on screens is a good idea. 
We also have a [wrapper class](https://orchid.software/en/docs/layouts/wrapper/) that allows us to do much more.


An intermediate link between the "Custom Template" and the standard layers can serve as a "Wrapper", with which
it is available to specify where other layers should be displayed.

```php
public function layout(): array
{
    return [
        Layout::wrapper('myTemplate', [
            'foo' => [
                RowLayout::class,
                RowLayout::class,
            ],
            'bar' => RowLayout::class,
        ]),
    ];
}
```

The variables `foo` and` bar` will be passed to the `myTemplate` template, containing the already collected `View`, which can be displayed:


```html
<div class="row">
    <div class="col-7 border-right">
        @foreach($foo as $row)
            {!! $row !!}
        @endforeach
    </div>
    <div class="col-5 no-gutter">
        {!! $bar !!}
    </div>
</div>
```

The variables from the query are also available in the template.


What form would you like to get with your own CSS rules? 
Maybe we can improve the experience without adding new layers?

**Comment by RaiserWeb** [comment]
Thanks for the information, this will enable me to be flexible with the layouts and will solve the issue.

Just to clarify, I was referring to class names added to layouts (not custom CSS)  eg in the layout columns,blade,php
```
<div class="row {{ $customClassString ?? ''}}">
    @foreach($manyForms as $key => $column)
        <div class="col-md">
            @foreach($column as $item)
                {!! $item ?? '' !!}
            @endforeach
        </div>
    @endforeach
</div>
```

Thanks for the great package, I am finding it very useful
