### ISSUE TITLE
Bulk Actions

### ISSUE THREAD

**Issue by bubunamawu** [orchidsoftware/platform#1296]
**Is your feature request related to a problem? Please describe.**
In the table layout is should be possible to select several items at a time and perform an action such as delete on all of them at once.

**Describe the solution you'd like**
A check box on each row to indicate which items are to be affected by the action
a check box in the header to select all items displayed 

**Additional context**
After selection the rows. There should be a drop down for the action and possibly a modal to input additional infomation relating to the action.

**Comment by tabuna** [comment]
Hey @bubunamawu  you can add checkboxes to your table. 

For example, how to do this for an existing table with users:

```php
TD::set('Name')
    ->cantHide()
    ->render(function (User $user) {
        return CheckBox::make('users[]')
            ->value($user->id)
            ->placeholder($user->name)
            ->checked(false);
    }),
```

Visually it will look like this:
![image](https://user-images.githubusercontent.com/5102591/95691770-56d6a780-0c2a-11eb-8724-a276870d95bd.png)


Selected will be sent into action.

**Comment by bubunamawu** [comment]
Thank you very much

**Comment by protocyber** [comment]
Thank you very much @tabuna . But how to add checkbox into column header which can be used to select all rows?

**Comment by Velisariy** [comment]
> Thank you very much @tabuna . But how to add checkbox into column header which can be used to select all rows?

Same question

**Comment by tabuna** [comment]
For such things, you can use packages, for example: https://github.com/lintaba/orchid-tables

**Comment by hqin2013** [comment]
Hi @tabuna 

How to get the checked row's value ("users[]") from the table in a **Modal window**?

ps: Try to use [lintaba/orchid-tables](https://github.com/lintaba/orchid-tables), but it is not compatible with Orchid 13 now.

**Comment by e1sep0** [comment]
> Hi @tabuna
> 
> How to get the checked row's value ("users[]") from the table in a **Modal window**?
> 
> ps: Try to use [lintaba/orchid-tables](https://github.com/lintaba/orchid-tables), but it is not compatible with Orchid 13 now.

I found solution:
1. Make your modal `Layout::modal('modalName', ModalLayout::class)`
2. In checkbox add attribute form:
```php
TD::make()
                ->render(
                    fn (User $user) => CheckBox::make('users[]')
                        ->value($user->id)
                        ->form('screen-modal-form-modalName')
                        ->checked(false)
                ),
```

And in your action, you will receive users array
