### ISSUE TITLE
How to filter from two tables? Model belongsTo

### ISSUE THREAD

**Issue by K12AZ** [orchidsoftware/platform#1304]
Hi, 

I am trying to filter from two tables. 

I have two Model, User, and Orders, 

` /**
     * The orders that belong to the user.
     */
    public function user()
    {
        return $this->belongsTo('App\User','user_id');
    }`

So I was able to generate a table view like this. (refer screenshot)

![image](https://user-images.githubusercontent.com/63956726/96024172-fa6fc400-0e85-11eb-83c5-97e9deaec76b.png)

In this table, how can I search for email? 

Looking for help.

TIA

**Comment by tabuna** [comment]
For complex filters, you can use:
```php
php artisan orchid:filter OrderFilter
```

You can check it out in the [documentation](https://orchid.software/en/docs/filters/#natural-filter).
You already have an [example](https://github.com/orchidsoftware/platform/blob/74beac8142c1251181d38c5f041da95d78ed08af/stubs/app/Orchid/Filters/RoleFilter.php#L1) of its use in the installation on the page with the list of users.

![screencast-localhost_8000-2020 10 14-02_15_12](https://user-images.githubusercontent.com/5102591/96027065-034d9f00-0e60-11eb-8a24-816355dfef53.gif)

**Comment by K12AZ** [comment]
Yes, I saw this, But can't we do what I suggested? 

For example in ORDER MODEL. 

```
  /**
     * @var array
     */
    protected $allowedFilters = [
        'name',
        'data', 
        'hash' ,
        'user.email',    -----> USER MODEL 
        'created_at',
        'deleted_at',
    ];
```

Like this?

**Comment by tabuna** [comment]
Filters using an HTTP request do not know how to influence relations.
