### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#1306]
There are many ways to contribute to the community without the desire or the required skills. One of the best is to attract new developers. If you know or meet people with programming skills, introduce them to the community and ask if they might be interested in developing Laravel Orchid.

But it would also be great to have a reviews section. I hope that over the years, the project has helped you. And I ask you to write about this so that your review would be shown on the main page.

![image](https://user-images.githubusercontent.com/5102591/96202540-2f544780-0f68-11eb-855f-6c88544dc536.png)

Please use the following template:

- Full name
- Country, city
- Photo
- Informative text of any length

**Comment by PSalador** [comment]
Павлов Павел
Россия. Шира
Для меня Orchid появился одновременно с Laravel, так как для обучения Laravel начал искать админку и выбор остановил на Orchid Platform. В данный момент все проекты  делаю на Orchid. Самое главное преимущество  Orchid, что можно быстро стартануть, и за очень короткое время можно перейти к самой сути проекта. А дальше легко масштабировать проект. Ещё огромный плюс в Orchid Platform, эта структура  организации кода изучение которой  помогает ускорить разработку и в других проектах.

**Comment by GeneralZorgan** [comment]
Владислав Пономарев
Россия, Краснодар

До встречи с Orchid постоянно приходилось писать админку с нуля. Удовольствие это было такое себе. Впервые услышал о Orchid в подкасте на "Пятиминутка PHP". Почитав документацию, решил попробовать и пользуюсь до сих пор. Orchid подходит под большинство, разрабатываемых мной проектов, и отлично масштабируется. Если у вас есть какие-то вопросы, то вам всегда помогут в официальном Telegram-чате проекта. Хотя ответы на большинство вопросов есть в документации.

**Comment by lemyskaman** [comment]
Lemys Alejandro López López
Venezuela, Valencia.

![Uploading IMG_20200430_222719.jpg…]()

The laravel ecosystem is vast as mature. But as an aged web developer, I realize that "richness" is not enough,  I need a stable and well-designed open source platform, in terms of architecture and principles which allows to me and my team ship solutions fast, with an easy to maintain base code and without all the common fancy "automatic magic"  that might be complex to adapt and useless most of the time. Orchid-platform is all that and more, Orchid-Platform boost out our productivity in levels that i can't almost not to believe with beautiful and expressive resulting code. Orchid-platform is application-nature agnostic but it fits like no other package on administrative kind of Solutions.
