### ISSUE TITLE
Return from listener only input, without layout

### ISSUE THREAD

**Issue by redRussianUnstoppable** [orchidsoftware/platform#1307]
That was great if admin can return only input in screen, without new layout

![7JA37f3hNrU](https://user-images.githubusercontent.com/71930677/96303803-7730a880-1014-11eb-83e1-0eb3fe8d815f.jpg)

**Comment by tabuna** [comment]
Hey @redRussianUnstoppable. What do you have in mind? 

You can specify all of these fields in the listener layout. and on the screen you will only have:
```php
public function layout(): array
{
    return [
        ListenerLayout::class
    ];
}
```

**Comment by redRussianUnstoppable** [comment]
Sorry, my mistake ¯\_(ツ)_/¯, its really work, thx for help !
