### ISSUE TITLE
Resources CSS and JS 404

### ISSUE THREAD

**Issue by JamesWrightDev** [orchidsoftware/platform#1322]
**Describe the bug**
In staging (Laravel Forge) the Orchid resources CSS and JS are not found, giving a 404. 

Have tried `php artisan orchid:link` but this has not solved the issue. 

Is this an issue with the Symlink or is there something else I can do to resolve this?

On the admin routes `dev-foobar.io/admin` the following is in the head

```
<link rel="stylesheet" type="text/css" href="http://dev-foobar.io/resources/orchid/css/orchid.css?id=01005b7515df1f41ec1f">

```

Files can be manually access here

```
dev-foobar.io/admin/resources/orchid/css/orchid.css?id=01005b7515df1f41ec1f"
```

**Server (please complete the following information):**
  - Platfrom Version: 9.4.4
  - Laravel Version: 8.0
  - PHP Version:   7.4 

**Additional context**

Nginx Config. 

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name .dev-foobar.io;
    server_tokens off;
    root /home/forge/dev-foobar.io/public;


    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.html index.htm index.php;

    charset utf-8;

    # FORGE CONFIG (DO NOT REMOVE!)
    include forge-conf/dev-housemates.io/server/*;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/dev-housemates.io-error.log error;

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
    
}
```

**Comment by tabuna** [comment]
Hey @JamesWrightDev. 
I can't open your domain. I think this is still an example.

If you have css/scripts available at:
```
dev-foobar.io/admin/resources/orchid/css/orchid.css?id=01005b7515df1f41ec1f
```

Then you didn't need to create a symbolic link. Delete it manually

**Comment by JamesWrightDev** [comment]
Hi @tabuna, Thanks for getting back to me, 

That was an example, the real url is 

https://occupy.dev-housemates.io/admin
https://occupy.dev-housemates.io/admin/resources/orchid/css/orchid.css?id=01005b7515df1f41ec1f

I have removed the symlink and the file is still not found

**Comment by tabuna** [comment]
Do you still have a public/resource directory?

**Comment by tabuna** [comment]
Path selection logic

1. If there is a setting for `app.mix_url`, we will use it.
2. If there is a `resource` directory. Then contact her for data
3. We return with the controller with the full cache and headers.

**Comment by JamesWrightDev** [comment]
`Do you still have a public/resource directory? If yes, then remove it` 

@tabuna this has resolved the issue!

**Comment by tabuna** [comment]
Excellent! Cool project. Good luck

**Comment by JohanQueo** [comment]
> `Do you still have a public/resource directory? If yes, then remove it`
> 
> @tabuna this has resolved the issue!

This Works! like a charm!
