### ISSUE TITLE
Buttons with cross-class method.

### ISSUE THREAD

**Issue by somoza** [orchidsoftware/platform#1338]
Hi! I want to add a delete button to the list screen. As I already have the remove() method in the EditScreen class and in order to apply DYY concept, I would love to do this instead of duplicate the method in the ListScreen class:

```
Button::make('Delete')
                             ->icon('trash')
                             ->method('MyModelEditScreen@remove');
```

Could be possible on some way?

Thanks in advance.

**Comment by tabuna** [comment]
Hi, you can use traits or inheritance. And also call it using a simple route:

```php
Button::make('Delete')->action(route('name', [
    'action' => 'The name of your method'
]));
```
