### ISSUE TITLE
Modal Title appears in button

### ISSUE THREAD

**Issue by RaiserWeb** [orchidsoftware/platform#1357]
**Describe the bug**
Title started appearing in button after recent update

**To Reproduce**
Create a Modal in command bar, set title. eg
```
            ModalToggle::make(__('Add Default Availability'))
                ->icon('plus')
               ->title('Add')
                ->method('add_availability')
                ->modal('add_default_availability')
                ->asyncParameters([
                    'class' => $this->class,
                ]),
```

**Expected behavior**
Should not see title

**Screenshots**
![image](https://user-images.githubusercontent.com/4104725/98842970-37f24d80-2442-11eb-9e48-7ce26d2a4521.png)

Version 9.8.2

**Comment by tabuna** [comment]
Hey @RaiserWeb, the update hasn't been for the last year, but the headlines were not affected.
For models, there is a separate method for setting them.
Both for the button and himself:

```php
Layout::modal('exampleModals', [
    Layout::rows([]),
])
    ->title('Window title');
````

or

```php
ModalToggle::make('Open async modal')
    ->modal('exampleModals')
    ->modalTitle('Dynamics title')
```
