### ISSUE TITLE
Typo in 1st step of the 4-small-steps-quick-start-tutorial

### ISSUE THREAD

**Issue by jensmusleh** [orchidsoftware/platform#1367]
I am a beginner in Laravel and stumpled over Orchid and it seems exactly what I was looking for. Great work - thank you.

In the first step of the nice 4-small-steps-quick-start at https://orchid.software/en/docs/quickstart/ there seems to be a small problem. I was not able to enter any mail address in the Relation field. There was also no stack trace to figure out whats wrong. Only hint was a message below the input field "The results could not be loaded".

So I changed the line
`use App\User;`
to
`use App\Models\User;`
and then it worked.

Regards
Jens

**Comment by tabuna** [comment]
Hey @jensmusleh, thanks. Before Laravel 8, there was no `Models` directory in the structure.
I brought in the edits by indicating it. You can also do it yourself. Each page has an edit button.

![image](https://user-images.githubusercontent.com/5102591/99183915-80ff1600-2750-11eb-9456-37b3abc2cd03.png)
