### ISSUE TITLE
Route matching breaks on change route order

### ISSUE THREAD

**Issue by RowanLivewall** [orchidsoftware/platform#1368]
**Describe the bug**
Switching route definition breaks route. Route matching could be better
**To Reproduce**
Here i can access the platform.systems.label.edit route:
`Route::screen('labels/{label}/edit', LabelEditScreen::class)->name('platform.systems.labels.edit');
Route::screen('labels', LabelListScreen::class)->name('platform.systems.labels');`
here i can't: 
`Route::screen('labels', LabelListScreen::class)->name('platform.systems.labels');
Route::screen('labels/{label}/edit', LabelEditScreen::class)->name('platform.systems.labels.edit');`

**Expected behavior**
When i try to access label/1/edit it should always match labels/{label}/edit. Order should not make a difference (in this case)

**Additional context**
Version: 7.18.0

**Comment by tabuna** [comment]
Hi @RowanLivewall  this is the behavior of routes. Unfortunately, there is nothing we can do about it now. In more recent versions, we have thought of better things. (Try it!)

As for the topic, we explain this behavior in the [documentation](https://orchid.software/en/docs/screens/#registering-routes).
