### ISSUE TITLE
Translations for the screen's, layout's class properties 

### ISSUE THREAD

**Issue by Hrache** [orchidsoftware/platform#1373]
**Is your feature request related to a problem? Please describe.**
The problem is in property translations such are $name and $description in the Screen classes, layout classes that ain't possible to handle by the laravel translation helper functions ...

**Describe the solution you'd like**
I've no idea what to suggest.

**Describe alternatives you've considered**
No any ...

**Additional context**
No additional context only thanks for the attention :)

**Comment by tabuna** [comment]
Hey @Hrache , the `__ ()` function is automatically applied to them.
There is also no problem in overriding them in the query method.

**Comment by Hrache** [comment]
Hi, thanks for the feedback. So means I can only have the index of the translation and everything will be alright. Thanks very much.
