### ISSUE TITLE
Translation for persian language farsi

### ISSUE THREAD

**Issue by wikiccu** [orchidsoftware/platform#1393]
Hello
I would ask you is there any plan for translation to the Persian/farsi language ?

**Comment by tabuna** [comment]
Hey @wikiccu, I have no plans to add languages that I do not speak.
 But I will gladly accept PR for adding them to the repository.

**Comment by wikiccu** [comment]
Sure I asked this because I wanted to send PR for translation 
thank you ill work on it.
