### ISSUE TITLE
Table inside card is possible ?

### ISSUE THREAD

**Issue by jouniikaheimo** [orchidsoftware/platform#1464]
Any method use table in cards ?

**Comment by tabuna** [comment]
What do you want to use the table in the card for? After all, it serves to display one information visually?

![image](https://user-images.githubusercontent.com/5102591/102346547-1429a680-3fb0-11eb-956b-c4641614bb80.png)
Maybe using Compendium is right for you?



But if you still want to display the table as a description of the card, then you can get the HTML of the table as follows:

```php
use Orchid\Screen\Repository;

$layout = new YorTable();

$html = $layout
        ->build(new Repository())
        ->render();
```

**Comment by jouniikaheimo** [comment]
ah ok that help lot of me :) i make dashboard where is lasted registered users etc.. and that i use cards...
