### ISSUE TITLE
Support for Mongodb Database Driver (Ability to override User model via config)

### ISSUE THREAD

**Issue by level39** [orchidsoftware/platform#1469]
**Is your feature request related to a problem? Please describe.**
Yes. Currently, the platform uses `Orchid\Platform\Models\User` as the `User` model and since there's no way to define the user model through configuration, we're stuck on using the `Illuminate\Foundation\Auth\User` as `Authenticatable`. 

**Describe the solution you'd like**
Allow the `User` model used by the platform to be configured through `platform.php` config file. 

**Additional context**
[MongoDB Driver](https://github.com/jenssegers/laravel-mongodb/issues) uses it's own `Authenticatable` which is required for native authentication when using the Mongodb driver.

**Comment by tabuna** [comment]
Hey @level39 , we do not necessarily require this particular class (you can change the published files). 
This is done for convenience only, as we expect traits and castes to be specified.

**Comment by level39** [comment]
Yeah, I'm already using the default model but the problem is with the AdminCommand which explicitly references the Orchid `User` model:

https://github.com/orchidsoftware/platform/blob/b0e77dfb02ad1c66a172912677aade183f41a110/src/Platform/Commands/AdminCommand.php#L10

Second problem is with the Roles model inside UserAccess trait:

https://github.com/orchidsoftware/platform/blob/b0e77dfb02ad1c66a172912677aade183f41a110/src/Access/UserAccess.php#L16

If you navigate to the Role mode, you'll see it references `Illuminate\Database\Eloquent\Model` which does not work with mongodb:

https://github.com/orchidsoftware/platform/blob/b0e77dfb02ad1c66a172912677aade183f41a110/src/Platform/Models/Role.php#L8

Also, I've published all publishable assets and these models are not published as part of it.

I've created a pull-request to fix this:

https://github.com/orchidsoftware/platform/pull/1470

Let me know if it requires any edits.

**Comment by level39** [comment]
Haven't tested yet, but the docs do allow you to override the default models:

[Model Classes](https://orchid.software/en/docs/configuration/#model-classes)
