### ISSUE TITLE
Autofocus filter input on popup show

### ISSUE THREAD

**Issue by pqr** [orchidsoftware/platform#1475]
When I click on filter funnel icon in table a small popup shows input and apply button.
Unfortunately this input field is not focused by defaults so I have to make another click to focus input before start typing.

Would be nice to autofocus this input field after popup showed (screenshot)

<img width="487" alt="image" src="https://user-images.githubusercontent.com/451007/103133075-732aa200-46b9-11eb-823c-8cdb42556dcb.png">

**Comment by tabuna** [comment]
Hey @pqr! Please see the latest issue. It should be like this:


https://user-images.githubusercontent.com/5102591/115941125-ce747180-a4ac-11eb-8cf8-a4169194d002.mp4
