### ISSUE TITLE
Form update in Modal

### ISSUE THREAD

**Issue by vallter2** [orchidsoftware/platform#1477]
I have problem with update data from modal form... I have screen A (Model\A) and in that screen have table layout for Model\B. I create successfully Modal and Form to edit data from table (Model\B), but when I click on Apply/Save and call method "updateB" I got a error...

```
public function updateB(B $ep, Request $request)
    {
        $ep->fill($request->get('episodes'))->save();

        Alert::info('You have successfully created an post.');
    }
```
`Argument 1 passed to App\Orchid\Screens\A\AEditScreen::updateB() must be an instance of App\Models\B, null given`

**Comment by tabuna** [comment]
Can you attach the complete code or create a minimal example to reproduce?

**Comment by vallter2** [comment]
Part of code:

in VideoEditScreen:
```
public function layout(): array
    {
        return [

 Layout::modal('exampleModal', [
                EpisodesEditLayout::class,
            ])->async('asyncGetData')->applyButton('Update')->closeButton('Close'),

...
```


```
public function asyncGetData(Episodes $episode): array
    {
        return [
            'episode' => $episode,
        ];
    }
```

```
    public function asyncUpdateEpisode(Episodes $episode, Request $request)
    {

        
        $episode->fill($request->get('episode'))->save();

        Alert::info('You have successfully created an post.');
    }
```

I have filling the problem is when I click on Update in Modal box all page refresh, and array $episode are empty. Any option to call ajax update function?

**Comment by mucan54** [comment]
You have to use ModalToggle asyncParameters method to pass variable to modal layout as mentioned https://orchid.software/en/docs/modals/#asynchronous-data-loading so your modal toggle should be like this:

```
ModalToggle::make('Open async modal')
    ->modal('exampleModal')
    ->modalTitle('Dynamics title')
    ->method('asyncGetData')
    ->asyncParameters($this->episode)
```

and you can add global episode variable in query method to can use $this->episode like: 

```
    public function query(Episode $episode): array
    {
        $this->exists = $episode->exists;

        if($this->exists){
            $this->name = 'Edit Episode';
            $this->episode = $episode;
        }

        return [
            'episode' => $episode
        ];
    }
```

for your example I guess you have a video object so you can use something like this : 


    public function query(Video $video): array
    {
        $this->exists = $video->exists;

        if($this->exists){
            $this->name = 'Edit Video';
            $this->episode = $video->episode;
        }

        return [
            'video' => $video
        ];
    }

**Comment by vallter2** [comment]
Hmm... I have ModalToggle and set asyncParameters. Delete function work ok, but update have problems...

I have two Models  Video and Episodes, in Video Edit Screen I show table with Episodes with query:

```
       return [
            'video' => $video,
            'episodes' => Episodes::where('video_id', $this->videoid)->filters()->defaultSort('list_order', 'asc')->paginate(),
            'episode' => $episode
        ];

// in Layout call EpisodesListLayout, and at top Modal EpisodesListLayout::class
```
In episode table layout I created ModalToggle 
```

TD::set('delete')->render(function (Episodes $episode) {
                return Button::make('')
                    ->icon('trash')
                    ->parameters(['id' => $episode->id])
                    ->confirm('Are you sure you want to delete?')
                    ->method('deleteEpisode')
                    ->render();
            }),
            TD::set('edit', 'Uredi')->render(function (Episodes $episode) {
                return  ModalToggle::make('Uredi')
                ->modal('exampleModal')
                ->method('asyncUpdateEpisode')
                ->asyncParameters($episode);
            })
```

In Video Edit Screen I create two functions one deleteEpisode (works ok), second asyncUpdateEpisode (show me error "null given")

**Comment by tabuna** [comment]
The asynch prefix is used when you want to replace the source of information. It is not needed here:

```php
public function updateEpisode(Episodes $episode, Request $request)
{
      $episode->fill($request->get('episode'))->save();

      Alert::info('You have successfully created an post.');
}
```

You also need to change the passing of parameters in the call method:

```php
TD::set('edit', 'Uredi')->render(function (Episodes $episode) {
    return  ModalToggle::make('Uredi')
        ->modal('exampleModal')
        ->method('updateEpisode')
        ->asyncParameters([
            'episode' => $episode->id
        ]);
})
````

You can see an example of work on the screen list of users. 

Button in table:
https://github.com/orchidsoftware/platform/blob/c8d09872ef6e3eb591e9c60a95f1a766a0fb3e3c/stubs/app/Orchid/Layouts/User/UserListLayout.php#L37-L49

Screen:

https://github.com/orchidsoftware/platform/blob/c8d09872ef6e3eb591e9c60a95f1a766a0fb3e3c/stubs/app/Orchid/Screens/User/UserListScreen.php#L79-L106

**Comment by vallter2** [comment]
Now I got error...

`Argument 1 passed to Illuminate\Database\Eloquent\Model::fill() must be of the type array, string given, called in ...`

**Comment by tabuna** [comment]
The variable you want to use to fill is not an array. Check the data you are sending

**Comment by vallter2** [comment]
Finally... The key is in use INPUT not GET

`$episode->fill($request->input('episode'))->save();`

Thank you
