### ISSUE TITLE
Confirm on Button Doesn't Work

### ISSUE THREAD

**Issue by mucan54** [orchidsoftware/platform#1482]
```
Button::make('Remove')
                ->icon('trash')
                ->method('remove')
                ->confirm('Delete ?')
```

In opened dialog delete button doesn't work.

**Comment by tabuna** [comment]
The given code works for me. Which version are you using? Are there any errors in the browser?

**Comment by mucan54** [comment]
Nothing on browser. I'm using Safari.

`"orchid/platform": "^9.14"`

![Screen Shot 2020-12-29 at 00 38 43](https://user-images.githubusercontent.com/5364325/103244503-4c48c600-496e-11eb-9cc5-5c0e311d1c22.png)


![Screen Shot 2020-12-29 at 00 38 51](https://user-images.githubusercontent.com/5364325/103244496-481ca880-496e-11eb-86db-f40fb2e2aa80.png)

**Comment by tabuna** [comment]
I was able to reproduce this.

**Comment by tabuna** [comment]
Could you please try the new version 9.14.4?

**Comment by mucan54** [comment]
Fixed. Thank you so much :) 👍

**Comment by mucan54** [comment]
After update I can not view errors, can it be because of update or because of my environment?
![Screen Shot 2020-12-30 at 00 03 22](https://user-images.githubusercontent.com/5364325/103313889-74016200-4a32-11eb-9cf6-dd73803a1363.png)
