### ISSUE TITLE
Tables pagination are not showing properly on mobile devices.

### ISSUE THREAD

**Issue by astersnake** [orchidsoftware/platform#1490]
**Describe the bug**
Tables pagination are not showing properly on mobile devices. The page numbers overflow in the left corner.

**To Reproduce**

  1. Create a table with multiple pages
  2. Check the table with a mobile device 

**Expected behavior**

Show page numbers properly.

**Screenshots**

<img width="463" alt="Captura de Pantalla 2021-01-07 a la(s) 22 12 06" src="https://user-images.githubusercontent.com/22416775/103962285-63896f80-5135-11eb-9cc7-b1709f8a92bb.png">

**Comment by tabuna** [comment]
Hi, can you check the release  [9.15.2](https://github.com/orchidsoftware/platform/releases/tag/9.15.2)

**Comment by astersnake** [comment]
Hi, is functional now. Thanks! In the future maybe would be an improvement if the number of pages is lower on mobile devices, so you can avoid horizontal scrolling.

**Comment by tabuna** [comment]
To solve this completely, I added the same method:

```php
/**
 * The number of links to display on each side of current page link.
 *
 * @return int
 */
protected function onEachSide(): int
{
    return 3;
}
```

This indicates how many elements should be on the page. https://laravel.com/docs/8.x/pagination#adjusting-the-pagination-link-window

Using this method, you can dynamically change the value. For example, we can view the user-agent (Example https://github.com/jenssegers/agent) and show a different amount depending on the device:


```php
/**
 * The number of links to display on each side of current page link.
 *
 * @return int
 */
protected function onEachSide(): int
{
    if((new Agent())->isMobile()){
        return 0;
    }

    return 3;
}
```

I think that this option would be a good solution and, at the same time, quite versatile.

**Comment by tabuna** [comment]
Feel free to open again.

**Comment by astersnake** [comment]
Working perfectly, amazing solution as always @tabuna. Thanks.
