### ISSUE TITLE
ItemMenu does not have the possibility to open the url/route in a new window

### ISSUE THREAD

**Issue by rabol** [orchidsoftware/platform#1510]
**Is your feature request related to a problem? Please describe.**
A ItemMenu::make() does not have the possibility to open the url or route in a new window

**Describe the solution you'd like**
It would be nice to have the possibility to open links in a new window

**Comment by tabuna** [comment]
This issue has been unanswered for a long time. Opening in a new tab:

```php
Menu::make('Google')
    ->href('https://google.com')
    ->target('_blank'),
```
