### ISSUE TITLE
How to add a currency format for HTML table data?

### ISSUE THREAD

**Issue by chanakaDe** [orchidsoftware/platform#1512]
Hi, 
I have created a layout to display some data in a table. 

```
protected function columns(): array
    {
        return [
            TD::make('brand', 'Brand')
                ->sort()
                ->filter(TD::FILTER_TEXT),

            TD::make('model', 'Model')->sort()->filter(TD::FILTER_TEXT),
            TD::make('package_name', 'Package')->sort()->filter(TD::FILTER_TEXT),
            TD::make('package_price', 'Package price (€)')->align(TD::ALIGN_RIGHT)->sort(),
            TD::make('device_price', 'Device price (€)')->align(TD::ALIGN_RIGHT)->sort(),
        ];
    }
```

And this is the output I have.

![Screenshot_2021-01-15 Sparhandy Tariffs Prices - Laravel(1)](https://user-images.githubusercontent.com/7803591/104725053-d6947680-5731-11eb-8329-77a05224e6c2.png)

I need to add currency features to Package price  and device price. This is the format I need.
$ 199.99 (The standard currency representation). 

How can I do this in my code? 
I searched, but no luck. 

Thank you in advance.

**Comment by tabuna** [comment]
Hey @chanakaDe  you can control the output of the string like:

```php
TD::make('device_price', 'Device price (€)')
    ->align(TD::ALIGN_RIGHT)
    ->sort()
    ->render(function($model) {
        return "$ ".number_format($model->device_price, 2);
    })
```

**Comment by chanakaDe** [comment]
@tabuna 
It works and thank you so much for the great framework and great help you provide here.
