### ISSUE TITLE
Error: Target class [role] does not exist.

### ISSUE THREAD

**Issue by sprklinginfo** [orchidsoftware/platform#1518]
**Describe the bug**
- Just installed the package (ver 7.18.0) in my working laravel 7.29.2 project. 
- My User model is under \App\Models, so I had to manually update the class with the instruction that 'You will need to update this manually.Change "extends Authenticatable" to "extends \Orchid\Platform\Models\User" in your User model'
- updated the 'config\platform.php' file, cleared cache...;
when visiting http://app.url/admin in the browser, I get:

Illuminate\Contracts\Container\BindingResolutionException
Target class [role] does not exist.

Any idea why I got this error?

**Comment by tabuna** [comment]
Hi @sprklinginfo. Version `7. *` is no longer supported. Please try more recent versions
