### ISSUE TITLE
Create new user via Systems -> Users screen

### ISSUE THREAD

**Issue by pqr** [orchidsoftware/platform#1527]
**Is your feature request related to a problem? Please describe.**
With default Orchid installation there is no possibility to create a new user via UI (on Systems -> Users screen), there is no "Add user" or "Create user" button.

I think it would be nice to have an option to create users from UI with default Orchid installation.

**Describe the solution you'd like**
I want to add "+ Add" button on Users screen.

One important addition: since password field in database have no default value I propose to add a "Password" field on user create/edit screen.
- When Creating a new user the Password field will be mandatory to fill in. This to prevent user creation with empty password by accident.
- When editing existing user the Password field might be left blank - means do not change current password.

Let us discuss this proposal. If agreed, I will implement and make a Pull Request.

**Comment by tabuna** [comment]
Hi, do you want a separate page with roles and permissions or a simple modal with email and password?

**Comment by pqr** [comment]
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/451007/104905667-bb28a600-5993-11eb-939f-7e33f11aac32.png">


<img width="1174" alt="image" src="https://user-images.githubusercontent.com/451007/104905597-a5b37c00-5993-11eb-82fc-bc77c394893e.png">

**Comment by dhb52** [comment]
`Role/User` data management together into a `Role and User` Menu group.
