### ISSUE TITLE
Uploading file to non-public storage using Field Upload gives 404 on Link to File

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [orchidsoftware/platform#1532]
**Describe the bug**

Switching Field 

```
Upload::make()->storage('local_private')
```

and filesystem.php

```
'local_private' => [
            'driver' => 'local',
            'root'   => storage_path('app/private'),
        ]
```

Gives a Link to File which 404s:

![image](https://user-images.githubusercontent.com/1327332/105421898-c0f3e500-5c3a-11eb-990d-a6a308fa157f.png)

![image](https://user-images.githubusercontent.com/1327332/105421810-9e61cc00-5c3a-11eb-8b9f-fbb5f5ad7c1c.png)

Thinking:

`/resources/views/fields/upload.blade.php`

```
@if($storage === 'public')
<div class="form-group">
    <a href="#" data-action="click->fields--upload#openLink">
        <small>
            <x-orchid-icon path="link" class="mr-2"/>

            {{ __('Link to file') }}
        </small>
    </a>
</div>
@endif
```

Should work?

**Comment by Caffe1neAdd1ct** [comment]
Another thought would be something like:

```php
@if(Config::get('filesystems')['disks'][$storage]['visibility'] ?? 'private' === 'public')
```

**Comment by Caffe1neAdd1ct** [comment]
Starting to get ugly in the view:

```php
@if(Config::get('filesystems')['disks'][$storage ?? 'public']['visibility'] ?? 'private' === 'public')
```

**Comment by tabuna** [comment]
Hey @Caffe1neAdd1ct. Please tell me what the problem for you is. Link or model window itself?

I think should only hide the link while leaving the ability to edit information in the database (modal window). As far as binding to `public` is concerned, it is not suitable for people using` s3`. We must check the name of the `visibility` property.

**Comment by Caffe1neAdd1ct** [comment]
Thanks @tabuna, issue is clicking Link when using non "public" filesystem config. Would the solution above (https://github.com/orchidsoftware/platform/issues/1532#issuecomment-765015369) be suitable in the upload.blade.php view file? Or would we need to change this?
