### ISSUE TITLE
Notification url

### ISSUE THREAD

**Issue by mucan54** [orchidsoftware/platform#1539]
Notification url doesn't work in safari. Can not click.

<img width="1315" alt="Screen Shot 2021-01-25 at 16 55 52" src="https://user-images.githubusercontent.com/5364325/105715085-33f8a680-5f2e-11eb-969d-94a7ba0f1943.png">

**Comment by tabuna** [comment]
Hey @mucan54, Can you please check the new release https://github.com/orchidsoftware/platform/releases/tag/9.19.4 
It works for me in Safari now.
