### ISSUE TITLE
Can't have the same label in main menu with different titles

### ISSUE THREAD

**Issue by pixelpeter** [orchidsoftware/platform#1543]
**Describe the bug**
It's not possible to define the same label twice in the main menu although these are group by different titles.
Currently the second entry will overwrite the first one

**To Reproduce**
Define the main menu like this
```
ItemMenu::label('My Label')
    ->title('FirstGroup')
    ->icon('briefcase'),

ItemMenu::label('My Label')
    ->title('SecondGroup')
    ->icon('layers'),   
```   

**Expected behavior**
In my opinion this should be possible

**Screenshots**
- n.a.

**Desktop (please complete the following information):**
- not dependend on OS

**Smartphone (please complete the following information):**
- not dependend on device

**Server (please complete the following information):**
  - Platform Version: [e.g. 9.19.0]
  - Laravel Version: [e.g. 8.24.0]
  - PHP Version:  [e.g. 7.4.13]
  - Database:  [MySql]
  - Database Version:  [5.7.31]

**Additional context**
n.a.

**Comment by tabuna** [comment]
We automatically generate a `slug` from the text specified in the `label`. And it is he who must be unique. You can specify it yourself, then elements with the same names will be displayed.

```php
ItemMenu::label('My Label')
    ->slug('unique-name-for-children')
    ->title('FirstGroup')
    ->icon('briefcase'),

ItemMenu::label('My Label')
    ->slug('another-unique-name')
    ->title('SecondGroup')
    ->icon('layers'),   
```

You can find more details here https://orchid.software/en/docs/menu/

**Comment by pixelpeter** [comment]
Thanks for this quick answer. 
I'll close the ticket
