### ISSUE TITLE
Matrix field doesn't work

### ISSUE THREAD

**Issue by Lucisu** [orchidsoftware/platform#1564]
**Describe the bug**
The Matrix field doesn't work, even with the example on documentation. The blade view does not receive values properly, only the columns of saved data.

**To Reproduce**

  1. Create a simple form with the field:
  ```php
Matrix::make('example')
         ->columns([
              'Attribute',
              'Value',
              'Units',
          ])
``` 
  1. Insert the data, or manually do it via the database: 

```json
[
    {
        "Units": "a",
        "Value": "b",
        "Attribute": "c"
    }
]
```

  1. Add `{{json_encode($fields)}}` to the first line of `vendor/orchid/platform/resources/views/partials/fields/matrixRow.blade.php`

**Expected behavior**
For some reason, the Matrix will be populated with one line, but with all columns empty, and the json_encoded will be:

`{"0":{},"Attribute":{},"1":{},"Value":{},"2":{},"Units":{}}`

**Screenshots**
![1](https://user-images.githubusercontent.com/46996317/107558210-483cd480-6bb9-11eb-972b-3c2fb4542c5d.jpg)

**Desktop:**
 - OS: Linux Ubuntu 20.04

**Server:**
  - Platfrom Version: 9.19.6
  - Laravel Version: 8.26.1
  - PHP Version:  7.4.3
  - Database:  MySql
  - Database Version:  8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

**Additional context**

If you change the construct function to this:

```php
public function __construct()
    {
        $this
            ->addBeforeRender(function () {
                if ($this->get('value') === null) {
                    $this->set('value', []);
                }

                $value = collect($this->get('value'))
                    ->sortKeys()
                    ->toArray();
                    
                echo json_encode($this->attributes['value']);die; // <<- this line

                ...
```

You'll see that the value is correct: 
`"[{\"Units\": \"a\", \"Value\": \"b\", \"Attribute\": \"c\"}]"`

Can anyone help me?

**Comment by tabuna** [comment]
Hi @Lucisu. I cannot confirm the problem. The field sends good data.
Maybe you are not saving data correctly in the model. For example, I do the following:

### Create migration with JSON column:
```php
$table->json('example');
```

### Added definitions to the model:

```php
protected $fillable = [
    'example'
];

protected $casts = [
    'example' => 'array',
];
```

Accordingly, a simple save works fine, both for insertion and display.

![image](https://user-images.githubusercontent.com/5102591/107856052-d40f6480-6e36-11eb-85c9-3ebea96e9ad0.png)

Please tell us how you save the resulting array. Perhaps you are trying to save as a string, and the field gets a string variant. For this problem? Tell us more, and also try to define the model as I did.

**Comment by Lucisu** [comment]
Hello @tabuna, thanks for the reply! The issue was about the `$casts` attribute, which wasn't set. That's working fine now! 

Thanks a lot for the help :)

**Comment by mesunil2010** [comment]
The casting worked for me. Thanks for the help.
