### ISSUE TITLE
Matrix field is not storing data

### ISSUE THREAD

**Issue by s1x** [orchidsoftware/platform#1565]
**Describe the bug**
Matrix input shows correct values, but is not saved back to the database.

**To Reproduce**

QuestionEditLayout.php

```php
            // Options Part
            Matrix::make('question.options')
                ->title('Options')
                ->horizontal()
                ->columns(['option', 'correct'])
                ->fields([
                    'option'   => Input::make()->type('text')->max(255),
                    'correct' => Switcher::make()->sendTrueOrFalse()->value(1),
                ]),
```
![image](https://user-images.githubusercontent.com/1734844/107855140-f6968300-6e20-11eb-93b3-c4b2ac33d040.png)

QuestionEditScreen.php
```php
...
$question->fill($request->get('question'))->save();
...
```

**Expected behavior**
Values are stored correctly in the database

**Server (please complete the following information):**
  - Platform Version: [e.g. 9.19.4]
  - Laravel Version: [e.g. 8.26.1]
  - PHP Version:  [e.g. 8.0]
  - Database:  [e.g. MySQL]
  - Database Version:  [e.g. 8.0.22]

**Comment by tabuna** [comment]
Hi, I wrote the same field. The value that comes up is completely correct:

```php
      "question" => array:1 [
        "options" => array:2 [
          1 => array:2 [
            "option" => "test enabled"
            "correct" => "1"
          ]
          2 => array:2 [
            "option" => "test disabled"
            "correct" => "0"
          ]
        ]
      ]
```

Can you tell us the details? For example, are you storing the field as JSON? Are you using cast?

**Comment by s1x** [comment]
Hey @tabuna,

thanks for the quick reply. So I've further investigated this and I confirm this is working as you wrote. So maybe I have here rather a question than a bug.

I've using the Matrix as a way to show options which relate to questions. Both have the correct relationship in their model. Options are in a separate table rather than in a json field. 
```php
...
class Question extends Model
{
    use HasFactory, AsSource, Filterable;
...
   public function options()
    {
        return $this->hasMany(QuestionOptions::class, 'question_id');
    }
```


```php
...
class QuestionOptions extends Model
{
    use HasFactory, AsSource, Filterable;
...
    /**
     * Relationship to the Question model
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function question()
    {
        return $this->belongsTo(Question::class, 'question_id');
    }
```

So using the Matrix field for relations rather than a array or json field/column is not possible?


Thanks for taking the time, appreciate it!

**Comment by tabuna** [comment]
The field expects data in the same format as it is transmitted. You can modify your result.

**Comment by s1x** [comment]
Yes, so as Laravel does not offer the function of fillable relations, so using this for relations was a tricky one. I've solved it now by iterating through the array by using an updateOrCreate combined with a check of existing ids vs the id from the request/form.
