### ISSUE TITLE
Installation - Adding admin addPermission() error 

### ISSUE THREAD

**Issue by jay2success** [orchidsoftware/platform#1580]
**Describe the bug**
Hi, i just updated my old project from laravel 7 to 8 then i installed Orchid.
The migration was successful but when adding admin it throw errors:
I noticed the roles table also empty.
Please help.

**Log**
`Installation started. Please wait...
Version: 9.19.8
Copied File [\vendor\orchid\platform\config\platform.php] To [\config\platform.php]
Copied Directory [\vendor\orchid\platform\database\migrations] To [\database\migrations]
Copied Directory [\vendor\orchid\platform\stubs\app\routes] To [\routes]
Copied Directory [\vendor\orchid\platform\stubs\app\Orchid] To [\app\Orchid]
Publishing complete.
Migrating: 2015_04_12_000000_create_orchid_users_table
Migrated:  2015_04_12_000000_create_orchid_users_table (962.07ms)
Migrating: 2015_10_19_214424_create_orchid_roles_table
Migrated:  2015_10_19_214424_create_orchid_roles_table (118.02ms)
Migrating: 2015_10_19_214425_create_orchid_role_users_table
Migrated:  2015_10_19_214425_create_orchid_role_users_table (835.89ms)
Migrating: 2016_08_07_125128_create_orchid_attachmentstable_table
Migrated:  2016_08_07_125128_create_orchid_attachmentstable_table (749.29ms)
Migrating: 2017_09_17_125801_create_notifications_table
Migrated:  2017_09_17_125801_create_notifications_table (262.87ms)
The [\public\storage] link already exists.
The links have been created.
Unable to locate "app/Models/User.php".  Did you move this file?
You will need to update this manually.
Change "extends Authenticatable" to "extends \Orchid\Platform\Models\User" in your User model
Also pay attention to the properties so that they are not overwritten.
Completed!
To create a user, run 'artisan orchid:admin'
To start the embedded server, run 'artisan serve'

Argument 2 passed to Orchid\Platform\ItemPermission::addPermission() must be of the type string, array given, called in app\Orchid\PlatformProvider.php on line 141

  at \vendor\orchid\platform\src\Platform\ItemPermission.php:39
     35▕      * @param string $name
     36▕      *
     37▕      * @return $this
     38▕      */
  ➜  39▕     public function addPermission(string $slug, string $name)
     40▕     {
     41▕         $this->items[] = [
     42▕             'slug'        => $slug,
     43▕             'description' => $name,

  1   \app\Orchid\PlatformProvider.php:141
      Orchid\Platform\ItemPermission::addPermission("platform.systems.users")

  2   \vendor\orchid\platform\src\Platform\OrchidServiceProvider.php:37
      App\Orchid\PlatformProvider::registerPermissions()`

**To Reproduce**

  1. php artisan orchid:install
  2. php artisan orchid:admin admin admin@admin.com password
 
**Expected behavior**
Installing orchid till finish.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Server (please complete the following information):**
  - Platfrom Version: 9.19.8
  - Laravel Version: 8
  - PHP Version:  7.4.6
  - Database:  MySQL
  - Database Version: 5.7.24

**Comment by tabuna** [comment]
> Change "extends Authenticatable" to "extends \Orchid\Platform\Models\User" in your User model Also pay attention to the properties so that they are not overwritten.

Hi, did you make this warning?

**Comment by jay2success** [comment]
Yes i did, already extends Authenticatable on the user model and still the same warning.

**Comment by fadlisaad** [comment]
I fix this by make new migration file to make default role as user

**Comment by jay2success** [comment]
Hi, thank you, i have moved to other solution for now, will come back if i am using this again.
