### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Druget** [orchidsoftware/platform#1581]
@aios  Aios Габриелян Давид Меликович - мошенник! Кинул на $840 долларов, не выполнил работу и пропал.
Номер карты приватбанк 5218572221792372
5218 5722 2179 2372
gabrielyan david - conman! Cheated me out of $$$ 840, didn't do the job, and disappeared.

**Comment by tabuna** [comment]
Привет, ваши деловые отношения ни как не связаны с Orchid.
