### ISSUE TITLE
Nested Column Header

### ISSUE THREAD

**Issue by kenanchristian** [orchidsoftware/platform#1600]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a nested header like this, but can't anything in the Docs.
Is it possible to create this in the current version?

<img width="913" alt="Screen Shot 2021-03-04 at 8 47 18 AM" src="https://user-images.githubusercontent.com/11202498/109898081-3c2ec900-7cc6-11eb-8783-f756f170dbc7.png">

So the "Revenue" Header will expand 4 columns, and the data row will contain the Q1, Q2, Q3, Q4 data.

**Comment by tabuna** [comment]
Hi @kenanchristian, there is no such possibility now. But we are open to PR
