### ISSUE TITLE
Invalid padding for command-bar buttons in mobile view

### ISSUE THREAD

**Issue by angularcircle** [orchidsoftware/platform#1603]
**Describe the bug**
Padding of command-bar items is set to 0 within "mobile view".

**To Reproduce**
  1. Create a screen with command bar and add some buttons
  1. Hover over the default link (or apply background using Bootstrap classes ie. `btn btn-primary`)
  1. Display the Screen within a viewport that is less than 768px wide

**Expected behavior**
Properly padded buttons. Padding inside links/buttons should not be altered in responsive view.

**Screenshots**

_Current_
![current-view](https://user-images.githubusercontent.com/304082/110380814-8c07ea00-8050-11eb-813f-a5a9af508489.png)

_Desired_
![desired-view](https://user-images.githubusercontent.com/304082/110380900-a80b8b80-8050-11eb-861a-78fb36f16c98.png)

**Server**
  - Platfrom Version: 9.19.8

**Additional context**
Caused by forcing `padding-left: 0` for command-bar items.  Maybe just add gray 1px border to the  default command bar items  to make them stand-out a little bit and solve intent of this "bug" (trying to left align button text with the text above/bellow)

**Comment by tabuna** [comment]
Should be fixed with release 10.12.2
