### ISSUE TITLE
Multiple requests (XHR) are fired for each Radio Listener change

### ISSUE THREAD

**Issue by angularcircle** [orchidsoftware/platform#1606]
**Describe the bug**
When multiple Radio items (either group of `Radio` or single `RadioButtons` component) are used within layout that utilize `Listener` there are multiple XHR requests performed on each click ie. for 3 items:
* first click: 1 request
* second click: 2 requests
* third click: 4 requests
* 4th -> 6
* 5th -> 13
* 6th -> 23 requests and so on

When `Select` component is used there is always only one XHR request triggered on value change (valid behavior) 

**To Reproduce**

  1. Create a Screen with some layout that have at least two radio items (`Radio` with the same `name` or `RadioButtons` component)
  2. Add  some `Listener` that will change a layout rows/columns below the radio fields
  3. Open the view in your webbrowser with devtools network tab active
  4. Observe the request counter on each radio/radiobutton click 
 
📄 **SampleScreen**
```php
    public function layout(): array
    {
        return [
            Layout::rows([
                RadioButtons::make('item')
                    ->options([
                        'A' => 'One',
                        'B' => 'Two',
                        'C' => 'Three'
                    ])
                    ->title(__('Item')),
                    ]),
            ItemListener::class
        ];
    }


    public function asyncSwitchItem($item){
        return [];
    }`
```

📄 **ItemListener**
```php
    protected $targets = ['item'];
    protected $asyncMethod = 'asyncSwitchItem';

    protected function layouts(): array
    {
        return [
            Layout::rows([
                Input::make('field')->title(__('Some field'))
            ])
        ];
    }
```

**Expected behavior**

One XHR per click

**Server:**

  - Platfrom Version: 9.19.8
  - Laravel Version: 8
  - PHP Version:  7.4

**Comment by tabuna** [comment]
Hi! put a field in the listener layout:

**SampleScreen**
```php
public function layout(): array
{
    return [
        ItemListener::class
    ];
}
```

**ItemListener**
```php
    protected $targets = ['item'];
    protected $asyncMethod = 'asyncSwitchItem';

    protected function layouts(): array
    {
        return [
            Layout::rows([
                RadioButtons::make('item')
                    ->options([
                        'A' => 'One',
                        'B' => 'Two',
                        'C' => 'Three'
                    ])
                    ->title(__('Item')),
                    ]),
                Input::make('field')->title(__('Some field'))
            ])
        ];
    }
```

**Comment by angularcircle** [comment]
Thanks @tabuna I thought that if part of the layout will be replaced after field value has changed it should be separated from it. Your solution suits my current use case and solves problem of redundant XHRs
