### ISSUE TITLE
[10.0] Lack of  (or incomplete) implicit model binding on screen methods

### ISSUE THREAD

**Issue by lemyskaman** [orchidsoftware/platform#1609]
**Is your feature request related to a problem? Please describe.**

On laravel controllers methods, as long as I pass a formrequest and a model as type-hint params (with the same var name as the route defined param) at the method heading, laravel automatically binds the model and made it becomes available from the formrequest route method (using the same route attribute name). If I'm not wrong that's what is called Implicit Binding on laravel.

When using Orchid's Screens and I try to replicate that behavior on any screen method I got from $request->route('param') just the value of the param (model key) instead of the hydrated model.

To illustrate the thing better let's say I have:

- a model (SomeModel)
```php
//app/Models/SomeModel.php
use Illuminate\Database\Eloquent\Model;

class SomeModel extends Model
{
    use HasFactory;
}

```

- a form request (SomeModelFormRequest)
```php
//app/Http/Request/SomModelRequest.php

use Illuminate\Foundation\Http\FormRequest;

class SomeModelFormRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
    
        return [
            //
        ];
    }
}
```

- a screen (SomeScreen) 
```php
//App/Screens/SomeScreen.php

use Orchid\Screen\Screen;

class SomeScreen extends Screen
{

    public $name = 'OrchidTestScreen';

    public $description = 'OrchidTestScreen';

    public function query(SomeModel $somemodel,SomeModelFormRequest $request): array
    {

        dd($request->route('somemodel'));
        return [];
    }

```
- and a controller (SomeController) to compare with the SomeScreen binding behavior.
```php
class SomeControler extends Controller
{
    //
    //
    public function index(SomeModel $somemodel,SomeModelFormRequest $request){

    	dd($request->route('somemodel'));

    }
}

```

If then we drive request with this routes at a route file:

```php

Route::get('plaincontroller/{somemodel?}/edit',[App\Http\Controllers\SomeControler::class,'index'])
    ->name('platform.controller');

Route::screen('/plainscreen/{somemodel?}/edit',App\Screens\SomeScreen::class)
    ->name('platform.screen');

```

Then pointing the browser at "platform.screen" route will display the value you passed on the get request from the browser as "somemodel" param, when instead oone would expect to get the model with that primary key attribute value as would happen if we point the browser to the "platform.controller" route.

**Describe alternatives you've considered**
Off course one alternative would be to do explicit binding normally on the route serviceprovider, but what would be useful is to give screen the screen the same hability of implicit binding

**Comment by tabuna** [comment]
[Released 10.0.0](https://github.com/orchidsoftware/platform/releases/tag/10.0.0)
