### ISSUE TITLE
Listener example throws exception

### ISSUE THREAD

**Issue by bilogic** [orchidsoftware/platform#1627]
**Describe the bug**
I copied the example here https://orchid.software/en/docs/listener/ and running it caused an exception
```
TypeError
Argument 1 passed to Orchid\Screen\Builder::Orchid\Screen\{closure}() 
must implement interface Orchid\Screen\Contracts\Fieldable, string given, called in
/media/folder/project/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php on line 234
```

**To Reproduce**

1. I copied the example

**Expected behavior**
The page should have loaded with no exception

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 89.0.4389.90

**Server (please complete the following information):**
  - Platform Version: 9.19.8
  - Laravel Version: 8.33.1
  - PHP Version: 7.4.13
  - Database: MySql
  - Database Version: 8.0.21

**Comment by bilogic** [comment]
I copied the example a little wrongly. No more exceptions. Thank you.

**Comment by KevinShianto** [comment]
> I copied the example a little wrongly. No more exceptions. Thank you.

Hi, can I know what you missed? I also encounter this problem, seems like I already follow the docs.

Thank You

**Comment by bilogic** [comment]
Sorry, I'm totally out of the ecosystem and can't recall also. It is probably a missing trait or something.

**Comment by caposaric** [comment]
@KevinShianto Did you manage to solve it? I'm going through the same.
