### ISSUE TITLE
Implement canSee method to Layout like in Field Class

### ISSUE THREAD

**Issue by fozbek** [orchidsoftware/platform#1636]
**Is your feature request related to a problem? Please describe.**
Implementation of the method "canSee" on Layout class is not correct and therefore forces me to assign Layout to array manually. This works for Field meanwhile always returns true on Layout class.
https://github.com/orchidsoftware/platform/blob/9.x/src/Screen/Layout.php#L93

**Describe the solution you'd like**
Maybe Layout can use CanSee trait like Field. 
https://github.com/orchidsoftware/platform/blob/9.x/src/Screen/Field.php#L35
https://github.com/orchidsoftware/platform/blob/9.x/src/Screen/CanSee.php

**Describe alternatives you've considered**
null

**Additional context**
null

**Comment by tabuna** [comment]
Hi @fozbek. This change may break the already written code. 
Therefore, we will release this only for the next major version. https://github.com/orchidsoftware/platform/issues/1559#issuecomment-775179447

**Comment by fozbek** [comment]
Hi @tabuna. Thank you.

Duplicate of https://github.com/orchidsoftware/platform/issues/1559#issuecomment-775179447
