### ISSUE TITLE
Style problems with barryvdh/laravel-debugbar.

### ISSUE THREAD

**Issue by sung1asses** [orchidsoftware/platform#1654]
**Describe the bug**
Applying styles to Debugbar

![image](https://user-images.githubusercontent.com/50788522/113505547-51b33f00-9561-11eb-87ad-5779f3d30b64.png)

**Comment by tabuna** [comment]
Hi @sung1asses, how did you determine that the error is on the orchid side and not barryvdh/laravel-debugbar?
After all, it is precisely his task to correctly inject into the `js/html` page, and not the task of the admin package.


I can recommend:
-  Сreating an issue for `barryvdh/laravel-debugbar`
- Use packages that don't try to distort `html` and its resources like https://underground.works/clockwork/

**Comment by sung1asses** [comment]
Yes, you're right. Thank you for your feedback.
