### ISSUE TITLE
User with only "Systems" permission will encounter error 403

### ISSUE THREAD

**Issue by faizfizy** [orchidsoftware/platform#1656]
**Describe the bug**
A user with only "Systems" permission encounter error 403 when accessing /admin/systems. Same error encountered while trying to logout by manually go to /admin/logout

**To Reproduce**

  1. Create a new user at /admin/users/create
  2. On permissions section, tick all except "Main"
  3. Save and view the user, then click "Impersonate user"

**Expected behavior**
User will directly redirected to System page or at least allowed to access when entered manually

**Comment by tabuna** [comment]
Hi @faizfizy, this is normal behavior. 
The mandate "system" allows visiting it. But first, you need to access the main one.

Here is a real-life example that makes this clear:

>  We have the keys to the office in the business center, but nothing else. The security will not let you go beyond the reception, no matter how much you shake the keys, because they expect to see a badge or a card.
