### ISSUE TITLE
Dropdown placement not align when using in table rows

### ISSUE THREAD

**Issue by leeliwei930** [orchidsoftware/platform#1665]
**Describe the bug**
Dropdown misalign when using in table rows

**To Reproduce**
Steps to reproduce the behaviour:

1. When I click out the dropdown button in the table row
2. The dropdown menu item gets placed in top-end instead of bottom-end

**Expected behavior**
The dropdown menu should be shown in the correct coordinate.

**Screenshots**
![image](https://user-images.githubusercontent.com/11514728/114658318-2e884c80-9d24-11eb-9ae9-c54cace1746a.png)

**Desktop (please complete the following information):**
 - OS: macOS BigSur
 - Browser  Microsft Edge 89.0.774.76
 - Version 11.2.3

**Server (please complete the following information):**
  - Platfrom Version: 9.21.0
  - Laravel Version: 8.37.0
  - PHP Version:  7.4
  - Database:  [e.g. MySql]
  - Database Version:  5.7

**Comment by leeliwei930** [comment]
@tabuna Already solved in > 9.21.0 orchid version.

**Comment by tabuna** [comment]
Hi @leeliwei930, I don’t think this is resolved. It selects the position automatically.
