### ISSUE TITLE
Media Catalog -  Selected attachment ID

### ISSUE THREAD

**Issue by vallter2** [orchidsoftware/platform#1667]
I can't get attachment ID from Media Catalog. If I upload new attachment I got ID, but when select file from Media Catalog no return value.

`Upload::make('event.picture')->title('Upload files')->maxFileSize(1)->multiple(false)->media()->title('Foto')->closeOnAdd()->targetId()`

**Comment by vallter2** [comment]
Any suggestions for my problem?

**Comment by tabuna** [comment]
Hi @vallter2. This should be fixed with the 10.4.1 release
