### ISSUE TITLE
Striped tables having text color white in striped row.

### ISSUE THREAD

**Issue by kubre** [orchidsoftware/platform#1680]
**Description**
Striped tables having text color white in stripped row. Saw this issue in project where I updated orchid to 10 and then tried it on fresh install and it was still there. I saw this happen with table inside custom view so it might be from bootstrap itself.  
 

**How to reproduce**

  1. Set striped true for table or for table in view add class table-striped 
  
**Expected behavior**
The odd rows still should have text color as black just like even rows.

**Screenshots**
From fresh install (browser firefox)
![image](https://user-images.githubusercontent.com/20380094/115337649-fe76f880-a1be-11eb-9768-75f5317dc96e.png)

for first row which is alternate bg color has its normal text turn white I selected it partially so it more obvious. But in second row which is normal it clearly visible. 

From last version project upgraded to latest version  (browser chromium)
![image](https://user-images.githubusercontent.com/20380094/115338512-975a4380-a1c0-11eb-90b1-bd267ec77d9e.png)

In above project the first is alternate bg color and all it contains is normal text causing it all to be white.

**Desktop**
 - OS: Manjaro
 - Browser chromium, firefox
 - Version latest

**Comment by tabuna** [comment]
Hi @kubre. Check out the latest release. This should be fixed.

**Comment by kubre** [comment]
Working both on new and old orchid installation completely fine after an update, Thank you responding so fast!
