### ISSUE TITLE
DateTime field doesn't allow direct input or even time?

### ISSUE THREAD

**Issue by AlaaElrifaie** [orchidsoftware/platform#1684]
**Describe the bug**
I am trying to use the DateTime field, it's working and showing but without the Time fields (only date) and doesn't allow direct input.
Photo: 
![18](https://user-images.githubusercontent.com/9083864/115608567-bbb04000-a2e6-11eb-8de3-57e1297f19b6.PNG)

**To Reproduce**

  1. In my Screen I am using the following code:
```
DateTimer::make('test.queued_for')
                    ->title('Queued For')
                    ->allowInput()
                    ->enableTime()
                    ->required(),
```

**Expected behavior**
To show time selection and allow direct input like this:
[https://orchid.software/assets/img/ui/datatime.png](url)

**Desktop (please complete the following information):**
 - OS: Windows.
 - Browser: Chrome.
 - Version: 89.0.4389.128.

**Server (please complete the following information):**
  - Platfrom Version: 10.0
  - Laravel Version: 8.12
  - PHP Version:  8.0
  - Database:  MySQL
  - Database Version:  8.0.24

**Comment by Caffe1neAdd1ct** [comment]
@AlaaElrifaie I've just been looking at this, i'm not seeing the same results:

```
return Layout::rows([
    \Orchid\Screen\Fields\DateTimer::make('date')
        ->required()
        ->title(__('Select sale Date:'))
        ->format('Y-m-d')
        ->value((new \Carbon\Carbon()))
        ->allowInput()
        ->enableTime()
]);
```

Gives me:

![image](https://user-images.githubusercontent.com/1327332/115790369-80814000-a3be-11eb-8853-cfe8e16e7ad7.png)

The only obvious differences I can see are you're on 10.0 and i've tried on both 9.7 and 10.1 (both working for me).
