### ISSUE TITLE
Resource/Views/Layouts/Table : Invalid Arguments Supplied for Foreach()

### ISSUE THREAD

**Issue by syofyanzuhad** [orchidsoftware/platform#1691]
**Describe the bug**

**To Reproduce**

  1. You can return an empty collection with array or an object.
  2. Or use some condition like this `@if (is_array($rows) || is_object($rows))` outside the foreach

**Expected behavior**

it should return a string like "No Data"

**Screenshots**

![image](https://user-images.githubusercontent.com/52684582/115943407-004ffd00-a4da-11eb-9db2-c180b9b24480.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20]
 - Browser [chrome]
 - Version [22]

**Smartphone (please complete the following information):**

**Server (please complete the following information):**
  - Platfrom Version: [e.g. 5.6.3]
  - Laravel Version: [8.0]
  - PHP Version:  [7.4]
  - Database:  [MySql]
  - Database Version:  [8.0.2]

**Additional context**

this is detail of error : https://flareapp.io/share/Bm06BQB7?error=Bm06BQB7&owner_token=58NFrUNO3L9vflCrpJGOYlHJA51cPtvx

**Comment by tabuna** [comment]
Hey @syofyanzuhad! I tried to pass as a table value the different types that you specified, an empty array, an empty collection, an object (With enumeration support). And I have no error.  What am I doing wrong?

```php
public function query(): array
{
    return [
        'tableCollect'        => collect(),
        'tableArray'          => [],
        'tableIterableObject' => new Repository([]),
    ];
}
```

**Comment by syofyanzuhad** [comment]
i try use like a tutorial..
maybe you got somethink, after look this :

`/home/syofyan/dreamworld/learning/laravel/adminpanel-orchid/app/Orchid/Layouts/PostListLayout.php`
```
<?php

namespace App\Orchid\Layouts;

use Orchid\Screen\Layouts\Table;
use Orchid\Screen\TD;

class PostListLayout extends Table
{
    /**
     * Data source.
     *
     * The name of the key to fetch it from the query.
     * The results of which will be elements of the table.
     *
     * @var string
     */
    protected $target = '';

    /**
     * Get the table cells to be displayed.
     *
     * @return TD[]
     */
    protected function columns(): array
    {
        return [
            TD::make('title', 'Title')
                ->render(function (Post $post) {
                    return Link::make($post->title)
                        ->route('platform.post.edit', $post);
                }),

            TD::make('created_at', 'Created'),
            TD::make('updated_at', 'Last edit'),
        ];
    }

}
```

`/home/syofyan/dreamworld/learning/laravel/adminpanel-orchid/app/Orchid/Screens/PostListScreen.php`
```
<?php

namespace App\Orchid\Screens;

use App\Orchid\Layouts\PostListLayout;
use App\Models\Post;
use Orchid\Screen\Actions\Link;
use Orchid\Screen\Screen;

class PostListScreen extends Screen
{
    /**
     * Display header name.
     *
     * @var string
     */
    public $name = 'Blog post';

    /**
     * Display header description.
     *
     * @var string
     */
    public $description = 'All blog posts';

    /**
     * Query data.
     *
     * @return array
     */
    public function query(): array
    {
        return [
            'posts' => Post::paginate()
        ];
    }

    /**
     * Button commands.
     *
     * @return Link[]
     */
    public function commandBar(): array
    {
        return [
            Link::make('Create new')
                ->icon('pencil')
                ->route('platform.post.edit')
        ];
    }

    /**
     * Views.
     *
     * @return Layout[]
     */
    public function layout(): array
    {
        return [
            PostListLayout::class
        ];
    }
}
```

**Comment by tabuna** [comment]
You are missing a key:

```php
    /**
     * Data source.
     *
     * The name of the key to fetch it from the query.
     * The results of which will be elements of the table.
     *
     * @var string
     */
    protected $target = '';
```

On the screen, you are using the `posts` key. So it should look like this:
```php
protected $target = 'posts';
```

**Comment by umangapathak999** [comment]
is this issue fixed? I had a similar problem today and can't seem to find a solution for it.

    protected function columns(): array
    {
        return [
            TD::make('id', 'ID'),
            
            TD::make('name', 'Product Category Name')
                ->render(function(ProductCategory $productCategory){
                    return Link::make($productCategory->name)
                                    ->route('platform.product-category.edit', $productCategory);
                }),
        ];
    }

This is the code I wrote while following the documentation.
