### ISSUE TITLE
Update to Bootstrap v5.0.0 final

### ISSUE THREAD

**Issue by wsdnathan** [orchidsoftware/platform#1720]
Released yesterday https://getbootstrap.com/ currently Orchid admin is on 5.0.0-beta3

**Comment by tabuna** [comment]
Hi @wsdnathan. I will definitely update. But current, this behavior in modal windows prevents me:  [bootstrap#33840 ](https://github.com/twbs/bootstrap/issues/33840)

**Comment by wsdnathan** [comment]
https://blog.getbootstrap.com/2021/05/13/bootstrap-5-0-1/

**Comment by tabuna** [comment]
A new release has been released.
