### ISSUE TITLE
Menu items are duplicated on each request when used with laravel/octane.

### ISSUE THREAD

**Issue by georgesa** [orchidsoftware/platform#1722]
**Describe the bug**
When using with laravel/octane, the menu items are duplicated on each request. It's probably something to do with how the menu items are registered and used in the view composer. 

**Server (please complete the following information):**
  - Platfrom Version: 10
  - Laravel Version: 8
  - PHP Version:  8

**Comment by tabuna** [comment]
Most likely, we need to clear the singleton class `Dashboard`. 
At the moment, I have not yet adapted the package for Octane.

**Comment by georgesa** [comment]
Hi @tabuna,

Thank you for your help and for the package, I really like using it!

Unfortunately, just flushing the Dashboard doesn't work. I tried a lot of things and I think the issue is with the `View::composer('platform::dashboard', ...` in `OrchidServiceProvider.php`.

If I just flush the Dashboard, I get this error: `You must call one of in() or append() methods before iterating over a Finder. (View: /var/www/html/resources/views/vendor/platform/app.blade.php)` https://flareapp.io/share/xPQDVOgm#F97

This is caused because the assets are not registered on the dashboard anymore. If I do:
```
$this->callAfterResolving(Dashboard::class, function ($dashboard) {
            $dashboard
                ->registerResource('stylesheets', config('platform.resource.stylesheets'))
                ->registerResource('scripts', config('platform.resource.scripts'))
                ->addPublicDirectory('orchid', Dashboard::path('public/'));
```
It works again, but the menu items are still added on each request. I even tried setting `->menu` to its empty state but it didn't help. If I had to bet, the View composer is calling `Dashboard::renderMenu` on each request and appends items each time.

I'm not sure how to solve it now and I understand that it's not yet adapted to octane. Not sure what changed, because version 9 was working ok with octane. I'll try to understand what changed between the versions in the near future.

**Comment by tabuna** [comment]
I think this PR https://github.com/orchidsoftware/platform/pull/1786 should fix the `Octane` situation.
I'm not too fond of this solution, but I have no alternative options. I'm open to suggestions

**Comment by tabuna** [comment]
I rolled back the change as it did not add new items to the menu using other service providers or packages.

**Comment by tabuna** [comment]
With the release of version 10.15.0, the menu will not be duplicated.
