### ISSUE TITLE
The empty method of Selection not override the values

### ISSUE THREAD

**Issue by mahmoudmohamedramadan** [orchidsoftware/platform#1747]
**Describe the bug**
When I called empty method after the filing methods like `fromModel` or `options` not overwritten the values

**Expected behavior**
I expect to when I use this method before filling methods will overwrite the values as shown in documents

**Screenshots**
<a href="https://imgur.com/CVwyxer">orchid_issue</a>

**Desktop (please complete the following information):**
 - Windows OS
 - Chrome Browser

**Smartphone (please complete the following information):**

**Server (please complete the following information):**
  - Platfrom Version: [e.g. 10.4]
  - Laravel Version: [e.g. 8.40]
  - PHP Version:  [e.g. ^7.3|^8.0]
  - Database:  [e.g. MySQL]
  - Database Version:  [e.g. 10.4.18]

**Comment by tabuna** [comment]
Hi @mahmoudmohamedramadan . Can you explain the problem in more detail.
 Because the screenshot above shows that everything is working correctly.

![image](https://user-images.githubusercontent.com/5102591/123170005-ac827580-d482-11eb-807b-69cc1c0b058a.png)

**Comment by mahmoudmohamedramadan** [comment]
Hi @tabuna, I mean that as you explain in Orchid Docs that I should suffix the filling methods like `options` in my code WITH the `empty` method otherwise the added value will be overwritten, BUT when I try to prefix the `empty` method WITH the filling methods as there is NO difference, the expected result that the key in the first param in the `empty` should overwrite the options values...it's true or NOT?
![01](https://user-images.githubusercontent.com/48416569/123417820-8ced6900-d5b8-11eb-8bc7-6e16e20c0332.png)

**Comment by tabuna** [comment]
Hi this footnote is no longer relevant for the latest versions.  I didn't really like the fact that you need to follow a certain order of calls.  Therefore, I changed the honey empty, so that it would be executed last

**Comment by mahmoudmohamedramadan** [comment]
Awesome, BUT sir, this method remains exist in <a href="https://orchid.software/en/docs/field/#select">DOCS</a>
