### ISSUE TITLE
All platform pages not found after fresh installation

### ISSUE THREAD

**Issue by sylzys** [orchidsoftware/platform#1764]
**Describe the bug**

I did a fresh installation following the documentation, everything seems to be installed well, did orchid:install, orchid:admin, orchid:link

I can access laravel example page, but all platform pages gives 404. I tried with prefix "/", "/admin", etc.
e.g with "/" as prefix, I enter my site domain, I get redirected to the login page, and get a 404

**To Reproduce**

  1. Follow [documentation instructions](https://orchid.software/en/docs/installation/)
  2. Configure .env APP_URL 
  3. Configure platform.php with `'prefix' => env('DASHBOARD_PREFIX', '/'),`

**Expected behavior**

I should have the login form displayed instead of a 404 error

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Browser : Firefox / Chrome

**Server (please complete the following information):**
  - Platfrom Version: 10.5.2
  - Laravel Version: v8.46.0
  - PHP Version:  7.4.20
  - Database:  Mysql
  - Database Version:  mysql  Ver 15.1 Distrib 10.3.27-MariaDB

**Comment by tabuna** [comment]
Hi @sylzys, I cannot confirm the problem.

- Make sure the domain in .env is correct.
- Make sure you can see the routes when doing `artisan route:list`
- Make sure routes have not been cached `artisan route:clear`

**Comment by olezhkafp** [comment]
Got the same error, but `php artisan route:clear` fixed it. Thanks

**Comment by sylzys** [comment]
Hi, I've redone eveyrhting. Rights are correct. Apache config is correct as I can see Laravel home page. I can test any route I want in platform.php, I'll get a 404.. .env is configured too.. I don't know what to do :'(

**Comment by tabuna** [comment]
Hi @sylzys, Laravel does[ not have a sample configuration](https://laravel.com/docs/8.x/deployment#nginx) for the apache2 server. 
There may be a configuration problem. If you add a new route, for example:

```php
Route::get('/example/{message}', function (string $message) {
    return $message;
});
```

Will it work for you?

**Comment by sylzys** [comment]
It's working now.. Strange thing to say the least,  cause I don't know what I've done..

I installed the debug bar, added a trailing slash in my APP_URL var (but it's working without now...)

I also cleared all caches again 🤷‍♂️

**Comment by sylzys** [comment]
Well.. it's not working anymore @tabuna  :'( (not even your route example)

The debug bar gives me this error on every page (except for '/' which is the laravel home page):

``` 

    /var/www/html/interne-dev/vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php#43Symfony\Component\HttpKernel\Exception\NotFoundHttpException

                return $this->getRouteForMethods($request, $others);
            }

            throw new NotFoundHttpException;
        }

        /**

    array:26 [▼
      0 => array:5 [▼
        "file" => "/var/www/html/interne-dev/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php"
        "line" => 162
        "function" => "handleMatchedRoute"
        "class" => "Illuminate\Routing\AbstractRouteCollection"
        "type" => "->"
      ]
      1 => array:5 [▼
        "file" => "/var/www/html/interne-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
        "line" => 647
        "function" => "match"
        "class" => "Illuminate\Routing\RouteCollection"
        "type" => "->"
      ]
      2 => array:5 [▼
        "file" => "/var/www/html/interne-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
        "line" => 636
        "function" => "findRoute"
        "class" => "Illuminate\Routing\Router"
        "type" => "->"
      ]
      3 => array:5 [▼
        "file" => "/var/www/html/interne-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
        "line" => 625
        "function" => "dispatchToRoute"
        "class" => "Illuminate\Routing\Router"
        "type" => "->"
      ]
      4 => array:5 [▶]
      5 => array:5 [▶]
      6 => array:5 [▶]
      7 => array:5 [▶]
      8 => array:5 [▶]
      9 => array:5 [▶]
      10 => array:5 [▶]
      11 => array:5 [▶]
      12 => array:5 [▶]
      13 => array:5 [▶]
      14 => array:5 [▶]
      15 => array:5 [▶]
      16 => array:5 [▶]
      17 => array:5 [▶]
      18 => array:5 [▶]
      19 => array:5 [▶]
      20 => array:5 [▶]
      21 => array:5 [▶]
      22 => array:5 [▶]
      23 => array:5 [▶]
      24 => array:5 [▼
        "file" => "/var/www/html/interne-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php"
        "line" => 110
        "function" => "sendRequestThroughRouter"
        "class" => "Illuminate\Foundation\Http\Kernel"
        "type" => "->"
      ]
      25 => array:5 [▼
        "file" => "/var/www/html/interne-dev/public/index.php"
        "line" => 52
        "function" => "handle"
        "class" => "Illuminate\Foundation\Http\Kernel"
        "type" => "->"
      ]
    ]
```

The file `"/var/www/html/interne-dev/public/index.php"` exists.. :(

**Comment by sylzys** [comment]
Working now thanks :)
