### ISSUE TITLE
Filter dropdown is closed when I click/focus on select2 element

### ISSUE THREAD

**Issue by protocyber** [orchidsoftware/platform#1767]
**Describe the bug**
Filter dropdown is closed when I click/focus on select2 element
And when I start typing on the select2, all the elements is hiding.

This bug happens on orchid/platform:10.4.0 and up

This bug does not happen on orchid/platform:10.3.0

**Screenshots**
![image](https://user-images.githubusercontent.com/21333516/121664832-189fc980-cad2-11eb-8b66-8d688ea2a97b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version 91.0.4472.101 (Official Build) (64-bit)

**Server (please complete the following information):**
  - Platfrom Version: 10.4.0 and 10.5.0
  - Laravel Version: 8
  - PHP Version:  7.3
  - Database:  MySQL
  - Database Version:  5

**Comment by renanbr** [comment]
I'm facing the same problem in `10.6.0`
