### ISSUE TITLE
Removing non "attached" or non existent role from user detach all roles

### ISSUE THREAD

**Issue by FrancescoAnotherbrick** [orchidsoftware/platform#1770]
When the methods `removeRole` or `removeRoleBySlug` (`UserAccess` trait), are called by passing a role that is either non-attached to the user or doesn't exists, all the user roles will be detached.

**To Reproduce**

  1. Create and a user and two roles ("user" and "super-user")
  2. Add the role "user" to the user
  3. One of the following
      a. Call `removeRoleBySlug` with a non existent role (e.g. "mega-user") as parameter
      b. Call `removeRoleBySlug`/`removeRole` with the "super-user" role as parameter
  4. The user will no longer have the "user" role

**Expected behavior:**
The user should not loose it's roles.

**Server:**
  - Platfrom Version: 10.5.2
  - Laravel Version: 8.47.0
  - PHP Version:  7.4
  - Database:  MySql
  - Database Version:  5.7.28

**Comment by tabuna** [comment]
Hi @FrancescoAnotherbrick , this should be fixed with the release https://github.com/orchidsoftware/platform/releases/tag/10.6.1
