### ISSUE TITLE
CSRF token mismatch in API call

### ISSUE THREAD

**Issue by makhweb** [orchidsoftware/platform#1771]
Description:
Picture field gives 419 error with message: "CSRF token mismatch"

To Reproduce
  1. Login to orchid
  2. Do not refresh the page, just open some create/edit screen
  3. Upload a picture

The same behaviour is happening with any API calls, including background notifications.

Desktop:
 - OS: Windows
 - Browser Chrome
 - Version 91.0.4472.114 

Server:
  - Platform Version: 10.5.2
  - Laravel Version: v8.47.0
  - PHP Version:  8.0.7
  - Database:  MySQL
  - Database Version:  5.7

**Comment by grigoriy-ivanov** [comment]
Maybe pull #1776 fix it

**Comment by tabuna** [comment]
This should be resolved with the release https://github.com/orchidsoftware/platform/releases/tag/10.6.0
