### ISSUE TITLE
The POST method is not supported for this route. Supported methods: GET, HEAD.

### ISSUE THREAD

**Issue by eleimt** [orchidsoftware/platform#1773]
![image](https://user-images.githubusercontent.com/16452150/122657020-69fe2780-d168-11eb-90b3-a3f3902778a2.png)
Любые `->method()` относящиеся к 2-й модали вызывают ошибку.

**Comment by mvehar** [comment]
Check if you have cache routes.

**Comment by tabuna** [comment]
Hi @eleimt ,  this should be resolved with 10.19.0 release.
