### ISSUE TITLE
Forgot to return cache entry for icons?

### ISSUE THREAD

**Issue by RowanLivewall** [orchidsoftware/platform#1779]
**Describe the bug**
Forgot to return cache entry for icons?

**To Reproduce**

  1. open IconFinder.php
  2. check line 67

**Expected behavior**
**Return** cache entry

**Screenshots**
![image](https://user-images.githubusercontent.com/72744844/123091539-c6439e80-d429-11eb-88f6-41a49a26fdc5.png)

**Additional context**
orchid version 9.19

**Comment by tabuna** [comment]
Hi @RowanLivewall. It looks like the return is really forgotten.
