### ISSUE TITLE
Проблема с css сразу после установки

### ISSUE THREAD

**Issue by nbrouka** [orchidsoftware/platform#1780]
Установка laravel на linux, запуск через sail, проблема наблюдается в chrome, в firefox все корректно

![image](https://user-images.githubusercontent.com/15109611/123115202-96f05a00-d448-11eb-90f3-34c43fd18760.png)

**Comment by tabuna** [comment]
Использую chrome и sail проблем не наблюдаю. Нужно больше подробностей.


Попробуйте отключить расширения.
