### ISSUE TITLE
Uncaught TypeError: e.target.xhr is undefined

### ISSUE THREAD

**Issue by longlp** [orchidsoftware/platform#1781]
I got that error log each time submit form 
It's only show up from 10.6 version 

**Screenshots**
![image](https://user-images.githubusercontent.com/7371708/123256982-c58b3500-d51b-11eb-845e-ccc63fc53422.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04
 - Browser chrome, firefox

**Server (please complete the following information):**

        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5",
        "league/flysystem-aws-s3-v3": "^1.0",
        "mailjet/mailjet-apiv3-php": "^1.5",
        "orchid/platform": "10.6.3",
        "php-mqtt/client": "^1.1",
        "php-mqtt/laravel-client": "^1.0",
        "phpoffice/phpspreadsheet": "^1.17",
        "predis/predis": "^1.1"

**Comment by tabuna** [comment]
This should be fixed with the release https://github.com/orchidsoftware/platform/releases/tag/10.7.0
