### ISSUE TITLE
Modal crashes after server validation

### ISSUE THREAD

**Issue by grigoriy-ivanov** [orchidsoftware/platform#1783]
**Describe the bug**
If an input filed does not pass server validation, the buttons are not displayed incorrectly

**Screenshots**

![Снимок](https://user-images.githubusercontent.com/13166748/123277565-e4cf9580-d50e-11eb-870d-3521002088a9.PNG)

**Comment by tabuna** [comment]
I cannot reproduce this on the latest version.
