### ISSUE TITLE
There is no way to change width of chart legend labels

### ISSUE THREAD

**Issue by SchmidtMilena** [orchidsoftware/platform#1784]
Legend under the chart has limitations for text length (replace part of the text with dots) and takes only 2/3 of charts width. Can I change it somewhere? I want it to take 100% of chart width so my text can be wider (and show whole text not just a small part of it. )
![image](https://user-images.githubusercontent.com/59263221/123444716-7b678980-d5d7-11eb-9b32-10c710b72db9.png)

**Comment by tabuna** [comment]
To display charts, we use the https://github.com/frappe/charts library. 
As far as I am familiar with their documents, they do not have such an opportunity. 
I think you should open this question in their repository.
