### ISSUE TITLE
Изменить логику маршрутов

### ISSUE THREAD

**Issue by falur** [orchidsoftware/platform#1789]
Недавно помогал человеку разбираться с платформой и понял что есть момент который не очевиден. Маршрутизация из за того что в макросе screen сейчас идёт добавление необязательного параметра method роуты надо строить в порядки от большего количество параметров к меньшему. Предлагаю сделать более очевидно:

```php
Route::get('path/to/screen', Screen::getHandle)
Route::post('path/to/screen/method', Screen::postHandle)
```

**Comment by tabuna** [comment]
@falur Можешь объяснить своё предложение? В документации мы указываем это 
![image](https://user-images.githubusercontent.com/5102591/123956617-8d6c7200-d9b3-11eb-89e0-3c983f3e6fb1.png)

**Comment by falur** [comment]
Для пользователя останется всё без изменений.
```php
Route::screen('users/{id}/edit', Screens\User\UserEditScreen::class)
    ->name('user.edit');

Route::screen('users/create', Screens\User\UserEditScreen::class)
    ->name('user.create');

Route::screen('users', Screens\User\UserTableScreen::class)
    ->name('user.list');
```

но внутри вместо 
```php
Route::macro('screen', function ($url, $screen) {
                /* @var Router $this */
                $route = $this->any($url.'/{method?}', [$screen, 'handle']);

                $methods = $screen::getAvailableMethods();

                if (! empty($methods)) {
                    $route->where('method', implode('|', $methods));
                }

                return $route;
            });
```

сделать

```php
Route::macro('screen', function ($url, $screen) {
                /* @var Router $this */
                $this->get($url, [$screen, 'handle']);
                $this->post($url . '/{method}', [$screen, 'postHandle']);
            });
```

Что это даст:
1) Теперь не имеет значения порядок объявления роутов, не будет непредвиденного поведения в случае если человек проглядел этот момент
2) Мы отделяем явно логику гет и пост запросов. Что даёт как минимум лучшее понимание в чтении кода и в его поддержке.

**Comment by tabuna** [comment]
> Для пользователя останется всё без изменений, кроме свободы в порядке - она появится

Это серьёзное изменение, которое влечёт за собой последствия. Например, мы записали макрос объявления маршрута как вы предлагаете:

```php
Route::macro('screen', function ($url, $screen) {
                /* @var Router $this */
                $this->get($url, [$screen, 'handle']);
                $this->post($url . '/{method}', [$screen, 'postHandle']);
            });
```

Какой их двух маршрутов будет возвращён, для продолжения? 

Например вы возвращаем `GET` для того, что бы можно было указывать имя маршрута и его хлебные крошки:

```php
Route::screen('profile', UserProfileScreen::class)
    ->name('platform.profile')
    ->breadcrumbs(function (Trail $trail) {
        return $trail->parent('platform.index')->push('Profile');
    });
```

Но тогда `POST` остался без имени и к нему нельзя будет сложнее когда потребуется. Но более важной вещью будет неочевидность с применением промежуточных слоёв, например:

```php
Route::screen('profile', UserProfileScreen::class)
    ->name('platform.profile')
    ->middleware('onlyAdmin')
```

Наш `middleware` будет присвоен только к `GET` запросам, который навряд ли влечёт какие либо последствия, но при этом оставляя `POST`  запросы открытыми к обращению. Это ещё больше запутает человека и к тому же открывает неочевидные обходные пути.

А что если мы возвращали бы группу в макросе? Тогда `middleware` работали бы правильно? Да, но мы возвращаемся к проблеме с указанием имени и хлебных крошек. 


Ранее, решая такую проблему, я добавил фильтр методов, что бы как можно больше снизить неверное обращение:

```php
$methods = $screen::getAvailableMethods();

if (! empty($methods)) {
    $route->where('method', implode('|', $methods));
}
```

На текущий момент у меня нет предложений как можно это улучшить, но я открыт к предложениям.

**Comment by falur** [comment]
Да действительно с именованием я упустил момент. Спасибо за обсуждение, обсуждение закрываю
