### ISSUE TITLE
Table 'laravel.admin_users' doesn't exist

### ISSUE THREAD

**Issue by edimar** [orchidsoftware/platform#1790]
After run tutorial pass by pass in new project. I have the error at ~/admin/login:

Illuminate\Database\QueryException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.admin_users' doesn't exist (SQL: select * from `admin_users` where `email` = admin@admin.com and `admin_users`.`deleted_at` is null limit 1)

**Comment by tabuna** [comment]
I need more information to reproduce the error
