### ISSUE TITLE
Matrix Field not working

### ISSUE THREAD

**Issue by mesunil2010** [orchidsoftware/platform#1796]
Matrix fields are not getting value after being saved in the edit screen

  1. Create any edit screen
  2. Add matrix field
  3. Save it.

Matrix field filled with value.

**Screenshots**
<img width="1414" alt="Screen Shot 2021-07-04 at 07 49 32" src="https://user-images.githubusercontent.com/6350746/124370958-850a8480-dc9c-11eb-9e6e-41774bc4102b.png">

**Comment by tabuna** [comment]
Hi @mesunil2010. Maybe this is a duplication, have you looked at #1565 #1564?

**Comment by mesunil2010** [comment]
The casting worked for me. Thanks for the help.
