### ISSUE TITLE
Check permissions in menu facade

### ISSUE THREAD

**Issue by agoalofalife** [orchidsoftware/platform#1799]
**Is your feature request related to a problem? Please describe.**
I use facade Menu and want to pass a few permissions but i can only one

**Describe the solution you'd like**
I suggest to change method `permission` which can get array 

**Describe alternatives you've considered**
Also we can add new method `permissions` in plural form

**Additional context**
```php
      Menu::make('Аналитика и отчеты')
            ->icon('chart')
            ->route('platform.analyticsAndReports')
            ->permission(['firstPermission', 'secondPermission'])
// or
   Menu::make('Аналитика и отчеты')
            ->icon('chart')
            ->route('platform.analyticsAndReports')
            ->permissions(['firstPermission', 'secondPermission'])
```

**Comment by tabuna** [comment]
Hi, I think this is a good idea.

We should be allowed to pass either a string or an array of strings as an argument. 

```php
Menu::make('example')->permission(['firstPermission', 'secondPermission'])
```

The new method can be confusing.
