### ISSUE TITLE
Relation in modal windows didnt focus on edit field

### ISSUE THREAD

**Issue by esk-ap** [orchidsoftware/platform#1826]
### Discussed in https://github.com/orchidsoftware/platform/discussions/1825

<div type='discussions-op-text'>

<sup>Originally posted by **esk-ap** August 11, 2021</sup>
Hello.

Im trying to use Relation in modal window. And i cant get focus on edit field for searching values.

I click on Input field but it looks like disabled.

Here my code for creating fields in Layout.
`
protected function fields(): array
    {
        return [
            Relation::make('products.brand')
                ->fromModel(Brand::class, 'name')
                ->applyScope('real')
                ->required()
                ->title(__('Производитель'))
                ->help('Начните вводить наименование производителя для поиска...'),

           Input::make('from_brand')
                ->title('Заменяемый производитель')
                ->help('Все существующие артикулы будут перенесены от одного производителя к другому без потери данных в прайсах. Заменяемый производитель будет удален.')
                ->required(),
        ];
    }
`

![image](https://user-images.githubusercontent.com/56771968/129006873-d04f6fa7-ffaf-41a2-bb06-ff810a7f3a9a.png)
</div>

**Comment by esk-ap** [comment]
I was made screen (not modal window) for this layout and all works fine

![image](https://user-images.githubusercontent.com/56771968/129019407-5b4a646b-a78a-42d0-8fd3-ff1d590798e9.png)

**Comment by tabuna** [comment]
Should be fixed with release [10.12.1](https://github.com/orchidsoftware/platform/releases/tag/10.12.1)
