### ISSUE TITLE
Автофокус на поле ввода для Relation и Select

### ISSUE THREAD

**Issue by esk-ap** [orchidsoftware/platform#1833]
При нажатии на поле Relation открывается выпадающий список, но для фильтрации приходится делать еще один клик, чтобы установить курсор в поле ввода.
Было бы неплохо делать автофокус на это поле.

**Comment by grigoriy-ivanov** [comment]
@esk-ap в версии https://github.com/orchidsoftware/platform/releases/tag/10.12.1 это было поправлено.
