### ISSUE TITLE
Case insensitive в фильтрах Table и Relation

### ISSUE THREAD

**Issue by esk-ap** [orchidsoftware/platform#1839]
Было бы неплохо сделать возможность регистронезависимого поиска в фильтрах Table и при поиске значения в Relation/Select.

И еще непонятно, почему в Select можно делать выборку fromQuery, а в Relation нельзя.

**Comment by tabuna** [comment]
You can use case-insensitive database encoding.  These usually end with “ci”. If you call add support for ILIKE, then open PR.

**Comment by esk-ap** [comment]
Не все базы поддерживают такой функционал. Например, в postgresql это реализуется только с помощью сторонних расширений.
