### ISSUE TITLE
Сортировка в Relation при создании и фильтрации

### ISSUE THREAD

**Issue by esk-ap** [orchidsoftware/platform#1840]
### Discussed in https://github.com/orchidsoftware/platform/discussions/1835

<div type='discussions-op-text'>

<sup>Originally posted by **esk-ap** August 17, 2021</sup>
Как сделать сортировку при создании Relation из класса? Метод orderBy() в вызываемом scope не работает.

Так же, непонятно как задать сортировку при фильтрации. Сортировать по алфавиту было бы удобнее для восприятия.

![img](https://user-images.githubusercontent.com/56771968/129700314-9cdbff91-9af2-408d-89ac-ca51f58853b9.png)

</div>

**Comment by tabuna** [comment]
You can define the sort order with the “scope” method. You can learn more and see examples in the documentation https://orchid.software/en/docs/field/#relation
