### ISSUE TITLE
Как публиковать на хостинге?

### ISSUE THREAD

**Issue by 65ermek** [orchidsoftware/platform#1847]
Здравствуйте! Как orchid публиковать на хостинге?

**Comment by tabuna** [comment]
Orchid не самостоятельный продукт это только пакет к популярному фреймворку Laravel. Думаю вам стоит переформулировать свой вопрос на «Как установить Laravel на хостинг» и тогда вы сможете найти сотни статей на эту тему. Так же я рекомендую пользоваться поддержкой которую предоставляет ваш хостинг провайдер так как он получает за это вознаграждение.
