### ISSUE TITLE
Атрибут Title для элемента формы Link

### ISSUE THREAD

**Issue by ghost** [orchidsoftware/platform#1850]
Хочу добавить в таблицу действие в виде иконки и по наведению на иконку отображать Title. Если писать такой код, то тэг A оборачивается в label и выводит сверху надпись "Статистика", вместо того чтобы просто добавить атрибут title.

Вызов ->popover('') для этого элемента не работает.

```
TD::make('stats', __('Действия'))
                    ->cantHide()
                    ->render(function(Product $product){
                        return Link::make()
                            ->icon('chart')
                            ->title('Статистика')
                            ->route('autoparts.products.stats', $product->id);
                }),

```

![img](https://user-images.githubusercontent.com/56771968/130925590-a88d4431-810f-4b9d-b6ef-db8800e1d4b4.png)

**Comment by tabuna** [comment]
Available with the next version. It uses a method that will disable form titles, errors, and helpers.

```php
Layout::rows([
    Link::make('Hello')->title('Lorem ipsum dolor sit amet')->withoutFormType()
]),
```
