### ISSUE TITLE
Form UI is distorted at Add/edit pages even after complete all installation steps

### ISSUE THREAD

**Issue by parm123** [orchidsoftware/platform#1851]
Click on profile button or Add button from user list .
See the form elements shift towards right means UI is totally distorted .

![Screenshot from 2021-08-26 22-46-54](https://user-images.githubusercontent.com/11145445/131007340-623386a8-75f5-486d-91c8-303124522b65.png)

**Comment by parm123** [comment]
@tabuna Please help me to resolve this .

**Comment by tabuna** [comment]
Hey @parm123 Please tell me in which browser this is happening, because I cannot reproduce this behavior. 
Also, make sure you disable all extensions.

**Comment by parm123** [comment]
Thanks @tabuna . Issue with older version of chrome . when i updated it the UI issue not appear .
