### ISSUE TITLE
Listener Created Button Doesn't Work

### ISSUE THREAD

**Issue by mucan54** [orchidsoftware/platform#1855]
I created button via listener and it didn't work.

1. Create a listener
2. Add listener to button which will created dynamically.
3. You will need to refresh the page to make button work.

Button should work without refresh, I think it is about binding.

Here is my case, table data updated by select box selections, but buttons doesnt work without refreshing page.

<img width="1262" alt="Ekran Resmi 2021-08-31 08 30 38" src="https://user-images.githubusercontent.com/5364325/131447376-577ebbcc-2ec5-4ec5-a339-cafafafa635b.png">

I use Safari browser.

**Comment by tabuna** [comment]
Could you provide steps to reproduce?

**Comment by mucan54** [comment]
My screen layout method:

`    public function layout(): array
    {

        return [
           QrQtyListener::class
            ];
    }`

My listener :

`    public function layout(): array
    {

        return [
          QrProductsListLayout::class,
            ];
    }`

My Layout : 

`    public function columns(): array
    {

        return [
            TD::make('name', 'Ürün İsmi')->sort(),
            TD::make(__('Delete'))
                ->align(TD::ALIGN_CENTER)
                ->width('100px')
                ->render(function (ModelsProducts $product) {
                    return Button::make('Sil')
                        ->icon('trash')
                        ->action('platform.qrone.delete',$product);}),
        ];
    }`
