### ISSUE TITLE
Get 419 error at login form

### ISSUE THREAD

**Issue by nimafam** [orchidsoftware/platform#1881]
Hi,

I get a 419 error in the login form. After deploying the website on a Windows server and Apache service I get this error. 

Could you please help me with this?

**Comment by nimafam** [comment]
Could please help me to solve the problem?

**Comment by tabuna** [comment]
Hi @nimafam, this error is not directly related to the package. Your setup has problems with Session. There are too many options here, from lack of reading/write permissions to proxying an apache request. The best way to look at tutorials on setting up laravel for your environment. There is also a lot of information on the Internet with this on the request "laravel 419 sessions not working"

**Comment by nimafam** [comment]
> reading/write permissions to proxying an apache request

Hi @tabuna, thank you for your answer, Ok I try to search about ut
