### ISSUE TITLE
Add badge to table element

### ISSUE THREAD

**Issue by Ayabadsir** [orchidsoftware/platform#1920]
### Discussed in https://github.com/orchidsoftware/platform/discussions/1919

<div type='discussions-op-text'>

<sup>Originally posted by **Ayabadsir** October 13, 2021</sup>
Hi, 

I tried this:

`TD::make('statut', __('Statut'))
                ->sort()
                ->cantHide()
                ->badge(function ($books) {
                    return $books->statut;
  }),`

And I got Method Orchid\Screen\TD::badge does not exist.

What can I do please!</div>

**Comment by tabuna** [comment]
There is no `badge` method for cells. You may have confused it with the `render` method.

```php
TD::make('statut', __('Statut'))
    ->sort()
    ->cantHide()
    ->render(function ($books) { 
        return $books->status; 
    })
```

**Comment by Ayabadsir** [comment]
Thank you, sorry I think I did not express my problem well. I would like to be able to color my statutes. For example red for lost, green for borrowing, etc.
C'est pour cela que j'ai tenté d'utiliser badge comme dans la demo.

![image](https://user-images.githubusercontent.com/24679609/137295567-197abd07-e69d-4f88-b7e6-a7dc46cb7b6a.png)
