### ISSUE TITLE
404 The application could not process your request

### ISSUE THREAD

**Issue by archlicher** [orchidsoftware/platform#1937]
**This popup message informs me every time I press export.**

I have a bunch of docs that I need to export from a DateTime Range. Everything goes well until I press the export button:
    _404 The application could not process your request_

How to proceed?

Thank you!

**Comment by tabuna** [comment]
I don't need a commercial code. You can write a minimal example that reproduces your error. Otherwise, we will only guess the reason for the error.

**Comment by archlicher** [comment]
I have solved
