### ISSUE TITLE
AttachmentController::getFilesByIds() does not exist

### ISSUE THREAD

**Issue by patlamontagne** [orchidsoftware/platform#1940]
**Describe the bug**

The systems route file seems to be refering to a non existing method on AttachmentController : 

https://github.com/orchidsoftware/platform/blob/master/routes/systems.php#L22

  - Platfrom Version: ^10.7
  - Laravel Version: ^8.40
  - PHP Version:  8

**Comment by tabuna** [comment]
Thanks for pointing this out. I removed the definition from routes.
