### ISSUE TITLE
Submit from Modals refreshes the whole screen

### ISSUE THREAD

**Issue by stonedleaf** [orchidsoftware/platform#1947]
**Describe the bug**
When you Submit or click the Apply button on a Modal, the whole page will refresh.

It produces the following issues:
1. If there are validation errors, they will appear on the modal AND on the parent screen.
2. Unsaved changes on the parent screen are removed

**To Reproduce**

  1. Create a simple form layout then put it on a Modal. 
  2. Activate the modal from 1 using a ModalToggle. The function for the method() of this ModalToggle should perform laravel validations
  3.  Go to the screen where 1 and 2 was added. Trigger the ModalToggle, and click Apply.

**Expected behavior**
The whole page should not refresh. Only the modal window should be affected.

**Additional context**
I think the issue is that the normal operation of form HTML tag is used instead of a javascript-based form submit operation.
Modal forms also uses the same js controller with forms on the main screen.

Is it possible to fix this issue?

Thank you

**Comment by tabuna** [comment]
Hey @stonedleaf 

> If there are validation errors, they will appear on the modal AND on the parent screen.

It happens only when the page has two completely identical fields and the modal window. When a validation error occurs, the forms do not know from which they were sent and notifications are displayed for both.

For this reason, the modal window will open. The solution is straightforward to use different names and prefixes for the fields. For example, `user.email` for a page form and` modal.email` for a modal window.


> Unsaved changes on the parent screen are removed

An action when submitting a form from a modal window can take any action. Including influencing the content already shown. Imagine a table with a list box and a modal window to add a new record. After adding, do you want to see it?

Therefore, we assume that the content has been changed and update the page. If you have any suggestions on how to track such changes, please share them.
