### ISSUE TITLE
 multiple repetition menu items when using laravel octane

### ISSUE THREAD

**Issue by e2site** [orchidsoftware/platform#1950]
**Describe the bug**
When using laravel octane left menu items multiple repetition

**To Reproduce**

  1. install octane
  2. login admin 
  3. click left menu, after few click there are lot of duplicate menu items

**Screenshots**
[Screenshot](https://i.ibb.co/N2xzjXy/laravel-bug.png)

**Server (please complete the following information):**
  - Platfrom Version: [10.14.0]
  - Laravel Version: [8.57.0]
  - PHP Version:  [8.0]
  - Database:  [MySql]
  - Database Version:  [8.2]

**Comment by tabuna** [comment]
Octane support starts from [10.15.0]( https://github.com/orchidsoftware/platform/blob/master/CHANGELOG.md#10150---2021-09-22) please update
