### ISSUE TITLE
Select has a wrong position in the modal

### ISSUE THREAD

**Issue by wh01ssh3** [orchidsoftware/platform#1966]
**Describe the bug**
When I open the selection in modal mode, it opens from the top. And when I scroll down and reopen the selection, it is far from the field.

**To Reproduce**

1. Open modal with selection in the end of modal. There should be little space at the bottom so the selection will open at the top
2. Open selection
3. Scroll down
4. Reopen the selection

**Expected behavior**
When I open the selection in modal mode, it opens from the top. And when I scroll down and reopen the selection, it should open near the field.

**Screenshots**

![Select](https://user-images.githubusercontent.com/19667313/141747154-15c12e67-54e4-4565-ae03-f26a4c8c205d.png)

**Desktop (please complete the following information):**
 - OS: ubuntu, Mac, windows 
 - Browser: chrome, safari
 - Version: chrome 95.0.4638.69, safari 15.1 (17612.2.9.1.20)

**Server (please complete the following information):**
  - Platfrom Version: 10.14.1
  - Laravel Version: 8.61.0

  - PHP Version:  7.4
  - Database:  MySql
  - Database Version:  8.2

**Additional context**
There is no this problem in previously release. I found the solution in change position to absolute, but can't fix the js that added the position and not sure about this solution

**Comment by tabuna** [comment]
This should be fixed with the release 10.24.0

**Comment by EgorGruzdev** [comment]
This fix led to incorrect display of select in matrix.

![image](https://user-images.githubusercontent.com/930669/148644416-21e095aa-9425-49f8-96a0-52357646bde0.png)
