### ISSUE TITLE
Setting asyncParameters on ModalToggle  show a 404 error page 

### ISSUE THREAD

**Issue by lhoucinecherif** [orchidsoftware/platform#1968]
Hi,

**Describe the bug**
Setting "asyncParameters" on "ModalToggle" lead to show a 404 page after clicking "Apply" button

**To Reproduce**

  1. Add Modal : 
  ```
//
Layout::modal('editSubscriptionModal', [
                CustomerHistoryModalRows::class,
                CustomerHistoryModalListener::class
            ])
                ->title("Update Subscription")
                ->applyButton('Update Subscription')
                ->async('asyncGetCustomerHistory'),
//
```
  2. Add action buttons to a Table
 
```
TD::make('action', 'Actions')->render(function (CustomerHistory $history) {
                return Group::make([
                 //
                    ModalToggle::make()
                        ->modal('editSubscriptionModal')
                        ->icon('pencil')
                        ->method('updateSubscription')
                        ->asyncParameters([ 
                            'history' => $history->id,
                        ]),
                    //            
                ]);
            })
```
3. Adding  the  action to execute:
```
 public function updateSubscription(Customer $customer, Request $request)
    {
     //
        Alert::info('You have successfully updated the customer.');
        return redirect()->route('platform.customer.edit', $customer);
    //
    }
```

A**Expected behavior**
It should execute the function "updateSubscription" 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 96.0.4664.45 (Build officiel) (64 bits)

**Server (please complete the following information):**
  - Platfrom Version: 10.22.1
  - Laravel Version: 8.71.0
  - PHP Version:  7.4.19
  - Database:   MySql
  - Database Version:  5.7.33

**Additional context**
it seems that by adding the "asyncParameters", those params are added to the post URL, instead of posting to "/admin/customer/32/updateSubscription" it post to "/admin/customer/32/updateSubscription**?history=68**" , so in my opinion its what caused the 404 error page ! maybe its a dynamic routing issue when adding params , (I need those params to dynamically load fields on the modal, but after that I need to update/save ... )

Thanks .

**Comment by lhoucinecherif** [comment]
A workaround is to override the generated action : 

```
TD::make('action', 'Actions')->render(function (CustomerHistory $history) {

               // Resolve the current route manually 
               $baseName = 'customer';
               $customer = data_get(request()->route()->parameters(),'customer');
               
                return Group::make([
                 //
                    ModalToggle::make()
                        ->modal('editSubscriptionModal')
                        ->icon('pencil')
                        ->method('updateSubscription')
                        ->asyncParameters([ 
                            'history' => $history->id,
                        ])
                         // override the action , so I remove the added params to the post url
                        ->action( config('platform.prefix') . "/$baseName/$customer->id/updateSubscription"),
                    //            
                ]);
            })
```

**Comment by lhoucinecherif** [comment]
Adding a hidden field  to the modal solved the issue 

`  Input::make('history.id')->type('hidden'),`

This is just a Workaround of this bug.

**Comment by tabuna** [comment]
> Adding a hidden field to the modal solved the issue
> 
> Input::make('history.id')->type('hidden'),
> 
> This is just a Workaround of this bug.

If your route does not contain the identifier you need, then you can pass it in the method:

```php
->method('updateSubscription',[
    'customer' => 1
]);
```

**Comment by lhoucinecherif** [comment]
@tabuna  Thank you so much for your help.
