### ISSUE TITLE
Incorrect menu behavior when using translations.

### ISSUE THREAD

**Issue by grigoriy-ivanov** [orchidsoftware/platform#1975]
**Describe the bug**

Using the code I get different id (translated) and href (not translated) and list does not expand

**To Reproduce**
```php
            Menu::make('Меню')
                ->title('Управление')
                ->icon('layers')
                ->list([
                    Menu::make('Настройки')
                        ->route('platform.systems'),
                ]),
```
```json
"Меню": "Menu"
```

**Comment by tabuna** [comment]
Hey @grigoriy-ivanov, you can specify any additional information because the above code works on the latest version of the package.

**Comment by grigoriy-ivanov** [comment]
@tabuna I tested on 10.24: problem not solved, 
When using translation menu list doesn't expand

Expected:
```html
<a data-turbo="true" class="nav-link d-flex align-items-center" href="#menu-menyu" data-bs-toggle="collapse" aria-expanded="true">
        Меню
            </a>

<div class="nav sub-menu ps-2 collapse show" id="menu-menyu" data-bs-parent="#headerMenuCollapse" style="">
                    <li class="nav-item ">
    <a data-turbo="true" class="nav-link d-flex align-items-center collapsed" href="http://test.serviceapp.gcms/dashboard/system">
       
        Settings
            </a>
</li>
            </div>
```
When we don't use translation platform generates ``` href="#menu-menyu"``` and ``` id="menu-menyu"```
Current:
```html
<a data-turbo="true" class="nav-link d-flex align-items-center collapsed" href="#menu-menyu" data-bs-toggle="collapse">
        Menu
            </a>

<div class="nav collapse sub-menu ps-2 " id="menu-menu" data-bs-parent="#headerMenuCollapse">
                    <li class="nav-item ">
    <a data-turbo="true" class="nav-link d-flex align-items-center collapsed" href="http://test.serviceapp.gcms/dashboard/system">
        Settings
            </a>
</li>
            </div>
```
When we use translation platform generates ``` href="#menu-menyu"``` and ``` id="menu-menu"```

**Comment by tabuna** [comment]
Hey @grigoriy-ivanov. If I understand correctly, then you have a problem with these names when you try to use something like this:

```php
Dashboard::addMenuSubElements(Dashboard::MENU_MAIN, 'menu', [
    Menu::make('Sub element item')->icon('badge')
]);
```

To create a submenu dynamic, you need to add the main item and specify its unique name using the slug method. This is also indicated in the documentation in this section https://orchid.software/en/docs/menu/#nested-menu

**Comment by grigoriy-ivanov** [comment]
@tabuna I make PR) #1996
