### ISSUE TITLE
Баг у абстракции скрина

### ISSUE THREAD

**Issue by windx-foobar** [orchidsoftware/platform#1982]
**Describe the bug**
Неправильный мердж массива. Попадает ключ, который не должен быть. Из-за этого рушится DI у экшена кнопки.
Например если вызывать дебаггер у экшена кнопки, получим такую картину:
`dd($model); // В данном случае, $model - это просто первый аргумент метода. Вместо модели, получим значение из ключа q, т.е. URI`

**To Reproduce**
Шаги:

  1. Создать скрин, кнопку с экшеном.
  2. Попробовать нажать на кнопку.

**Expected behavior**
Ожидалось мерджа без лишних параметров в абстрактном классе Screen, чтобы подхватилась модель в экшене.
На момент написания ишью, не грузились скриншоты.
Подробности в телеграм: @tyominomi

**Desktop (please complete the following information):**
 - OS: Manjaro Linux

**Server (please complete the following information):**
  - Platfrom Version: 10.23.0
  - Laravel Version: 8.63.0
  - PHP Version:  8.0.11

**Additional context**
В конечном итоге эта проблема решается очень легко. Но изза того что большинство методов Screen приватные, я не могу корректно наследовать методы, остается просто копировать, что не имеет смысла.

**Comment by windx-foobar** [comment]
@tabuna Вот скриншот примерного решения.
https://i.imgur.com/rAd2xM3.png

**Comment by astersnake** [comment]
Please submit your issues in English.
