### ISSUE TITLE
Remove the uploaded file from `Stroage` folder, and `DB` in `Upload` Field

### ISSUE THREAD

**Issue by mahmoudmohamedramadan** [orchidsoftware/platform#1983]
There is an awesome field in orchid called `Upload` when we upload a file the file is uploaded into the `storage` folder and saved into `database` also, and this scenario is almost nice because, if the user really wants to upload this file it will take no time for uploading into storage, and saving into database BUT what if he did not need to upload this file and want to remove it the real scenario that must happen is this uploaded file must be removed from the `storage` folder and `database` which this not happen when user click `Remove` button and I tried more to solve this issue BUT I failed for sorry. There are two solutions for that issue

### First
It will be enough to just preview the image using jQuery WITHOUT needing to really upload it and saving into the database

### Second
When the user click the `Remove` button the uploaded image must be removed from the `storage folder and `database`

**Comment by tabuna** [comment]
> if the user really wants to upload this file it will take no time for uploading into storage, and saving into database BUT what if he did not need to upload this file and want to remove it the real scenario that must happen is this uploaded file must be removed from the storage folder and database which this not happen when user click Remove button and I tried more to solve this issue BUT I failed for sorry.

Files from physical media are deleted only when all links to it are also deleted. You can check this by deleting the model and making sure the hash is unique. More details here https://orchid.software/en/docs/attachments/

> It will be enough to just preview the image using jQuery WITHOUT needing to really upload it and saving into the database

If you do not want to use attachments and manually manage the download, you can use the default upload field at any time:

```php
Input:make('upload')->type('file'):
```

You can also create your fields using your favorite libraries. You can read more here https://orchid.software/en/docs/builder/#representation-of-elements-of-a-form


> When the user click the Remove button the uploaded image must be removed from the storage folder and database`

As I said earlier, files that are not used in other models are deleted in the Eloquent event (Make sure you use them)

**Comment by mahmoudmohamedramadan** [comment]
Thank you very much
