### ISSUE TITLE
Remove unsaved image using `Quil` Field from the database

### ISSUE THREAD

**Issue by mahmoudmohamedramadan** [orchidsoftware/platform#1987]
I noticed something wrong while dealing WITH the `Quil` Field is when I uploaded an image to the `Quil` I noticed that this image is automatically saved into the `attachments` table and this feature is nice BUT when I remove it from `Quil` the record was still remaining into the database and this is a big issue because this issue will cause many unwanted records.

## Solutions

**First, Save the image ONLY into the `attachments` table when the user wants to save it**

**Second, If the user upload an image into `Quil` then remove it, the record must be removed using `Observers` or something like that**

**Comment by tabuna** [comment]
This description is too general. Please suggest a specific solution
