### ISSUE TITLE
CRITICAL BUG: database field name collision with model class specific attributes

### ISSUE THREAD

**Issue by ivanomatteo** [orchidsoftware/platform#1989]
**Describe the bug**
The trait "AsSource" is part of the model class, so can access also to private and protected members.

AsSource->getContent() function, when a field is null, as last attempt try to access to field value in this way:
`$this->$field`
but this is not the correct way, because class specific attributes (public,protected,private) take the precendence over the database fields.

This may lead to unespected errors.

**To Reproduce**
For example if we use this trait on a model with a nullable database field called "visible" ==  null
Arr::get($this->toArray(), $field) ---> is null
Arr::get($this->getRelations(), $field) ---> is null
$this->$field ---> refear to "protected $visible = []"

**Expected behavior**
AsSource->getContent() should return null in the described case, but return an array.

**Server (please complete the following information):**
  All

**Additional context**
in AsSource->getContent() 
$this->toArray() force the execution of all casts and accessors, but only one field is requested,
so it's also an unecessary overhead.

I also opened a pull request:
https://github.com/orchidsoftware/platform/pull/1988

**Comment by tabuna** [comment]
With the release of 10.25.0, the `getContent` method will no longer return model properties.
