### ISSUE TITLE
Listeners does not work with Layout::block()

### ISSUE THREAD

**Issue by astersnake** [orchidsoftware/platform#1998]
1. Create a a listener according the documentation in the tutorial
  2. Add a ` Layout::block()` in the same layout return
  3. The listener will not work

For example:
```php
    public function layout(): array
    {
        return [
            TestListener::class, 
            TestLayout::class,
        ];
    }
```
   Works perfect, but in the following case, the listener is not working
  ```php
    public function layout(): array
    {
        return [
            TestListener::class,
            Layout::block(TestLayout::class)
                ->title(__('Test')),
        ];
    }
```
Also if the listener is the argument of `Layout::block()` It will not work either.

**Comment by tabuna** [comment]
Hi @astersnake. I have not been able to reproduce the specified behavior on the latest version of the package.

Using this tutorial https://orchid.software/en/docs/listener/ , I have placed the fields in the block layer:

```php
namespace App\Orchid\Layouts;

use Orchid\Screen\Fields\Input;
use Orchid\Support\Facades\Layout;
use Orchid\Screen\Layouts\Listener;

class AmountListener extends Listener
{
    /**
     * List of field names for which values will be listened.
     *
     * @var string[]
     */
    protected $targets = [
        'a',
        'b',
    ];

    /**
     * What screen method should be called
     * as a source for an asynchronous request.
     *
     * The name of the method must
     * begin with the prefix "async"
     *
     * @var string
     */
    protected $asyncMethod = 'asyncSum';

    /**
     * @return Layout[]
     */
    protected function layouts(): array
    {
        return [
            Layout::block(AmountRows::class)
                ->title('Test')
                ->description('Lorem ipsum dolor sit amet, consectetur adipiscing elit...'),
        ];
    }
}
```

![image](https://user-images.githubusercontent.com/5102591/144747026-8cb34294-2c60-4f82-9000-eca781e7571c.png)


And it still works. I also tried to remove the drying fields from it and place them separately in the block:

```php
/**
 * Views.
 *
 * @return Layout[]
 */
public function layout(): array
{
    return [
        Layout::block([
            Layout::rows([
                Input::make('a')
                    ->title('First argument')
                    ->type('number'),

                Input::make('b')
                    ->title('Second argument')
                    ->type('number'),
            ]),
        ]),

        AmountListener::class,
    ];
}
```

![image](https://user-images.githubusercontent.com/5102591/144747010-81827a19-200d-4b34-8b84-24f210e4bafa.png)


Did I miss something or misunderstand your behavior?

**Comment by astersnake** [comment]
Ok, I missed something before, to reproduce the problem you need to use the `commands` function:

    /**
     * @return array
     */
    public function layout(): array
    {
        return [
            Layout::block(TestLayout::class)
                ->title(__('Test'))
                ->description(__('Test'))
                ->commands(
                    Button::make(__('Save'))
                        ->type(Color::DEFAULT())
                        ->icon('check')
                        ->canSee($this->model->exists)
                        ->method('save')
                ),
            TestListener::class,
        ];
    }

In this case, the listener is no longer working.

Another example:

            Layout::block(TestListener::class)
                ->title(__('Test'))
                ->description(__('test'))

Works perfectly, but the following example doesn't work.

      Layout::block(TestListener::class)
            ->title(__('Test'))
            ->description(__('test'))
            ->commands(
                Button::make(__('Save'))
                    ->type(Color::DEFAULT())
                    ->icon('check')
                    ->canSee($this->model->exists)
                    ->method('save')
            )

I think is because of the `canSee()` property.

**Comment by tabuna** [comment]
Hey, @astersnake.  Request status is not persisted between hits. So when you first defined `$this->model->exists`, then on the second (asynchronous) call, the class is re-created, and the property value no longer exists for it.

The best thing to do is define all the data in the query screen or your asynchronous method and then access the store.
