### ISSUE TITLE
Filter dropdown is closed when I click/focus on select2 element

### ISSUE THREAD

**Issue by ManojKiranA** [orchidsoftware/platform#2001]
**Describe the bug**

After creating the filter for relations when i try to select a specific relations the dropdown is auto closing

**To Reproduce**

  1.Create Column 
  2. Add a select filter to it like
  3. Try to select a value

```
TD::make('columnname', 'Column')
            ->cantHide()
            ->filter(
                Select::make('columnname')
                ->options([
                    'index'   => 'Index',
                    'noindex' => 'No index',
                ])
        )
```
**Expected behavior**
Dropdown should not close automatically.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 96.0.4664.45 

**Server (please complete the following information):**
  - Platfrom Version: ^10.25
  - Laravel Version: 8.65
  - PHP Version:  8.0.12
  - Database:  MariaDB
  - Database Version:  10.4.21-MariaDB

**Comment by tabuna** [comment]
Hey @ManojKiranA. This should be fixed with the release https://github.com/orchidsoftware/platform/releases/tag/10.27.2
