### ISSUE TITLE
Select in matrix retains only the first value when going back after validation

### ISSUE THREAD

**Issue by brianlw** [orchidsoftware/platform#2019]
**Describe the bug**
I am using a matrix. Each row has a select dropdown which is made as follows:
```
$options = [1 => 'option 1', 2 => 'option 2', 3 => 'option 3'];

Matrix::make('sites')->id('sites')
                ->title('Enter sites.')
                ->columns(['Site' => 'id', 'url'])
                ->fields([
                    'id' => Select::make('site')->options($options),
                    'url' => Input::make('text')->type('url')->required(),
                ])
```

Then in my save method in the screen I do the following
```
return back()->withInput();
```

Now in my matrix the selects all got the same value which is based on the first selected value.

**To Reproduce**

  1. Enter all different values in the selects of the matrix:
![screenshot 1](https://i.imgur.com/mugxmly.png)

  2. I press save and in my screen I call this method `return back()->withInput();`
  3. Matrix is now looking as follow:
![screenshot 2](https://i.imgur.com/1E1Yh5S.png)
  

**Expected behavior**
All selects in the matrix should keep the right value after validating.

**Desktop:**
 - OS: Mac
 - Browser Chrome
 - Version 96

**Server:**
  - Platfrom Version: 10.26.0
  - Laravel Version: 8.0
  - PHP Version:  7.4

**Comment by tabuna** [comment]
Hey @brianlw. Check out the new release https://github.com/orchidsoftware/platform/releases/tag/10.27.1

It happens because, in the Select field, we strictly check the value, for example, 1 === 1. And in the session, the old input was returned as a string.

**Comment by brianlw** [comment]
Thanks @tabuna , works great now!
