### ISSUE TITLE
tempnam(): file created in the system's temporary directory

### ISSUE THREAD

**Issue by Hrache** [orchidsoftware/platform#2068]
Hi!
**Describe the bug**
I just installed Orichid and after the step **composer require orchid/platform** when I load the page it throws such exception ### 
tempnam(): file created in the system's temporary directory

**Expected behavior**
just a normal installation flow depending on installation instruction that is provided by the software

**Screenshots**
https://ibb.co/0tTSyQ6

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - Browser Latest MS Edge
 - Version 97.0.1072.62 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Server (please complete the following information):**
  - Platfrom Version: Apache 2.4.46
  - Laravel Version: 8.75
  - PHP Version:  8.0.12
  - Database:  MySql
  - Database Version:  8.0.21

**Additional context**
Help!

**Comment by tabuna** [comment]
Hello @Hrache, this is not a packaging error but a local environment error.
Make sure your `php.ini` has a valid `upload_tmp_dir` path and is also writable.

**Comment by Hrache** [comment]
Thanks for the answer **tabuna**, but what are the exact permissions that I should give to the **tmp** directory of my server, because I removed that directory, recreated it and gave the same permissions that are in the orchid docs, but useless?!
