### ISSUE TITLE
Add Mobility to UserPresenter

### ISSUE THREAD

**Issue by Augen2203** [orchidsoftware/platform#2089]
**At one point, while testing a number of roles, I encountered an unpleasant error, I think the screenshot below will demonstrate it better than words.**

**Also ran into this in tables.**

**Decided to fix it for myself and maybe it will be useful.**

<img width="371" alt="Снимок экрана 2022-01-28 в 22 59 31" src="https://user-images.githubusercontent.com/59070939/151621790-583e37a5-300c-4cad-8671-bab5b63add6e.png">

**Actually my solution:**

```
    /**
     * @param int $numberRoles number of output roles
     * @return string
     * @throws \Throwable
     */
    public function subTitle(int $numberRoles = 2): string
    {
        $roles = $this->entity->roles->pluck('name');

        /** @var $roles Collection */
        if ($roles->isNotEmpty()) {
            return $roles = Label::make()
                ->title($roles
                    ->take($numberRoles)
                    ->implode(' / ')
                )
                ->popover(($roles->count() > $numberRoles)
                    ? $roles->implode(' / ')
                    : false)
                ->__toString();
        }

        return __('Regular user');
    }
```

**In the case of **UserPresenter**, where we know that the "`subTitle()`" method gives us a string of roles, we can now control how many roles should be displayed and which should be hidden in the **popover****

**Result:**
![ezgif-5-5ac94ceee7](https://user-images.githubusercontent.com/59070939/151625224-bcf6e234-6f04-4689-b201-9e38051a8f22.gif)

**Comment by tabuna** [comment]
Hi @Augen2203. I don't want to complicate the stand for new users. But you have an interesting solution to the problem. To prevent this from happening again, a limit on the number of characters was added
