### ISSUE TITLE
The layout breaks when the role name is long

### ISSUE THREAD

**Issue by Impeck** [orchidsoftware/platform#2107]
When using long role names or when using multiple roles for one user, the user's avatar size decreases.

![2022-02-03_14-24-27](https://user-images.githubusercontent.com/1071117/152315441-a61b3883-2a59-41aa-b6f0-243b9aaeb49a.png)

This is true for the latest version of the platform 10.31.0.

**Comment by tabuna** [comment]
New installations are now limited to a number of characters in a string.
