### ISSUE TITLE
Removing search field in Select

### ISSUE THREAD

**Issue by oleksiakszymon** [orchidsoftware/platform#2115]
### Discussed in https://github.com/orchidsoftware/platform/discussions/2091

<div type='discussions-op-text'>

<sup>Originally posted by **oleksiakszymon** January 28, 2022</sup>
Hello,
I'm trying to make quite simple select filters and have no clue how to remove field to search possible options in select dropdown.
Thanks in advance
![image](https://user-images.githubusercontent.com/73693900/151626533-d7ff6acf-7cb1-49cb-8f16-9eb7c3e013fe.png)
</div>

**Comment by alithedeveloper** [comment]
Hey @oleksiakszymon , I was in same predicament and wanted to have a simple select dropdown rather than the default one. I achieved that by using a custom view file.
```
  // example-select.blade.php
  <div class="bg-white rounded shadow-sm p-4 py-4 d-flex flex-column">
    <div class="form-group">
        <label for="example">Example Select </label>
        <select class="form-control" style="appearance: auto !important" id="example" name="example">
            <option value="0">No</option>
            <option value="1">Yes</option>
        </select>
    </div>
</div>
```
Then you can reference it where you want, in my case i wanted to use it in Modal

```
  Layout::modal('Example', [
        Layout::view('example-select', ['data' => $someData])
    ]),
```

**Comment by astersnake** [comment]
As this is already in discussion https://github.com/orchidsoftware/platform/discussions/2091 and @alithedeveloper has given you a solution, I will close this issue.
