### ISSUE TITLE
Laravel9/orchid12 upgrade(?) bug. 

### ISSUE THREAD

**Issue by Borks** [orchidsoftware/platform#2128]
**Describe the bug**
You must call one of in() or append() methods before iterating over a Finder. 
Orchid platform fails to load any page with error above

**To Reproduce**

  1. Upgraded to laravel 9
  2. Upgraded to orchid 12

**Expected behavior**
I expected the page to load. Main application (not orchid) works fine with new upgraded laravel 9.

**Screenshots**
![image](https://user-images.githubusercontent.com/5571023/153714844-09886ac3-57e2-4fac-80f7-6fafa41f41c0.png)

**Server (please complete the following information):**
  - Platfrom Version: 12.0.0
  - Laravel Version: 9.0.2
  - PHP Version:   8.0.15

**Comment by Borks** [comment]
Issue solved by republishing vendor files..

**Comment by polyskalov** [comment]
https://orchid.software/en/docs/upgrade/#icons

**Comment by Borks** [comment]
Seems you already got it fixed @polyskalov Sorry for not answering sooner.
