### ISSUE TITLE
Matrix-field add row bug

### ISSUE THREAD

**Issue by KupperXD** [orchidsoftware/platform#2171]
Hello. There is a bug. related to js script
Immediately after the action of adding a new row to matrix table, following error occurs; 
<img src="https://i.imgur.com/EzyfB8q.png"></img>
The bug occurs due to the inner field in the matrix. which has a template and matrix_controller finds the wrong template.
I fix it there - https://github.com/orchidsoftware/platform/pull/2170

**Comment by tabuna** [comment]
Hi @KupperXD, I can't reproduce this just by clicking on the button. Is there any other information that can help reproduce the problem? (Tried Safari/Chrome)

**Comment by KupperXD** [comment]
> Hi @KupperXD, I can't reproduce this just by clicking on the button. Is there any other information that can help reproduce the problem? (Tried Safari/Chrome)

Hi 
In order to recreate the bug described, it's needed  to add a column into matrix, which has a template.
for example, for me it's like this <img src="https://i.imgur.com/JpaNyk8.png">
I'm creating a Matrix and add an area   Upload::make (standard Orchid)
It consists of  template - <img src="https://i.imgur.com/dyATE0a.png">
And that's what matrix_controller.js  is looking for, but it should find a template for a current line coping.

So, in case we add a field to matrix, which has an attached template. so the matrix_controller.js is not going to work properly while row adding.

**Comment by Rogue85** [comment]
Same error

```
Matrix::make('block.data.items')->columns([
    'Заголовок' => 'title',
    'Файл' => 'file',
])->fields([
    'title'   => Input::make()->type('text'),
    'file' => Upload::make()->maxFiles(1),
]),
```

**Comment by tabuna** [comment]
Hi, with release `12.2.2` should be resolved
