### ISSUE TITLE
Error for update password in profile page

### ISSUE THREAD

**Issue by moskoweb** [orchidsoftware/platform#2176]
**Describe the bug**
After update for latest version from Orchid and Laravel, an error occurs for change password.

**To Reproduce**
  1. Open Profile page
  2. Insert Old Password
  3. Insert new password
  4. Submit

**Additional context**
Here is the code we used to solve the problem
```php
public function changePassword(Request $request): void
{
    $request->validate([
        'old_password' => 'required',
        'password'     => 'required|confirmed',
    ]);

    if (Hash::check($request->old_password, $request->user()->password)) {
        tap($request->user(), function ($user) use ($request) {
            $user->password = Hash::make($request->get('password'));
        })->save();

        Toast::success(__('Password changed.'));
    } else {
        Toast::error(__('Current password does not match'));
    }
}
```

**Comment by tabuna** [comment]
Hi @moskoweb, please have a look at the Laravel update documentation: https://laravel.com/docs/9.x/upgrade#the-password-rule Maybe you need to make changes to the previously published code.

**Comment by moskoweb** [comment]
I hadn't seen this update, it really worked.
