### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by paulocoutinhox** [orchidsoftware/platform#2179]
Hi,

I installed version 12.2.1 now and get some problems:

1 - Storage url is wrong:
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/395096/158319437-ca73b611-83db-46b9-a876-ed755e11cdf9.png">

2 - If you try select image from media library, and close and reopen media library, it is multiplying the items inside it and the URL of storage of media library is wrong too:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/395096/158319599-4f1a2f97-1852-407c-add7-455b12e42e1b.png">

3 - The storage only works when upload first time, after, the URL of storage is wrong:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/395096/158319693-6b0e6cef-5e4c-483b-828b-0ac022e97c7a.png">

Wrong path example after select already uploaded media:
`http://localhost/storage/2022/03/15/3af4c7ffb7e1eb8d5c3272da07a0c34a3cacdb07.png`

Correct path example after upload:
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAA[...]`

4 - The calendar is bigger on mobile size page:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/395096/158320174-38a2c6fd-2a3b-45ee-9bc9-f3c0969c9473.png">

Thanks.

**Comment by trong291990** [comment]
About #1, #2, #3: Let try this: https://laravel.com/docs/9.x/filesystem#the-public-disk

**Comment by tabuna** [comment]
Hi, @paulocoutinhox As for your initial list of 1-3 problems, they are all most likely related to the fact that your `.env` file value `APP_URL` is different from what you use in your browser.

For example, the value in the file is `http://127.0.0.1`, and in the browser using the artisan server, the port is also specified `http://127.0.0.1:8000`.

Once the settings match, the images will be shown.



> 4 - The calendar is bigger on mobile size page:


You are viewing with an emulator in your browser, which does not reflect reality. On a phone, this uses native elements. For example, this is how my time selection looks on my iPhone:

![telegram-cloud-photo-size-2-5321489756082779955-x](https://user-images.githubusercontent.com/5102591/159600666-0269534e-3c2a-4bee-889a-df0d9b09dcd2.jpg)
