### ISSUE TITLE
Cannot integration tawk.to

### ISSUE THREAD

**Issue by thephucit** [orchidsoftware/platform#2180]
I add this code to file _brand/header.blade.php_
```php
@push('scripts')
    <script src="/vendor/js/tawk.js?v={{ time() }}"></script>
@endpush
```

After switching screens, chat box tawk cannot be displayed again

**Comment by tabuna** [comment]
Hello, this is not a direct error. Orchid emulates SPA using https://hotwired.dev

You can also view events briefly on the documentation site https://orchid.software/en/docs/javascript/
