### ISSUE TITLE
Allow Screen `checkAccess` method to be overriden 

### ISSUE THREAD

**Issue by sot-geo** [orchidsoftware/platform#2188]
Helllo guys.

You have done a fantastic job here :smiley: 

Please can you change  Screen `checkAccess` from private to protected? It could help a lot in order to add some checks in custom applications

https://github.com/orchidsoftware/platform/blob/b2ce43e3163cb16e0c4f7242fc611d88f5ce4349/src/Screen/Screen.php#L240

Thanks in advance

**Comment by tabuna** [comment]
Since version 12.4.3 the method is declared as protected
