### ISSUE TITLE
File upload doesn't work for S3 - makeDirectory cannot be used with S3?

### ISSUE THREAD

**Issue by BenWoodford** [orchidsoftware/platform#2193]
Unless I'm missing something, you cannot use `makeDirectory` with an S3 filesystem driver as S3 has no concept of a directory - when you create a directory it has to be because a file has been uploaded to it.

You can simulate this very easily using `Storage::disk('s3')->makeDirectory("foo/bar");` which will fail with an `UnableToWrite` exception.

What use does the `makeDirectory` call have here anyway, given that Flysystem will automatically create the directory tree when you put a file?

**Comment by tabuna** [comment]
Hi @BenWoodford, I don't use S3 in real projects. But in my opinion, the directory can be made if there is a scope.

I can confirm that the directory will be created automatically when using the local driver.
 Let's remove manual directory creation.

**Comment by tabuna** [comment]
The directory is no longer pre-created as of version 12.3.2
