### ISSUE TITLE
Error: Laravel9 - Finder

### ISSUE THREAD

**Issue by vallter2** [orchidsoftware/platform#2204]
**Describe the bug**
After update Laravel to 9, and Platform to 12, I got message:

**vendor\symfony\finder\Finder.php::[611]**
**You must call one of in() or append() methods before iterating over a Finder.**

**Server (please complete the following information):**
  - Platfrom Version: 12.3.2
  - Laravel Version: 9.9.0
  - PHP Version:  8.1.5

**Comment by tabuna** [comment]
Hi @vallter2 Duplicates: https://github.com/orchidsoftware/platform/issues/2128


The section you need is located here https://orchid.software/en/docs/upgrade/#icons
```php
'icons' => [
    'orc' => \Orchid\IconPack\Path::getFolder(),
]
```
