### ISSUE TITLE
`withTrashed()` method for routes does not work as expected and still return 404 error for soft deleted models screen

### ISSUE THREAD

**Issue by czernika** [orchidsoftware/platform#2218]
**Describe the bug**

Hi!

I found out that `withTrashed()` [route method](https://laravel.com/docs/9.x/routing#implicit-soft-deleted-models) is not working with `screen` - it will throw 404 error on soft deleted models (`User` model has `SoftDeletes` trait and `deleted_at` column is present)

**To Reproduce**

1. Create screen route (and appropriate Screen with necessary methods filled in)

```php
// platform.php
Route::screen('users/{user}', UserShowScreen::class)
        ->name('platform.systems.users.show')
        ->withTrashed() // this one
        ->breadcrumbs(function (Trail $trail, $user) {
            return $trail
                ->parent('platform.systems.users')
                ->push($user->name, route('platform.systems.users.show', $user));
        });
```
2. Softly delete User (for example with id 9)
3. Go to `/admin/users/9`
4. It will show 404 page

**Expected behavior**
User screen with information about deleted user with id 9

**Additional context**
If I change route to get `id` as a parameter and found soft deleted model by my own within Screen(`User::withTrashed()->findOrFail($id)`) it will work. So my guess the problem is with model binding of `query` method

```php
// UserShowScreen.php
class UserShowScreen
{
    // Soft deleted User model does NOT binding 
    public function query(User $user): iterable
    {
        $user->load(['roles']);

        return compact('user');
    }
}
```

## Proposed Solution

When I start digging deeper I found that if I change [this](https://github.com/orchidsoftware/platform/blob/master/src/Screen/Resolvers/ScreenDependencyResolver.php#L71) lines of `ScreenDependencyResolver`

```php
$model = $instance->resolveRouteBinding($value);
```

into 

```php
$routeBindingMethod = Route::current()->allowsTrashedBindings() && in_array(SoftDeletes::class, class_uses_recursive($instance))
        ? 'resolveSoftDeletableRouteBinding'
        : 'resolveRouteBinding';

$model = $instance->{$routeBindingMethod}($value);
```

`withTrashed()` method will show soft deleted models page when it's present and throw 404 when it's not.

These lines are basically [the copy of Laravel way](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Routing/ImplicitRouteBinding.php#L45) of resolving routes query dependencies for soft deleted models but I'm not entirely sure about this as a lack of knowledge about Laravel - that's why I am addressing this as an issue

**Comment by tabuna** [comment]
Hi @czernika Yes, we use a different way of defining parameters. And I'm not sure that we should fix it in this class. We have another way of binding that you can change in your screen:

```php
use Orchid\Screen\Resolvers\RouteDependencyResolver;

/**
 * @param string $method
 * @param array  $httpQueryArguments
 *
 * @throws \Illuminate\Contracts\Container\BindingResolutionException
 * @throws \ReflectionException
 *
 * @return array
 */
protected function resolveDependencies(string $method, array $httpQueryArguments = []): array
{
    return app()->make(RouteDependencyResolver::class)->resolveScreen($this, $method, $httpQueryArguments);
}
```

It already uses the Laravel methods you refer to. Could you confirm the performance or lack of it when using this method?

**Comment by czernika** [comment]
@tabuna Thanks with this method it works as charm)
