### ISSUE TITLE
Cannot Add a role to a user ( new or existing user )

### ISSUE THREAD

**Issue by HijenHEK** [orchidsoftware/platform#2235]
**Description**
Orchid provides roles to group permissions and adds them to a certain user.
the issue is I cannot add a role to an existing user or create a new user with a role.

**To Reproduce**

  1. got to the users list
  2. select a user to edit ( or click new user )
  3. add a role to it

**Expected behavior**
a role should be assigned to the user 

**Screenshots**
Issue face when trying to update:

![image](https://drive.google.com/uc?export=view&id=1RCsRA8qSrxO6ArSz_aRyLBNdvRIun8Lg)

Issue faced when creating a new user with a role: 

![image](https://drive.google.com/uc?export=view&id=1WqSVa7w33s21mfaSLuvlvY-Z-j_LphDi)

**Comment by czernika** [comment]
@HijenHEK looks like it more about mass assignment problem within your `User` model. You're basically allowing `roles` field to be filled. Edit your `protected $fillable` property so it didn't contain `roles` (or maybe you have empty `$guarded`)

**Comment by tabuna** [comment]
Should work with guarded properties since version `12.4.4`
