### ISSUE TITLE
Call to undefined method Orchid\Platform\Models\User::createToken()

### ISSUE THREAD

**Issue by kaizirlewagen** [orchidsoftware/platform#2241]
I try to use Orchid with Laravel [Sanctum](https://laravel.com/docs/9.x/sanctum). 

I modify the use model \App\Models\User.php

```
use Laravel\Sanctum\HasApiTokens;
 
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
}
```
After that i modify \App\Orchid\Screens\User\UserEditScreen.php

```
    /**
     * @param User    $user
     * @param Request $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function save(User $user, Request $request)
    {
        ...
        $user->createToken('API Token')->plainTextToken;
        ...
    }
```
If i add a new user i got the following error:

Call to undefined method Orchid\Platform\Models\User::createToken()

I extend the model, but the screen uses use Orchid\Platform\Models\User;

What can i do?`

**Server (please complete the following information):**
  - Platform Version: 12.4.4
  - Laravel Version: 9.12.2
  - PHP Version:  8.0.16
  - Database: mysql
  - Database Version:  10.5.15

**Comment by kaizirlewagen** [comment]
If i use the app user model, instead of Orchid\Platform\Models\User it works.

```
use App\Models\User;
```

Is this correct to do it this way?

**Comment by tabuna** [comment]
Yes, that's right.  Use your own user model
