### ISSUE TITLE
Select 2 placeholder is not working

### ISSUE THREAD

**Issue by AidasK** [orchidsoftware/platform#2250]
**Describe the bug**
I want to fill in a nullable relation in a database through select2 field. Though null value is never sent so it can not be filled.

**To Reproduce**
1. 
```php
 Relation::make('crawler.country_id')
                    ->fromModel(Country::class, 'name')
                    ->placeholder('Any'),
```
2. 
```php

    public function createOrUpdate(Crawler $crawler, Request $request): RedirectResponse
    {
        $data = $request->validate([
            'crawler.country_id' => 'nullable|exists:countries,id',
        ]);
        $crawler->fill($data['crawler'])->save();
      }
```
3. $crawler never gets saved with country_id null, because when "Any" is selected, no field is sent in the form. Hence 
`$data = $request->validate([`, produces `$data === []` empty array.

**Expected behavior**
$request should contain crawler.country_id key with an empty value, so it would be returned in the validation rules.

**Screenshots**
<img width="819" alt="image" src="https://user-images.githubusercontent.com/2088484/169691903-f3195792-4793-42ab-859f-15668dd9c10f.png">

**Server (please complete the following information):**
  - Platfrom Version:  12.5.0
  - Laravel Version: 9.13
  - PHP Version:  8.0
  - Database:  MySql
  - Database Version:  8.0

**Additional context**

My current workaround is to create a select field and populate empty value myself. Though it's not ideal as placeholder value is never displayed, but it works as intended.
```php
Select::make('crawler.country_id')
                    ->title('Country')
                    ->options([
                        '' => 'Any',
                    ] + Country::pluck('name', 'id')->toArray()),
```
<img width="774" alt="image" src="https://user-images.githubusercontent.com/2088484/169691980-8bdf0d5b-68d0-4a7a-982a-7af746e86807.png">

**Comment by tabuna** [comment]
Hi @AidasK `placeholder` is not a value and is not sent to the server. 
For a simpler explanation, let's take for example a regular `html` input:

```html
<input type="text" placeholder="What is your name?">
```

When a person does not fill in the field, then the question "What is your name?" will not be sent. 
Exactly the same behavior for `select2`. You can learn more about the html attribute here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#placeholder

**Comment by AidasK** [comment]
Though let's not close this so fast, there is an another issue then. How should we use this select with a nullable value? If placeholder is not sent, relation can be never filled with null.

Let's take this for example:
```
 Relation::make('crawler.country_id')
                    ->fromModel(Country::class, 'name')
                    ->placeholder('Any'),
```

Model country does not have a null value on countries table, so this value does not appear in the list. The only option to push null value here was via placeholder, which is not sent to the backend. So maybe you could suggest an another way to set this relation to null?

**Comment by UksusoFF** [comment]
On Relation field `popover` method not working as same as `placeholder`.
