### ISSUE TITLE
403 Forbidden in a new project

### ISSUE THREAD

**Issue by Dorsone** [orchidsoftware/platform#2263]
**Describe the bug**
I installed the platform to new Laravel project by reading the documentation (successfully installed), but after logging for entering to admin panel I have got the error 403 forbidden .
[Screenshots(Google Disk)](https://drive.google.com/drive/folders/14hg7pDmPJa0695HRIYTH9oxNaDIfoj83?usp=sharing) and I don`t touch other files, besides user migration, seeder and factory 

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Yandex
 - Browser Version latest
 - OS Version: 21H1

**Server (please complete the following information):**
  - Platfrom Version: 12.0
  - Laravel Version: 9.1
  - PHP Version:  8.1
  - Database:  MySql
  - Database Version:  8.0

**Comment by spmsupun** [comment]
I am having the same issue, any solutions?

**Comment by spmsupun** [comment]
Okay, I had to debug the package itself and I found out you need to set a role and add the role to the roles table, and set up the permission and the relationship. it doesn't automatically happen when you  add a user

**Comment by spmsupun** [comment]
Okay I found a seeder(OrchidDatabaseSeeder) but it doesn't mention the documentation

**Comment by tabuna** [comment]
Hi @spmsupun It's all right. When executing a command, the user is allocated individual permissions. You don't have to add roles. I can assume that your inherited model does not have a `cast` property:

```php
/**
 * The attributes that should be cast to native types.
 *
 * @var array
 */
protected $casts = [
    'permissions'          => 'array',
    //...
];
```

**Comment by spmsupun** [comment]
ahh yeah,it works. I wished I had known this before I went through all the trouble 😅
