### ISSUE TITLE
Slecting files with media catalog : the same request is triggered on modal "Reopen"

### ISSUE THREAD

**Issue by HijenHEK** [orchidsoftware/platform#2266]
## Issue and how to reproduce

when closing the modal of the media catalog and reopening it on the same page the ajax request gets triggered again resulting in duplicate files in the modal and unnecessary requests 

## Expected behavior

I expect that the same request won't get retriggered when reopening the modal or the modal clears the media list when closing it

## Screens

![image](https://drive.google.com/uc?export=view&id=1lMnpXhMgKwR1q9ZuINAkbaH0Kl0jKHuG)

**Comment by tabuna** [comment]
Should be fixed in release 12.6.2
