### ISSUE TITLE
Cannot compile resources webpack errors 

### ISSUE THREAD

**Issue by HijenHEK** [orchidsoftware/platform#2267]
## Description 

trying to resolve this issue [#2266](https://github.com/orchidsoftware/platform/issues/2266) , i ran `npm run dev` and errors related to `simplemde` and `codeminor` popped up! then some js functionalities don't work when trying it locally,

![image](https://drive.google.com/uc?export=view&id=10BvcKxaewwp5tiA096Lu2e6SQDFpdlgf)

## Expected behaviour

node should compile the assets with no production errors, so i can customize js and style resources 

## what i have tried 

following some resources , was trying to understand the issue , maybe its an npm versioning issue , it wasnt clear for me the codeminor plugin usage, but everything works fine before compiling assets but even with no changes to the master branch running the scripts drives the same issue thats why i said maybe its an env issue 

- https://github.com/sparksuite/simplemde-markdown-editor/issues/150
- https://laravel-mix.com/docs/2.1/quick-webpack-configuration#using-a-callback-function

same issues

## Env

npm : 8.5.0
node : 16.14.2

**Comment by tabuna** [comment]
At the moment, I haven't found anything better than just adding a compiled editor file. It has not been supported for a long time and it would be great to replace it with something with support.

**Comment by tabuna** [comment]
Should be fixed in release 12.6.2
