### ISSUE TITLE
Cannot modify some defaults (e.g. main, system permissions)

### ISSUE THREAD

**Issue by BenWoodford** [orchidsoftware/platform#2301]
Some things are initialised in the `PlatformServiceProvider` class, rather than the `OrchidServiceProvider` that can be overridden. This means we are forced to have the main and system permissions for instance, despite them being entirely configurable in the routes and screens we have available to us.

The registration of the `Main` and `System` categories should really be in the `OrchidServiceProvider` class so that if the provider in the platform config is changed, it'll allow changing these permissions as well.

**Comment by tabuna** [comment]
Hi @BenWoodford I'm not sure about this. On the one hand, I want you to be in control as much as possible. But things like attachments are systemic and are not really under your control by default, so they are declared in the package and do not go by default. Also, standard naming conventions can be used by packages knowing that such a group definitely exists.

**Comment by BenWoodford** [comment]
Unless you're not using attachments, in which case it's a permission you don't really want clogging up the UI

**Comment by tabuna** [comment]
If it's just an aesthetic issue, then you can remove it at the singleton level, like so:

```php
Dashbord::removePermission('key')
```

Or add to exceptions in the display layer
