### ISSUE TITLE
[13.x] Select and Relation fields visual issues for relations with model

### ISSUE THREAD

**Issue by czernika** [orchidsoftware/platform#2312]
I have Project model and Partner, each Project may belongs to a partner, so DB structure is

| id | name | partner_id |

Since 13.0 there are few issues when using `fromModel` for both Select and Relation filed. To reproduce create two models and relations between them as above, `partner_id` mey be nullable. In examples bellow I will call these models "partner" and "project"

```php
// project migration

$table->id();
$table->string('name');
$table->foreignId('partner_id')
    ->nullable()
    ->constrained()
    ->onDelete('set null');
$table->timestamps();
```

**a. Relation field is not rendering selected value when fetching it from database**

Steps to reproduce
1. Create Relation field

```php
Relation::make('project.partner_id')
    ->fromModel(Partner::class, 'name')
    ->title(__('Partner')),
```

2. Select some value (for example, partner with id=4)
3. Save

Result: database will be updated with correct value (4), but I will not see this in select - visually it will be empty. Here comes second potential "issue" - relation exists (partner_id=4), but if I hit save again, relation will be `null` again, as select doesn't have selected value. It is good on purpose, so why I put it in quotes, but for example if I edit project name and haven't checked partner select, relation will be terminated

My guess, tom-select does know nothing about selected value as it has no options for select. So if change [these](https://github.com/orchidsoftware/platform/blob/master/src/Screen/Fields/Relation.php#L123) lines like

```php
$value = collect($value)
    ->map(static function ($item) use ($text, $key) {
        return [
            'id'   => $item->$key,
            'text' => $item->$text,
        ];
    });

$this->set('value', $value->toJson());

// add `selected` to `$attributes` with default `id` and `text` keys
$this->set('selected', $value->first() ?? [
    'id' => null,
    'text' => '',
]);
```

and blade relation template into (add at least one option)
```
<select id="{{$id}}" data-relation-target="select" {{ $attributes }}>
    <option value="{{ $selected['id'] }}">{{ $selected['text'] }}</option>
</select>
```

I will be able to see rendered value. But maybe better to do something with [tom-select](https://tom-select.js.org/docs/) itself, like `onInitialize()` event? I'm bad at JS, cannot point here... Also needs to be checked for `fromClass` method I guess...

**b. Select field rendering first selected value anyway, even if it's not exists**

** Steps to reproduce **
1. Create Select field for same case

```php
Select::make('project.partner_id')
    ->fromModel(Partner::class, 'name')
    ->title(__('Partner')),

```
2. Make sure partner_id set to `null` in databse
3. But you will see first partner as selected, which is confusing. And if I hit Save button, project will be assigned to a first partner. If I delete partner name, hit save - the relation will be saved as `null`, but still first partner will be shown as selected

As a solution here, may be add default empty option like

```
<select {{ $attributes }}>
    @if ($nullable)
        <option value="">{{ __('No value') }}</option>
    @endif
    @foreach($options as $key => $option)
        <option value="{{$key}}"
                @isset($value)
                @if (is_array($value) && in_array($key, $value, true)) selected
                @elseif (isset($value[$key]) && $value[$key] == $option) selected
                @elseif ($key === $value) selected
                @endif
                @endisset
        >{{$option}}</option>
    @endforeach
</select>
```

Potential problem - tom-select allows you to delete option completely (don't know correct English, just backspace label), so null value can be passed anyway from request which may trigger database error for non-nullable relation

*By the way both hidden inputs from `relation.blade.php` and `select.blade.php` may be removed for this reason. As `nullable()` method may be removed I guess or refactored (null value always a possibility now)*

Screenshots to understand

Layout:

```php
Select::make('project.partner_id')
    ->fromModel(Partner::class, 'name')
    ->title(__('Partner')),

Relation::make('project.partner_id')
    ->fromModel(Partner::class, 'name')
    ->title(__('Partner')),
```

Partners table:

| Partner_id | Name |
| --- | --- |
| 1 | Torphy, Thiel and Kemmer |
| 2 | Heaney-Cremin |

Cases:

`partner_id === null`

Expected: both selects must be empty

![Снимок экрана от 2022-07-23 19-02-25](https://user-images.githubusercontent.com/86893348/180613271-ee5b7cbc-9d58-4db6-a6e3-e894c1f0ea96.png)

`partner_id === 2`

Expected: both should show `Heaney-Creamin` as selected

![Снимок экрана от 2022-07-23 19-02-36](https://user-images.githubusercontent.com/86893348/180613283-33c7939f-34ef-47de-a258-96b6f5cb2c14.png)

**Comment by jremeh** [comment]
I'm not sure if this fix is causing issues for me only, but when I use the same demo code below

```
Select::make('select')
    ->options([
        'index'   => 'Index',
        'noindex' => 'No index',
    ])
    ->title('Select tags')
    ->help('Allow search bots to index');
```

I'm getting ```ErrorException: Undefined variable $nullable```

**Comment by czernika** [comment]
@jremeh have you tried to clear cache with `php artisan optimize:clear`? And what version of Orchid do you use?

**Comment by jremeh** [comment]
@czernika my bad, it worked, thanks!
