### ISSUE TITLE
Anonymous components in Layout::component(component) and TD::make(..)->component(component)

### ISSUE THREAD

**Issue by szonov** [orchidsoftware/platform#2324]
**Is your feature request related to a problem? Please describe.**

Currently both functions accepts component as class name. But Laravel has nice feature "anonymous components", when creating of class is not required, just make view in resources/views/components directory and can go with it. 
Personally, I've using these anonyomus components very often, when component have no logic, just output in needed design.

**Describe the solution you'd like**

I propose support anonymous components in
```
Orchid\Screen\Cell@component
Orchid\Screen\Cell@asComponent
Orchid\Screen\LayoutFactory@component
```

Resolving parameters for anynomus components can be done by passing Closures in $parameters .

For example, anynomous component view: 

resources/views/components/badge.blade.php
```html
@props(['type' => 'success', 'value' => null])

<span class="badge badge-{{$type}}">{{$value}}</span>

```

How it can be used in TD

```php
TD::make('name')->component('badge', [
    'type' => fn ($user) => $user->deleted_at ? 'danger': 'success',
    'value' => fn ($user) => $user->name
])
```

Additionally, I propose similar params resolving for classes components, for example for component

```php

class Badge extends Component
{
    public function __construct(public $value, public $type = 'success')
    {
    }
}

```

TD can be used as

```php 

TD::make('name')->component('badge', [
    'type' => fn ($user) => $user->deleted_at ? 'danger': 'success',
    'value' => fn ($user) => $user->name
]);

// or 

TD::make('name')->component(Badge::class, [
    'type' => fn ($user) => $user->deleted_at ? 'danger': 'success',
    'value' => fn ($user) => $user->name
]);
```

**Comment by szonov** [comment]
@tabuna 
I've made pull request, please check it

**Comment by tabuna** [comment]
Hi @szonov Could you please also add the usage you describe:

```php
TD::make('name')->component('badge', [
    'type' => fn ($user) => $user->deleted_at ? 'danger': 'success',
    'value' => fn ($user) => $user->name
])
```
For example here:
https://github.com/orchidsoftware/platform/blob/master/tests/Unit/Screen/TDComponentTest.php

And other places so we always have a working use case

**Comment by szonov** [comment]
I've added tests for TD 'component' and 'asComponent' methods
