### ISSUE TITLE
Matrix field don't delete a row if this is the last row present for the field

### ISSUE THREAD

**Issue by gioacchinopoletto** [orchidsoftware/platform#2331]
**Describe the bug**
Matrix field don't delete a row if this is the last row present for the field, because on MySQL return this error:
`Check constraint 'people_chk_2' is violated. All changes were reverted (DDL statements can't be reverted).`

It seems that on deleting the last row the field will be saved as NULL and not as empty JSON and constraint violation error break last row deletion.

**To Reproduce**

  1. Try to add one or more rows to a matrix field
  1. Try to delete the last row on the field --> field empty as result

**Expected behavior**
As expected the matrix field should be empty deleting last row present.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: OSX 12.5 Monterey
 - Browser: Safari 15.6 (17613.3.9.1.5), Google Chrome 104.0.5112.79

**Smartphone (please complete the following information):**
Not tested yet

**Server (please complete the following information):**
  - Platfrom Version: 13.1.0
  - Laravel Version: 9.23.0
  - PHP Version:  8.1.9
  - Database:  MySQL
  - Database Version:  8.0.27

**Additional context**
Table field - emails in my case - is casted as array on model, and created as Jsonb on migration:
`$table->jsonb('emails')->comment("Email addresses")->nullable();`

When I have runned the migration MySQL create:
`emails longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT Email addresses`
`CONSTRAINT people_chk_2 CHECK (json_valid('emails'))`

**Comment by astersnake** [comment]
This seems more like a problem on your side than an Orchid issue. The matrix field returns an array, and it is up to you what you do with that in your function.

**Comment by gioacchinopoletto** [comment]
> This seems more like a problem on your side than an Orchid issue. The matrix field returns an array, and it is up to you what you do with that in your function.

I think isn't a problem on my side because I don't have find something on documentation about Matrix field that not save an empty array if you delete the entire field content.
Probably **I don't know if I have used the correct field type definition on my migration (jsonb)** because on deleting last value pair or array Orchid set field to NULL and not as an empty array.

**Comment by astersnake** [comment]
Can you share a minimal reproducible example or screen where you obtain this behavior?

**Comment by astersnake** [comment]
I will close this as it is inactive and probably not an Orchid issue.

**Comment by gioacchinopoletto** [comment]
> I will close this as it is inactive and probably not an Orchid issue.

Why? Some issues still open for months... 
But, anyway I think I have written all elements to reproduce this behavior. Screens are unuseful in this case.

**Comment by astersnake** [comment]
We're working on improving the issues on this repository.

Orchid doesn't save/update anything on your database when you use an input field. It is up to you to save it (using a function) and treat it before saving. I asked for more code on your side because this doesn't seem like an Orchid issue.

**Comment by gioacchinopoletto** [comment]
> We're working on improving the issues on this repository.
> 
> Orchid doesn't save/update anything on your database when you use an input field. It is up to you to save it (using a function) and treat it before saving. I asked for more code on your side because this doesn't seem like an Orchid issue.

I know this, in fact I save, edit and delete the matrix field (emails in my table) without problem with standard save function:

`public function save(People $people, Request $request)
    {
        $this->exists = $people->exists;
        
        $request->validate([
           (omissis) 

            'people.emails' => [
                'nullable',
            ],

           (omissis) 
        ]);
        
        $people
            ->fill($request->get('people'))
            ->save();

        $people->bndroles()->detach();

        $people->bndroles()->attach($request->input('people.bndroles'));

        Toast::info(__('Person was saved'));

        (omissis)        

         return redirect()->route('platform.tables.people');   
    }`

I see the problem when I try to remove last element on emails matrix field.

**Comment by gioacchinopoletto** [comment]
For future reference if someone have same problem.
I have solved the problem on deleting last element on array on this way before fill `people`:

```
if( $request->input('people.emails') == null)
{
            $people_array = $request->people;
            $people_array['emails']  = [];

            $request->merge([
                'people' => $people_array,
            ]);
}
```
