### ISSUE TITLE
setting guard to null creates issue on `Relation` field

### ISSUE THREAD

**Issue by oversoul** [orchidsoftware/platform#2362]
**Describe the bug**
disabling guard in the config, results in an error on `RelationRequest`

**To Reproduce**

  1. disable guard and platform middleware
  2. create a relation field
  3. `return $this->user()->hasAccess('platform.index');` this will error out. (no user)

**Expected behavior**
returning true

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser: Firefox

**Additional context**
didn't do much digging, but i think this might exist in earlier versions. could be wrong.

possible fix:
```
if (! config('platform.guard')) {
    return true;
}
return $this->user()->hasAccess('platform.index');
```

**Comment by tabuna** [comment]
Yes, I think that this check is redundant and can cause problems if you need to use orchid in public.

**Comment by tabuna** [comment]
@oversoul Since version 13.2.0, there is no check.
