### ISSUE TITLE
Allow customize TomSelect options

### ISSUE THREAD

**Issue by alihardan** [orchidsoftware/platform#2363]
I was trying to add a select box which allows user to create options dynamically (Other than the default options). It's possible in Tom Select as you see in their example: [Example](https://tom-select.js.org/examples/)

All what I need is setting option key 'create' in TomSelect initialize, but there is no right way it seems.

Thanks.

**Comment by tabuna** [comment]
Hello, it seems this PR https://github.com/orchidsoftware/platform/pull/2342 has already solved what you want

**Comment by alihardan** [comment]
Great, thanks. I was on old version and because this feature wasn't mentioned in the documentation, I thought not exists yet.
