### ISSUE TITLE
Hidden or disabled Relation field is not being saved

### ISSUE THREAD

**Issue by seteq** [orchidsoftware/platform#2394]
Hi,

I have been following the tutorials from the docs and now I'm trying to have a "author" field in the database to track who edited something. When the Relation element is hidden or disabled, the value of this element is not being submitted at all when saved.

Is there any way to include hidden or disabled elements in the saved dataset?

The parts of my screen file:

```
   public function query(Category $category): iterable
    {
        return [
            'category' => $category,
            'category.author' => Auth::id(),
        ];
    }

public function layout(): iterable
    {
        return [
            Layout::rows([
               Relation::make('category.author')
                    ->title('Author')
                    ->fromModel(User::class, 'name')
                    ->canSee(false),
            ])
        ];
    }
```

Thank you :-)

**Comment by tabuna** [comment]
If you want to create a field that was sent from the client device, but was hidden from him, you can use a field with the type hidden:

```php
Input::make()->type('hidden')
```
