### ISSUE TITLE
Slow IconComponent and Menu rendering

### ISSUE THREAD

**Issue by mvehar** [orchidsoftware/platform#2410]
**Is your feature request related to a problem? Please describe.**
After profiling slow rendering on table views we found out that IconComponent is slow due to IconFinder searching for icons in all subdirectories. Even though there is already some caching implemented we have problem with e.g. Menu which uses a lot of different icons 

**Describe the solution you'd like**
Cache paths to icons OR implement that icons are loaded async via HTTP requests. Is there a way to use css only icons (not loading SVGs all the time)?

**Describe alternatives you've considered**
Im thinking in adding separate component x-orchid-cssicon that will be replaced in orchid templates. 

**Additional context**
Main focus was using FontAwesome icons

**Comment by tabuna** [comment]
Hi @mvehar, I tried to fix the bypass when there are a lot of files. Please see the latest version
