### ISSUE TITLE
Is there any limitation on Form Select?

### ISSUE THREAD

**Issue by mnurullahsaglam** [orchidsoftware/platform#2439]
### Discussed in https://github.com/orchidsoftware/platform/discussions/2422

<div type='discussions-op-text'>

<sup>Originally posted by **archlicher** November  2, 2022</sup>
Hi,

I am facing a problem with `Form Select` - how can I add more than 50 items to it with package `monarobase/country-list`?

Thank you</div>

**Comment by tabuna** [comment]
Hi @jigsaw075 Can you please describe what you want to achieve

**Comment by Mazena86** [comment]
I would guess he's trying to add more than 50 values to the Select. I have a Select with a lot of values, but it only displays up to...something like 50 values, but if I start typing a value I know is beyond what I see, it will allow me to select it.

**Comment by jigsaw075** [comment]
sorry, i missed the notification. i'm trying to list all counties with select option but it doesn't show all the values like @Mazena86. here is the code.
`                Select::make('country_code')
                    ->title("Country")
                    ->options(CountryListFacade::getList())
                    ->empty('Select...')
                    ->required(),
`

**Comment by czernika** [comment]
Oh, I can see where it comes from. Tom select official [documentation](https://tom-select.js.org/docs/) limits amount of displayed items to 50 (`maxOptions` value)

> `maxOptions` | The max number of options to display in the dropdown. Set `maxOptions` to `null` for an unlimited number of options. Default: `50`

**Comment by tabuna** [comment]
I think this issue was referring to the same behavior as described here: https://github.com/orchidsoftware/platform/issues/2478
