### ISSUE TITLE
Previous tab doesn't open after selecting a page in a table layout

### ISSUE THREAD

**Issue by nesstord** [orchidsoftware/platform#2443]
**To Reproduce**

  1. Create a screen with 2 tabs;
  2. On the second tab create a table layout with enough data for pagination; 
  3. Click on second page, it will redirect you to the first tab.

**Expected behavior**
After selecting the page, we must return to the tab with the table.

**Screenshots**
![bug](https://user-images.githubusercontent.com/56038047/202164134-e22e8d2f-2936-45a1-99cd-0e76fa027da7.gif)

**Comment by nesstord** [comment]
https://github.com/orchidsoftware/platform/pull/2444

**Comment by tabuna** [comment]
Hi @nesstord When using tabs with pagination and filters, I recommend using `Orchid\Screen\Layouts\TabMenu`

Example:
https://github.com/orchidsoftware/platform/blob/4d24a8025d1f3338221cffc8a78bd1bc63012925/stubs/app/Orchid/Layouts/Examples/TabMenuExample.php#L8 


Real page fragmentation avoids conflicts when using GET parameters
