### ISSUE TITLE
SQL Server Dates

### ISSUE THREAD

**Issue by tartesso26** [orchidsoftware/platform#2446]
**Describe the bug**
when you use orchid with sql server, dates generates many errors.
Convert datetime to string to show on table returns error
Save date on updated_at or created_at also returns error

**To Reproduce**

  1. create a new table
  2. create model
  3. try to create a new one or edit

**Expected behavior**
it was expected row edited, but not

**Screenshots**
![image](https://user-images.githubusercontent.com/32328544/202455787-f5442530-1f81-45d6-a56a-b413777437c4.png)

**Comment by tabuna** [comment]
We do not work with the database directly. So I'm not sure if this is our fault. You can customize your Eloquent model with MS SQL Server running.


Topic example:

- https://stackoverflow.com/questions/36451179/datetime-issue-with-laravel-5-2-ms-sql-server
- https://laracasts.com/index.php/index.php/discuss/channels/eloquent/datetime-issue-with-laravel-52-ms-sql-server?page=1&replyId=156370

**Comment by tartesso26** [comment]
i tried to customize attachments model, but can´t find the file, it seems not exist that model, so when try to upload an image, which include insert into attachments db, it fails

**Comment by tartesso26** [comment]
finally i could solve it
