### ISSUE TITLE
Tabs stacking up content instead of toggling it on and off

### ISSUE THREAD

**Issue by Mazena86** [orchidsoftware/platform#2447]
After updating to the latest version of Orchid, my old tabs stopped working. Instead of switching the appropriate content on/off, it stacks new content below the already visible content.

  1. Create a layout with two or more tabs with whatever content
  2. Switch between the tabs

Prior to the update, the same tabs worked properly. Below is a screenshot of the current state of tab functionality.

![image](https://user-images.githubusercontent.com/11873244/202478734-c0401680-ea87-4e83-86d9-9b663684ec0b.png)

**Server (please complete the following information):**
  - Platfrom Version: 13.7.1
  - Laravel Version: 9.19.0
  - PHP Version:  8.1.9

**Comment by tabuna** [comment]
What version did you update from? It is possible that your resources have not been updated.

**Comment by Mazena86** [comment]
That was from 13.0.0. I ran composer update again and it did copy some resources, but the pages started crashing with a null exception. Oddly enough, updating to the newest version 13.8.0 now seems to have fixed both the crashing and tabs not switching properly.

**Comment by e1sep0** [comment]
I have updated to 14-alpha3, and have similar issue, in 13 tabs worked, but now they are broken
