### ISSUE TITLE
Validation for Confirm Button

### ISSUE THREAD

**Issue by Whizboy-Arnold** [orchidsoftware/platform#2452]
**Is your feature request related to a problem? Please describe.**
I am frustrated that I cannot customize the dialogue box in Buttons to validate something before confirming

**Describe the solution you'd like**
A callback to be called before action is issued

**Describe alternatives you've considered**
Tried to use modal but to no avail

**Additional context**

**Comment by tabuna** [comment]
I believe that for the implementation of this, the recently released Laravel package by precognition https://laravel.com/docs/10.x/precognition is likely suitable. At the moment, I don't plan to work on implementing it into the package myself, but I would be happy to accept a pull request (PR).
