### ISSUE TITLE
Upload field bug 

### ISSUE THREAD

**Issue by mePrazen** [orchidsoftware/platform#2454]
how are these all the files coming while using upload field 
![image](https://user-images.githubusercontent.com/80998395/202993565-0e3d3726-8e53-4083-a082-dfea99607831.png)

And how can i solve it ?

**Comment by astersnake** [comment]
Hi, you need to provide more information. In a clean Orchid installation, this does not happen.

**Comment by astersnake** [comment]
I will close this due to the lack of information. Feel free to provide a more detailed description of your problem.

**Comment by gabtorr** [comment]
This looks like a bad implementation of the field, imho.

**Comment by tabuna** [comment]
@gabtorr Thank you for your feedback. We appreciate you taking the time to share your thoughts on our implementation of this field. If you believe there are areas that can be improved, we would be happy to review a pull request with your suggested changes. Collaboration and constructive feedback are essential for creating high-quality work, and we welcome any contributions that can help us improve.
