### ISSUE TITLE
Sort table records in Tabs layout

### ISSUE THREAD

**Issue by plamenradev** [orchidsoftware/platform#2469]
**Describe the bug**
Sorting table results in Tabs layout. If the table is not placed in the default active tab (first one or set by activeTab() method) you have been switched to the default tab, so you need to click again on the tab where the table is placed in order to see sorted results. It stays on the current tab after sorting multiple times by any column.

**To Reproduce**

  1. Create Tabs layout with more than 1 tab
  2. Create Table layout in tab different than the default one (by default first one or set by activeTab() method)
  3. Sort the results in the table by any column

**Expected behavior**
Sort table results and do not switch to the default tab.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 107.0.5304.121 

**Server (please complete the following information):**
  - Platfrom Version: 13.6
  - Laravel Version: 9.42
  - PHP Version:  8.1.9
  - Database:  MySql
  - Database Version:  8.0

![image](https://user-images.githubusercontent.com/11794833/207021725-c8020a6b-aa9e-455a-86aa-a57d9003db05.png)

**Comment by tabuna** [comment]
Duplicate https://github.com/orchidsoftware/platform/issues/2443

**Comment by tabuna** [comment]
If you need to use in tabs, that may conflict. For example, GET parameters, then I recommend using independent screens, which can be designed in tabs. An example of this, you can see in the [documentation](https://orchid.software/en/docs/custom-template/#tabmenu). 
Feel free to reopen this if there are problems.
