### ISSUE TITLE
both filter date range and input not working

### ISSUE THREAD

**Issue by aviqbaihaqy** [orchidsoftware/platform#2473]
**Describe the bug**
when applying filter on two columns it doesn't work properly, because the url will be replaced by the contents of the date range or input, but this doesn't happen if applying both filters to two regular inputs

**Desktop (please complete the following information):**
 - OS: mac os ventura
 - Browser chrome
 - Version 108.0.5359.98 (Official Build) (arm64)

**Comment by tabuna** [comment]
This should be resolved in [release 13.9.2](https://github.com/orchidsoftware/platform/releases/tag/13.9.2)

**Comment by aviqbaihaqy** [comment]
ok thanks
