### ISSUE TITLE
Make it possible to increase the max options in TomSelect

### ISSUE THREAD

**Issue by Edinburgher** [orchidsoftware/platform#2478]
**Is your feature request related to a problem? Please describe.**
Since upgrading to Version 13 and the switch to TomSelect from select2, the maxOptions in the Select form element are set to the standard 50 and are not changeable from PHP. 50 options are not enough in my case (country select).

**Describe the solution you'd like**
Either set the maxOptions to the number of options or give a possibility to adjust the maxOptions similar to adjusting maxItems using an attribute.

**Comment by tabuna** [comment]
This problem should be solved in version [13.9.1](https://github.com/orchidsoftware/platform/releases/tag/13.9.1)
I have removed the display `options` limit for the `Select` field.
