### ISSUE TITLE
Multiple modal in screen

### ISSUE THREAD

**Issue by giovannicuce** [orchidsoftware/platform#2500]
I found a bug when have multiple modal in screen with async function. The async function return content of first modal of screen instead a correct content.

Example, I have this modals, but the async function return the content of "modalAddSection" in any modal toggle

` 
           Layout::modal('modalAddSection', PageSectionLayout::class)
                ->title(__("Aggiungi sezione"))
                ->applyButton(__("Salva"))
                ->method("saveSection")
                ->canSee(Auth::user()->hasAccess("static_pages_write"))
                ->async("asyncSection")
                ->staticBackdrop(true),

            Layout::modal('modalAddWidget', PageWidgetLayout::class)
                ->title(__("Aggiungi widget"))
                ->applyButton(__("Salva"))
                ->method("saveWidget")
                ->async("asyncWidget")
                ->canSee(Auth::user()->hasAccess("static_pages_write"))
                ->staticBackdrop(true),

            Layout::modal('modalEditWidget', PageEditWidgetLayout::class)
                ->title(__("Modifica widget"))
                ->applyButton(__("Salva"))
                ->method("saveDataWidget")
                ->canSee(Auth::user()->hasAccess("static_pages_write"))
                ->async("asyncWidget")
                ->size(Modal::SIZE_LG)
                ->staticBackdrop(true)
`

Downgrade to 13.9.1 and it works.

**Comment by tabuna** [comment]
Hi @giovannicuce, This should be fixed with the release of [13.9.4](https://github.com/orchidsoftware/platform/releases/tag/13.9.4). Feel free to reopen the issue.
