### ISSUE TITLE
Dropdown Menu in Multiple Level

### ISSUE THREAD

**Issue by Cris123m** [orchidsoftware/platform#2509]
**Describe the bug**
Issues with dropdown having multiple levels.
Submenu does not open correctly.

**To Reproduce**

`Menu::make(__('Menu'))
        ->icon('calculator-alt')
        ->list([
            Menu::make(__('Submenu 1'))
                  ->icon('calculator-alt')
                  ->list([
                          Menu::make(__('Submenu 2'))
                   ])
         ])
`

**Expected behavior**
Dropdown submenu independient open

**Desktop (please complete the following information):**
 - OS: All
 - Browser All

**Server (please complete the following information):**
  - Platfrom Version: 13.9.0
  - Laravel Version: 9
  - PHP Version:  8

**Comment by tabuna** [comment]
Only one level of nesting is currently supported
