### ISSUE TITLE
Incorrect behavior when using searchColumns()

### ISSUE THREAD

**Issue by grigoriy-ivanov** [orchidsoftware/platform#2512]
**Describe the bug**
Incorrect behavior when using searchColumns(). If the search phrase is not in an option, the result is displayed as "Not found". But response from server is correct.
<img width="535" alt="Снимок экрана 2023-01-30 в 16 54 14" src="https://user-images.githubusercontent.com/13166748/215496716-3db33ad5-551d-43b3-a32b-3f485167d150.png">
<img width="535" alt="Снимок экрана 2023-01-30 в 16 53 58" src="https://user-images.githubusercontent.com/13166748/215496722-bff726f4-3daf-402f-b372-3e8d3a6e57ee.png">

**Comment by tabuna** [comment]
This thread was very helpful in dealing with this situation: https://github.com/orchidjs/tom-select/issues/78

You need to specify two properties to disable client-side filtering:

```js
searchField: [],
sortField: [{field:'$order'},{field:'$score'}],
```

**Comment by grigoriy-ivanov** [comment]
It is possible to apply fix in 13.x version?
