### ISSUE TITLE
BUG  filter table

### ISSUE THREAD

**Issue by giovannicuce** [orchidsoftware/platform#2559]
I find a bug in filter of table. If in filter of type Input, search with a value with comma (example 'Gentile, Dottore') the page return error.

`htmlspecialchars(): Argument #1 ($string) must be of type string, array given`

The system make a explode of comma for value.

Can you fix it?

**Comment by tabuna** [comment]
Hello. Indeed, automatic detection of the applied filter has been a problem for a long time when using commas. I couldn't fix it without releasing critical changes. With the release of version 14.0, this should no longer be an issue, as now the filter operator is set manually by the developer for each column.
