### ISSUE TITLE
Mixed Content error when logging in, in production

### ISSUE THREAD

**Issue by TomDo1234** [orchidsoftware/platform#2562]
Mixed Content: The page at 'https://myurl.com/dashboard/login' was loaded over HTTPS, but requested an insecure resource 'http://myurl.com/dashboard/login'. This request has been blocked; the content must be served over HTTPS. orchid.js?id=62edb142c354a956b491548ce53c56db:2 Uncaught (in promise) TypeError: Failed to fetch     at F.perform (orchid.js?id=62edb142c354a956b491548ce53c56db:2:49853);

/dashboard is my prefix for the orchid dashboard instead of /admin

I am getting a mixed content error for some reason, My deployment is behind Cloudflare.

In local everything works. But in production I get mixed content

I have set the dashboard_domain to the https://myurl.com
and my laravel APP_URL is also that.

**Comment by TomDo1234** [comment]
Nvm I fixed it:

1. Set cloudflare encryption to full
2. On my AWS I had to configure ACM and the ELB to accept SSL
3. php artisan route:clear

**Comment by Abdullajon8111** [comment]
There's no way to disable mixed content using javascript but you can add this tag

<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
to your HTML to allow mixed content
