### ISSUE TITLE
Delete button: method is null

### ISSUE THREAD

**Issue by ppalmeida** [orchidsoftware/platform#2563]
I am trying to simply delete a model listed in a regular/common screen.

These are the routes:

```php
// routes/platform.php file:

Route::screen('phase-templates', PhaseTemplateScreen::class)
    ->name('platform.phase-templates');
Route::screen('phase-templates/create', PhaseTemplateEditScreen::class)
    ->name('platform.phase-templates.create');
Route::screen('phase-templates/{phaseTemplate}/edit', PhaseTemplateEditScreen::class)
    ->name('platform.phase-templates.edit');
// This is the remove route:
Route::screen('phase-templates/remove', PhaseTemplateEditScreen::class)
    ->name('platform.phase-templates.remove');
```

The button is declared like this:

```php
// app/Orchid/Layouts/PhaseTemplate/PhaseTemplateListLayout.php file:
 /**
     * Get the columns elements to be displayed.
     *
     * @return TD[]
     */
    protected function columns(): iterable
    {
        return [
          // other lines and...
            TD::make(__('Actions'))
                ->align(TD::ALIGN_RIGHT)
                ->width('100px')
                ->render(function (PhaseTemplate $template) {
                    return DropDown::make()
                        ->icon('options-vertical')
                        ->list([
                            Link::make(__('Edit'))
                                ->route('platform.phase-templates.edit', $template->id)
                                ->icon('pencil'),
                            Button::make(__('Delete'))
                                ->icon('trash')
                                ->confirm(__('Once the template is deleted, all of its resources and data will be permanently deleted.'))
                                ->method('remove', [
                                    'id' => $template->id,
                                ]),
                            ]);
                    }
                ),
        ];
    }
```

So, essentially, if I write the route as above, the error is "method on Screen is null":

```
Orchid\Screen\Screen::callMethod(): Argument #1 ($method) must be of type string, null given, called in /project/vendor/orchid/platform/src/Screen/Screen.php on line 220
```

If I change the route to be like this:

```php
Route::screen('phase-templates/{phaseTemplate}/remove', PhaseTemplateEditScreen::class)
    ->name('platform.phase-templates.remove');
```

The error changes to:

```
The POST method is not supported for this route. Supported methods: GET, HEAD.
```

Which makes no sense at all, since I'm registering a `Screen` route. So, POST should be already in place. Either way, the URL being called by the button click is POST to:

```
http://localhost:8000/admin/phase-templates/remove?id=6
```

So, my question is: how should I implement a delete button? What am I doing wrong?

Composer infos:
"laravel/framework": "^9.0",
"orchid/crud": "^3.7",
"orchid/platform": "^12.6",

Thank you all for any help/assistance.

**Comment by astersnake** [comment]
if you are in a model edit screen, the route should be:
```php
Route::screen('phase-templates/{phaseTemplate}/remove', PhaseTemplateRemoveScreen::class)
    ->name('platform.phase-templates.remove');
```

Be sure to have the `remove` method in your class, and if I am not wrong, the button should be like this:

```php
Button::make(__('Delete'))
    ->icon('trash')
    ->confirm(__('Once the template is deleted, all of its resources and data will be permanently deleted.'))
    ->method('remove')
    ->parameters(['id' => $user->id])
```

Also, remember to run the command `php artisan clear:optimize`

**Comment by drabodan** [comment]
Documentation https://orchid.software/en/docs/screens/#routing-screens and https://orchid.software/en/docs/screens/#screen-actions

No need to add an extra route, that is, this

```php
Route::screen('phase-templates/remove', PhaseTemplateEditScreen::class)
    ->name('platform.phase-templates.remove');
```
no need.

You need to add method "remove" to screen "PhaseTemplateScreen" (and also in "PhaseTemplateEditScreen", if the edit screen also has a delete button).

Example of a layout that has a button - https://github.com/orchidsoftware/platform/blob/b619ec0bf938483ecfac435bd6e3a0fd619ba251/stubs/app/Orchid/Layouts/User/UserListLayout.php#L63-L68

Screen example with method - https://github.com/orchidsoftware/platform/blob/b619ec0bf938483ecfac435bd6e3a0fd619ba251/stubs/app/Orchid/Screens/User/UserListScreen.php#L112-L117

If the method is used in several screens, for example, "list" and "edit", then it is better to make a base screen class that will have a delete method, and a screen "list" and "edit" through inheritance from the base one (although all this is in the documentation).
