### ISSUE TITLE
Non multilingual phrase

### ISSUE THREAD

**Issue by MaxLogic88** [orchidsoftware/platform#2575]
File src/Screen/Layouts/Table.php
Line 128 
`return 'Import or create objects, or check back later for updates';`
missing __() constuction for multilingual functionality

**Comment by drabodan** [comment]
In fact, since version [14.0.0-alpha1](https://github.com/orchidsoftware/platform/releases/tag/14.0.0-alpha1) this has already been resolved  https://github.com/orchidsoftware/platform/commit/da4ff034c228c8e87b87fc39566896fc97007208

**Comment by MaxLogic88** [comment]
Ok, thanks
