### ISSUE TITLE
Allow the developer to create custom layouts

### ISSUE THREAD

**Issue by swarakaka** [orchidsoftware/platform#2579]
Hello @tabuna,

I find it a good idea to make this method public, so that developers can create their own base layouts, if necessary for some of the screens.

https://github.com/orchidsoftware/platform/blob/328571b14ba28e12f64d2ffa813e6e577c486dee/src/Screen/Screen.php#L43

**Comment by tabuna** [comment]
Hello, @swarakaka ! It would indeed be nice to provide the ability to define custom templates for certain screens. However, there are a few things that come to mind immediately:

- How would support and documentation be maintained for these custom templates.
- The style of custom templates could differ significantly from what users see on other screens, which could cause confusion.
- Is there an example of a screen that couldn't be solved with a simple `Layout::view()`

Do you have any thoughts on this matter?

**Comment by swarakaka** [comment]
Regarding the first question about how support and documentation would be maintained for custom templates, it seems like providing clear instructions on how to modify the [base view](https://github.com/orchidsoftware/platform/blob/master/resources/views/layouts/base.blade.php) or use the code in a custom template, as well as including examples of how to customize the template, would be helpful. This could ensure that developers have the resources they need to use custom templates effectively.

For the second question about potential confusion caused by custom templates that differ significantly from other screens, clear guidance on how to customize the template in a way that maintains consistency with the overall design and user experience, as well as examples of how to do so, would be beneficial. This could help ensure that users don't experience confusion due to significant style differences between screens.

I've tried it myself and layout::view() isn't the main solution, especially if you want to hide menus when the user doesn't need to see them.

**Comment by dkarvounaris** [comment]
Using Orchid for the first time and building an application which requires different screens for different users, this would definitely be very helpful, especially if it may be easily achievable in Orchid.

**Comment by tabuna** [comment]
This has been released since version 14.0
