### ISSUE TITLE
Service Provider should not register always everything

### ISSUE THREAD

**Issue by dkarvounaris** [orchidsoftware/platform#2586]
**Describe the bug**

Currently, the package's service provider is loading and registering everything, regardless if it's needed only on the CLI and not in web requests. This adds additional burden on each web request, in terms of memory requirements, cpu usage and request time. This can affect high-performance environments as well high-traffic systems with limited resources. Measured in a development environment, not running the console-specific parts for web requests made easily a difference of 10-15ms (most likely less in an optimized production environment).

**Expected behavior**
Optimally, a service provider should only register or load what is required. This is also displayed in basic examples of the Laravel documentation, one of them in https://laravel.com/docs/10.x/packages#commands and is also often considered a best practice.

**How to solve**
A separate service provider can be used for everything which should be loaded only on the console. This service provider will include registrations for migrations, resource and assets publishing, registering commands and the about command. They are all neither needed nor used during web requests. This service provider is then conditionally registered only when the app is running on the console.

I opened this ticket, as I may actually provide also the required pull request for this - it would be nice if it would be included in the 14 release (I'm developing my client's app with the alpha right now), as also to provide a place for discussion if necessary, especially since I just recently started using Orchid.

**Comment by tabuna** [comment]
Hi. I haven't done a load speed measurement test, but I am using the built-in `commands` method:

https://github.com/laravel/framework/blob/d6ffa449cbb1bfb44f8f3dcddbb4d872ca457dd8/src/Illuminate/Support/ServiceProvider.php#L393-L406

Which commands before the console start event:

https://github.com/laravel/framework/blob/d6ffa449cbb1bfb44f8f3dcddbb4d872ca457dd8/src/Illuminate/Console/Application.php#L44-L49

Since HTTP request does not call Artisan (_Although you can use `Artisan::call()` facade_). 
Then all the closure functions will not be executed. Isn't this equivalent to the documentation link you provided?

**Comment by dkarvounaris** [comment]
Yes, it's correct that the closures won't be executed, however it still executes all the statements to register all kind of things, even though they'll never be used or be required in a HTTP request. 

Here shown (determined with a lazy-dev approach :D) that all methods with be called.
![image](https://github.com/orchidsoftware/platform/assets/4226932/b636191c-76f4-4e89-b271-8f8055887ee4)
![image](https://github.com/orchidsoftware/platform/assets/4226932/e737048e-6905-4d43-909d-9dcf3ecdd93e)

It's however not required to set any resources for publishing, as they will be only ever be published through the console, nor migrations are required to be registered nor some other things, for a HTTP request. They can safely be moved into a Service Provider of it's own, this way, not even some additional classes will be autoloaded or checked for existence. 

After my optimization on my pull request #2611 , only what is required is being loaded:

![image](https://github.com/orchidsoftware/platform/assets/4226932/bc617e9a-6353-493c-8011-6f663457365a)
![image](https://github.com/orchidsoftware/platform/assets/4226932/0b628546-2541-4305-87c4-e2557b97ec39)
(Orchid still works!)

While console loads everything:
![image](https://github.com/orchidsoftware/platform/assets/4226932/17d86f0a-22c3-4940-8fde-9a732b1677a4)

There is probably still one optimization possible here. If Orchid is used only as a back-office, and the front office doesn't make use of it, as seen in the screenshots above with a standard laravel installation, we may be able to avoid loading any additional providers, registering translations, blade components and views, as they won't be required then.

**Comment by tabuna** [comment]
It was fixed after PR was accepted. #2611
