### ISSUE TITLE
acceptedFiles does not work

### ISSUE THREAD

**Issue by DarKsandr** [orchidsoftware/platform#2587]
acceptedFiles does not work for the Picture and Cropper element. I using orchid/platform version 13.10.0 and 14.0.0-alpha3

**Comment by DarKsandr** [comment]
@tabuna thanks, extensions appeared in the window, but the backend still skips any files

**Comment by tabuna** [comment]
Hi @DarKsandr. Uploading files as an administrator is one route for multiple fields. It has no artificial limitations other than permission checks. If you need to regulate rules, you can create your own upload point and specify checks there. https://orchid.software/en/docs/attachments
