### ISSUE TITLE
Roles / Permissions screen and actions after update to 14

### ISSUE THREAD

**Issue by gioacchinopoletto** [orchidsoftware/platform#2629]
**Describe the bug**
After upgrading to version 14 I have problems with system roles:

- the roles are present and displayed correctly in the RoleListScreen;
- Permissions are regularly stored in the database as an array;
- the menu items that I have associated with "canSee" to the role are displayed correctly;

despite this:

- if I open the RoleEditScreen there are no role data (name and slug) which I see instead in the RoleListScreen and the permissions checkboxes are all unflagged;
- if I try to save the role with the new permissions I get a 403 Forbidden error, but nothing is saved in the log or database.

**To Reproduce**

  1. Update to Laravel 14.0.3
  2. Update Orchid CRUD to latest version
  3. Update Orchid Fortify to latest version
  4. Display Roles screen  

**Expected behavior**
Correctly display the data present in the database for the roles and be able to modify them since the user used has permissions in the database.
**I tried a fresh install of Orchid and the screens work fine**, for this reason I don't think that this bug depends on System or Browser.

**Comment by gioacchinopoletto** [comment]
I have made some test and:
- the code is the same between a new orchid installation and my running installation except for `public $role` on top of `RoleEditScreen.php`;
- when I try to edit a Role the `$role` returned to layout is an empty array;  

any suggestions about this?

**Comment by tabuna** [comment]
Hi, looked in the actual project what changes were made in the update

```diff
// Platform > System > Roles > Role
- Route::screen('roles/{roles}/edit', RoleEditScreen::class)
-     ->name('platform.systems.roles.edit');

+ Route::screen('roles/{role}/edit', RoleEditScreen::class)
+    ->name('platform.systems.roles.edit');
```

This is due to the fact that the dependency and route resolver now relies on the same principle as in Laravel when using a controller.

Has this change worked for you?

**Comment by gioacchinopoletto** [comment]
Many thanks @tabuna, I don't have see this!
Work **perfectly**!
