### ISSUE TITLE
404 ошибка

### ISSUE THREAD

**Issue by Mr-Coquin** [orchidsoftware/platform#2630]
На VPS сервере с LiteSpeed поставил composer create-project laravel/laravel orchid-project "8.*" --prefer-dist

Поменял файл .env (пользователь создался) 
config/platform.php тоже внес все изминения. 

Подскажите куда можно копать ? 
Все время 404 ошибка. Уже по разному пытался ее исправить

**Comment by Rfferrao87** [comment]
@Mr-Coquin Bug reports must be submitted in English according to official Orchid's [Reporting Bugs](https://orchid.software/en/community/bug-report/#be-concise-but-explain-the-issue) guidelines:

![image](https://github.com/orchidsoftware/platform/assets/25744318/e5bea624-08ef-4ebf-b17d-20c30f790f79)

Sorry, but would you mind reviewing your issue accordingly just so we can start on the right track?
