### ISSUE TITLE
Can not get attachments to display when editing

### ISSUE THREAD

**Issue by AlizHarb** [orchidsoftware/platform#2638]
Hello
I'm using upload for images with the relation, everything works fine until i want to edit.
Images not being display back under the upload input

here is my query
```
public function query(City $city): iterable
    {
        $city->load('attachment');

        return [
            'city' => $city,
        ];
    }
```

**Comment by tabuna** [comment]
There is too little information to be able to reproduce the error you encountered.

**Comment by AlizHarb** [comment]
> 

I'm using Attachable trait and relation for uploading images, everything works very well but i can not get the images to display when i want to edit the city
![image](https://github.com/orchidsoftware/platform/assets/34816428/de37e655-1618-487a-a8f4-1e2429299a62)

**Comment by tabuna** [comment]
Name of the `Upload::make('attachment')` field?

**Comment by AlizHarb** [comment]
> Name of the `Upload::make('attachment')` field?

```Upload::make('city.image')
                            ->title('City Image')
                            ->maxFiles(1)
                            ->groups('cities')
                            ->acceptedFiles('image/*')
                            ->media(),```

**Comment by tabuna** [comment]
The naming should match what is stored with the model:

```php
Input::name('city.name') 
// value equivalent to 
$city->name
```

You can learn more at https://orchid.software/en/docs/screens/

**Comment by AlizHarb** [comment]
> The naming should match what is stored with the model:
> 
> ```
> Input::name('city.name') 
> // value equivalent to 
> $city->name
> ```
> 
> You can learn more at https://orchid.software/en/docs/screens/

ok i got that point, as you see in the screenshot that all inputs returned the values, i just want to return the images as well, i have tried to use attachment like that
```
Upload::make('attachment')
```
but did not work :(

**Comment by tabuna** [comment]
We have the key of the `city.*`

```php
Upload::make('city.attachment')
```

**Comment by AlizHarb** [comment]
> We have the key of the `city.*`
> 
> ```
> Upload::make('city.attachment')
> ```

Thank you, now it works but the image is not displaying but it exists in the directory, also the media is empty
![image](https://github.com/orchidsoftware/platform/assets/34816428/65403bd1-a185-4d0d-af90-d80f55f832b0)
