### ISSUE TITLE
Adding a field to role model

### ISSUE THREAD

**Issue by AlizHarb** [orchidsoftware/platform#2647]
How is possible to rewrite on the role model?
i would like to add extra fillable columns

**Comment by czernika** [comment]
1. Create new migration file to add new column(s)
2. Create new Role model which extends default Orchid one

```php
namespace App\Models;

use Orchid\Platform\Models\Role as OrchidRole;

class Role extends OrchidRole
{
    // change $fillable
}
```

3. Replace `Orchid\Platform\Models\Role` with `App\Models\Role` everywhere in your app
4. Add Role class mapping within any ServiceProvider class - this will ensure `roles` relationship returns exact your model

```php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use App\Models\Role;
use Orchid\Platform\Models\Role as OrchidRole;
use Orchid\Support\Facades\Dashboard;

class AppServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        Dashboard::useModel(OrchidRole::class, Role::class);
    }
}
```
