### ISSUE TITLE
Do not automatically upload attachments

### ISSUE THREAD

**Issue by stonedleaf** [orchidsoftware/platform#2648]
**Is your feature request related to a problem? Please describe.**
When adding image/attachment to a form, the uploaded file on the Picture field is saved to the database and stored. However, the user did not submit the form. The uploaded file and database record becomes a waste of space that needs to be manually checked.

**Describe the solution you'd like**
Do not save a record in the database or move to storage when the form is not yet submitted

**Describe alternatives you've considered**
Create my own Field class

**Additional context**
n/a

**Comment by tabuna** [comment]
You don't need to create a custom field. Instead, you can utilize a regular file input field in your HTML form. This will enable users to choose a file from their computer and submit it with the form. Once the form is processed on the server, you will have access to the submitted file and can perform any required actions accordingly.

```php
Input::make('...')->type('file')
```
