### ISSUE TITLE
Preloader for async modals windows

### ISSUE THREAD

**Issue by g-ra** [orchidsoftware/platform#2652]
This feature will solve the problem of data flickering during long asynchronous downloads.

Now "flickering" occurs on fast queries, but on large queries a modal window opens, with old information and only after loading - the data changes

I see two solutions:
1) Add default loader from bootstrap
2) Give the ability to do unset in blade templates so that this design, for example, can work
![image](https://github.com/orchidsoftware/platform/assets/11320990/ee6a8540-516c-4929-8bdf-8b73d07bab78)

**Comment by tabuna** [comment]
Hi, this seems to have been solved in 14.4.0 - 2023-06-21

https://github.com/orchidsoftware/platform/assets/5102591/a78b2a7f-71da-421b-9377-16c2519b0e8c
