### ISSUE TITLE
validating upload & handle matrix delete

### ISSUE THREAD

**Issue by AlizHarb** [orchidsoftware/platform#2661]
Hello
I'm facing a problem with validating using Upload input
`Upload::make('item.attachment')
                        ->title('Item Image')
                        ->maxFiles(1)
                        ->acceptedFiles('image/*')
                        ->groups('items')
                        ->storage('public')
                        ->media(),`
`$request->validate([
            'item.attachment' => 'required|image'
        ]);`

Also i have one extra question, how can i handle the matrix deletion? 

thanks

**Comment by AlizHarb** [comment]
anyone about validating the attachments?

**Comment by MercerMorning** [comment]
@AlizHarb Hi, i think it's impossible to validate uploaded files, because they save once you attached them. Frontend make post request (systems/files) using axios. You can validate only ids of saved attachments in your screen. I think you should try to make your own form element
