### ISSUE TITLE
Bootstrap icons can not load in platform screen

### ISSUE THREAD

**Issue by andares** [orchidsoftware/platform#2662]
**Describe the bug**
I'm not sure if this is a bug. Here's the situation: I'm using the following code in the commandBar() to build a button, but the icon is not displaying correctly. The Bootstrap icon is not loading. Can you please help me identify the possible reasons for this? Currently, the development environment is Laravel 9.x, and the Orchid version is 13.10.

**To Reproduce**

  1. create a laravel project and install orchid platform.
  1. start web server for project.
  1. modify commandBar() to add an icon that resource name is 'bs.cloud' (or any other bootstrap icon name)
  1. refresh the browser, the bs icon is not work.

**Expected behavior**
There is code in commandBar():

```php
    public function commandBar(): iterable
    {
        return [
            Link::make('Cloud Service')
                ->href('https://portal.azure.com/')
                ->icon('bs.cloud'), // It's not work
        ];
    }
```

There is my composer.json require list:

```
        "doctrine/dbal": "^3.5",
        "guzzlehttp/guzzle": "^7.5",
        "laravel/framework": "^9.19",
        "laravel/sanctum": "^3.0",
        "laravel/tinker": "^2.7",
        "orchid/blade-icons": "^2.1",
        "orchid/platform": "^13.10",
        "twbs/bootstrap-icons": "^1.10",
```

No svg tag rendered:

![图片](https://github.com/orchidsoftware/platform/assets/7556505/82cfe1d7-f5b9-40c5-b562-323f0069217f)

**Server (please complete the following information):**
  - Platfrom Version: 13.10
  - Laravel Version: 9.19+
  - PHP Version:  8.1

**Additional context**

And it is not work by `<x-orchid-icon />` tag too.

Thanks again.

**Comment by andares** [comment]
I try to make local custom icon, that's ok, no problem. Only bootstrap icon is not work.

**Comment by tabuna** [comment]
Hello. The default Bootstrap icons are only loaded starting from version 14.x. In version 13.x, we used our own icons, which you can find here:

[Orchid Icon Pack](https://orchid.software/en/docs/orchid-icons/)

If you want to install and use Bootstrap icons separately, you can follow the instructions described here:

[Docs for Custom icons](https://orchid.software/en/docs/icons/#custom-icons)

**Comment by andares** [comment]
Understood, thanks for your response! By the way, is it necessary to have Laravel 10 in order to install orchid 14? I followed the steps in the documentation, but I ended up with version 13.
