### ISSUE TITLE
save attachments with group

### ISSUE THREAD

**Issue by damirqa** [orchidsoftware/platform#2670]
При загрузке файла при помощи Upload, не сохраняется group.

When uploading a file using Upload, the group is not being saved.

  1. In the `save` method of the `Screen` class, save the file as follows:
```php
        if ($request->route('id')) {
            $informationPatients = InformationPatients::query()->where('id', $request->route('id'))->firstOrFail();
        }

        $informationPatients->fill($request->get('informationPatients'))->save();
        $informationPatients->load('attachment');

        $informationPatients->attachment('images')->syncWithoutDetaching($request->get('images'));
        $informationPatients->attachment('files')->syncWithoutDetaching($request->get('files'));
```
  2. Then, in the `query` method of the `Screen` class, I try to retrieve files by group name, but I receive an empty collection: `$informationPatients->attachment('images')->get()`

I expected to get a collection by group name. The `group` field in the `attachments` table is empty.
I also have some additional questions. How can I pass attachments in Upload? `$request->get('attachment', [])`.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]

**Server (please complete the following information):**
  - Platfrom Version: [e.g. 14.6]
  - Laravel Version: [e.g. 10.10]
  - PHP Version:  [e.g. 8.1]
  - Database:  [e.g. MySql]
  - Database Version:  [e.g. 5.7]

**Comment by tabuna** [comment]
The group installation works differently. You specify to which group the field belongs, for example:

```php
Upload::make('attachment')->groups('photos')
// ... Other fields
Upload::make('attachment')->groups('video')
```

Upon file upload, it is assigned a group. The values are also filtered based on this group for display. There is no need to save each group separately; it is sufficient to use:

```php
$model->attachment()->syncWithoutDetaching($request->get('attachment'), []);
```
