### ISSUE TITLE
Client-side validation on multi-tab layout

### ISSUE THREAD

**Issue by johnnuman** [orchidsoftware/platform#2676]
### Discussed in https://github.com/orgs/orchidsoftware/discussions/2675

<div type='discussions-op-text'>

<sup>Originally posted by **johnnuman** July 20, 2023</sup>
On a complex screen layout with multiple tabs, if the user tries to submit the data, it shows a validation error as expected and highlights all the fields with validation error as expected.
But if the fields failing the validation are on a different tab than the active one, there is no indication for the user to know why the submit is failing. Even if the user switches to other tabs, there is no indication of failing fields until he clicks the submit again.
Is this by design? Is there a way to improve this experience?</div>

**Comment by tabuna** [comment]
Hi. I don't do client-side validation, except built into the browser. When you create a large page and want to visually divide it into tabs, I recommend `TabMenu` https://orchid.software/en/docs/custom-template/#tabmenu
