### ISSUE TITLE
Call to undefined method ReflectionUnionType::getName()

### ISSUE THREAD

**Issue by triumph-isingh** [orchidsoftware/platform#2703]
**Describe the bug**
When visiting the route from browser I get the following error:

**_Call to undefined method ReflectionUnionType::getName()_**

**Screenshots**
![Screenshot 2023-08-30 at 13 19 29](https://github.com/orchidsoftware/platform/assets/120404365/df46482a-6bc4-43d5-8d59-cae89aa88be8)

**Desktop (please complete the following information):**
 - OS: MacOS 13.2.1
 - Browser Chrome, Safari, Firefox

**Server (please complete the following information):**
  - Platfrom Version: 14.9.1
  - Laravel Version: 10.4.1
  - PHP Version:  8.2.4
  - Database:  MariaDB
  - Database Version:  10.6

**Additional context**
I have located the issue in callMethod in Orchid\Screen\Screen.php [Line: 415]

Using `Route::substituteBindings($route);` instead of `Route::substituteImplicitBindings($route);` fixes the issue.
I am not sure what the impact will be of making this change.

![Screenshot 2023-08-30 at 13 22 08](https://github.com/orchidsoftware/platform/assets/120404365/3defef2c-bc69-46ba-a8cc-526736e11b90)

**Comment by tabuna** [comment]
Please describe the steps to reproduce the issue.
This will help us replicate the error on our end and narrow down the potential cause.
