### ISSUE TITLE
Action "change->form#changed" references undefined method "changed"

### ISSUE THREAD

**Issue by EeKay** [orchidsoftware/platform#2705]
**Describe the bug**
After upgrading my project to Laravel 10 and Orchid 14 (14.9.1), following the upgrade guide, I tested and the screens are all displayed nicely etc.

My forms now seem to be broken as the JS tries to invoke event functions that aren't found?

ie: when i change a value on an input, and move the focus to another field i get:

```
[Error] Error invoking action "change->form#changed"

Error: Action "change->form#changed" references undefined method "changed" — orchid.js:2:5804

Object
controller: e {context: _}
element: <form id="post-form">
event: Event {isTrusted: true, immediatePropagationStopped: false, stopImmediatePropagation: function, params: {}, type: "change", …}
identifier: "form"
index: 3

Object Prototype
	handleError (orchid.js:2:36779)
	handleError (orchid.js:2:25476)
	invokeWithEvent (orchid.js:2:6523)
	handleEvent (orchid.js:2:5653)
	handleEvent (orchid.js:2:844)

```

breakpoint in the orchid.js's "handleError" function on line 1917 gives me:

```
message: "Action \"change->form#changed\" references undefined method \"changed\""
sourceURL: "http://woordenschat.test/vendor/orchid/js/orchid.js"
stack: "method@http://woordenschat.test/vendor/orchid/js/orchid.js:2:5803↵invokeWithEvent@http://woordenschat.test/vendor/orchid/js/orchid.js:2:6240…"
```

**To Reproduce**

  1. Upgraded project to Laravel 10 and Orchid 14.9.1
  2. Follow the upgrade guide
  3. Ran composer and npm run dev and cleaned config, routes and cache
  4. On local testversion, I go to a screen with a form, edit the input field value, press tab

**Expected behavior**
I'd expect no JS value, the event js being called properly to handle updates, and being able to "save" the info. 
I get a JS error and the save (and delete buttons etc dont work because of this).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Browser: Safari
 - Version: 16.6

**Server (please complete the following information):**
  - Platfrom Version: 4.9.1
  - Laravel Version: 10.21.0
  - PHP Version:  8.2.1
  - Database:  MySQL
  - Database Version:  ?

**Additional context**

**Comment by tabuna** [comment]
Hi @EeKay! The function you're looking for is actually present in the provided files:

You can find it here: [form_controller.js](https://github.com/orchidsoftware/platform/blob/17419f28ba9e87996c8f9da07f3117212c72912b/resources/js/controllers/form_controller.js#L183-L189)

To ensure that you have the most up-to-date resources, make sure to run the following command:

```bash
php artisan orchid:publish
```

I highly recommend adding this command to your composer file so that it can be executed automatically.

For more information, you can refer to the documentation [here](https://orchid.software/en/docs/installation/#keeping-assets-updated).

**Comment by EeKay** [comment]
Thanks I indeed forgot to re publish orchid to get the ja in order 🙏🏻
