### ISSUE TITLE
orchid:install not working for 14.14 on laravel 10.10

### ISSUE THREAD

**Issue by psycho3069** [orchidsoftware/platform#2721]
**Describe the bug**
I tried to install orchid platform in a fresh laravel project but it is stuck on "php artisan orchid:install" step. Screenshot attached below

**To Reproduce**

  1. follow the installation procedures mentioned in the docs upto the step where to run "php artisan orchid:install"

**Expected behavior**
I expected the orchid template to be installed.

**Screenshots**
![image](https://github.com/orchidsoftware/platform/assets/33130889/69b3c826-765b-4acd-99cd-94427d059f6f)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro (version 22H2 - build 22621.2361)
 - Browser: chrome (Version 117.0.5938.132)

**Server (please complete the following information):**
  - Platfrom Version: [14.14.0]
  - Laravel Version: [10.10]
  - PHP Version:  [8.1]
  - Database:  [MySql]
  - Database Version:  [8.0.30]

**Comment by tabuna** [comment]
Before running the command, make sure that you have properly configured the database connection. You can specify these settings in the ".env" file (usually starting with "DB_") and ensure that they are correctly filled.

Once you have checked and updated the ".env" file, retry the installation process.

**Comment by sjfarhanzaman** [comment]
It works with proper configuration! My configuration was bad! @tabuna
