### ISSUE TITLE
Docs update

### ISSUE THREAD

**Issue by ribafs** [orchidsoftware/platform#2722]
Version 14.14

In page
https://orchid.software/en/docs/quickstart/

https://orchid.software/en/docs/quickstart/#navigation

Changed from
registerMainMenu() method.

to
menu() method

Thank you for excelent software

**Comment by tabuna** [comment]
Hey! Thanks for bringing this up. Just wanted to let you know that although `registerMainMenu` is an older method, it's still compatible with the latest version. However, it's marked as deprecated, so it's recommended to use the updated method instead.

By the way, if you have any suggestions for the documentation, you can contribute by clicking on the edit button located on the top right side of the page. Feel free to make any improvements or additions you think would be beneficial. Thanks again!
