### ISSUE TITLE
Clickable icon is missing for a filterable field

### ISSUE THREAD

**Issue by Davka** [orchidsoftware/platform#2736]
**Describe the bug**

I have a table with a column that I want to filter. However, I don't see the icon to click on, so it's impossible to open the drop-down menu to do the filtering

**To Reproduce**

Create 
```
TD::make('foo', 'bar'))
                ->sort()
                ->filter(),
```

**Screenshots**
<img width="298" alt="Bildschirmfoto 2023-10-24 um 10 11 27" src="https://github.com/orchidsoftware/platform/assets/1117697/400edffb-4d16-4120-bd92-ca08e8b108b4">

**Additional context**

**Comment by tabuna** [comment]
Hey! I found something that might help with the issue you mentioned. Take a look at this link: [GitHub Issue #2662](https://github.com/orchidsoftware/platform/issues/2662#issuecomment-1631686038).

**Comment by Davka** [comment]
Thanks, that was the solution.
