### ISSUE TITLE
DateTimer format24hr() doesn't work

### ISSUE THREAD

**Issue by plamenradev** [orchidsoftware/platform#2742]
**Describe the bug**
When using DateTimer field format24hr(true) method does nothing.

**To Reproduce**

  1. Create DateTimer field
  
  ```
DateTimer::make('open')
    ->title('Opening date')
    ->enableTime()
    ->format24hr()
```

**Expected behavior**
Time format in 24 hours instead of AM/PM

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.6
 - Browser: Chrome
 - Version: 118.0.5993.88 (Official Build) (arm64)

**Server (please complete the following information):**
  - Platfrom Version: 13.10.0
  - Laravel Version: 9.52.9
  - PHP Version:  8.1.9

**Comment by BrianWendt** [comment]
I don't fully understand the Stimulus controller stuff yet to know why, but it seems at line 47 of vendor\orchid\platform\resources\js\controllers\datetime_controller.js that the key for "time_24hr", "maxDate", "minDate", and "allowEmpty" come back as false.
"allowEmpty" doesn't appear to be a supported option on flatpickr in the recent versions but the other 3 do appear to be valid options. Other options like "enableTime" and "dateFormat" are working as expected.

Sorry that I don't have a solution, but that is what I've discovered so far.

**Comment by lihe6666** [comment]
![image](https://github.com/orchidsoftware/platform/assets/2598007/d355ccd7-6fe0-4c09-8809-5ec654e9cc75)

Yes, you are right. I will follow up on this issue.

**Comment by lihe6666** [comment]
![image](https://github.com/orchidsoftware/platform/assets/2598007/d4e4752a-269b-483a-96fb-2c8168f0cd9e)

#2775

**Comment by lihe6666** [comment]
@plamenradev This problem can be closed
