### ISSUE TITLE
Screen name() with apostrophe gets escaped causing &#039; to appear instead.

### ISSUE THREAD

**Issue by BrianWendt** [orchidsoftware/platform#2755]
**Describe the bug**
Screen name() with apostrophe get's escaped causing **& # 0 3 9 ;** to appear instead. (spaces added because markdown decodes the **& # 0 3 9 ;** as and apostrophe)

**To Reproduce**

  1. Create a screen (blah blah blah)
  1. Have the `name()` method return "You're testing this"
  1. Render screen and see the entity code in the header and <title> tag

**Expected behavior**
I expect the title and header to read "You're testing this" but it returns "You& # 0 3 9 ;re testing this" 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version

**Smartphone (please complete the following information):**

**Server (please complete the following information):**
  - Platfrom Version: 14.14
  - Laravel Version: 10.10
  - PHP Version:  [e.g. 8.1]
  - Database:  MariaDB
  - Database Version: 10.4.28

**Additional context**

**Comment by BrianWendt** [comment]
I think the `e()` helper function should be removed from the 'title' section is defined. Only the Screen class uses that view and the $name is set via a method that is strict typed as a string. The @yeild directive already escapes strings which I think is causing the problem. With that in mind, I think removing the e() shouldn't cause any security vulnerability.

**Comment by tabuna** [comment]
Yes, I think that escaping was unnecessary. I suggest upgrading to the latest version to fix this issue.
