### ISSUE TITLE
The route link is incorrect!

### ISSUE THREAD

**Issue by lihe6666** [orchidsoftware/platform#2762]
**Describe the bug**

I applied for the HTTPS protocol, but when I requested my backendI applied for the HTTPS protocol, but when I requested my backend address, I submitted the login form using the HTTP protocol, which seems incorrect.

**To Reproduce**

  1. env:  ![7e8886a8e5f13064d686066b4248ec3](https://github.com/orchidsoftware/platform/assets/2598007/0b52f425-4f0d-4eb5-a205-6575c440d57e)
  2.  nginx reverse proxy: ![image](https://github.com/orchidsoftware/platform/assets/2598007/3c463961-1e64-4a1b-a8a5-bcca569691f4)
  3. logout:  ![679a6f5f3b7709a3fc3fa168abeee69](https://github.com/orchidsoftware/platform/assets/2598007/367192f9-9a94-400c-958d-b0596f4e2ea9)

**Expected behavior**

It should be https://[domain.com]/

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [ 107.0.5304.122]

**Server (please complete the following information):**
  - Platfrom Version: [14.16]
  - Laravel Version: [10]
  - PHP Version:  [8.2]
  - Database:  [Mysql]
  - Database Version:  [8.0]

**Additional context**

Help me!

**Comment by tabuna** [comment]
Duplicate: https://github.com/orchidsoftware/platform/issues/2690#issuecomment-1685139122

**Comment by lihe6666** [comment]
Okay, I'll close it
