### ISSUE TITLE
Error Class "Auth" not found on login page

### ISSUE THREAD

**Issue by ToshiYoung** [orchidsoftware/platform#2802]
https://github.com/orchidsoftware/platform/blob/d83bab1fbc3dada5e12ffdba457eb367d456e423/resources/views/app.blade.php#L14

Auth::check() return error Class "Auth" not found

**Comment by tabuna** [comment]
Please ensure that your configuration comes with the default settings and does not replace them

https://github.com/laravel/laravel/blob/20261731467a6adc9393189d75b6e2362e1c31c0/config/app.php#L184-L187
