### ISSUE TITLE
Resource file is too big

### ISSUE THREAD

**Issue by aminemeickel** [orchidsoftware/platform#2803]
is there a way to reduce the size of published vendor js and css file 
is a bit to big when working on really poor connection
<img width="678" alt="image" src="https://github.com/orchidsoftware/platform/assets/68289833/1bffaec0-6c4e-447e-838e-5413ccf184bc">
thank you

**Comment by tabuna** [comment]
Could you please let me know what size you consider acceptable? 
How do you see should supply file sizes reduce?

For comparison purposes, the alternative Laravel Nova: 

- app.js - 1mb 
- vendor.js- 2.2mb. 
- app.css - 262 kB
- custom fonts 

Therefore, I don't think it's correct to say that the supplied file size is large, in isolation from the alternatives.

**Comment by aminemeickel** [comment]
It was the issue from my setup the cache was not enable therefore every action was downloading the entire resource each time thank you for your great work
