### ISSUE TITLE
Parameter is not being passed to Screen's method

### ISSUE THREAD

**Issue by AbdelmageedIsmail** [orchidsoftware/platform#2818]
**Describe the bug**
Filter parameter is not being passed to Screen's method when its value is 0

**To Reproduce**
  1. In a Screen some filters inside a Selection.
  2. One of these filter is Gender filter which has  `options([
                0 => 'male',
                1 => 'female',
            ])
            `
  1. Add a Button `test_button` to the Screen. The Button calls `some_method` and passes request()->all() as a parameter (see screenshot)
  1. Filter the data in the screen by selecting 'male' in the gender filter
  1. Click on the  `test_button`
  1. In the `some_method` print the received Request  

**Expected behavior**
When the Button clicked,  `gender=0` should show up in the url and `"gender" => 0` in the query section of the request object received in the method.

**Screenshots**
![image](https://github.com/orchidsoftware/platform/assets/20727134/c89c8f04-01f9-4403-b0ed-d9e7b5e7c9b6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome
 - Version: 122.0.6261.113

**Server (please complete the following information):**
  - Platfrom Version: 14.18.0
  - Laravel Version: 10.41.0
  - PHP Version:  8.1.0
  - Database:   MySql
  - Database Version:  8.2.0

**Comment by tabuna** [comment]
Should be resolved as of version https://github.com/orchidsoftware/platform/releases/tag/14.21.1

**Comment by AbdelmageedIsmail** [comment]
Confirmed, Than you so much
