### ISSUE TITLE
Mix - Orchid.js File takes too much load time 

### ISSUE THREAD

**Issue by pratikraman-dev** [orchidsoftware/platform#2826]
**Describe the bug**

When i click on new page everytime it takes around 30 - 50 seconds to load 

**Additional context**

![image](https://github.com/orchidsoftware/platform/assets/8825570/153cf806-eac7-4d19-89b9-c91da2d453db)

**Comment by tabuna** [comment]
In the context of your screenshot, the orchid.js script triggers the loading of data for the `/listcontractor` page, which you can see in the screenshot. What is the relevance of orchid.js here?
