### ISSUE TITLE
Cannot delete a selected item in the Relation field

### ISSUE THREAD

**Issue by EizEddin** [orchidsoftware/platform#2840]
**Bug Description:**

When I use a Relation field to search for and select an item, once an item is selected, I can no longer delete that item, or the text in that field. I press the delete/backspace key, but nothing happens.

**Steps to reproduce the behavior:**

  1. You can use the example field "Select for Eloquent model" which comes with Orchid
  2. Select a user from the list
  3. Try pressing the backspace key to delete the selected text, but it doesn't work.  

**Expected behavior:**

When pressing the backspace key, it supposed to delete the selected text in that field, so you can search for another item if you want.  

**Screenshots**
<img width="453" alt="Screenshot 2024-06-04 at 19 57 54" src="https://github.com/orchidsoftware/platform/assets/3897959/b222eb82-5f04-4b61-afab-cb908fe2a75b">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome & Chormium

**Server (please complete the following information):**
  - Platfrom Version: 14.23.1
  - Laravel Version: 11
  - PHP Version:  8.3
  - Database:  MySQL

**Comment by tabuna** [comment]
I apologize for the delay in my response. Before diving into the solution, let’s first understand how the `<select>` element works in a browser.

When you use the following code:

```html
<select name="pets">
    <option value="dog">Dog</option>
    <option value="cat">Cat</option>
    <option value="hamster">Hamster</option>
</select>
```

By default, the first option will be selected, and it cannot be removed or left empty. This is the standard behavior for [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select). To alter this behavior, a common practice is to add an empty `<option>` element, like so:

```html
<select name="pets">
    <option value="">--Please choose an option--</option>
    <option value="dog">Dog</option>
    <option value="cat">Cat</option>
    <option value="hamster">Hamster</option>
</select>
```

Similarly, the `Select` element in Orchid requires a similar approach. For example, you can use the following code:

```php
Select::make('user')
    ->fromModel(\App\Models\User::class, 'name')
    ->allowEmpty()
```

If you have any further questions or need additional assistance, please feel free to let me know!
