### ISSUE TITLE
How to change RedirectIfAuthenticated route

### ISSUE THREAD

**Issue by VardgesK** [orchidsoftware/platform#2878]
Currently, when an authenticated user navigates to the admin/login route, they are redirected to the welcome page. I would like to change this behavior so that authenticated users are redirected to admin/main instead.

admin/login => (if user logged in) => admin/main

**Comment by tabuna** [comment]
You can specify in the settings which route you want to set as the main one. This route will be displayed when clicking on the application name, and it will also be the one users are redirected to after logging in and in other cases.

https://github.com/orchidsoftware/platform/blob/1e330811e878ad4386dddf33cabb070d6586d480/config/platform.php#L89-L102

**Comment by VardgesK** [comment]
@tabuna thanks for answer, but after login, when Im typing admin/login its redirect to welcome page.

I solve the issue in this way

// AppServiceProvider.php

//in method boot()
RedirectIfAuthenticated::redirectUsing(fn() => route('platform.main'));
