### ISSUE TITLE
Column Visibility Menu Overlaps with Tab Titles

### ISSUE THREAD

**Issue by ezhevak** [orchidsoftware/platform#2894]
**Describe the bug**  
The column visibility menu overlaps with the tab titles.

**To Reproduce**

```php
Layout::tabs([
    __('messages.deals.list') => [
        DealListLayout::class,
    ],
]);
```

In the `DealListLayout`, the following is specified:

```php
protected function columns(): iterable
{
    return [
        TD::make('deal_date', __("messages.deals.date"))
            ->usingComponent(DateTimeSplit::class, upperFormat: 'd.m.Y', lowerFormat: 'H:i'),
        
        TD::make('deal_address', __("messages.deals.address")),
        
        TD::make('updated_at', __("messages.updated_at"))
            ->usingComponent(DateTimeSplit::class, upperFormat: 'd.m.Y', lowerFormat: 'H:i'),
        
        TD::make('created_at', __("messages.created_at"))
            ->usingComponent(DateTimeSplit::class, upperFormat: 'd.m.Y', lowerFormat: 'H:i'),
    ];
}
```

**Expected behavior**  
The list should be displayed above the tab titles.

**Screenshots**  
![telegram-cloud-photo-size-2-5402347394512837484-x](https://github.com/user-attachments/assets/f1307fd6-aa80-40a0-a10b-93d558b9852f)

**Desktop (please complete the following information):**
- OS: [MacOS]
- Browser: [Chrome 28.0.6613.120]

**Server (please complete the following information):**
- Platform Version: [e.g. 14.34]
- Laravel Version: [e.g. 10]
- PHP Version:  [e.g. 8.2]
- Database:  [e.g. MySQL]
- Database Version:  [e.g. 8.2]

**Additional context**

**Comment by tabuna** [comment]
Fixed earlier, tested on 14.36.0.
