### ISSUE TITLE
Menu is gone.

### ISSUE THREAD

**Issue by bbwl521** [orchidsoftware/platform#2897]
## Problem/task description:
It is necessary to create/update documentation for the page to make it more readable and understandable for users. Currently, the documentation is either missing or incomplete/unclear.

![image](https://github.com/user-attachments/assets/17082958-90d2-4ee4-8de3-5576811d0f46)

![image](https://github.com/user-attachments/assets/9751ed85-33d8-436c-a455-442e2c50cf91)

Menu is gone.

## Expected outcome:
It is expected that creating/updating the documentation will improve understanding of how to use the code [Please specify specific expected outcomes].

## Proposed solution:
[Please specify what should be included in the documentation].

**Comment by tabuna** [comment]
Thank you for bringing this up! However, the current description lacks specificity, which makes it difficult to implement improvements.

Could you clarify which information seems incomplete or unclear? For example, is there a specific paragraph, or could you ask a question that I could answer here and then update the documentation accordingly?

If you have suggestions for what should be added to the documentation (such as specific sections or topics), please feel free to share them. This will help us incorporate your feedback and make meaningful improvements.
