### ISSUE TITLE
Actions menu only partly visible in users management panel

### ISSUE THREAD

**Issue by andrewthewave** [orchidsoftware/platform#2900]
**Describe the bug**
Trying to open action menu by clicking three dots button, only some portion of it appears
**To Reproduce**

  1. Enter users management panel on /admin/users
  2. Open actions menu by clicking on three dots button next to user

**Expected behavior**
A menu is fully visible and can be interacted with

**Screenshots**
![image](https://github.com/user-attachments/assets/070fb37d-4c72-40fb-8ac4-8d748df0d8d2)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 129.0.0.0

**Smartphone (please complete the following information):**

**Server (please complete the following information):**
  - Platform Version: 14.36
  - Laravel Version: 10.9
  - PHP Version:  8.1
  - Database:  Pgsql
  - Database Version:  15.2

**Additional context**
Tried on different OS (windows/linux) / PC / browsers - issue persists

**Comment by tabuna** [comment]
I cannot reproduce this issue in Chrome with the latest version of the package. However, I’m aware that this problem occurred before. Are you sure all resources were published during the update? You can verify this by running the `artisan about` command.

**Comment by andrewthewave** [comment]
Yes, turns out resources were outdated, after publishing them the glitch is gone. Thank you!
