### ISSUE TITLE
Please re-check again for version 14.42.0

### ISSUE THREAD

**Issue by aldoetobex** [orchidsoftware/platform#2919]
Dear Developer Orchid,
I've found the issue of version [14.42.0](https://github.com/orchidsoftware/platform/releases/tag/14.42.0) release. Please re-check again the modal function. All modal for this version is not working. Thanks!

![image](https://github.com/user-attachments/assets/cd0f4e3b-eb92-4281-865c-de3c221a6fa7)

PHP : 8.3.xxx
Laravel : 11.9.xxx
OS : macOS 15.0.1 (Apple M1)

**Comment by taqwaaziz95** [comment]
Yes its very annoying , because my modals , does not show , its just empty like that . 
so I need to Downgrade my Orchid .

**Comment by tabuna** [comment]
Sorry to hear you ran into this issue — the release did go out a bit sooner than expected. 
It should be fixed now. Thanks so much for your patience and support!
