### ISSUE TITLE
Проблема с доступом

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#353]
До обновления все было норм. Orchid/platform была установлена 25 ноября.
Сейчас обновил через `composer update  orchid/platform:dev-master  `
После обновления нет доступа к моему расширению, во вкладке Permission его вообще нет, а было.
[Ссылка на мое расширение ](https://github.com/PSalador/uslugi)

Кстати после обновления надпись
A new stable version of ORCHID is available. Please update to the latest version.
не исчезла

**Comment by tabuna** [comment]
Сожалею, что вы столкнулись с такой проблемой.
Во время обновления были ошибки?

Можете показать файл bootstrap/cache/packages.php вашего приложения?

**Comment by PSalador** [comment]
да 
[packages.zip](https://github.com/orchidsoftware/Platform/files/1532471/packages.zip)

**Comment by tabuna** [comment]
После выполнения команды `php artisan package:discover` результат такой же?

**Comment by PSalador** [comment]
> После выполнения команды php artisan package:discover результат такой же?

Выполнил - результат такой же.

**Comment by tabuna** [comment]
Хм, а можете сделать связку 'php artisan clear-compiled  && php artisan package:discover'
Проблема в auto-discover, так как в вашем файле packages.php  пакет uslugi находится выше, чем platform соответственно и подключается раньше.

**Comment by tabuna** [comment]
Я попробовал воспроизвести твою проблему следующим образом, поставил последний релиз и master пакет Monitor, после чего в скомпилированном файле изменил последовательность. Результат отличный.

Твой пакет мне не удалось поставить, так как он не зарегистрирован на [packagist](https://packagist.org/search/?q=salador%2Fuslugi&reason=package_not_found)

**Comment by PSalador** [comment]
Благодарю. Получилось.
Еще ошибку выдавал на `bootstrap/cache/services.php` - там тоже изменил последовательность и заработало.

**Comment by tabuna** [comment]
А как вы меняли? Помогли ли вам команды которые я писал? Или вы решили это по другому?

**Comment by PSalador** [comment]
Нет команды не помогли. Поменял вручную.

**Comment by PSalador** [comment]
Запустил предыдущие команды раздельно -  `php artisan clear-compiled` удаляет эти файлы, 
а `php artisan package:discover` создает заново.
Надо где-то указать, что мой пакет нужно позже ставить.

**Comment by PSalador** [comment]
Понял в чем я накосячил. В composer.json моего пакета нужно было добавить
```
  "require": {
         "php": ">=7.0",
	"orchid/platform": "dev-master"
  },
```
добавил теперь всё норм.

**Comment by tabuna** [comment]
Можете записать, что бы загружались только релизы
```
  "require": {
    	"orchid/platform": "^2.0"
  },
```

**Comment by PSalador** [comment]
Опять после обновления опять та же проблема, проделал все действия, не помогло. 
Пока поменял последовательность вручную.

**Comment by tabuna** [comment]
Хм, мне это не очень нравится, можешь описать как именно у тебя подключен пакет в твоём приложении, так как я понимаю, что он находится у тебя не в вендоре?

Мне необходимо воспроизвести такое поведение, потому что я не наблюдаю такого с другими пакетами, например [Monitor](https://github.com/Feralas/Monitor)

**Comment by PSalador** [comment]
1) В корневом каталоге Laravel добавил папку Package, а уже в неё установил свой пакет.
2) В корневом файле composer.json установленного Laravel добавил строки чтобы искал пакет в каталоге pachage
```
	 "repositories": [
        {
			"packagist.org": false,
            "type": "path",
            "url": "./package/uslugi"
        }
	]
```
3) Подключил с помощью команды `composer require salador/uslugi:dev-master --prefer-source` правда в vendor он установил только ссылку.
4) Опубликовал провайдера с помощью команды `php artisan vendor:publish --provider="Salador\Uslugi\Providers\UslugiServiceProvider"`
5) Установил таблицы данных `php artisan migrate`
