### ISSUE TITLE
Меню и уведомления

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#358]
Существует серьёзная UI/UX проблема связанная с меню и уведомлениями. 
Заключается в неправильном и нелогичном подходе построения интерфейса.

Например:
![2017-12-08 00 07 15](https://user-images.githubusercontent.com/5102591/33738853-c54b9a84-dbab-11e7-9fec-de3522a9102a.png)
Если на текущем экране нет функциональных кнопок управления, то верхнее меню выглядит так.
Иначе отображается хотя бы одна пользовательская кнопка.
![2017-12-08 00 08 24](https://user-images.githubusercontent.com/5102591/33738897-f990e542-dbab-11e7-9026-a271acf5e7f4.png)

Это достаточно не логично, что в зависимости от состояния экрана меняется интерфейс.

Плюс ко всему, выпадающее меню имеет ограничения, и по умолчанию включает в себя пункты меню:

- На сайт (А что если сайта нет? Убрать нельзя)
- Профиль (А что если прав нет? Убрать нельзя, А что если человеку не нужно поле name? Email тоже доверять нельзя, только id, но это бред)
- Выйти
 
Получается, что это существенное ограничение, которое нужно либо решать, либо убирать.

Так же в этой области расположены уведомления, которые можно  отрыть, но так как у нас левая панель занимает 350px и к этому ещё прибавляется 300px с правой стороны для уведомлений.
И того, 650px, что бы просто отобразить системные данные. (Явно не гуд)

Обсудив ситуацию с дизайнером, пришли к выводу, что лучшим решением будет, будет убрать эту панель и показывать на этом месте только commandBar (Кнопки). А системные вещи перенести в левое меню. 

Так как при показе по умолчанию левое суб-меню было всегда пустым (Что вызывало критику), логичнее всего перенести уведомления именно в эту область.

![2017-12-08 00 18 48](https://user-images.githubusercontent.com/5102591/33739232-60610332-dbad-11e7-9b36-8dd34ff8158b.png)

Это позволяет существенно объединить интерфейс, но создаёт сразу 2 новых проблемы.

- Где визуально показывать, что есть новые уведомления (На логотипе?)
- Где расположить кнопку выхода?

Оба этих вопроса остаются открытыми.

Плюс
- Очищать или удалять уведомления (Раньше можно было делать и то и другое)

Если делать кнопку выхода в самом нижним углу, то будет ли она понятна и очевидна каждому?
Сомневаюсь.

![2017-12-08 00 25 37](https://user-images.githubusercontent.com/5102591/33739486-5591a55a-dbae-11e7-9b69-e6069b4bcbb4.png)

А если как пункт меню , то выглядит более очевидно, но как то стрёмно (?)

![2017-12-08 00 24 56](https://user-images.githubusercontent.com/5102591/33739551-884a9e70-dbae-11e7-9347-33f63ed4be79.png)

**Comment by PSalador** [comment]
Да наверно лучше будет перенести оповещения в левое суб-меню. (Хотя до этого не добрался ещё)
> Где визуально показывать, что есть новые уведомления (На логотипе?)
Надо смотреть в дизайне, на логотипе думаю норм будет.
Я так понял, что эти номерки как-то можно возле каждого пункта меню добавить (возле Экраны есть 5) как?

> Где расположить кнопку выхода?
Выход не часто нужен можно мелким сделать.
Можно ещё  в суб-меню над уведомлениями вставить профиль и ниже иконки разные в том числе и выход.
![profile](https://user-images.githubusercontent.com/29531264/33755804-0fe40378-dc25-11e7-88eb-70d4fb0bbafe.jpg)

> Очищать или удалять уведомления (Раньше можно было делать и то и другое)
и то и другое

**Comment by tabuna** [comment]
> Я так понял, что эти номерки как-то можно возле каждого пункта меню добавить (возле Экраны есть 5) как?

[Расширение](https://orchid.software/ru/docs/extension/)
Ключ `badge`
```php
        $this->dashboard->menu->add('Main', [
            'slug'       => 'slug-my-menu',
            'icon'       => 'icon',
            'route'      => '#',
            'label'      => 'My name Menu',
            'childs'     => true,
            'main'       => true,
            'active'     => 'dashboard.mymenu.*',
            'permission' => 'dashboard.mymenu',
                'badge'      => [
                    'class' => 'bg-primary',
                    'data' => function(){
                        return 7;
                    }
                ],
            'sort'       => 1,
        ]);
```


> Выход не часто нужен можно мелким сделать.
> Можно ещё в суб-меню над уведомлениями вставить профиль и ниже иконки разные в том числе и выход.

Панелью могу пользоваться различного положения люди. По этому хз, стоит ли делать мелким.

Профиль и т.п. очень спорные, потому что это сделает жёсткую привязку.
Например, в миграции laravel по умолчанию идёт user с полями

- name
- email

А что если разработчику не нужны эти данные, а например 

- phone
- first name
- last name

Тогда либо будет получать ошибку, либо делать пустые колонки в БД, что ни как нигуд, всё равно отображать будет нечего. По этому я сомневаюсь в таком подходе.

**Comment by PSalador** [comment]
> Панелью могу пользоваться различного положения люди. По этому хз, стоит ли делать мелким.

Можно покрупнее и справа от профиля.

Если нет, тогда выход лучше в нижнем левом углу, чем в меню.

В Laravel порог входа высокий. Так что разработчик разберется с кнопкой выхода, и что поставить если у него не будет поля name.

А вот если не найдет поля где отображается текущий профиль, то задумается.
Нативное отображение профиля пользователя в правом верхнем углу (как сейчас в orchid), посмотрел на вскидку несколько сайтов которые сейчас открыты (yandex, mail, wordpress, github) везде в правом верхнем углу отображается профиль.

**Comment by tabuna** [comment]
> Так что разработчик разберется с кнопкой выхода, и что поставить если у него не будет поля name.

Это будет требовать дополнительных усилий и поддержки. Которые могут не потребоваться, или же не очень важные. Проблема в том, что практически во всех проектах которые я видел, большинство вещей было прибито, я хочу двигаться в сторону [Screen](https://github.com/orchidsoftware/platform/issues/330), что бы дать возможность строить бизнес-приложения, а не только администрировать проекты.


> Нативное отображение профиля пользователя в правом верхнем углу (как сейчас в orchid), посмотрел на вскидку несколько сайтов которые сейчас открыты (yandex, mail, wordpress, github) везде в правом верхнем углу отображается профиль.

Совершенно не обязательно следовать этим принципам так как перечисленные продукты массовые и находятся в другом сегменте. 

Например, CMS  Statamic от разработчика Laravel имеет профиль в нижний части экрана (Но он ярко выраженный)

![cp-alt](https://user-images.githubusercontent.com/5102591/33782557-4338abc6-dc6a-11e7-83c2-b052f1561910.png)


Или же другое популярное решение Craftcms на базе Yii (Конечно не в СНГ)

![craft-cms-plugin-pounts-entries](https://user-images.githubusercontent.com/5102591/33782808-208e55a2-dc6b-11e7-9682-51b4596e92d6.png)

Так, что тут не всё однозначно. 
Верхняя панель и так занята, не думаю, что стоит оставлять, так как есть. 

Можешь заменить, что например WP или другие делают под этим меню ещё одни слой, что бы уже там помещать кнопки управления, я уже проходил через этот этап. (Можешь посмотреть в первых релизах).

**Comment by PSalador** [comment]
Можно как в CMS Statamic:
1) Внизу убрать две кнопки которые сейчас.
2) Вниз добавить иконку с надписью My Account  в стиле главного меню. (только одно, Logout не добавлять)
3) Всё остальное вынести в суб-меню - Профиль, Имя, Email, Выход.

**Comment by PSalador** [comment]
Как добавить уведомления в dashboard?
сделал так в demo экранов
```
 public function create()
    {
		Alert::info('Message');
		$user = User::find(1);
		$user->notify(new \Orchid\Platform\Notifications\DashboardNotification([
			'title' => 'Hello Word',
			'message' => 'New post!',
			'action' => 'https://google.com',
			'type' => 'error',
		]));
	return redirect()->route('dashboard.screens.demo.list');
}
```
Он сообщение Alert выводит а уведомления в dashboard нет, и ошибки никакой не выдает.

**Comment by tabuna** [comment]
Возможно ты вошёл не под User с id 1.

Попробуй например так

```php
$user = Auth::user();
$faker = \Faker\Factory::create();

$user->notify(new DashboardNotification([
    'title'   => $faker->text(20),
    'message' => $faker->text(100),
    'action'  => 'https://google.com',
    'type'    => array_random([
        'info',
        'success',
        'warning',
        'error',
    ]),
]));
```

**Comment by PSalador** [comment]
Получилось. Странно у меня один пользователь.

Желательно сделать, чтобы можно было по одному удалять уведомления.

**Comment by tabuna** [comment]
@PSalador просто пользователь не имел id равным 1.

Я думаю, стоит закрыть это и вернутся позднее уже к кнопки `настройки` потому что не очень хорошо, что бы любой пользователь мог сбрасывать кэш у всех
