### ISSUE TITLE
Поддержка Markdown

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#359]
Думаю имеет смысл добавить помимо стандартного wysiwyg редактора ещё лёгкий markdown.

Для этого потребуется :

1. добавить в сборку [SimpleMDE](https://simplemde.com/) (или альтернативу ?)
2. Создать новое поле и зарегистрировать его

**Comment by PSalador** [comment]
Давай сделаю, я как раз с полями разбираюсь.

1,3 Получается нужно подключить через composer.json
2. Добавить шаблон в resources/views/fields  и класс который ссылается на шаблон в /src/Platform/Fields/Types
4. Еще не знаю как.

**Comment by tabuna** [comment]
Было бы здорово
Я почему то думал, что у laravel появилась поддержка markdown. Во всяком случае, письма можно отправлять с такой разметкой, может и не потребуется ставить отдельный пакет.

Давай поставим только то, что зависит от нас. Если разработчику нужно будет пакет для обработки он его поставит вручную. Обновил.

**Comment by PSalador** [comment]
> Я почему то думал, что у laravel появилась поддержка markdown. Во всяком случае, письма можно отправлять с такой разметкой, может и не потребуется ставить отдельный пакет.

Посмотрел - получается laravel [parsedown ](https://github.com/erusev/parsedown) подтягивает,
и подключает его в  \Illuminate\Mail\Markdown.php

**Comment by PSalador** [comment]
Ошибка в `platform/resources/views/fields/tinymce.blade.php` в 61строке лишняя запятая в конце
`success('/storage/' + response.data.path + response.data.name + '.' + response.data.extension,);`

Сделал SimpleMDE, в config/platform.php заменил wysiwyg на
`'wysiwyg'      => Orchid\Platform\Fields\Types\SimpleMDEField::class,`
у меня работает, в БД сохраняет.
