### ISSUE TITLE
Проблема с полем Place

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#360]
Ставлю поле Place (карта).
Сначала была ошибка:

> You have included the Google Maps API multiple times on this page. This may cause unexpected errors.

я так понял это баг Laravel он `@stack('scripts')` два раза подряд отображает.
Убрал в `place.blade.php` обрамление скрипта `@push('scripts') @endpush` думаю не должно быть ошибок из-за того, что скрипт отображается не в конце.
Ошибка исчезла, но карта не отображается, а никаких ошибок скриптов нет.

Вот как отображается:
![place1](https://user-images.githubusercontent.com/29531264/33785762-1189e458-dc99-11e7-8c1f-caa92f2bb8d5.png)

Может какие-нибудь дополнительные данные нужно передать в Behaviors классе?
У меня так:
```
'location'    => [
                'tag'         	=> 'place',
                'type'        	=> 'text',
                'name'        	=> 'location',
                'prefix'       	=> 'master',
                'title'       	=>  'Location',
                'placeholder' 	=> 'Location',,
            ],
```

**Comment by tabuna** [comment]
Хм, нет в этом ничего страшного, в действительности нужно указать google api key
Можете посмотреть [тут](https://orchid.software/ru/docs/field/)

### Локация
Поле локация требует, чтобы ключ для карты Google указывался в `config/service services.google.maps.key`
```php
//
'google' => [
    'maps' => [
        'key' => 'secret string'
    ],
],
```

**Comment by PSalador** [comment]
Ключ в `services.google.maps.key` я указал, скрипт его подгружает.

**Comment by tabuna** [comment]
У google большая связка ключей, возможно вы не выдали прав на карты или домен

Так же убедитесь, что правильно указали параметры
Например мой тестовый файл `/config/services.php` выглядит так:


```php

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Stripe, Mailgun, SparkPost and others. This file provides a sane
    | default location for this type of information, allowing packages
    | to have a conventional place to find your various credentials.
    |
    */

    'mailgun' => [
        'domain' => env('MAILGUN_DOMAIN'),
        'secret' => env('MAILGUN_SECRET'),
    ],

    'ses' => [
        'key' => env('SES_KEY'),
        'secret' => env('SES_SECRET'),
        'region' => 'us-east-1',
    ],

    'sparkpost' => [
        'secret' => env('SPARKPOST_SECRET'),
    ],

    'stripe' => [
        'model' => App\User::class,
        'key' => env('STRIPE_KEY'),
        'secret' => env('STRIPE_SECRET'),
    ],

    'google' => [
        'analytics' => [
            'key' => ***************-***************************************.apps.googleusercontent.com',
        ],
        'maps' => [
            'key' => '*********************************************************',
        ],
    ],


];
```


![2017-12-09 00-49-13](https://user-images.githubusercontent.com/5102591/33786605-d0aa1afc-dc7a-11e7-8081-640629b970db.png)
![2017-12-09 00-48-45](https://user-images.githubusercontent.com/5102591/33786606-d0cf3da0-dc7a-11e7-82e4-4493354ddb73.png)

**Comment by PSalador** [comment]
Оказывается всё работает)
Думал нужно нажать кнопку справа и выбрать, а оказывается нужно ввести место в поле.

Нужно будет дополнительное поле сделать - место по умолчанию, а то серый экран вылазит когда в поле ничего не забито.
