### ISSUE TITLE
The code editor takes 30% of the js file

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#361]
It may be worth making it as a separate package

**Comment by PSalador** [comment]
Yes, all editors combine into a separate package.

Plus, the moment.js loads all the locales (118 languages) in orchid.js.

**Comment by PSalador** [comment]
Я это сделаю. C webpack разобрался.
Думаю редакторы надо сделать чтобы отдельно загружались.
Как лучше сделать - каждый редактор в отдельный файл или все объединить в один.

**Comment by PSalador** [comment]
В dashboard.blade.php есть строка подключения сторонних скриптов
```
@foreach(Dashboard::getProperty('resources')['scripts'] as $scripts)
    <script src="{{$scripts}}" type="text/javascript"></script>
@endforeach
```
Есть пример как с ней работать?

**Comment by tabuna** [comment]
Я пока не уверен, стоит ли решать данную проблему, и если решать, то какими методами.

Примеры и т.п. есть в [документации](https://orchid.software/ru/docs)

Например:

Расширить в своём приложении внеся изменения в конфиг
```php
    /*
    |--------------------------------------------------------------------------
    | Dashboard Resource
    |--------------------------------------------------------------------------
    |
    | Automatically connect the stored links. For example js and css files
    |
    */
    'resource' => [
        'stylesheets' => [],
        'scripts'     => [],
    ],
```

или через сервис провайдер (Подходит для пакетов):

```php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Orchid\Platform\Kernel\Dashboard;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot(Dashboard $dashboard)
    {
        $dashboard->registerResource('stylesheets','custom.css');
        $dashboard->registerResource('scripts','custom.js');
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```

**Comment by tabuna** [comment]
У меня всё ещё нет однозначного решения. 
Может посмотреть альтернативу `ace.js` в виде решения от [MS](https://microsoft.github.io/monaco-editor/)? Он явно лучше выполняет свою задачу, но не известно будет ли он весить меньше и у него нет поддержки на мобильных устройствах.

**Comment by PSalador** [comment]
А что поставил сегодняшнее обновление с revert-376-master?
Там мне получилось примерно на 0.5 Мб размер JS сократить (примерно 250 кб с локализаций moment.js и столько же с умньшения размера code editor)

**Comment by tabuna** [comment]
Думаю это не существенный вопрос, с каждым разом мы начинаем тянуть всё больше и больше зависимостей. Будет правильно в будущем делать отдельные пакеты для ace или monaco, так как они частные случаи использования.

**Comment by aios** [comment]
А мне кажется лучше делать вендоризацию - то бишь динамический набор зависимостей на тот или иной набор данных - в зависимости от компонентов подтягиваемых через экраны. 

Это означает что вам нужно собирать зависимости в чанки - накладывать через микс на каждую из страниц) поверьте вес точно изменится) а зависимости будут динамичные. Так же вы сможете контролить набор зависимостей прямо из экрана.

**Comment by PSalador** [comment]
@aios Можешь кинуть ссылку куда копать про чанки и динамический набор зависимостей. 
Вот я в [ветке с BS4](https://github.com/orchidsoftware/platform/tree/revert-376-master/) в moment.js вырезал все лишние локали - оставил только самые распространенные, хотя можно оставит только две - русский и тайский (для которых есть перевод в Orchid, английский по умолчанию), это уменьшило размер исходного js примерно на 10%.
Правильно я понимаю, что если собирать динамически, то в  moment.js можно подгрузить только те локали которые указаны в config/platform.php?
