### ISSUE TITLE
Migration less to sass and Bootstrap 4

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#370]

**Comment by PSalador** [comment]
I'll make.

**Comment by tabuna** [comment]
you make me happy with this

**Comment by PSalador** [comment]
)
Раньше была на https://orchid.software демо версия, сейчас где-нибудь есть? А то сравнивать верстку затруднительно.

**Comment by tabuna** [comment]
Replacing `less` with` sass` (Thanks @PSalador) bf7d1cc54c7ea5d910a1ec9e795749be6a0a7b63

**Comment by PSalador** [comment]
А как сейчас быть, я Bootstrap 4 поправил верстку, 
меню работает,
увидел что в новой версии все поля есть на демо странице - поправил в ней верстку.
сделал страницу с экранами - там поправил верстку вверху,
Я так понимаю сейчас он pull request не примет.

**Comment by tabuna** [comment]
@PSalador не переживай. Конфликты слияния разберу

**Comment by PSalador** [comment]
@tabuna  revert-376-master обновил.

- перевел на  bootstrap4.beta2   сабменю сделал, локализация открывается
- что было на скриншотах - пофиксил
- пофикил мобильную версию.

**Comment by PSalador** [comment]
Вроде доделал bootstrup 4.
@tabuna Александр посмотри [revert-376-master ](https://github.com/orchidsoftware/platform/tree/revert-376-master), а то мне всё отлично видится.

**Comment by tabuna** [comment]
@PSalador я имею множество проблем со сборкой. Например ругается, что нет переменной `$grid-breakpoints`

```sass
$screen-sm-min: map-get($grid-breakpoints, sm);
$screen-md-min: map-get($grid-breakpoints, md);
$screen-lg-min: map-get($grid-breakpoints, lg);
```

Проверь пожалуйста

**Comment by PSalador** [comment]
Всё норм должно быть -$grid-breakpoints  определяется в variables.scss в 12 строке.

**Comment by tabuna** [comment]
@PSalador  зайди в чат, мы как раз сейчас обсуждаем это

**Comment by PSalador** [comment]
А где чат? На gitter.im нет.

**Comment by Rendol** [comment]
https://lara-orchid.slack.com/messages/C6JJA6X0V/

**Comment by tabuna** [comment]
Думаю, что данный таск можно закрывать и если будут проблемы то решать их по мере проявления.
@PSalador Спасибо тебе большое.
