### ISSUE TITLE
Save Field Place to DB

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#372]
1) Есть ли опыт сохранение данных поля Place в базу  данных? Сохранить получилось, но когда редактируешь запись, не получается нормально её прочитать, чтобы при редактирование нажав на маркер отображалась карта.

2) В файле place.blade.php функция `@push('scripts')` в итоге дважды вставляет скрипт, разобраться не получилось почему так.

**Comment by tabuna** [comment]
1. Опыт есть,  такой проблемы нет, работает в продакшене
1. Скорее всего у тебя 2 языка активны или на одной странице сразу 2 поиска

**Comment by PSalador** [comment]
> Опыт есть, такой проблемы нет, работает в продакшене

Какой тип записи в базе данных надо использовать? Я попробовал строковый под адрес, и point под координаты. Записывать научился, вот так
```
$attributes = $request->all();
$attributes['location']= \DB::raw("GeomFromText('POINT(".$attributes['adress']['lat']." ".$attributes['adress']['lng'].")')");
$attributes['adress']=$attributes['adress']['name'];
$master->fill($attributes);
$master->save();
```
 но не пойму как считать назад и сделать чтобы в `$value` записывал массив. Идеи приходят, только если place.blade.php переписать.

> Скорее всего у тебя 2 языка активны или на одной странице сразу 2 поиска

Поисков нет ни одного, активность 2 языков незнаю как проверить. Странно, что если добавляю поле place в записи page или post там всё норм. Значит какая-то проблема у меня в расширении. `@stack('scripts')` нигде не использую.

**Comment by tabuna** [comment]
> Какой тип записи в базе данных надо использовать?

Я использовал JSON, но это не обязательно, просто поле отдаёт тебе массивом и хочет, что бы ты отправлял массивом.

**Comment by PSalador** [comment]
Благодарю, получилось. 
Адрес и координаты сделал чтобы сохранялись в одно json поле adress
В модели добавил 
```
    protected $casts = [
        'adress' => 'array',
    ];
```
он стал записывать как массив, но при считывании не преобразовывал, после  в модели добавил функцию 
```
public function setAdressJson()     {
  if (isset($this->attributes['adress'])) {
    $this->attributes['adress'] = json_decode($this->attributes['adress'],true);  //преобразуем в json
  }
  return $this;
 }
```
