### ISSUE TITLE
Add api_token

### ISSUE THREAD

**Issue by kiwina** [orchidsoftware/platform#375]
An improvement adding api_token to the user table

**Comment by tabuna** [comment]
Hello, why should this be? You can do this in your application

**Comment by kiwina** [comment]
Since its part of laravel core that could improve on api development, since i saw that there is some plan to make an api

**Comment by tabuna** [comment]
Yes, the API is planned, but the authorization or keys must be on the user side. The api_token field is not universal, for example, if you use Laravel Passport
