### ISSUE TITLE
How to get the category?

### ISSUE THREAD

**Issue by kiwina** [orchidsoftware/platform#378]
hi i cant seem to fin a easy way to get the category of a post??

**Comment by tabuna** [comment]
Hi I do not understand

**Comment by kiwina** [comment]
well the first option print "category" witch well that isn't right

second option is not getting the post category directly isn't it!!
so i tried getTermsAttribute but that trows an error because taxonomies is a builder instance so it needs ->get() in order to work properly to return the array
