### ISSUE TITLE
Dashboard: permissions. Можно работать с постами без доступа.

### ISSUE THREAD

**Issue by Rendol** [orchidsoftware/platform#387]
### Expected Behavior
Если отсутствует permission для доступа к посту определенного типа, кидать 403.

### Actual Behavior
При отсутствии доступа пункт в меню не выводится, но можно открыть по прямой ссылке.

### Steps to Reproduce the Problem
  1. Создать новый тип для Posts
  1. Открыть url вида /dashboard/posts/{type|slug}
  1. Убедиться, что доступ открытый

### Specifications

  - PHP Version: 7.1.11
  - Database Version: PostgreSQL 10.1
  - Laravel: 5.5.27
  - Orchid: dev-master (f60ea00)

### Screenshots
![image](https://user-images.githubusercontent.com/2122240/34361346-fa159a72-ea9b-11e7-99b3-7a889fe8e2f1.png)

**Comment by Rendol** [comment]
Проблема в том, что мидлвер навешивается после этапа обработки мидлверов.
![image](https://user-images.githubusercontent.com/2122240/34361846-a4c74e12-eaa0-11e7-941b-1d43dace4d99.png)

![image](https://user-images.githubusercontent.com/2122240/34361856-b9f24cb0-eaa0-11e7-8643-9d1df63c3d2d.png)

![image](https://user-images.githubusercontent.com/2122240/34361836-983327a2-eaa0-11e7-912e-a79e06005b7f.png)

**Comment by tabuna** [comment]
Исправил в  1d6f029744da7a386b8e7fa6a37a788aaffaacf0

**Comment by tabuna** [comment]
Выпустил патч в `2.0.8`

**Comment by TITAN-UZ** [comment]
Как надо обновить

**Comment by tabuna** [comment]
```
composer update
```

**Comment by TITAN-UZ** [comment]
Так сделал но текст не уходить 

A new stable version of ORCHID is available. Please update to the latest version.

**Comment by TITAN-UZ** [comment]
Все кэш почистил сработал

**Comment by tabuna** [comment]
Сообщение кешируется, что бы каждый раз не обращаться к внешним сервисам.
Можешь очистить кэш либо через графический интерфейс, либо командой:

```
php artisan cache:clear
```


Опоздал ;)
