### ISSUE TITLE
Автоматическая генерация slug, если поле не заполнено и задано свойство slugFields

### ISSUE THREAD

**Issue by Rendol** [orchidsoftware/platform#388]
Сейчас, если удалить значение из поля Semantic URL, то  новое на основе, например названия поста, не создаётся.

**IFixIt** :-)

**Comment by tabuna** [comment]
Так так полегче, у тебя же в поведении есть свойство slug

```php
namespace DummyNamespace;

use Orchid\Platform\Behaviors\Many;

class DummyClass extends Many
{

    /**
     * @var string
     */
    public $name = '';

    /**
     * @var string
     */
    public $slug = '';

    /**
     * @var string
     */
    public $icon = '';

    /**
     * Slug url /news/{name}.
     * @var string
     */
    public $slugFields = '';

    /**
     * Rules Validation.
     * @return array
     */
    public function rules()
    {
        return [];
    }

    /**
     * @return array
     */
    public function fields()
    {
        return [];
    }

    /**
     * Grid View for post type.
     */
    public function grid()
    {
        return [];
    }

    /**
     * @return array
     */
    public function modules()
    {
        return [];
    }
}
```

Slug будет слушать любое поле которое ты укажешь и генерировать значение по нему

**Comment by Rendol** [comment]
Не, это в методе update.
Если мы не трогали slug, то он и не изменится.
А вот если мы очистили это поле и задали новое значение в поле, которое указано в slugFields, то должно сгенерироваться новое значение slug.
Уже сделал, только накосячил с пулл-реквестом... сейчас исправлю и отправлю.

**Comment by Rendol** [comment]
Сделал коммит, делать пулл-реквест, или сам заберешь? :-)

**Comment by tabuna** [comment]
Лучше сделай PR

**Comment by Rendol** [comment]
И да, сейчас в контроллере код написан так, что slugFields обязательное поле.
\Orchid\Platform\Http\Controllers\Posts\PostController::store
Http/Controllers/Posts/PostController.php:87
Если не задать в поведении, то валится ошибка при сохранении.
В \Orchid\Platform\Http\Controllers\Posts\PostController::update я поправил, а тот момент упустил.

**Comment by tabuna** [comment]
> И да, сейчас в контроллере код написан так, что slugFields обязательное поле.

Ну всё правильно, slugFields обязательное свойство.

_P.S._
Мне кажется мы не в том направлении идём. Можно же решить slug на уровне значения по умолчанию.

Да и кода меньше, единственное изменение

```php
    if ($request->filled('slug')) {
        $slug = $request->get('slug');
    } else {
        $content = $request->get('content');
        // Значение по умолчанию, "1" вынесем как константу и будет норм
        $slug = $type->slugFields ? reset($content)[$type->slugFields] : 1;
    }
```


@Rendol  Что ты об этом думаешь?

**Comment by Rendol** [comment]
> Ну всё правильно, slugFields обязательное свойство.

Странно немного, т.к. я могу вообще его не указывать, а всегда прописывать руками... но да ладно, дело хозяйское.

Не понял, зачем значение по умолчанию нужно?
Основная проблема у меня была в этом месте:
```
-        if ($request->filled('slug') && $request->get('slug') !== $post->slug) {
+        if (!empty($slug) && $slug !== $post->slug) {
```
т.е. если изменил название поста и хочу чтобы сгенерировался новый semantic url

**Comment by Rendol** [comment]
Мысль не закончил:
Хочу генерацию и для этого просто очищаю поле Semantic Url.
Соответственно платформа видит, что поле пустое, берет новое название и из него создает новый Semantic Url
