### ISSUE TITLE
Demo-page  not found (status of 404)

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#392]
After last update demo-page (/dashboard/pages/demo-page) not found.

**Comment by tabuna** [comment]
Check Permission

**Comment by PSalador** [comment]
No, it not helped.

**Comment by tabuna** [comment]
Does the file exist?
Is it specified in config? If specified, did you try to clear the cache?

**Comment by PSalador** [comment]
> Does the file exist?
Yes.

> Is it specified in config?
Yes.

> If specified, did you try to clear the cache?
yes `php artisan cache:clear` and `php artisan config:clear`

**Comment by tabuna** [comment]
Sorry. I fixed it. #2d1f23151857bbdd36aa7d736ac5277368aab86a

**Comment by jes490** [comment]
I had the same issue. I did `php artisan route:list` and found out that Orchid used localhost as domain in routes. So I changed APP_URL in .env file to the actual host (I was using a homestead) and it worked.

**Comment by PSalador** [comment]
> I had the same issue. I did php artisan route:list and found out that Orchid used localhost as domain in routes. So I changed APP_URL in .env file to the actual host (I was using a homestead) and it worked.

No, it's after the 2.0.8 update.
Now after the update 2.0.9 everything works.

 > I fixed it.

In first site updated via `composer update` - after the update works..
In second site updated via copy new files -  - after the update not works..
Problems :
Builder.php - _use Orchid\Platform\\**Platform**\\Fields\Parser;_
Parcer.php - _namespace Orchid\Platform\\**Platform**\\Fields;_

**Comment by tabuna** [comment]
Да епть, не одно так второе. Срочно делаю тесты

**Comment by PSalador** [comment]
) Бывает.
