### ISSUE TITLE
New field `upload`

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#399]
Добавить новый тип для загрузки файлов. 

Точнее он уже есть:
![2017-12-31 15 12 03](https://user-images.githubusercontent.com/5102591/34461502-1124c752-ee3d-11e7-85a5-fc2a6ecd70ca.png)

Нужно вынести отдельно, а старое использование вызывать уже новый. 

Так мы сохраним старое состояние и добавим возможность использование в нескольких местах (Например деление по категориям). Так и использование в Screen

**Comment by tabuna** [comment]
#625 добавляет требуемое поле.

Загрузка полностью основана на модели "Вложения" и для своей работы требует подключённого трейта

**Comment by PSalador** [comment]
- [ ] исправить ошибки #639 
- [ ] сделать нормальное сохранение #645
