### ISSUE TITLE
New field "tags"

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#400]
Сейчас можно использовать поле для полей такого вида
![2017-12-31 15 15 51](https://user-images.githubusercontent.com/5102591/34461518-8f5f36ca-ee3d-11e7-8410-6209f493bb94.png)

Он имеет несколько проблем, как стилистических, так и моральных (Давно не обновлялся, хз как ещё для bs4).

Хотя существует и другой вид тегов от `select2`, который не имеет таких проблем. 
![2017-12-31 15 15 34](https://user-images.githubusercontent.com/5102591/34461527-c352cd66-ee3d-11e7-9c99-c0ae5a2c65ac.png)

Думаю, стоит оставить только один вид (`select2`)

**Comment by PSalador** [comment]
Переделано, но сохраняет в виде массива, есть несколько вариантов решения:
1. Оставить как есть
2. Переделать в строку через js
3. Сделать нормальное сохранение #645

**Comment by tabuna** [comment]
Старый компонент полей удалил. Теперь теги одинаковы везде. Такс закрываю, будет доступно с новым релизом
