### ISSUE TITLE
Attachments: save image

### ISSUE THREAD

**Issue by Rendol** [orchidsoftware/platform#401]
Проблемы:

- [x] 1. Не производит пост обработку изображений saveImageProcessing (исправить опечатку)
- [x]  2. Image::make (src/Platform/Attachments/File.php:183) кидает ошибку об отсутствии временного файла: Unable to find file (/tmp/php....).
- [x] 3. Сделать сохранение файла через Storage
- [x] 4. Сделать удаление файла через Storage в Attachment

**Comment by Rendol** [comment]
Изменил (new File) на:
```
            $attachment[] = app()->make(File::class, [
                'file' => $file,
                'storage' => Storage::disk('public')
            ])->load();
```
Как я использую всё это дело:
```
<?php
/**
 * YaDiskServiceProvider.php.
 */

namespace App\Providers;

use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use League\Flysystem\Filesystem;
use Arhitector\Yandex\Disk as Client;
use Arhitector\Yandex\Disk\Adapter\Flysystem as Adapter;
use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Route;
use Orchid\Platform\Attachments\File;

/**
 * Class YaDiskServiceProvider
 * @package App\Providers
 */
class YaDiskServiceProvider extends ServiceProvider
{
    /**
     * Perform post-registration booting of services.
     *
     * @return void
     */
    public function boot()
    {
        Storage::extend('yaDisk', function ($app, $config) {
            $client = new Client($config['accessToken']);
            return new Filesystem(new Adapter($client, 'disk:' . $config['baseDir']));
        });
        Route::pattern('storagePath', '.*');
        Route::get('/storage/{storagePath}', function ($path) {
            /** @var Adapter $storage */
            $fullPath = storage_path('app/public/' . $path);
            $dirPath = dirname($fullPath);
            if (!is_dir($dirPath)) {
                mkdir($dirPath, 0755, true);
            }
            try {
                $content = Storage::disk('yaDisk')->get($path);
                file_put_contents($fullPath, $content);
                return app()->make('redirect')->refresh();
            }
            catch (\Exception $e) {
                abort(404);
            }
        });
        app()->extend(File::class, function($file, $app) {
            $file->storage = Storage::disk('yaDisk');
            return $file;
        });
    }
}
```

**Comment by Rendol** [comment]
@tabuna что скажешь?

**Comment by tabuna** [comment]
Хахах 1 января в восемь часов утра...

**Comment by tabuna** [comment]
Могу сказать только «курлык-курлык»курлык-курлык))

**Comment by aios** [comment]
Похоже на те проблемы с которыми я столкнулся в сове при создании или правке поля с картинками

**Comment by tabuna** [comment]
@aios ты их исправил ?

**Comment by tabuna** [comment]
@Rendol Вроде всё здраво. Может ещё стоит вынести Storage::disk('public') в конфиг?

**Comment by Rendol** [comment]
@tabuna если честно, не вижу как это сделать красиво.
1. Сейчас код понятен для чтения
2. Если менять, то тогда везде по проекту

**Comment by Rendol** [comment]
Мысль в слух:
Было бы здорово в медиа-менеджере (в интерфейсе) сделать выпадашку с выбором хранилища, тогда получится универсальный вьювер.

**Comment by Rendol** [comment]
И по 4 пункту:
1. Storage сейчас зашит внутри модели, нужна помощь: как красиво заинжектить?
2. Предположение, @tabuna поправь, если ошибаюсь: Удаление attachment идёт с удалением всех связей и самого файла - это не верно, файл может быть привязан к другому посту. Такая привязка возникает аз-за расчёта хэша файла, т.е. за счёт исключения дубляжей.

**Comment by tabuna** [comment]
**Должно быть:**

Файл один, записей модели много, на один файл может быть сколько угодно моделей. 

Кейс:
Например один и тот же файл может иметь разное описание в зависимости от контекста и дату загрузки. 

При  удаление модели должна быть проверка используется ли файл где либо ещё, если нет, удалять

**Менеджер:**
> Было бы здорово в медиа-менеджере (в интерфейсе) сделать выпадашку с выбором хранилища, тогда получится универсальный вьювер.

Если не ошибаюсь, то в контроллере всё построено на `Storage`, так что не должно возникнуть проблем, с тем, что мы ему будет подсовывать. `public` или ещё что либо.

Но тут возникнет сложность, в том, что laravel по умолчанию поставляется сразу с несколькими конфигами `public/private/s3/local` захотят ли пользователи делать доступными например файловую систему `private`, то есть опять новый ключ делать в нашем конфиге. 

А так, я только за такой функционал.

**О чём я:**
> @tabuna если честно, не вижу как это сделать красиво.
> 
> Сейчас код понятен для чтения
> Если менять, то тогда везде по проекту

Я имею ввиду, что подсовывать в качестве хранилища, например 
```php
 Storage::disk(config('platform.filesystems.public'))
```

**Comment by Rendol** [comment]
> Я имею ввиду, что подсовывать в качестве хранилища, например

Не, не то. Это должно быть управляемо самим контроллером или интерфейсом.
Сейчас файлы все грузятся в public. Но я более чем уверен, что может потребоваться загрузка в приватное хранилище. Т.е. грузим с одной страницы и в public и в private.

**Comment by tabuna** [comment]
> Не, не то. Это должно быть управляемо самим контроллером или интерфейсом.
Как? Где? Зачем? Может я думаю, не о том, что ты имеешь ввиду

> Сейчас файлы все грузятся в public. Но я более чем уверен, что может потребоваться загрузка в приватное хранилище. Т.е. грузим с одной страницы и в public и в private.
Так разве вынос параметра в конфиг не решит? Нужно класть в private указал хранилище, нужно в s3 указал другое хранилище и т.д.

**Comment by Rendol** [comment]
> Так разве вынос параметра в конфиг не решит? Нужно класть в private указал хранилище, нужно в s3 указал другое хранилище и т.д.

Нет, не решает. Конфиг только одно место определит в рамках всего проекта.
Конкретный кейс:
1. Одни изображения я гружу в публичную часть для просмотра (например с watermak)
2. Другие прикрепляю в private хранилище

Всё это я делаю при создании например фото на продажу.

**Comment by tabuna** [comment]
Можем попробовать указывать хранилище в параметрах поля.

**Comment by Rendol** [comment]
> Можем попробовать указывать хранилище в параметрах поля.
Тогда это нужно учесть для всех загрузок в проекте.
Можешь пример привести как это будет выглядеть?

**Comment by tabuna** [comment]
1. Определим в `разрешениях` какие хранилища доступны для пользователя.
2. Для загрузок добавим дополнительный аргумент 'хранилище' и поставим `public` по умолчанию
3. Profit.

**Comment by Rendol** [comment]
@tabuna, я всё думаю про удаление.
Т.к. файл может быть загружен в любое хранилище, получается, что мы должны знать куда он был загружен. Или при удалении смотреть откуда запрос идёт (с какого поля)?

**Comment by Rendol** [comment]
Стратегический вопрос))

**Comment by Rendol** [comment]
В общем пошёл от второго варианта, сейчас залью

**Comment by tabuna** [comment]
> Стратегический вопрос))

Считаю, что нужно придерживаться умеренных целей. Всякие `поведения` с `posts` и `page` должны на себя брать готовые строители (Справочники и т.п.). Где действия очень просты и предсказуемы. Если человеку нужно разработчику нужно больше свободы и контроля, то должны использоваться `Экраны`

**Comment by Rendol** [comment]
@tabuna Мне кажется ты меня не понял...
Я про модель Attachment. Должна ли она знать где она хранится?
К примеру: имя, путь и ещё много чего она знает.
