### ISSUE TITLE
[2.1] Дизайн файлового менеджера

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#427]
При работе с файловым менеджером есть несколько важных замечаний которые бы хорошо исправить к 2.1. почти все они касаются визуальной части.

**Общее:**
1. Правая часть с информацией о файле постоянно скачет
1. Нет переводов

**Управление:**

1. Для чего нам понадобился ещё один команд бар? Думаю имеет смысл вынести кнопки управления "Upload" , "refresh", "New folder" в верхнее меню, которое используют другие экраны.
1. Кнопку же удалить перенести в правую часть к информации о файле, туда же можно добавить "переместить" и "переименовать"
  

P.S. сам сценарий можно убрать из blade в js

**Comment by tabuna** [comment]
![2018-01-11 02-30-55](https://user-images.githubusercontent.com/5102591/34801033-7ac146c6-f677-11e7-84e9-2570862c9208.png)

**Comment by tabuna** [comment]
Доделать перевод.

**Comment by PSalador** [comment]
Что-то кнопка "Переместить" работает не правильно.
И кнопка "Переименовать" не переименовывает, (только создает видимость что переименовала).

**Comment by tabuna** [comment]
Исправил
