### ISSUE TITLE
Добавление данных в шаблоны Layouts

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#430]
**Например:**

Необходимо добавить название для своей таблицы, соответственно название у каждой таблице будет разным. Это название требуется передавать.

**Решение:**

Добавить метод, который бы добавлял набор данных (Которые не имеют отношения для форм и т.п) в шаблон.

**Comment by tabuna** [comment]
подумать View::composer ?

**Comment by PSalador** [comment]
Что-то непонятно, а такое решение не подойдет:
Screen
```
public function query() : array
    {
       $options['title']='Table title';
        return [
            'data'   => $data,
            'options'    => $options,
        ];
    }
```
Layout
```
public function fields(): array    {
    return  [
        Field::tag('input')
            ->name('data.name'),
        Field::tag('label')
            ->name('options.title')
    ]
}
```

**Comment by tabuna** [comment]
@PSalador ох, думаю нет. Так как речь именно о _кастомных_ шаблонах и передачей параметров в них. Мы уже добавляли свойство `$compose` в `Orchid\Platform\Screen\Layouts`, но это решение мне не очень сильно нравиться.

Не так давно переработал этот механизм и добавил возможности устанавливать любой `view` по необходимости. 

**Это выглядит следующим образом:**


```php

    /**
     * Query data.
     *
     * @return array
     */
    public function query(): array
    {
        return [
            'model' => Model::first(),
        ];
    }

    /**
     * Views.
     *
     * @return array
     * @throws \Orchid\Press\TypeException
     */
    public function layout(): array
    {
        return [
            Layouts::view('cutom'),
        ];
    }
```

Тогда при отображении экрана, будет переданы все результаты `query`:

```html
<a href="{{ route('home',$model) }}">Link to Model </a>
```


Считаю, что это поможет в написании более универсальных экранов (Что бы не переопределять постоянно layouts), и поможет решить эту проблему. Нужно задокументировать это.
