### ISSUE TITLE
Add namespace for route bind keys

### ISSUE THREAD

**Issue by Rendol** [orchidsoftware/platform#446]
See `\Orchid\Platform\Providers\RouteServiceProvider` uses `Route::bind`

This:
```php
        Route::bind('category', function ($value) {
            return Taxonomy::findOrFail($value);
        });
```
replaced to:
```php
        Route::bind('orchidCategory', function ($value) {
            return Taxonomy::findOrFail($value);
        });
```

@tabuna what you think?

I can fix it.

**Comment by tabuna** [comment]
Думаю, если мы решим сделать это, то это должно быть однообразно.
То есть добавить префикс ко всем биндингам которые относятся к панели управления
- Role
- Category
- Type
- Widget
- Slug
- Page

Так же я бы изменил написание, на что то в роде:

```php
Route::bind('dashboard-category', function ($value) {
    return Taxonomy::findOrFail($value);
});
```


Можно ли биндинги переопределять в своём приложении? Например Page и Slug могли быть полезны по умолчанию?

**Comment by Rendol** [comment]
> То есть добавить префикс ко всем биндингам которые относятся к панели управления

Так, похоже кто-то не посмотрел мой коммит)))
Я предложил и сразу отправил изменения;-)

Сейчас поменяю формат `orchidType` на `dashboard-type`.

> Можно ли биндинги переопределять в своём приложении?
1. Если хочешь использовать `bind-keys` в своём приложении, то это плохая идея:
    1. Во-первых эти биндинги могут измениться (чисто теоретически)
    1. Во-вторых если ты включить режим админки headless, то у тебя ничего не должно работать (возможно я ошибаюсь здесь)
    1. Третье: в какой-то момент ты можешь админку вынести из проекта в отдельный (читай на отдельный сервер)

> Например Page и Slug могли быть полезны по умолчанию?
1. Они не настолько сложны, чтобы их выносить (и потом поддерживать), лучше в документацию добавить как пример.

**Comment by Rendol** [comment]
@tabuna фиаско, братан... через тире не биндиться...
`Illuminate/Routing/Router.php:894`
```php
    /**
     * Add a new route parameter binder.
     *
     * @param  string  $key
     * @param  string|callable  $binder
     * @return void
     */
    public function bind($key, $binder)
    {
        $this->binders[str_replace('-', '_', $key)] = RouteBinding::forCallback(
            $this->container, $binder
        );
    }
```

Только `underscore`, только `hardcode` =)
