### ISSUE TITLE
Array type fields

### ISSUE THREAD

**Issue by angay9** [orchidsoftware/platform#456]
Is there a way to add a field that be duplicated. For instance, I want to build a Gallery behavior and I would like a user to add multiple pictures. Is it possible to do something like this?
```php
 /**
     * @return array
     */
    public function fields() : array
    {
        return [
            'pictures'  =>  'tag:picture|name:pictures[]|multiple:true',
        ];
    }
```
And when a user wants to add new pictures, he can add as many as he wants.

Or even a better, if there was a way to specify a group of fields that can be duplicated.
Maybe something like this
```
 /**
     * @return array
     */

    public function fields() : array
    {
        return [
            'pictures'  =>  [
                'multiple'  => true,
                'max'  =>   10, // User can add 10 fields at most
                'fields' => [
                    'image' => 'tag:picture',
                    'description'   =>  'tag:input|type:text',
                ]
            ]
        ];
    }
```
Then, a user would be able to add new fields, where he would be able to add an image and description to each one of those.

**Comment by tabuna** [comment]
Hey. Even now there is an implementation for this

**Attachments:**
![ezgif-2-a90fe11614](https://user-images.githubusercontent.com/5102591/35003303-7fcc9ae6-fafd-11e7-86ca-0b86dcdf003b.gif)
_All image can specify the size and quality (in config)_


```php
$item = Post::find(42);
$item->attachment('image')->get();

$image = $item->attachment('image')->fisrt();

//Returns the address of the image with the desired image resolution
$image->url('standart');
```


-----
You also have the ability to create your own fields. They are also defined in the config

**Comment by PSalador** [comment]
#685
