### ISSUE TITLE
Error as select menu "demo post"

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#457]
Version: 	2.0.11
![screenshot1](https://user-images.githubusercontent.com/29531264/35002468-5886adcc-fb1c-11e7-8ff6-332347e727c5.png)

**Comment by PSalador** [comment]
Update to dev-master and the error has disappeared.
But new error, in Edit post and page.
```
Field robot does not exist or inheritance FieldContract (View:/vendor/orchid/platform/resources/views/container/posts/page.blade.php)
```

**Comment by tabuna** [comment]
Посмотри CHANGELOG.md
