### ISSUE TITLE
[2.1] Некоторые косяки и вопросы в dev

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#460]
#### /dashboard/systems/category

- [x] 1. Если выбран русский язык панели - разделы в базе сохраняются с пометкой "en", 
и по адресу /dashboard/systems/category не отображается название.
- [x] 2. При создании и редактировании в селект нельзя выбрать родительскую категорию. Проблема в русском - скорее всего из-за первого пункта.
- [ ] 3.  В английском с выбором родительской категории всё норм, но в select нельзя проследить иерархию.

**Comment by PSalador** [comment]
## Меню

#### /dashboard/systems/menu

1. В dev в меню пропал пункт меню - нет не в "en" ни в "ru", хотя по адресу /dashboard/systems/menu переходит.
2. При русской локализации меню не сохраняется. В английской - норм. 
3. В меню список Relations (Отношения) какую практическую пользу несет? Не слишком ли он перегружен?
4. Меню работает если parent=NULL, если parent=0 то не отображается. (В базе на NULL изменить нельзя) - может у меню не имеющего родителя сделать parent=0?
5. После каждого перетаскивания меняется id пунктов меню - мне кажется это не правильно id должен оставаться таким как при создании, а для сортировки есть sort.

**Comment by tabuna** [comment]
## Разделы

#### /dashboard/systems/category

> Если выбран русский язык панели - разделы в базе сохраняются с пометкой "en", 
и по адресу /dashboard/systems/category не отображается название.

Скорее всего ты имеешь ввиду, не "русский язык панели", а общий язык для "Laravel", за сохранение и получение данных у нас есть методы вроде `getContent` который определяет по текущему языку установленного в приложении (На момент исполнения конечно).

Проблема в том, что нужно изменить локализацию в `config/platform.php`

> При создании и редактировании в селект нельзя выбрать родительскую категорию. Проблема в русском - скорее всего из-за первого пункта.

Такое же поведение, как и пункт выше.

> В английском с выбором родительской категории всё норм, но в select нельзя проследить иерархию.


Хм, я не очень понимаю, как отслеживать иерархию в обычном select. Если разделять и конкатенировать значения будут совсем не читаемые.  У меня нет предложений на этот счёт.

**Comment by PSalador** [comment]
## Posts

#### dashboard/posts/demo/create

1. JavaScript ошибка при создании поста `An invalid form control with name='content[en][body2]' is not focusable.` из-за `->required()` в markdown.
2. При создании поста после ошибке вверху 
```
Oh snap! Change a few things up and try submitting again.
The content.en.name field is required.
```
очищаются все введенные данные и не дает сохранять post.

**Comment by PSalador** [comment]
## Пользователи, Роли

#### /dashboard/systems/users
#### /dashboard/systems/roles

1. Может сделать стандартный список ролей что бы понятно было какие роли для чего например (Админ, Пользователь, Автор), хотя бы (Админ, Пользователь), чтобы был понятен минимальный набор ролей.
2. Если зайти под пользователем без прав, то он больше не сможет зайти под другим логином (недоступно /dashboard/login), а /dashboard/logout выдает ошибку.
3. Пользователь мог выбрать язык панели.
4. dashboard/systems/cache доступно у пользователей без роли dashboard.systems
5. Что за роль dashboard.systems.attachment?
6. Возможно ли чтобы пользователь с доступом к dashboard.systems.media  имел доступ только к своим файлам?
7. Пагинация в пользователях и ролях косячит.
8. По разному обрабатываются поле permissions в ролях и пользователях, в БД ролей запись dashboard.systems":"0" аналогична "dashboard.systems":"1" и эта роль будет помечена галочкой, в отличае от БД пользователей.
9. Перевод на русский ролей - "Параметр**ам** системы","Категори**ям**", а также не переводятся названия заголовков блоков ролей.

**Comment by PSalador** [comment]
## Комментарии

#### dashboard/systems/comment

1. При выводе комментариев ошибка Route [dashboard.marketing.comment.edit] not defined. (View: /vendor/orchid/platform/resources/views/container/systems/comment/grid.blade.php)

**Comment by tabuna** [comment]
> Может сделать стандартный список ролей что бы понятно было какие роли для чего например (Админ, Пользователь, Автор), хотя бы (Админ, Пользователь), чтобы был понятен минимальный набор ролей.

Ну это не косяк и не вопрос ;) Пользователь и так может это сделать.
Но вообще конечно можно, что то такое придумать сразу.

> Если зайти под пользователем без прав, то он больше не сможет зайти под другим логином (недоступно /dashboard/login), а /dashboard/logout выдает ошибку.

Это нормально, например кейс, если есть сайт с пользователями, то у них может и не быть прав для просмотра панели.

> Подумать: Чтобы пользователь мог выбрать язык панели.

Я конечно "за", но не очень понятно как именно это осуществлять, хранить язык в бд, не очень практично для проектов без локализации, да и редактировать свой профиль в панели, не каждый может. Делать через сессию, она не бесконечна... Вообще конечно лучим решением будет написать в доке, например о том, как сделать поддержку языка для пользователя.

> dashboard/systems/cache доступно у пользователей без роли dashboard.systems - вообще вроде не привязано к ролям.

Это, да пока ничего не придумал, кроме как убрать вообще этот пункт из меню, но хочется туда добавить, что либо.

> Что за роль dashboard.systems.attachment?
Даёт возможность загружать файлы и их прикреплять.

> Возможно ли чтобы пользователь с доступом к dashboard.systems.media  имел доступ только к своим файлам?

Вообще да, сейчас появились варианты. посмотри конфиг.


> Пагинация в пользователях и ролях косячит.

Можешь пример, я несколько раз слышал об этом, но наверное я куда то не туда смотрю всё время.

> По разному обрабатываются поле permissions в ролях и пользователях, в БД ролей запись dashboard.systems":"0" аналогична "dashboard.systems":"1" и эта роль будет помечена галочкой, в отличае от БД пользователей.

Нужно срочно смотреть, "0" или "1" вообще быть не должно, только int значения


> Перевод на русский ролей - "Параметр**ам** системы","Категори**ям**", а также не переводятся названия заголовков блоков ролей.

Исправишь?

**Comment by PSalador** [comment]
Отметил то, что проверил и сделано.

> Возможно ли чтобы пользователь с доступом к dashboard.systems.media имел доступ только к своим файлам?
Вообще да, сейчас появились варианты. посмотри конфиг.

**Comment by tabuna** [comment]
> 3. В меню список Relations (Отношения) какую практическую пользу несет? Не слишком ли он перегружен?

Так стандартный список отношений для ссылки, что бы ты изменил?

>  4. Меню работает если parent=NULL, если parent=0 то не отображается. (В базе на NULL изменить нельзя) - может у меню не имеющего родителя сделать parent=0?

Поддерживаю, убрал вообще null, поставил жёсткое приведение к типу `integer`, то есть в новых установках всё будет хорошо, для старых будет работать правило `(int)null // 0`

**Теперь нужно исправить все примеры и доку, что бы считать от 0. ->where('parent',0)**


>  5. После каждого перетаскивания меняется id пунктов меню - мне кажется это не правильно id должен оставаться таким как при создании, а для сортировки есть sort.

Исправил

**Comment by tabuna** [comment]
> Может сделать стандартный список ролей что бы понятно было какие роли для чего например (Админ, Пользователь, Автор), хотя бы (Админ, Пользователь), чтобы был понятен минимальный набор ролей.

Думаю можно использовать сиды в будущем или написать отдельные для `Demo`, что бы было заполнено как можно больше данных

> 3. Подумать: Чтобы пользователь мог выбрать язык панели.

Давай сделаем отдельным таском не в этом релизе.

>  6. Возможно ли чтобы пользователь с доступом к dashboard.systems.media имел доступ только к своим файлам?

Да, я установил в конфиге параметр для media, но тебе так или иначе свой драйвер указывать для него. Это забота laravel и проекта, со стороны orchid мы сделали всё необходимое для этого.

> По разному обрабатываются поле permissions в ролях и пользователях, в БД ролей запись dashboard.systems":"0" аналогична "dashboard.systems":"1" и эта роль будет помечена галочкой, в отличае от БД пользователей.

Проблема в том, что приходит в формате `string`, не знаю как исправить без костыля.

**Comment by PSalador** [comment]
>> В меню список Relations (Отношения) какую практическую пользу несет? Не слишком ли он перегружен?
> 
> Так стандартный список отношений для ссылки, что бы ты изменил?

Я просто не понимаю зачем они нужны, какую практическую пользу несут? Я выбираю любое отношения, а он всё равно переходит по ссылке которая оказана, но поначалу приходиться вникать какое выбрать, пока не поймешь, что от выбора отношения ничего не зависит - и ставишь любое.

**Comment by tabuna** [comment]
@PSalador 

это же rel

_Пример шаблона_
```
<div class="row">
    @foreach($menu->chunk($chunk) as $value)
        <div class="col-md-3 col-xs-6">
            <ul class="list-unstyled l-h-2x">

                @foreach($value as $item)

                    <li>
                        <a href="{{$item->slug}}"
                           title="{{$item->title}}"
                           target="{{$item->target}}"
                           rel="{{$item->robot}}"
                           class="{{$item->style}} text-ellipsis"

                        >
                            <i class="fa fa-angle-right text-muted m-r-sm"></i> {{$item->label}}
                        </a>
                    </li>
                @endforeach
            </ul>
        </div>
    @endforeach
</div>
```


Можем убрать, если в этом есть смысл?

**Comment by PSalador** [comment]
> это же rel
Можем убрать, если в этом есть смысл?

Понятно, 
да не пусть остаются.

**Comment by tabuna** [comment]
Заметил касяк, что добавление никак невалидируется
