### ISSUE TITLE
Error on Pages

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#468]
В страницах dashboard/pages/demo-page

1.Если выбрана одна локаль, то при сохранении выдает ошибку 
```
Call to a member function all() on null
in src/Platform/Core/Models/Post.php:156
```
http://prntscr.com/i35nbm 

Я так понял это из-за views\container\posts\modules\base.blade.php
в нем строки передают локаль:
```
    @else
        @foreach($locales as $key => $locale)
            <input type="hidden" name="options[locale][{{$key}}]"
                   value="true">
        @endforeach
    @endif
```
а в page этого нет

2. Если выбрано две локали то если не заполнить данные для второй то в скриптах выдает
```
An invalid form control with name='content[ru][name]' is not focusable.
...
```
проблема в том, что в постах можно отключить заполнение для второй локали, а в страницах нет.
И всё равно, когда заполняешь данные за две локали - выводит ошибку указанную в пункте 1.

**Comment by tabuna** [comment]
### Если выбрана одна локаль, то при сохранении выдает ошибку

Нашёл проблему, ребят я конечно очень радуюсь каждый раз с новым PR, но чёт это какой то [треш](https://github.com/orchidsoftware/platform/pull/434/files#diff-db02c63e136463775732f837528fbeafL197).


**Было:**

Получаем опции в виде коллекции, вроде ничего сверхъестественного, если опций не будет вернётся пустая коллекция.
```php
    /**
     * @return \Illuminate\Support\Collection
     */
    public function getOptions() : Collection
    {
        return collect($this->options);
    }
```

**Стало:**

Я не знаю как это вообще в dev, до этого работало, магия.

Берём массив, вызываем метод all() и потом оборачиваем в коллекцию, мало того, что у нас null, так мы у null вызываем ещё и методы...
```php
    /**
     * @return \Illuminate\Support\Collection
     */
    public function getOptions() : Collection
    {
        return collect($this->options->all());
    }
```


Я вернул рабочий вариант.


### Если выбрано две локали то если не заполнить данные для второй то в скриптах выдает

Хром говорит, что есть невалидные (не заполненные) данные, которые он не может отобразить на странице. Скорее всего нужно будет писать js обработчик или что то в этом духе, говорящий пользователю, что нужно указать другой язык? 
Любые идеи по этому поводу.

**Comment by Rendol** [comment]
@tabuna 
1. теперь ты вернул ошибку которая была исправлена.
2. я у тебя спрашивал, зачем ты оборачиваешь массив в коллекцию, ответа не получил.
3. почему options null тоже вопрос, т.к. это должен быть массив.
4. теперь в коллекцию пытается обернуться Repository.

Я нем могу ответить почему используется обертывание в коллекцию (в чём задумка), но если его убрать, проблема уйдёт.

З.Ы. Сейчас сломанный вариант.

**Comment by tabuna** [comment]
@Rendol 
1. О какой ошибки ты говоришь? Можешь привести код, который будет вызывать ошибку?
1. Для того, что бы сразу можно было использовать методы коллекции, тебе будет самому на много удобнее, например, взять из опции только определённые значения.
1. null возможен когда объект только инициализировался
1. И? Ошибки то не будет.

Пример того почему обёртывается в коллекцию:
```php
$post = Post::find(1);
$post->getOptions()->only(['product_id', 'name'])
```

Та жа запись, если не будет коллекции:
```php
$post = Post::find(1);

collect($post->getOptions())->only(['product_id', 'name'])
```


**Почему я её добавил?**
При использовании laravel, начинаешь привыкать к ним, так как почти во всех основных данных возвращается именно объект коллекции, например `Request`. Плюс это удобно

**Comment by Rendol** [comment]
@tabuna 
При сохранении, падает такая ошибка:
```
SQLSTATE[22P05]: Untranslatable character: 7 ERROR: unsupported Unicode escape sequence DETAIL: \u0000 cannot be converted to text. CONTEXT: JSON data
```
```
"options" = {"\u0000*\u0000items":{"locale":{"ru":"true"}}}, "updated_at" = 2018-01-24 07:44:42 where "id" = 57)
```

Т.е. коллекция создается не правильно из-за того что передаётся объект Repository, вместо массива.

**Comment by Rendol** [comment]
POST Data:

options | array:1 [▼   "locale" => array:1 [▼     "ru" => "true"   ] ]
-- | --

**Comment by tabuna** [comment]
Да, ты прав, я получаю не правильную запись в базе данных (Но ошибки нет lol?).
Тогда я не понимаю, для чего мы оборачиваем это дело в Repository? 

Ведь и коллекция отлично ходит по вложениям:
```php

$array = [
    'catalog' => [
      'motel' => [
          'Arizona' => [
              'name' => 'test'
          ]
      ],
      'hotel' => [],
    ],
];


$motel = collect($array)->get('catalog.motel.Arizona');

/*
array:1 [▼
  "name" => "test"
]
*/
```

**Comment by Rendol** [comment]
1. Делал для getContent() - здесь с поддержкой языка.
2. коллекция выдернет значение по ключу: $post->options['catalog.motel.Arizona']?

Скорее всего можно и убрать для options, только для getContent нужно оставить, чтобы можно было так писать:

```php

    /**
     * Grid View for post type.
     */
    public function grid(): array
    {
        return [
            'slug' => 'Идентификатор',
            'peoples.0.lastName' => 'Фамилия',
            'peoples.0.firstName' => 'Имя',
            'publish_at' => 'Дата публикации',
            'created_at' => 'Дата создания',
        ];
    }
```

**Comment by tabuna** [comment]
Походу, мы это не правильно вообще решили. 


Мне кажется можно переписать getContent, что бы так воспринимал, это должно быть в духе:

```php
/**
 * @param      $field
 * @param null $lang
 *
 * @return mixed|null
 */
public function getContent($field, $lang = null)
{
    $attributes = array_keys($this->getAttributes());

    if (in_array($field, $attributes)) {
        return $this->getAttribute($field);
    }
    
    $lang = $lang ?? App::getLocale();

    return collect($this->getAttribute($this->jsonColumnName))->get($lang . '.' . $field);
}
```

Это решит наши проблемы и будет намного чище. Что ты об этом думаешь?

**Comment by Rendol** [comment]
Это упростит поддержку.
Только потеряем короткое обращение по ключу ArrayAcces.
```php
$post->content['en.customer.passport.firstName'];
```
Но думаю так никто писать не будет. ( кроме меня :-))) )

**Comment by tabuna** [comment]
Конечно, вместо 100 строчек, 5 ) посмотри ветку 
https://github.com/orchidsoftware/platform/tree/feature/issue_468

**Comment by Rendol** [comment]
Остальное тоже выпилил?
Нигде getContent не дёргает обычные поля?

**Comment by Rendol** [comment]
Я об этом
```php
 return $this->$field;
```

**Comment by tabuna** [comment]
Так за этот как раз таки отвечает:
```php
return $this->getAttribute($field);
```

**Comment by Rendol** [comment]
@tabuna да, ты прав не внимательно посмотрел.

Осталось вернуть дефолтное значение:
```php
catch (\ErrorException $exception) {
  $content = collect($this->{$this->jsonColumnName})->first();
  if (array_key_exists($field, $content)) {
    return $content[$field];		
  }
}
```

Удобно для перевода на другой язык, когда форма подставляет на русском, а ты уже переводишь и сохраняешь

**Comment by tabuna** [comment]
@Rendol добавил обработку для запасного языка.


Нужно что то решать со вторым пунктом, любые предложения по этому поводу.

**Comment by PSalador** [comment]
Или убрать проверку заполненности полей для второстепенных локалей.
Или сделать таб для каждой локали как в постах.
Вообще в постах же нормально сделано, также сделать и в pages.

**Comment by tabuna** [comment]
@PSalador Погоди, так там одинаково же сделано?

**Comment by Rendol** [comment]
В постах тоже такая ошибка валится...
Проверку на .is(':visible') нужно добавлять.

**Comment by Rendol** [comment]
И ещё момент, языка может быть 2 включено, а заполнять я хочу только один в данный момент времени. Значит проверку надо делать только активной страницы.

**Comment by PSalador** [comment]
> Погоди, так там одинаково же сделано?

В постах можно отключить заполнение одного из языков, в страницах нет.

**Comment by tabuna** [comment]
Если перед отправкой мы будем проверять валидность формы, и если не заполнены поля на каком либо языке, явно сообщать об этом пользователю, например в виде модального окна или `dashboard.alert('Заполните поля на N языке')`, это решит по сути нашу проблему с ошибками в консоли и явно сообщит пользователю, что что то не так?

**Comment by PSalador** [comment]
Думаю, да.

**Comment by tabuna** [comment]
![screenshot-localhost-8000-2018-02-03-01-10-32-178](https://user-images.githubusercontent.com/5102591/35757199-1d814a32-087f-11e8-82b2-be4d429f2f10.png)
