### ISSUE TITLE
Ошибка в отображении комментариев

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#497]
Хочу вывести комментарии к посту как описано в [документации](https://orchid.software/ru/docs/comments#otnosheniya):
`$comments = Comment::findByPostId($post->id);`

но выдает ошибку [здесь](https://github.com/orchidsoftware/platform/blob/master/src/Platform/Core/Models/Comment.php#L53):
`Type error: Return value of Orchid\Platform\Core\Models\Comment::findByPostId() must be an instance of Orchid\Platform\Core\Models\Comment, instance of Illuminate\Database\Eloquent\Collection returned`

Добавил в каталог файл MyComment.php с содержимым:
```
<?php
namespace App\Http\Controllers;
use Orchid\Platform\Core\Models\Comment;
class MyComment extends Comment
{
    public function findByPostIdN($postId)
    {
        return $this->where('post_id', $postId)->get();
    }	
}
```

Вызываю так `$comments = (new MyComment)->findByPostIdN($post->id);`  работает.

**Comment by PSalador** [comment]
В итоге функция в файле MyComment.php вот такая получилась - вывод иерархии комментариев с авторами. Но вроде 2 уровень вложенности комментариев не будет выводить.
```
    public function findByPostIdN($postId)    {
        return $this->
			where('post_id', $postId)->
			where('parent_id', 0)->
			where('approved', 1)->
			with(['replies' => function($query)	{
					$query->where('approved', 1);
				}])->
			with('author')->get();
    }	
```

**Comment by PSalador** [comment]
Теперь чтобы получить только корневые и разрешенные комментарии, использую
`$comments = Comment::findByPostId($post->id)->where('parent_id', 0)->where('approved', 1);`

получить разрешенные дочерние комментарии `$comment->replies->where('approved', 1)`

**Comment by tabuna** [comment]
А почему ты не запишешь сразу в post? Ну то есть в каком то таком виде (Не копируй):

```php
$post = Post::with([
    'comments.replies' => function($query){
       $query->where('approved',1);
    }
])

```

**Comment by PSalador** [comment]
> А почему ты не запишешь сразу в post? 

Мне кажется без разницы в пост будет записан или отдельной переменной во view.

Если спрашиваешь почему не выбрал дочерние. То думаю, что он выберет дочерние только 1 уровня вложенности, а остальные нет.

**Comment by tabuna** [comment]
> Мне кажется без разницы в пост будет записан или отдельной переменной во view.

Так огромная разница, 1 запрос к бд или несколько
