### ISSUE TITLE
In route add prefix, and transform binding

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#500]
In many route add prefix dashboard:

- category.show 
- comment.show 
- menu.store 
- menu.create 
- menu.destroy 
- menu.edit 
- roles.show
- users.show 

Transform binding to slug or id:
- category
- comment
- menu
- role
- user

**Comment by tabuna** [comment]
Убрал эти роуты, так как они не использовались.
У Category и Role установил возможность обращение по slug, остальные Comments/Menu/User в этом не нуждаются, так как у них есть только id и он автоматически применится.
