### ISSUE TITLE
Can't install platform

### ISSUE THREAD

**Issue by hoekie** [orchidsoftware/platform#511]
Hi there!

I'm trying to install the orchid platform on a fresh laravel installation according the installation manual but it gives me the following error.

Can you tell me what went wrong?

Thanks!

composer require orchid/platform
Using version ^2.0 for orchid/platform
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - orchid/platform 2.0 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - orchid/platform 2.0.1 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - orchid/platform 2.0.10 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - orchid/platform 2.0.11 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - orchid/platform 2.0.14 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - orchid/platform 2.0.2 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - orchid/platform 2.0.3 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - orchid/platform 2.0.4 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - orchid/platform 2.0.5 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - orchid/platform 2.0.6 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - orchid/platform 2.0.7 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - orchid/platform 2.0.8 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - orchid/platform 2.0.9 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - Conclusion: don't install laravel/framework 5.5.x-dev
    - Installation request for orchid/platform ^2.0 -> satisfiable by orchid/platform[2.0, 2.0.1, 2.0.10, 2.0.11, 2.0.14, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9].

Installation failed, reverting ./composer.json to its original content.

**Comment by tabuna** [comment]
The new version of Laravel, was released just yesterday.
We have not yet prepared a stable release for him.

Use version 5.5:
```php
composer create-project laravel/laravel orchid  "5.5.*" --prefer-dist
```


_Release for 5.6 is expected in the near future._

**Comment by hoekie** [comment]
Ah, I should have known...
Thanks for your quick response tabuna!
