### ISSUE TITLE
Улучшение документации. Терминология.

### ISSUE THREAD

**Issue by AratKruglik** [orchidsoftware/platform#515]
Что непонятно:
1. Общее назначение.
1.1. Первое, что неясно, что делает платформа, для чего она? Т.е. это не просто админка? Это платформа на которой можно строить общую пользовательскую часть, ведь там есть система виджетов (к примеру) и прочего? Было бы хорошо указать эту информацию в предисловии более простыми идоступными словами, а не очень сложными оборотамибизнес-процессов и логике программиста. Примеры есть чисто по админке...
2. Терминология.
2.1. Безголовый режим. Что это такое? Что имеется ввиду? Лично мне непонятно как и где это использовать. Не хватает примеров.
2.2. Поведения (одиночное и множественное, стандартное). Речь идет о Singleton и Multytone? Не совсем правильно переводить (тем более дословно) уже привычную разработчикам терминологию. Если же я неправильно понял, то совершено непонятно, что имеется ввиду под понятием "поведение". Или как пользоваться ими в публичной части? Непонятно совершенно...
Также в документации использованы в качестве примера совершенно идентичные куски кода.
http://prntscr.com/icix0d

**Comment by Rendol** [comment]
+1 к пункту 2.2. Я сначала думал, что это поведение для поста. В какой-то момент лаже методы пытался вызывать из поведения в виде ```$post->....```. Только потом понял, что это поведение платформы)

**Comment by AratKruglik** [comment]
И вот тут я завис окончательно. Что значит "поведение платформы"? О_о

**Comment by Rendol** [comment]
Для себя я это обозначил как поведение интерфейса платформы))

**Comment by tabuna** [comment]
> 2.1. Безголовый режим. Что это такое? Что имеется ввиду? Лично мне непонятно как и где это использовать. Не хватает примеров.

При активации такого режима, ORCHID не будет регистрировать маршруты в вашем приложении, вам будет необходимо описывать весь требуемый функционал самостоятельно.

**Comment by Nks** [comment]
Добавить документацию к selection.

**Comment by tabuna** [comment]
Удалил почти все рефлексирующие потуги. Оставил самое основное и важное.

1. Изменил описание. Только для backoffice-приложений.
2. Теперь все термины общепринятые.
