### ISSUE TITLE
Возможность менять модель пользователя админки.

### ISSUE THREAD

**Issue by aleksei-budaev** [orchidsoftware/platform#523]
Возможно, я неправильно понял документацию, а возможно просто не знаю каких-то основ, но. 
Получается, нет возможности разделить пользователей на две таблицы - администраторов, и обычных посетителей? 
Если так, то как-то не комильфо хранить их всех в отдельной базе с флагом is_admin. 
Или все-таки возможность есть?

**Comment by aios** [comment]
@aleksei-budaev Для таких целей вообще как бы роли есть...

**Comment by tabuna** [comment]
> Получается, нет возможности разделить пользователей на две таблицы - администраторов, и обычных посетителей?

Можно, но тогда вы должны будете самостоятельно определять права доступа. :shit:

> Если так, то как-то не комильфо хранить их всех в отдельной базе с флагом is_admin.

Никто, не предлагает ничего подобного. :shit:

 > Или все-таки возможность есть?

Существует [MAC](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%BD%D0%B4%D0%B0%D1%82%D0%BD%D0%BE%D0%B5_%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%BE%D0%BC). :thumbsup:



Вы можете создать роль "Администратор" со всеми правами и **наделять пользователей этой ролью** (или явно указывать необходимые права у каждого). 

##### Пример создания роли:
![screenshot-localhost-8000-2018 02 12-01-29-42](https://user-images.githubusercontent.com/5102591/36079490-74915d64-0f94-11e8-8c61-ee4b36dee433.png)

Пользователи могут имеет сколько угодно ролей, при проверки доступа все разрешения будут учитываться.

##### Пример установки прав пользователя и ролей
![screenshot-localhost-8000-2018 02 12-01-30-50](https://user-images.githubusercontent.com/5102591/36079499-96010972-0f94-11e8-921a-fbf972ca476d.png)


**P.S.**
Эта информация есть в [документации](https://orchid.software/ru/docs/access), дайте пожалуйста знать если, что то не понятно.

**Comment by aleksei-budaev** [comment]
@aios @tabuna похоже, что у меня в голове жил старый и недобрый способ решения такой задачи. С Вашей помощью понял как надо, вопросов нет. Спасибо!
