### ISSUE TITLE
Путь к файлу в attachment.

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#525]
В медиафайлах можно легко получить путь к файлу, а в прикрепленных изображениях к постам и страницам нет такой возможности.
Приходится чтобы вставить изображение в редактор переходить в "Медиафайлы" искать там загруженное изображение, копировать путь.

**Comment by tabuna** [comment]
Хм, так "вложения" сделаны, что бы они автоматом крепились к постам.
Для вложения изображений в редактор существует отдельная кнопка

**Comment by tabuna** [comment]
Давай тогда сейчас добавим прямую ссылку в описание файла?

**Comment by PSalador** [comment]
Давай.

**Comment by tabuna** [comment]
Добавил

**Comment by PSalador** [comment]
Отлично!
