### ISSUE TITLE
Ошибки в медиафайлах 

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#526]
1. Нельзя загружать файлы перетаскиванием.
2. При загрузке файл попадает не в текущую папку а в корневую.
3. При загрузке дублирует расширение (.png.png    .jpg.jpg)
4. Превью изображений в иконках перестал показывать. [Поправил](https://github.com/orchidsoftware/platform/pull/522/commits/c4d2a3d8b7f59f818ca44c8b9c8e56aac3df2dfb)

**Comment by tabuna** [comment]
3. Исправил

**Comment by PSalador** [comment]
А почему 2 не ошибка? так же не должно быть.

**Comment by PSalador** [comment]
5. Какой-то косяк при выборе категорий - выбираются не с первого раза и патается открыть ту же что и открыта сейчас. Баг скорее всего после последнего обновления - на демо такого нет.
![orchid4](https://user-images.githubusercontent.com/29531264/36411132-9f5a6e60-1646-11e8-9433-195114c46c69.gif)

**Comment by PSalador** [comment]
6. Слишком узкая правая сторона, что сильно выражается на экранах с маленьким расширением. Например в видео исчезает кнопка "на весь экран". Нужно пошире примерно как в видео из предыдущего пункта 5.
![orchid6](https://user-images.githubusercontent.com/29531264/36411352-cd71b3f2-1647-11e8-82ed-6d7dda70937c.gif)

**Comment by PSalador** [comment]
1. Почему нельзя сделать загрузку как в постах? Сейчас даже не видно ход загрузки.
2. При загрузке файл попадает не в текущую папку а в корневую.
Записал видео из [демки ](https://demo.orchid.software/dashboard/systems/media) 
как эти два пункта расстраивают ожидания пользователей, 
![orchid7](https://user-images.githubusercontent.com/29531264/36411771-c922c8ca-1649-11e8-893b-fc69e9f15eda.gif)

**Comment by PSalador** [comment]
7. При переносе файла можно перенести только в категории которые находятся на этом уровне. Также при переносе иногда переносятся и текущие каталоги.
![orchid9](https://user-images.githubusercontent.com/29531264/36413838-a3288020-1652-11e8-925e-c6dfdfe40d4e.gif)

**Comment by PSalador** [comment]
1. Сделал загрузку перетаскиванием b8ec93faad68acd7742e255873affa411af0d4e4

**Comment by PSalador** [comment]
Из предыдущих пунктов осталось сделать 6 и 7
8. Переделать на stimulus
9. Ужасно смотрится в мобильной версии https://prnt.sc/jref7u   может в мобильной вверху вместо иконок с надписями оставить только надписи и правый сайдбар убрать вниз?
10. Для чего вторая кнопка "Переместить"?

**Comment by tabuna** [comment]
Если не ошибаюсь, один из пользователей прислал PR в `master`, где решил некоторые проблемы, нужно посмотреть.

По поводу мобильной версии, можно сделать в 2 строки (Заголовок/Меню), где меню скролилось как в документации?

![2018-06-06 10-34-33](https://user-images.githubusercontent.com/5102591/41023472-37c3fbe0-6975-11e8-9aff-3ad007fabe0f.png)
