### ISSUE TITLE
А зачем добавляется new?

### ISSUE THREAD

**Issue by agoalofalife** [orchidsoftware/platform#531]
https://github.com/orchidsoftware/platform/blob/7c9231e59605e25afa6ef7723e5f416e3a6d4cd1/src/Platform/Http/Controllers/Systems/RoleController.php#L28

В конструктор нам уже пришел объект, это с какой то особенной целью делается?
Или чего то я не понимаю))

**Comment by tabuna** [comment]
Незачем)) В других классах такого нет.
