### ISSUE TITLE
ошибка >useCurrent();

### ISSUE THREAD

**Issue by ewgenm** [orchidsoftware/platform#533]
Делаю всё по инструкции в документации "Использование экранов"(https://orchid.software/ru/docs/tutorial_profile)

на шаге  где нужно создать миграцию create_table_users_history
artisan ругается на строку
$table->timestamps('created_at')->useCurrent();

 Symfony\Component\Debug\Exception\FatalThrowableError  : Call to a member function useCurrent() on null

### Specifications

   PHP Version => 7.1.7
  - Database Version: MySql 5.7 x64

**Comment by tabuna** [comment]
Попробуйте изменить
```php
$table->timestamps('created_at')->useCurrent();
//на
$table->timestamp('created_at')->useCurrent();
```

**Comment by ewgenm** [comment]
Спасибо, помогло.

**Comment by tabuna** [comment]
Кстати, в документации написано правильно.
