### ISSUE TITLE
Как в поле передать В Input value по умолчанию?

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#540]
В Layout пишу 
```
'type'	=> Field::tag('input')
                ->type('hidden')
                ->name('field.type')
                ->value('myvalue'),	
```
но в input view попадает атрибут ["value"]=> NULL

это ошибка или так задумано?
как передать default value?

**Comment by PSalador** [comment]
Есть Modify атрибут для полей
 то есть можно менять значения, например:
```
->modifyName()
->modifyValue() 
->modifyOptions()
->modifyAnyAttributes()
```

**Comment by Leshkens** [comment]
Покажи пример, как этим атрибутом воспользоваться. А то тоже нужно вставить дефолтное значение и вот что-то с Modify никак не могу разобраться.

**Comment by tabuna** [comment]
Теперь это работает корректно:

```
Field::tag('input')
    ->type('text')
    ->name('name')
    ->max(255)
    ->required()
    ->value('Значение по умолчанию')
    ->title('Name Articles')
    ->help('Article title'),
```

Значение по умолчанию будет только если в пришедших данных будет `null`
