### ISSUE TITLE
Ошибка при выводе списка значений таблицы.

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#541]
В [table.blade.php#L21](https://github.com/orchidsoftware/platform/blob/master/resources/views/container/layouts/table.blade.php#L21) строка
`$datum->getContent($td->name)`
я понимаю это для json, но мне нужно вывести вот так
`$datum->{$td->name}`
как совместить, чтобы и то и то работало?

**Comment by tabuna** [comment]
Можно записывать имена с вложением 'json.array.array.value'. Так же всегда можно воспользоваться функцией замыкания

**Comment by PSalador** [comment]
Можно ссылку, что за функция замыкания?

**Comment by tabuna** [comment]
Пример с явной вложенностью (Через точку):
```php
/**
  * Grid View for post type.
  */
 public function grid()
 {
     return [
         TD::name('cities.capital.name')->title('Город'),
         TD::name('cities.capital.people')->title('Количество жителей'),
     ];
 }
```
cities - json содержащий данные;
capital - объект/массив хранящий название столицы и количество жителей


Пример с функцией замыканией:
```php
         TD::name('cities')->title('Город')
         ->setRender(function($post){
             // return результат обработки
            // Например, $post->getContent('cities.capital.name')
         })
```

`$post` будет содержать всю строку и требуется лишь вернуть данные для отображения

**Comment by tabuna** [comment]
Кстати вы так же можете попробовать dot обращение
