### ISSUE TITLE
Needing Translations for this platform?

### ISSUE THREAD

**Issue by caratzky** [orchidsoftware/platform#544]
Hello,

I am an active Utopian Contributor to open source projects. I translate files into my native tongues, Filipino, Tagalog and Cebuano and am being rewarded well by Utopian. Please tell me if you need translations for easy understanding by people from different nationalities. Once started, Utopian translators will come flooding into this project to contribute high-quality translations to Spanish, Turkish, Chinese, French, etc. 

Waiting to hear from you.

Best Regards,
caratzky

**Comment by PSalador** [comment]
Thank you for your interest in our project.

Our documentation and language files are still in active development.

To translate files into other languages, we need to add task to the [utopian.io](https://utopian.io), I understand correctly?

**Comment by caratzky** [comment]
I don't get you @PSalador . I don't know how to add tasks to utopian.io but we are posting our translations to utopian.io for rewards.

**Comment by tabuna** [comment]
Hey.

The availability of the project is severely limited due to the fact that the main documentation and localization files are written in Russian.
This gives me a strong headache every day.

You will make me happy if you contribute.

**Comment by caratzky** [comment]
You can rely on me, @tabuna , being an experienced Utopian Translator, that all translations to Filipino will be properly made and thoroughly checked by me. That is if you give me the authority. After posting just one translation contribution to Utopian, translators for different languages will surely flood in this repository and give you more headaches (lol), but at least, we're doing our services free of any reward from you.

**Comment by caratzky** [comment]
Should I directly edit the files for my translations and you'll have them merged in a separate branch?

**Comment by tabuna** [comment]
Plz, use a separate branch

**Comment by caratzky** [comment]
Ok @tabuna Thank you.

**Comment by caratzky** [comment]
It's okay @tabuna . It's not a problem, if there are some files in russian that must be translated, I'll have to translate them to English first, then to my native tongue. Trust me, I can restructure well the google-translated phrases to correct english grammatization. Thank you for trusting me with the job. This is a big help to me, so I won't fail your expectations. Just warn me if I'm doing something wrong. Thank you.

**Comment by caratzky** [comment]
@tabuna  I noticed a lot of wrong punctualizations and faulty sentence structuring in the english version of the files in the docs folder. Shall I just leave them as it is?

**Comment by tabuna** [comment]
@caratzky 

English files were made by Google a translator. Most likely he literally translated some phrases and formulations. If you have the opportunity, I would be happy to eliminate it.

**Comment by caratzky** [comment]
Done! Thanks.
