### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by hoekie** [orchidsoftware/platform#561]
Hi,

I have a few questions about the orchid framework:

1. I don't like to edit core files so I want to override the language file en\common.php.
Can you tell me how to do that?
I've tried several ways to do it but it appears that nothing works as expected:

  - The Laravel way: resources\lang\vendor\platform\en\common.php
  - resources\lang\vendor\orchid\en\common.php
  - resources\lang\vendor\orchid\platform\en\common.php
  - resources\lang\vendor\en\common.php
  - resources\lang\en\common.php

2. How can I use a fresh dashboard in my application?
I mean, without any buttons in the menu so I can make my own?
I,ve allready commented out the page and the post classes in the platform config but can't find a way to disable the system button although I still want to use the users and roles functionality.

Maybe its obvious but laravel is pretty new to me...

Thanks in advance...

I really love the approach of Orchid to build a dashboard like that so keep up the good work!

Richard

**Comment by PSalador** [comment]
The answer on first question.
1. You can edit file \vendor\orchid\platform\resources\lang\en\common.php
2. You can copy dir \vendor\orchid\platform\resources\lang\en\ 
to resources\lang\orchid  and replace path in [FoundationServiceProvider.php](https://github.com/orchidsoftware/platform/blob/master/src/Platform/Providers/FoundationServiceProvider.php#L56)
Then call `php artisan vendor: publish --provider = "Orchid\Platform\Providers\FoundationServiceProvider"`

**Comment by hoekie** [comment]
Cool! Thanks @PSalador
