### ISSUE TITLE
Индивидуальные права для записей

### ISSUE THREAD

**Issue by EchoDeveloper** [orchidsoftware/platform#563]
Подскажите, пожалуйста, есть ли в Ochid функционал, позволяющий, например, видеть все записи блога, а редактировать только те, которые создал текущий активный пользователь?
И если есть, приведите пожалуйста пример.

**Comment by tabuna** [comment]
Привет @EchoDeveloper 

Есть несколько вариантов, всё зависит конечно же от того, что ты хочешь получить в действительности.

**Хороший вариант:**
Создать [два экрана](https://orchid.software/ru/docs/tutorial_profile), для вывода списка и редактирования.
В экране редактирования делать проверку `if/gate/access/etc` является ли авторизованный пользователь владельцем этой записи. Если нет, не показывать соответственно эту "кнопку".
Для безопасности, лучше так же проверять это дело в обычном `Request`.

##### Плюсы и минусы
Вам даётся полный контроль над построением, по этому он более гибкий, но требует чуть большего написания программного кода.

**Вариант похуже:**
Использовать [поведения](https://orchid.software/ru/docs/behaviors) и к модели `Post` добавить `observer`, который при сохранении будет проверять, в случаи не соответствия не применять изменения и сообщать об ошибке.

##### Плюсы и минусы
Вы не можете контролировать существующие кнопки/уведомления и т.п.
observer будет применяться к каждой записи, что потребует дополнительной проверки.


---------
Это лишь те, что пришли мне в голову на текущий момент. 
Возможны и другие варианты решения вашей задачи.
