### ISSUE TITLE
Не работает Alert в экранах

### ISSUE THREAD

**Issue by EchoDeveloper** [orchidsoftware/platform#564]
![image](https://user-images.githubusercontent.com/14197283/36484865-a6084b52-172b-11e8-9a61-f9bb62d216bb.png)
А в документации он легко "используется".
![image](https://user-images.githubusercontent.com/14197283/36484818-7ecbfdf4-172b-11e8-8dce-8e2e0a5999f4.png)

**Comment by tabuna** [comment]
@EchoDeveloper 

Alert - это фасад. Пожалуйста укажите пространство имён.


`use Orchid\Platform\Facades\Alert;`

**Comment by tabuna** [comment]
Если вам по каким либо причинам не удобно использовать фасад, существует и функция-помощник:
```php
 alert($message = null, $level = 'info');
```

**Comment by EchoDeveloper** [comment]
@tabuna Спасибо. Я полагаю необходимо в документацию добавить много подобных инструкций.
Например:
`use Orchid\Platform\Screen\Link;
use Orchid\Platform\Screen\Layouts;`
В файлах экранов.

**Comment by el-pixellife** [comment]
v4.7.1
```
Alert::message('Saved!');
return Redirect::home();
```
Не срабатывает с редиректом, работает только если остаемся на том же экране

**Comment by tabuna** [comment]
@el-pixellife 

Ваша проблема ни как не связана с этой темой, пожалуйста в следующий раз создавайте новые.

Попытался воспроизвести вашу проблему и к сожалению не получилось, сделал:

```php
class AlertTestScreen extends Screen
{
   //...
    /**
     * Button commands.
     *
     * @return array
     */
    public function commandBar(): array
    {
        return [
            Link::name('Alert')->method('testAlert'),
        ];
    }

    /**
     * @return \Illuminate\Http\RedirectResponse
     */
    public function testAlert()
    {
        Alert::message('Saved!');
        return Redirect::route('platform.systems.index');
    }

}
```

Уведомление было отображено в настройках. Могу предположить, что при `Redirect::home()` у вас происходит редирект несколько раз и по этому уведомление теряется.

Попробуйте выполнить метод `testAlert` у вас в приложении

**Comment by el-pixellife** [comment]
@tabuna 

> Ваша проблема ни как не связана с этой темой, пожалуйста в следующий раз создавайте новые.
Учту. 

Стоило переавторизоваться в админке, как Alert заработал. 
В коде ничего не трогал
