### ISSUE TITLE
Несколько вопросов

### ISSUE THREAD

**Issue by EchoDeveloper** [orchidsoftware/platform#567]
Вообще не хотелось бы каждый раз сюда писать(стыд), но ссылки на канал slack я не нашел.
Я новичок в этой платформе и всегда хотел бы иметь возможность задать вопрос компетентным разработчикам, надеюсь скинете ссылочку.
Что на данный момент интересует:

1)
![image](https://user-images.githubusercontent.com/14197283/36493682-35b2bf0c-1741-11e8-802e-512ff4773552.png)

При переходе к редактированию браузер остаётся на экране "/dashboard/reviews".

2) Как в query экрана получить данные из url?
![image](https://user-images.githubusercontent.com/14197283/36493364-7b78cd70-1740-11e8-8713-2653e874886f.png)

3) Есть ли простые способы манипуляций с данными в экране? Например, у меня есть таблица отзывов в экране и я хочу добавить пару методов для управления отзывом (удалить, сменить статус), не переходя в экран редактирования самого отзыва, т.е. прямо из ячейки таблицы с помощью кнопки или селекта.
На данный момент я создал контроллер отзывов, срендерил ссылку в таблице и ajax'ом ссылаюсь на url удаления записи. Вроде то, что нужно, а вроде и не эстетично. Надеюсь на ваше терпение <3

**Comment by tabuna** [comment]
> Вообще не хотелось бы каждый раз сюда писать(стыд), но ссылки на канал slack я не нашел.
> Я новичок в этой платформе и всегда хотел бы иметь возможность задать вопрос компетентным разработчикам, надеюсь скинете ссылочку.
> 

Мы стараемся присутствовать во всех социально значимых проектах:
![2018-02-21 20 26 23](https://user-images.githubusercontent.com/5102591/36495179-8299dd2e-1745-11e8-8766-0a47df2e786f.png)
![2018-02-21 20 26 03](https://user-images.githubusercontent.com/5102591/36495180-82c1d608-1745-11e8-992f-4e40ddefff6f.png)

На текущий момент, лучшее https://t.me/orchid_community

------

1. Не очень понимаю, что вы имеете в виду. Не меняется меню?

2. Данные будут переданы в качестве аргумента.
Например, [так](https://github.com/tabuna/Vision-Clinic/blob/master/app/Http/Controllers/Screens/Clinic/Product/ProductEdit.php#L34-L39):
```php
    public function query($product = null) : array
    {
        return [
            'product' => is_null($product) ? new Product() : $product,
        ];
    }
```

3. Мы работаем над этим, на текущий момент лучше использовать `view`, что бы обработка в ячейках не повторялись

**Comment by tabuna** [comment]
Надеюсь, что у вас всё получилось. Я закрою этот issue из-за не активности.
