### ISSUE TITLE
Ошибка в attachment при дублировании

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#570]
Если физически файл был удален в папке storage но осталась запись в БД attachment, то при загрузке такого же файла он его не загружает а ставит ссылку на предыдущий, которого уже нет.

Также файл можно удалить в одном из постов, то он удалится физически, хотя в других постах есть на него ссылки.

**Comment by PSalador** [comment]
Может его вообще физически не удалять, а удалять только  текущую запись в attachment?

**Comment by tabuna** [comment]
Хм, но ведь физически файл будет удалён только тогда, когда не будет ссылок на него.
Скорее всего там есть ошибка и проверка возвращает `true`

**Comment by PSalador** [comment]
Посмотрел в модели - никаких проверок нет.

**Comment by tabuna** [comment]
Значит как раз в этом и касяк. Должна же стоять проверка. (Возможно я её зафиксировал и стёр...)

**Comment by PSalador** [comment]
Я не смог разобраться - вижу где удаляет файл, а где удаляет запись не пойму.

**Comment by tabuna** [comment]
[Удаляет ссылку.](https://github.com/orchidsoftware/platform/blob/master/src/Platform/Core/Models/Attachment.php#L109-L118)
[Удаляет физически файл.](https://github.com/orchidsoftware/platform/blob/master/src/Platform/Core/Models/Attachment.php#L134-L147)

**Comment by PSalador** [comment]
#573

**Comment by tabuna** [comment]
Всё хорошо, только удалять необходимо не по имени, а по хешу.
Я исправил.
