### ISSUE TITLE
Add more columns to Users

### ISSUE THREAD

**Issue by eonlab** [orchidsoftware/platform#579]
Hi,

What is the best way to add new columns to Users table? I was able to move and overwrite the UserBase Behaviour by changing the platform config file but how can I move and overwrite the User Model (Orchid\Platform\Core\Models\User) so I can add the new columns to the $fillable array?

Thanks

**Comment by PSalador** [comment]
Hi.
1. Create new migration file.
 `php artisan make:migration create_fields_for_users`
2. Add new field to table Users 
in path /database/migrations/2018_00_00_000000_create_fields_for_users.php
```
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateFieldsForUsers extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->string('first_name')->nullable();
            $table->string('last_name')->nullable();
            $table->integer('city_id')->nullable();
            $table->string('avatar')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users', function (Blueprint $table) {
            $table->dropColumn('first_name');
            $table->dropColumn('last_name');
            $table->dropColumn('city_id');
            $table->dropColumn('avatar');
        });
    }
}
```

3. Apply migration `php artisan migrate`
4. Update User model in path App\User.php
```
namespace App;

use Orchid\Platform\Core\Models\User as BaseUser;

class User extends BaseUser
{

    /**
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'last_login',
        'avatar',
        'permissions',
        'first_name',
        'last_name',
        'city_id',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function history(){
       return $this->hasMany(History::class);
    }

}
```

**Comment by tabuna** [comment]
This is mistake. I'll add class management in the next update.

**Comment by tabuna** [comment]
@eonlab Now you can create your own form and add it using events. And in the methods use your own user model

**Comment by eonlab** [comment]
@PSalador Thank you!

@tabuna Can you please give a example? I think this might be very useful until the update.

Other thing is: The checkbox field type doesn't seem to work, I had to change it to a select
Field::tag('checkbox')
                ->name('free')
                ->value(1)
                ->title('Free')
                ->placeholder('Event for free')
                ->help('Event for free'),

**Comment by tabuna** [comment]
@eonlab 
Use the form. We have a simple tutorial for [this](https://orchid.software/en/docs/tutorial_phpinfo).
In the form, you can create other methods, save, delete, read. In these methods, use your own model that has the correct fill.
All events are described [here](https://github.com/orchidsoftware/platform/blob/master/src/Platform/Providers/EventServiceProvider.php#L31-L53).
That is, you need to listen to `Orchid\Platform\Events\Systems\UserEvent`

**Comment by eonlab** [comment]
Is there a repository of the demo website? I'm having some difficulties with the Screens and Layouts and the docs are not working for me.

Thank You.

**Comment by tabuna** [comment]
Oh sure.

Example [screen](https://github.com/tabuna/tutorial_create_profile_for_orchid) usage.
Example of creating a [blog](https://github.com/tabuna/SimpleBlogOrchid).

In the coming days there will be a more complete and professional translation of the documentation in English with examples.


If you need more example, just say.
I will do it.

**Comment by eonlab** [comment]
Thanks @tabuna ! That helped! I followed your advice and used a form - UserContactsForm.php - to have extra fields in the Users table. I've setup the event and a new tab shows up in the user's edit page but I get this error when I try to use my own User model:

Type error: Argument 1 passed to App\Http\Forms\UserContactsForm::get() must be an instance of App\User or null,

If I change it to the original one: Orchid\Platform\Core\Models\User It works.
The user model used App\User extends Orchid\Platform\Core\Models\User
What am I missing here?

I think this would be also a very useful example/tutorial

Thanks.

**Comment by tabuna** [comment]
@eonlab 

You did everything right.
In order to avoid asking the same data in each form, we do it in advance and pass it to those already prepared. So if you need another model, you need to declare it explicitly.

```php
    /**
     * @param \Orchid\Platform\Core\Models\User $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function get(\Orchid\Platform\Core\Models\User $user)
    {
        $user = \App\User::find($user->id);
    }
```

I regret. In the future, one can come up with a reflection that such a substitution should be less obvious

**Comment by eonlab** [comment]
Great, it worked!
How to change the order the tabs show? The one I've created from UserContactsForm.php now shows first. Can the order be changed?

On the grids, how can we change the way the data is displayed. For instance: if we want to add a column for the user avatar. How to get the data from the database and change it the way it will display the image.

**Comment by eonlab** [comment]
@tabuna Adding more fields to the users table is not working 100% using your suggestion. When I try to add or edit a user the extra fields are not saved to the database, the Orchid\Platform\Http\Controllers\Systems\UserController still uses this model Orchid\Platform\Core\Models\User. To test it I've changed it to App\User and it saved the extra fields when edit a user but it doesn't save when adding a new user.

**Comment by tabuna** [comment]
Hi, I hope you succeeded and you are interested.
In the version for the developer, this problem was fixed.
