### ISSUE TITLE
Method Illuminate\Database\Query\Builder::hasAccess 

### ISSUE THREAD

**Issue by vrtc** [orchidsoftware/platform#615]
### Expected Behavior

Method Illuminate\Database\Query\Builder::hasAccess 

### Steps to Reproduce the Problem

  1. После установки, пытаюсь войти созданным юзером

### Specifications

  - ORCHID Version: latest
  - Laravel Version: 5.6
  - PHP Version: 7.2.3
  - Database Version: percona 5.7

**Comment by tabuna** [comment]
Почему этот issue был закрыт? У вас всё хорошо? Возможно вы не унаследовали [пользователя](https://orchid.software/ru/docs/installation#model-polzovatelya)

## Модель пользователя

Платформа поставляется с готовым набором функций пользователя, например, разграничение прав доступа, по этому
необходимо унаследовать базовую модель в `App\Users`:

```php
namespace App;

use Orchid\Platform\Core\Models\User as BaseUser;

class User extends BaseUser
{

}

```

Для создания пользователя с максимальными правами на текущий момент, необходимо выполнить команду передав
имя пользователя, электронный адрес и пароль:
```php
php artisan make:admin admin admin@admin.com password
```
