### ISSUE TITLE
Фильтрация и сортировка

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#621]
**Автоматическая HTTP фильтрация и сортировка:**

Подключаем трейт к модели и разрешаем глобальные параметры, которые может установить клиент. 

Например :
```php
use FilterTrait;


/**
 * @var
 */
protected $allowedFilters = [
    'id',
    'user_id',
    'type',
    'status',
    'content',
    'options',
    'slug',
    'publish_at',
    'created_at',
    'deleted_at',
];

/**
 * @var
 */
protected $allowedSorts = [
    'id',
    'user_id',
    'type',
    'status',
    'slug',
    'publish_at',
    'created_at',
    'deleted_at',
];

/**
 * @var
 */
protected $allowedIncludes = [
    'comments',
    'author'
];

```

Использование:

```php
Post::filters()->defaultSort('id')->paginate();
```

Как будет реагировать фильтрация:

```php
http://example.com/demo?filter[id]=1
$model->where('id','=',1)


http://example.com/demo?filter[id]=1,2,3,4,5
$model->whereIn('id',[1,2,3,4,5]);


http://example.com/demo?filter[content.ru.name]=dwqdwq
$model->where('content->ru->name','=','dwqdwq');

```

Как будет реагировать сортировка:

```php
http://example.com/demo?sort=content.ru.name
$model->orderBy('content.ru.name','asc');

http://example.com/demo?sort=-content.ru.name
$model->orderBy('content.ru.name','desc');
```

Как будет реагировать жадная загрузка:

```php
http://example.com/demo?include=comments,author
$model->with(['comments','author'])
```

--------

Вопросы:

1. Как лучше всего сделать параметры фильтрации, например, если необходимы условия с дистанцией (Даты), или поиск `Like` или простые `>`,`<`;
2. Как указывать фильтры, сортировки и т.п. для вложений? Их ограничений и т.п.

**Comment by tabuna** [comment]
![ezgif-1-7830e9bb35](https://user-images.githubusercontent.com/5102591/37978988-152bd16e-31f0-11e8-875a-436bce2e0a93.gif)

**Comment by tabuna** [comment]
Думаю нет нужны реализовывать возможность `with`, так как не вижу для неё возможности в графическом интерфейсе.

**Comment by tabuna** [comment]
Фильтр на `where и whereIn` работает

`whereIn` достигается разделением записью параметров через зяпятую

![2018-03-29 00 33 43](https://user-images.githubusercontent.com/5102591/38057681-e0bb3420-32e8-11e8-9aa3-015b882d7771.png)

**Comment by tabuna** [comment]
**Приблизительный интерфейс:**

![2018-03-29 01 00 49](https://user-images.githubusercontent.com/5102591/38058763-acb792a0-32ec-11e8-947f-76e49ff32ce2.png)
![2018-03-29 01 00 34](https://user-images.githubusercontent.com/5102591/38058764-acd79f96-32ec-11e8-9985-746df8625b62.png)
![2018-03-29 01 00 22](https://user-images.githubusercontent.com/5102591/38058765-acf6b296-32ec-11e8-8291-d473e2354e22.png)

**Comment by PSalador** [comment]
Я не знаю что добавить, всё грамотно.
Что приходит на ум, чисто визуально:

1. У даты возможность выбора промежутка между определенными датами.
2. В фильтрах также возможность интервала.
3. Там где выбор (равно, больше, меньше) сделать селектом.
