### ISSUE TITLE
Easy installation

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#622]
## Currently the installation looks like this

Firstly, download the Laravel installer using Composer:
```php
$ composer require orchid/platform
```

Extend your user model using the `Orchid\Core\Models\User as BaseUser` alias:

```php
namespace App;

use Orchid\Platform\Core\Models\User as BaseUser;

class User extends BaseUser
{

}

```

Publish ORCHID's vendor files

```php
php artisan vendor:publish --provider="Orchid\Platform\Providers\FoundationServiceProvider"
php artisan vendor:publish --all
```

Run your database migration
```php
php artisan migrate
```

Make available css/js/etc files
```php
php artisan storage:link
php artisan orchid:link
```

Create your admin user
```php
php artisan make:admin admin admin@admin.com password
```

Run server
```php
php artisan serve
```

# Make the majority of operations in one command

Firstly, download the Laravel installer using Composer:
```php
$ composer require orchid/platform
```

Install package

```php
php artisan orchid:install
```

Create your admin user
```php
php artisan make:admin admin admin@admin.com password
```

Run server
```php
php artisan serve
```

---------
Automatic execution of the following commands:

1. Publish files
1. Applying Migrations
1. Creating links
1. User model inheritance
1. Adding links to ignoring

![2018-04-04 12-27-16](https://user-images.githubusercontent.com/5102591/38299803-da17a336-3803-11e8-9b5a-5e5ab9192803.png)

**Comment by tabuna** [comment]
Добавил диалог создания нового пользователя сразу после установки

**Comment by tabuna** [comment]
Добавить диалог, спрашивающий на каком домене и с каким префиксом устанавливать. (Простая запись в конец .env файл)

по умолчанию:
- localhost
- dashboard

**Comment by PSalador** [comment]
В [инсталлере](https://github.com/orchidcommunity/Installer/blob/master/install_orchid) диалог спрашивающий префикс DASHBOARD_PREFIX
Также делал диалог спрашивающий какой язык [Orchid поставить по умолчанию.](https://github.com/orchidcommunity/Installer/blob/master/install_orchid#L180)

**Comment by tabuna** [comment]
Да это почти тоже самое.

Вот только с языком проблематично, так как он указывается в виде массива

**Comment by tabuna** [comment]
Добавил `DASHBOARD_PREFIX` и `DASHBOARD_DOMAIN`, необходимо добавить форматирование

**Comment by tabuna** [comment]
Проверил, вроде всё ок.

**Comment by PSalador** [comment]
Проверил - работает.
Только в  DASHBOARD_DOMAIN нужно помощь написать что вводить в виде sitename.ru без http://

**Comment by tabuna** [comment]
Может самим обрезать HTTP так ещё проще для пользователя будет

**Comment by PSalador** [comment]
Да скорее всего так лучше.
Ещё установка так получается:
```
composer create-project laravel/laravel orchid "5.6.*" --prefer-dist
composer require orchid/platform:"dev-develop"
php artisan orchid:install
```
