### ISSUE TITLE
Method getContent does not exist.

### ISSUE THREAD

**Issue by eonlab** [orchidsoftware/platform#624]
Using this as described at the documentation:

// Only related categories and posts
$category = Taxonomy::where('taxonomy', 'category')->with('posts')->get();
$category->each(function($category) {
    echo $category->getContent('name');
});

It gives this error:
Method Illuminate\Database\Query\Builder::getContent does not exist.

**Comment by eonlab** [comment]
It seems the Multilanguage Trait is not added to the Taxonomy model:

namespace Orchid\Platform\Core\Models;
use Orchid\Platform\Core\Traits\MultiLanguage;
class Taxonomy extends Model
{
  use MultiLanguage;
}

and it should be:
echo $category->term->getContent('name');

**Comment by tabuna** [comment]
I, there really is an error. Taxonometry does not have a field for localization. 
It is necessary to use the term

```php
$category = Taxonomy::where('taxonomy', 'category')->with('posts')->get();

$category->each(function($category) {
    echo $category->term->getContent('name');
});
```
