### ISSUE TITLE
Замена vue на stimulus

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#628]
Необходимо заменить vue, потому, что такого типа фрейморки, Angular, Vue, React, нацелены на превращения json в DOM элементы, в тоже самое время DOM у нас строиться стандартными средствами blade.

Нужно не только провести замену, но и привести весь js в порядок на использование современных функций и стандартов.

**Comment by PSalador** [comment]
- [x] 1. Переделать поле upload (attachment.js) - в основном сделано #639
- [ ] 2. Переделать медиафайлы (filemanager.js) 
- [ ] 3. Переделать создание меню (menu.js)
