### ISSUE TITLE
Изменить позиционирование Behavior

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#632]
Поведения в глазах людей сильно пересекаются с другими понятиями из шаблонов проектирования или реализаций из Yii, возможно стоит переименовать их?

Возможно больше подойдёт вида 1С - "Справочники/References" ?
Любые предложения по этому поводу.

**Comment by PSalador** [comment]
Тоже Behavior вначале путало, но References тоже не нативно.
Может что-нибудь от слова, основа - basis, base, ground.

**Comment by tabuna** [comment]
Если честно, я не уверен как это назвать, ещё с учётом того, что это должно быть и Single и Many.
Будет очень стрёмно если классы будут отличаться только окончанием `s`. 

Можно посмотреть как названо в других сферах.

**Comment by Malezha** [comment]
А как на счет сущности (entity) - SingleEntity, ManyEntity? Текущие поведения по сути конструктор сущности и можно отталкиваться от этого понятия.
