### ISSUE TITLE
Разделение функционала на пакеты

### ISSUE THREAD

**Issue by Malezha** [orchidsoftware/platform#634]
Как на счет разделить в отдельные пакеты некоторый функционал? Заодно перенести зависимости на интерфейсы.

Пакет Platform (Core):

* Экраны
* Формы
* Виджеты

Пакет Auth, зависит от Platform (Core):

* Пользователь и роли
* Функционал разрешений

Пакет CMS зависит от Auth:

* Поведение
* Категории
* Меню
* Теги
* Комментарии

Пакет Notification зависит от Auth:

* Уведомления

Основная причина - не всегда нужны компоненты CMS, а нужен только конструктор админки. Сейчас такой функционал предлагается отключать через разрешения, но это не всегда удобно, да и хочется иметь возможность наследовать и переоределять некоторые возможности.

**Comment by Malezha** [comment]
Это предложение к ветке 3.0 
@tabuna поставь пожалуйста метки.

**Comment by tabuna** [comment]
@Malezha Можешь пожалуйста пояснить плюсы такого разделения? У нас уже был такой опыт, что все пакеты были разделены, но отдельно ни когда не использовались в отдельных проектах как самостоятельная часть. 

> Основная причина - не всегда нужны компоненты CMS, а нужен только конструктор админки.

Какое негативное влияние ты испытываешь? Можно попробовать просто разделить на несколько сервис провайдеров и отключать/подключать. 

**Например**, если ты в `laravel` не используешь отправку электронных сообщений, то можно отключить : `Illuminate\Mail\MailServiceProvider::class,`.

Возможно нам стоит поступить так же? или аналогичным образом.

По умолчанию ставить всё из коробки, если разработчику не нужно это, то он указывает только нужные провайдеры в `config/app.php`

**Comment by tabuna** [comment]
Я тебя понял, давай найдём оптимально хорошее решение.

> Например мне не нужен конструктор меню, я отключаю к нему доступ для всех. Делаю проект, передаю к заказчику, а он потом хочет настроить роли менеджерам и видит что тут есть что то "лишнее" и задает вопрос как это убрать. 

Даже после деления на пакеты, такая проблематика может остаться, например я подключаю управление контетом делаю проект, но задействованы не все возможности, например комментарии, получается, что их не как и не удалить даже в такой реализации.

**Comment by Malezha** [comment]
> Даже после деления на пакеты, такая проблематика может остаться

Пакетами просто удобно разделять на разные независимые части, основная цель - возможность включать и отключать разные компоненты. Очень желательно сделать это, не переписывая все заново.

В качестве примера - система разрешений. Она есть, она уже жестко прибита к платформе. Но давайте отдадим её реализацию на выбор пользователя. По умолчанию, в пакете core (я так буду называть пакет с основным кодом, с помощью которого строится интерфейс админки) используется реализация проверки разрешений, которая всегда отдает положительный результат, таким образом можно "отключить" проверку прав вообще. Так же в комплекте поставляется реализация на основе [политик](https://laravel.com/docs/5.6/authorization#creating-policies). Переключиться мы можем в конфиге на выбранную реализацию. Пакет auth поставляет свою реализацию, которая основана на ролях. Стандартный пакет platform (так я дальше буду называть пакет, который включает в себя полный набор всех возможностей и сконфигурирован правильным образом) зависит от auth и в конфиге по умолчанию включает его реализацию. Итого, главное написать контракт менеджера разрешений и дать возможность его переопределять через конфиг.

В общем, я могу подробнее написать с примерами что и куда можно попробовать разделить, накидать интерфейсы, но тут уже нужна консультация с тобой.

**Comment by Malezha** [comment]
Набросал быстренько конфиг, как я его вижу.

```php
<?php

return [

    /* ... */

    /**
     * You can change used permission manager.
     *  - Orchid\Core\Authorization\AllwayTrue::class - always retrun true
     *  - Orchid\Core\Authorization\PolicyManager::class - use Laravel Policy system
     *
     * Other manager what implements Orchid\Core\Authorization\PermissionManagerContract::class
     */
    'permission_manager' => Orchid\Core\Authorization\AllwayTrue::class,

    /**
     * Components service provires witch used Orchid
     */
    'components' => [
        /** Auth package */
        Orchid\Auth\ServiceProvider::class, // Base auth package service provider.

        /** CMS package */
        Orchid\CMS\ServiceProvider::class, // Base cms package service provider. Initialize behaviors
        Orchid\CMS\Component\Category\ServiceProvider::class,
        Orchid\CMS\Component\Tags\ServiceProvider::class,
        Orchid\CMS\Component\Menu\ServiceProvider::class,

        /** Platform package */
        Orchid\Platform\ServiceProvider::class, // Configure platform
        Orchid\Platform\Component\System\ServiceProvider::class, // Issue #628 dashboard
    ],


    /* ... */

    /**
     * All components merge default package config with curent
     */
    'auth' => [ // Override default auth package config
        'user' => App\User::class, // Must implements Orchid\Auth\Contracts\User::class,

        'use_roles' => false, // Disable roles
    ],

    'cms' => [
        'single_behavior' => [ // Default [Orchid\CMS\Behavior\DemoSingle::class,]
            App/Behavior/About::class,
            App/Behavior/Contacts::class,
        ], 

        'many_behavior' => [ // Default [Orchid\CMS\Behavior\DemoMany::class,]
            App/Behavior/Posts::class,
        ], 
    ],
];
```

**Comment by PSalador** [comment]
Я бы просто убрал ненужные пункты в [MenuComposer.php
](https://github.com/orchidsoftware/platform/blob/master/src/Platform/Http/Composers/MenuComposer.php)

**Comment by Malezha** [comment]
>Я бы просто убрал ненужные пункты в MenuComposer.php

Не решает проблемы дефолтных пермишенов, да и каком образом убрать то можно, [методов не хватает](https://github.com/orchidsoftware/platform/blob/master/src/Platform/Menu/Menu.php).

**Comment by tabuna** [comment]
Начнём, добавил возможность удаления пермишена по `slug` (Вне зависимости когда он был зарегистрирован).

Пример использования:

```
$dashboard->removePermission('dashboard.systems.media')
```

Удаление происходит только при первоначальной настройки, если пользователь обладал этими правами до "удаления", то он и дальше продолжит обладать им.

**Comment by tabuna** [comment]
@Malezha 

- Alert
- Auth
- Platform
- Press
- Setting
- Support
- Widget

**Comment by tabuna** [comment]
**Пакет был разбит, на 2 сущности Platform и Press.**

```json
  "extra": {
    "laravel": {
      "providers": [
        "Orchid\\Platform\\Providers\\FoundationServiceProvider",
        "Orchid\\Press\\Providers\\PressServiceProvider"
      ],
      "aliases": {
        "Dashboard": "Orchid\\Support\\Facades\\Dashboard",
        "Alert": "Orchid\\Support\\Facades\\Alert",
        "Setting": "Orchid\\Support\\Facades\\Setting"
      }
    }
  },
```


`Press` может быть отключён, тогда в приложении не будет, ни миграции, ни меню, ни роутов и т.п. 

----
Если у кого нибудь есть желание, пожалуйста дайте мне знать об этом.
