### ISSUE TITLE
HTML editor is gone from backend

### ISSUE THREAD

**Issue by BOBPG** [orchidsoftware/platform#635]
### Expected Behavior
HTML editor like in the privious version

### Actual Behavior
It's gone

### Specifications
Please add the HTML editor again

**Comment by tabuna** [comment]
![2018-08-07 02 09 38](https://user-images.githubusercontent.com/5102591/43745361-f73e3b24-99e6-11e8-8200-7a42a5e1d233.png)

#### Added a more lightweight [editor](https://kazzkiq.github.io/CodeFlask/):

The syntax has been saved and new methods have been added

-------------
I'm sorry that I did not react so long, it's still in development
