### ISSUE TITLE
File explorer bug

### ISSUE THREAD

**Issue by angay9** [orchidsoftware/platform#637]
@tabuna 
I am having a problem with file explorer.
Here is my folder structure: **2018/04/17**, **2018/04/18**.
When I click on 2018 for the first time and then click on 04 folder, nothing shows up - the folder looks empty.
![orchid_1](https://user-images.githubusercontent.com/7267075/39033732-c5f4bd40-4473-11e8-91cb-9d33abb59e42.png)

![orchid_2](https://user-images.githubusercontent.com/7267075/39033743-d031dda6-4473-11e8-8660-599680042df4.png)

Also, in the breadcrumbs I am getting **2018/2018** path.
![orchid_3](https://user-images.githubusercontent.com/7267075/39033845-53f0b1a8-4474-11e8-9e94-18e24e98a900.png)

But then, If I click on **2018**, then I see **04** and then open **04** folder, I see my files.
![orchid_4](https://user-images.githubusercontent.com/7267075/39033914-9ffea8de-4474-11e8-8b5b-accec71bcd40.png)

![orchid_5](https://user-images.githubusercontent.com/7267075/39033941-c0671a16-4474-11e8-80a7-af387165e540.png)

**Comment by tabuna** [comment]
Hello, thanks for taking the time to write about this.We are working on a fix
