### ISSUE TITLE
Feature Request: More complex List field

### ISSUE THREAD

**Issue by angay9** [orchidsoftware/platform#638]
As of now, orchid has this List field, that allows to dynamically add/remove items.
But it only allows for simple <input> fields,
is it possible to have the List field configurable so that it can render no only <input> fields, but also like <textarea> or <input type="file"> or other fields?
Thanks

@tabuna

**Comment by tabuna** [comment]
hi @angay9 

The best solution is to create an independently suitable field for you.
It's just `view`.

_platform/resources/views/fields/input.blade.php_ ([master](https://github.com/orchidsoftware/platform/blob/master/src/Platform/Fields/Types/InputField.php))

```php
<div class="form-group{{ $errors->has($oldName) ? ' has-error' : '' }}">
    @if(isset($title))
        <label for="{{$id}}">{{$title}}</label>
    @endif
    <input @include('dashboard::partials.fields.attributes', ['attributes' => $attributes]) data-mask="{{$mask or ''}}">
    @if(isset($help))
        <p class="form-text text-muted">{{$help}}</p>
    @endif
</div>
@include('dashboard::partials.fields.hr', ['show' => $hr ?? true])
```

_platform/resources/views/fields/input.blade.php_ ([dev](https://github.com/orchidsoftware/platform/blob/develop/src/Platform/Fields/Types/InputField.php))

```php
@component('dashboard::partials.fields.group',get_defined_vars())
    <input @include('dashboard::partials.fields.attributes', ['attributes' => $attributes]) data-mask="{{$mask or ''}}">
@endcomponent
```

And [register](https://github.com/orchidsoftware/platform/blob/develop/config/platform.php#L112-L126) it in the configuration. It's not difficult and will give you the opportunity to create flexible things, such as a route map, lists and other things.


I will only include the base fields, so it's likely that I'll do it myself small

**Comment by PSalador** [comment]
#685
