### ISSUE TITLE
No tags table causes 500 error

### ISSUE THREAD

**Issue by angay9** [orchidsoftware/platform#640]
I am trying to use the tags for my Post behavior (using the default form BasePostForm that Orchid is using), but I am getting an error that tags table does not exist. 
There is no migration for the tags table as well provided by Orchid.

Should I add the table myself?

@tabuna

**Comment by tabuna** [comment]
Tags are provided by a third-party package, so you need to export them as well.
It is recommended to use the following commands:

```php
php artisan vendor:publish --all
```

Run your database migration

```
php artisan migrate
```

**Comment by angay9** [comment]
Ok, I figured it out.
Had to publish the migration for tags from the `Cartalyst\Tags\TagsServiceProvider` and migrate the db again.

**Comment by tabuna** [comment]
As soon as # 622 is closed
No such problems should be experienced by anyone
