### ISSUE TITLE
php artisan migrate is not working

### ISSUE THREAD

**Issue by saeedvaziry** [orchidsoftware/platform#643]
$ php artisan migrate

	   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null' at line 1 (SQL: alter table `users` add `last_login` timestamp null, add `permissions` json null)

	  at C:\xampp\htdocs\projects\opp-admin\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
	    660|         // If an exception occurs when attempting to run a query, we'll format the error
	    661|         // message to include the bindings with SQL, which will make this exception a
	    662|         // lot more helpful to the developer instead of just the database's errors.
	    663|         catch (Exception $e) {
	  > 664|             throw new QueryException(
	    665|                 $query, $this->prepareBindings($bindings), $e
	    666|             );
	    667|         }
	    668|

	  Exception trace:

	  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null' at line 1")
	      C:\xampp\htdocs\projects\opp-admin\vendor\laravel\framework\src\Illuminate\Database\Connection.php:452

	  2   PDO::prepare("alter table `users` add `last_login` timestamp null, add `permissions` json null")
	      C:\xampp\htdocs\projects\opp-admin\vendor\laravel\framework\src\Illuminate\Database\Connection.php:452

	  Please use the argument -v to see more details.

**Comment by tabuna** [comment]
Hi, I'm sorry that you ran into this. The reason for such errors is the implementation of json in [maria db](https://github.com/laravel/framework/issues?utf8=%E2%9C%93&q=MariaDB+JSON+). You can change your software or try to use an additional package that introduces the possibility of [using](https://github.com/ybr-nx/laravel-mariadb)
