### ISSUE TITLE
Issue with custom Post class and tags

### ISSUE THREAD

**Issue by angay9** [orchidsoftware/platform#644]
In my application I created a new Post model which inherit's orchid's `Orchid\Platform\Core\Models\Post` class.
The problem is that when I add tags to my post in admin panel, inside the tagged and tags tables the `taggable_type` is set to `Orchid\Platform\Core\Models\Post`, but in my view I use my custom `App\Post` model and therefore when I use 
```
$post->tags()
```
it doesn't return me a list of tags.

Is there a way to make orchid use my custom Post class internally when saving the tags to the database without having to overwrite a lot of code?
Thanks

**Comment by tabuna** [comment]
Hack:
```
class Post extends BasePost
{
    /**
     * @return string
     */
    public function get_called_class()
    {
        return get_parent_class($this);
    }

``

**Comment by angay9** [comment]
Hmm.. it didn't work for me

**Comment by tabuna** [comment]
@angay9  Sorry for the long answer.

We have several solutions, they are all based on changing classes and require PR.


**Simple config**
This example is described in #417 

**Old Spark**
[Example](https://github.com/daem0ndev/laravel-spark/blob/master/app/Spark.php#L212-L216) 

```php
$this->many(Spark::model('user','Default vendor class'))
```


**New Spark**
[docs](https://spark.laravel.com/docs/6.0/customization)
```php
Spark::useUserModel('Namespace\User');

Spark::useTeamModel('Namespace\Team');

Spark::swap('UserRepository@current', function () {
    // Return the current user...
});

```


Do you have the opportunity to do this?

**Comment by angay9** [comment]
@tabuna 
Thanks for your response.
How am I supposed to use it?

```
Dashboard::useModel('post', App\Post::class);
```
?

**Comment by tabuna** [comment]
This [functionality](https://github.com/orchidsoftware/platform/blob/develop/tests/Unit/DashboardTest.php) refers to the branches of the [developer](https://github.com/orchidsoftware/platform/tree/develop)

_Changing the class to your own:_

```php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Orchid\Platform\Dashboard;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Dashboard::useModel(\Orchid\Platform\Models\User::class,\App\User::class);
    }
}
```

_Mass substitution of classes_

```php
Dashboard::configure([
    'models' => [
       \Orchid\Platform\Models\User::class => \App\User::class
       \Orchid\Press\Models\Post::class    => \App\Post::class
    ],
]);
```


*Substitution classes must be inherited

**Comment by angay9** [comment]
Is there somehting else I need to do, because earlier I had my `App\Behaviours\Many\Post` registered inside `config/platform.php`, but when I update to develop branch the Post behaviours don't show up in dashboard, I can't edit/view them.
Any suggestions?

Is it possible that this commit (https://github.com/orchidsoftware/platform/commit/c90cf99272eff352e433cb1d4f0289b4d5c46c90) - get's merged into `2.*` version?
