### ISSUE TITLE
Возможность получения экрана из ajax запроса.

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#646]
Нужна возможность получения формы экрана из ajax запроса. Те компиляция формы экрана без левого меню и шапки.

**Comment by PSalador** [comment]
Скорее всего уже неактуально, так как нужно было для того чтобы открывать экран в модальном окне, а эта функция реализована.

**Comment by tabuna** [comment]
> Скорее всего уже неактуально, так как нужно было для того чтобы открывать экран в модальном окне, а эта функция реализована.

В действительности, всё актуально, но нет смысла делать это прямо сейчас, это более глобальная задача, что бы любой Layout можно было получать асинхронно, то, что написано сейчас - костыль, оставленный для примера и на будущее, что бы сохранить совместимость, с тем, что уже было в dev ветки.
