### ISSUE TITLE
Ошибочное поведение Roles?

### ISSUE THREAD

**Issue by aizhar777** [orchidsoftware/platform#647]
`$role->getUsers(); ` возвращает коллекцию классов `Orchid\Platform\Core\Models\User` тогда не получается использовать методы класса App\User

"orchid/platform": "^2.2"

**Comment by tabuna** [comment]
Это не является ошибкой, но явно требует внимания. Пакет не знает, что существуют отдельные классы созданные пользователем, по этому всегда отдаёт только свои собственные. Описание можно найти в #644. То есть должен быть создан механизм подмены классов, которого на текущий момент нет.

Если необходимо решить только проблему, что описана выше, требуется унаследовать `Role` и изменить связь.

**Comment by aizhar777** [comment]
Да я так и сделал ))), может в будущем добавить в конфиг platform.php стручку которая будет показывать пакету какой класс использовать?
В любом случае благодарю за такой удобный пакет))
