### ISSUE TITLE
Нужны примеры 

### ISSUE THREAD

**Issue by aleksandrguru** [orchidsoftware/platform#648]
В сети нет информация , документация лично мне не очень понятна , проще было разобраться с другими системами , поставил все что есть на гитхабе. Один пример по созданию блога и то я так понял он устарел.

**Comment by tabuna** [comment]
Здравствуй Александр, спасибо, что нашёл время и написал об этом.

На текущий момент у нас есть 3 пошаговых примера с исходным кодом:
- [Создание блога](https://orchid.software/ru/docs/tutorial_blog)
- [Расширение формы](https://orchid.software/ru/docs/tutorial_phpinfo)
- [Создание экрана](https://orchid.software/ru/docs/tutorial_profile)

Каждый периодически обновляется, что позволяет сохранять актуальность.

Можете привести примеры "других", что бы проще сориентироваться? Так же если у вас есть какие то конкретные вопросы/недопонимания, не стесняйтесь задавать их.

**Comment by aleksandrguru** [comment]
Да я тоже по примеру , блога пытался что то сделать в итоге не вышло , документацию читал но так и не понял чем лучше такой подход. Документация и примеры написаны какими то отрывками.

**Comment by codemistake** [comment]
Соглашусь с ребятами выше, найти инфу по DTO проще и она понятнее, чем документация к ORCHID

**Comment by adxin** [comment]
> На текущий момент у нас есть 3 пошаговых примера с исходным кодом:
> Создание блога
> Расширение формы
> Создание экрана
Ссылки на примеры не работают, может подскажет кто нибудь рабочие линки?

**Comment by d1moncom** [comment]
Тоже согласен. Читаю документацию, все вроде классно, но как реально с этим работать, с какого боку подойти, не знаю. Счтитю, что хорошим помощником было бы видео. Не надо ничего писать, это наверняка больше потребует времени. А просто сесть и записать скринкаст, как создать тот же блог, по типу вордпресс. Автор зная все особенности продукта на это затратит наверно час или два, а зато пользы развитию проекта сколько!

**Comment by tabuna** [comment]
> Ссылки на примеры не работают, может подскажет кто нибудь рабочие линки?

При установки вы уже имеете большинство реальных примеров использования.
Например, две сущности с множественными и единичным поведением, простой экран и определение многих функций. По мимо этого, всё что находиться в директории `app/Orchid` является как готовым решением, так и примерами, которые вы можете изменять, расширять или удалять.

**Comment by tabuna** [comment]
Добавил раздел "Быстрый старт". Большего сейчас ожидать не стоит.
