### ISSUE TITLE
Js issue when editing post

### ISSUE THREAD

**Issue by angay9** [orchidsoftware/platform#649]
Sometimes or even most times when I go to edit a post, the inputs for tags and categories don't get initialized. If I open it for a second time, then it starts working. 
This happens almost all the time

![image](https://user-images.githubusercontent.com/7267075/39795634-b4dbb81e-5351-11e8-8914-8f8889221309.png)

@tabuna

**Comment by tabuna** [comment]
This is due to the use of the [debug package](https://github.com/barryvdh/laravel-debugbar).
It interferes with the operation of the page.

You can disable its use specifically in the admin panel by writing a condition in the service provider. Or use an alternative, for example, I like [clockwork](https://github.com/itsgoingd/clockwork)

**Comment by angay9** [comment]
@tabuna 
thanks.
Could you tell me more about how can I disable it in the service provider?
Thanks

**Comment by angay9** [comment]
I was able to resolve it by using ` app('debugbar')->disable();` in my `AppServiceProvider`.

Thanks

**Comment by tabuna** [comment]
I wanted to say that you can disable it only for the administration section. You can add this as in the service provider / composer (globally), or by [adding](https://github.com/orchidsoftware/platform/blob/master/config/platform.php#L52) to [Middleware](https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php#L29-L44):


Example:
```php
namespace App\Http\Middleware;

use Closure;

class DisableDebugPackageMiddleware
{
    public function handle($request, Closure $next)
    {
        app('debugbar')->disable();

        return $next($request);
    }
}
```

Added groups in `Kernel.php`
```php
    protected $middlewareGroups = [
       'myRules' => [ 
           \App\Http\Middleware\DisableDebugPackageMiddleware::class,
        ],
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
        'api' => [
            'throttle:60,1',
            'bindings',
        ],
    ];
```

Added `platform` config:
```php
    'middleware' => [
        'public'  => ['web'],
        'private' => ['web', 'dashboard', 'myRules'],
    ],
```


This should be a good solution
