### ISSUE TITLE
Дублируются пункты меню.

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#650]
При добавлении нового пункта меню все предыдущие также дублируются в базе данных.
Когда создаешь все норм, но потом когда опять заходишь в меню то появляются дублирующие пункты меню.
![menu](https://user-images.githubusercontent.com/29531264/39863462-ebfd5f1c-5470-11e8-9e01-67a1d0b900ef.png)

**Comment by PSalador** [comment]
В MenuController.php каждый раз отправляется массив всех пунктов меню и он проверяет по 'id' и через firstOrNew и создает новый элемент если у пункта нет id - поэтому пока не перегрузишь страницу и он не подцепит id элементов с базы то у каждого добавленного элемента будет id=0, и он заново их запишет в базу
```
    private function createMenuElement(array $items, $parent = 0)
    {
        foreach ($items as $item) {
            Dashboard::model(Menu::class)::firstOrNew([
                'id' => $item['id'],
            ])->fill(array_merge($item, [
                'lang'   => $this->lang,
                'type'   => $this->menu,
                'parent' => $parent,
            ]))->save();

            if (array_key_exists('children', $item)) {
                $this->createMenuElement($item['children'], $item['id']);
            }
        }
    }
```
вижу два способа решения:
1) как-то отправлять в браузер id добавленого элемента
2) проверять по вторичным параметрам кроме id ('title', 'slug')

**Comment by tabuna** [comment]
Думаю имеет смысл только отправлять [id](https://github.com/orchidsoftware/platform/blob/develop/src/Press/Http/Controllers/MenuController.php#L90) (несколько), при сохранении элемента и его [записывать их DOM](https://github.com/orchidsoftware/platform/blob/develop/resources/assets/js/components/menu.js#L140)

Думаю решить это в рамках таска #628

**Comment by PSalador** [comment]
> Думаю имеет смысл только отправлять id (несколько),

А  как привязывать элементы к полученным id? - по порядку заново переписывать?

Ещё можно отправлять на сервер не список всех пунктов меню, а только добавленный тогда не будет таких проблем.

**Comment by PSalador** [comment]
Сделать в рамках #628
