### ISSUE TITLE
Как добавить телефон к учебному экрану?

### ISSUE THREAD

**Issue by ewgenm** [orchidsoftware/platform#651]
Заголовок дебильный (простите за него)
Скорее всего вопрос не к Orchid а к Laravel, однако попытаю счастья здесь...

К учебному примеру "Создание экрана", я попытался добавить телефон
создал миграцию - 

`
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePhoneTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('phone', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->default(0);
            $table->string('phone',10);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('phone');
    }
}
`

создал модель Phone.php
`
namespace App;

use Illuminate\Database\Eloquent\Model;

class Phone extends Model
{
    //
    protected $table='phone';
    public $timestamps=false;

    protected $fillable = [
        'user_id',
        'phone'
    ];

    public function user(){
        return $this->belongsTo(User::class);
    }
}
`
модель User теперь такая -

`
namespace App;

use Illuminate\Support\Facades\App;
use Orchid\Platform\Core\Models\User as BaseUser;

class User extends BaseUser
{

    /**
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'last_login',
        'avatar',
        'permissions',
        'first_name',
        'last_name',
        'city_id',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function history(){
       return $this->hasMany(History::class);
    }

    public function city(){
        return $this->hasOne(City::class);
    }

    public function phone(){

        return $this->hasOne(Phone::class);
    }`
ProfileScreen выглядит так
`<?php

namespace App\Http\Controllers\Screens;

use App\History;
use App\Http\Filters\BrowserFilter;
use App\Http\Filters\PlatformFilter;
use App\Http\Requests\ChangePassword;
use App\Layouts\BrowserLayout;
use App\Layouts\HistoryLayout;
use App\Layouts\PlatformLayout;
use App\Layouts\ProfileLayout;
use App\Layouts\ProfilePasswordLayout;
use App\Phone;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Orchid\Platform\Facades\Alert;
use Orchid\Platform\Screen\Layouts;
use Orchid\Platform\Screen\Link;
use Orchid\Platform\Screen\Screen;

class ProfileScreen extends Screen
{
    /**
     * Display header name
     *
     * @var string
     */
    public $name = 'Профиль';

    /**
     * Display header description
     *
     * @var string
     */
    public $description = 'Полное управление пользователем в одном месте';

    /**
     * Query data
     *
     * @return array
     */
    public function query(): array
    {
        $profile = Auth::user();
        $phone = Phone::where('user_id', $profile->id)->first();

        $history = History::where('user_id', $profile->id)->filtersApply([
            BrowserFilter::class,
            PlatformFilter::class,
        ])->paginate();
        $statistics = [
            'browser'  => History::getStatisticsColumns("browser"),
            'platform' => History::getStatisticsColumns("platform"),
        ];

        return compact('profile', 'history', 'statistics','phone');
    }

    /**
     * Button commands
     *
     * @return array
     */
    public function commandBar(): array
    {
        return [
            Link::name('Изменить пароль')
                ->modal('password')
                ->title('Смена пароля')
                ->method('changePassword'),
            Link::name('Обновить профиль')
                ->method('update')
        ];
    }

    /**
     * Views
     *
     * @return array
     */
    public function layout(): array
    {
        return [
            Layouts::columns([
                'Профиль пользователя' => [
                    ProfileLayout::class,
                    Layouts::columns([
                        [PlatformLayout::class],
                        [BrowserLayout::class],
                    ])
                ],
                'История'              => [
                    HistoryLayout::class,
                ],
            ]),
            Layouts::modals([
                'password' => [
                    ProfilePasswordLayout::class
                ],
            ])
        ];
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request)
    {
        $profile = Auth::user();
        Auth::user()->fill($request->get('profile'))->save();

        $phone = $profile->find(1)->phone();

        $phone->phone = $request->input("profile.phone");
        $phone->save();

        Alert::info('Профиль успешно обновлён');
        return redirect()->back();
    }

    /**
     * @param ChangePassword $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function changePassword(ChangePassword $request)
    {
        Auth::user()->password = Hash::make($request->input('profile.password'));
        Auth::user()->save();

        Alert::info('Ваш пароль успешно изменён');
        return redirect()->back();
    }
}
`
в ProfileLayout добавил вот это-

`
           Field::tag('input')
                ->type('text')
                ->name('profile.phone.phone')
                ->mask('+7(999)999-9999')
                ->title('Телефон')
                ->help('Номер телефона'),
`
получаю 

`
Type error: Too few arguments to function Illuminate\Database\Eloquent\Relations\HasOneOrMany::save(), 0 passed in E:\OSPanel\domains\orchid.dev\app\Http\Controllers\Screens\ProfileScreen.php on line 121 and exactly 1 expected 
`

**Comment by tabuna** [comment]
Во первых **связь не соответствует базе данных**:

```php
public function phone()
{
    return $this->hasOne(Phone::class);
}
```
Кто должен обеспечить связь 1 к 1 если записей несколько?
Более правильное решение было бы либо **изменить БД, либо связь. на `hasMany`**

-----

Зачем устанавливать связь если её не использовать?
```php
    $profile = Auth::user();
    $phone = Phone::where('user_id', $profile->id)->first();
```
Лучше же: 
```php
    $profile = Auth::user();
    $phone = $profile->phone();  //возвращаемые данные будут разные, смотря какая связь
```

_P.S. А ещё лучше всё жадной загрузкой забирать._

-----

Методы:
```php
    Field::tag('input')
          ->type('text')
          ->name('profile.phone.phone')
          ->mask('+7(999)999-9999')
          ->title('Телефон')
          ->help('Номер телефона')
```

**Comment by tabuna** [comment]
Присоединяйся к [чату](https://t.me/orchid_community) там намного получать инфу не связанную с багами/планами и т.п.
