### ISSUE TITLE
Feature request - add ability to upload images to a SimpleMDE field

### ISSUE THREAD

**Issue by angay9** [orchidsoftware/platform#653]
It would be nice if there was an ability to upload images to a simplemde editor rather than manually pasting url of an image. Similarly to how it works in tinymce plugin.
Is this possible @tabuna ?
Thanks

**Comment by tabuna** [comment]
Yes, that's a good idea. This download is possible.
I would be happy if you add it yourself.

**Comment by tabuna** [comment]
Hi @angay9 . Now the [field](https://github.com/orchidsoftware/platform/blob/ea4dc660548b105042b7138e8c67dbf7db1f60ee/resources/js/controllers/fields/simplemde_controller.js#L85-L88) has the property to [load](https://yadi.sk/i/-CSrDm6U3aAUEJ) images/files, etc. in its graphical interface.


![ezgif-1-f651b00cf9](https://user-images.githubusercontent.com/5102591/44007411-7bf6031e-9e9d-11e8-8e55-cd3b93a0ac30.gif)

I know it's been a long time, but maybe you like it. Will be available from next release
