### ISSUE TITLE
Как передавать данные в layout?

### ISSUE THREAD

**Issue by ewgenm** [orchidsoftware/platform#655]
Опять я с тупыми вопросами...
Ни как не пойму, как передаются данные в Layout.

делаю всё, как в уроке "создание экрана"
далее, добавляю в ProfileScreen.php в query()
`$agencyAll=Agency::all(['id','agency'])->toArray();`
и
`return( compact('profile', 'history', 'statistics','agencyAll'));`

в ProfileLayout.php добавляю
`
            Field::tag('select')
                ->name('profile.agency')
                ->title('Агентство')
                ->options('profile.agencyAll'),
`
получаю ошибку
`Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Invalid argument supplied for foreach()`

как вообще получить переменные в Layout и что я делаю не так?

**Comment by tabuna** [comment]
**Рассмотрим не большой пример:**

Допустим у нас есть экран с методом `query` который возвращает определённый набор, а именно массив с единственным элементом, где ключом будет `name`, а значением 'Евгений'

```php
    /**
     * Query data
     *
     * @return array
     */
    public function query(): array
    {
        return [
           'name' => 'Евгений'
        ];
    }
```

Каждый подключенный Layouts может иметь результат выполнения нашей функции, считая это источником информации. Теперь когда мы положили в это хранилище некоторое значение, мы можем это автоматически подключить:

```php
    /**
     * Views
     *
     * @return array
     * @throws \Orchid\Platform\Exceptions\TypeException
     */
    public function fields(): array
    {
        return [
            Field::tag('input')
                ->name('name')
        ];
    }
``` 

Когда будет происходить формирование полей, значение `Евгений` автоматически подставиться в наше поле из-за ключа `name`.

--------

Такое формирование может быть не только с простыми типами, но и с объектами/массивами, каждый переданный массив будет преобразован в класс `Repository`, а объект потребует подключения трейта для локализации, либо своей собственной функции `getContent`.

**Пример с объектами:**


```php
    /**
     * Query data
     *
     * @return array
     */
    public function query(): array
    {
        return [
           'user' => \App\User::find(1)
        ];
    }
```
Заметьте, что класс `App\User` использует trait `Orchid\Platform\Core\Traits\MultiLanguage` и у него есть атрибут `email`, тогда что бы получить его в нашем layouts мы будем использовать `dot` подход _(Этот же подход и для массивов)_

```php
    /**
     * Views
     *
     * @return array
     * @throws \Orchid\Platform\Exceptions\TypeException
     */
    public function fields(): array
    {
        return [
            Field::tag('input')
                ->name('user.email')
        ];
    }
``` 


----

Такой бинд ключа и значений не является обязательным, вы так же можете использовать классические подходы. Не стесняйтесь задавать вопросы, если вам непонятна какая либо часть в документации мы можем расширить её вместе с вами.
