### ISSUE TITLE
Вынести в конфиг путь к resources

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#660]
Навеяно этим #561 issue - если вынести в конфиг путь к папке resources/view  то можно будет локально редактировать шаблоны админки, не боясь обновляться.

**Comment by tabuna** [comment]
Так мы можем сделать проще без всяких файлов конфигурации, просто публиковать шаблоны как предлагает нам сам laravel, [например](https://github.com/orchidsoftware/platform/pull/656). Но тогда в установки нужно убрать публикацию всего, что бы человек делал это осознано с помощью команды:

```bash
php artisan vendor:publish -сервис провайдер -views
```
