### ISSUE TITLE
документация, демо, нововведения

### ISSUE THREAD

**Issue by h-zone** [orchidsoftware/platform#662]
Прошу более подробно описать Таксонометрию, на примерах и демо, дабы пощупать, так как теория не всем даёт представление общей картины (вопрос в механизме восприятия Теоретиком и Практиком).

Прошу подробно описать реализацию следующей конструкции:
- категории данных
- данные
- свойства данных
В качестве контекста можно применить "интернет магазин".
= Единица товара привязана к категориЯМ (именно множественное значение)
= Единица товара имеет множество свойств вида имя/значение (в виде вертикальной таблицы)

Прошу подумать о реализации зависимостей в формах, если не реализовано (я не нашёл).
При этом нужны зависимости в рейдже полиморфа.
т.е.:
таблица имеет поля: `id | name | morphable_id | morphable_type`
зависимый селект грузит в себя записи указанной в `morphable_type` модели.
в сове это не реализуемо в принципе, ибо проблема в отсутствии данных в том же onEdit / фронтэнде, и даже не патчится путём поиска и прогрузки этих данных где и как -либо, ибо "архитектура"...
надо решить эту тему, ибо решение этого вопроса позволит писать сложные CRM на архитектуре админки.

**Comment by h-zone** [comment]
+

есть смыл подумать о **генераторе структур** данных прямо из админки

1) (уже названо)
- категории данных
- свойства данных
- данные, имеют множество категорий и множество свойств
все таблицы вертикальные

2) (уже названо)
зависимые данные

3)
данные статик, хранимые не в модели (БД), а именно в php-файле, где-то лежащем, но доступным из моделей, а-ля реляция. возможно решение работать через коллекции.
чтобы не дёргать БД из-за 4-5 статичных строк (однако эти строки требуется редактировать/добавлять/удалять именно из админки)
= повысит, хоть не существенно производительность процессора и не будет жрать неоправданно память при обращении к бд за столь мелкими объёмами данных, кои редко меняются.

**Comment by tabuna** [comment]
> Прошу подробно описать реализацию следующей конструкции:
категории данных
данные
свойства данных
В качестве контекста можно применить "интернет магазин".
= Единица товара привязана к категориЯМ (именно множественное значение)
= Единица товара имеет множество свойств вида имя/значение (в виде вертикальной таблицы)

Прошу либо конкретизировать, либо говорить в рамках функциональности.
В контексте интернет-магазина или других подобных, orchid не предоставляет готовых решений, а лишь набор определённых сценариев:

 - Экраны
 - Настройки
 - Разделение прав доступа
 - etc

Вы можете взять любую структуру, которая сочитается с философией laravel и orchid.
Описанная выше схема **классическая реализация паттерна** [EAV](https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model). Существуют уже готовые и узко направленные реализации, например, [Rinvex Attributes](https://github.com/rinvex/attributes), [sunel/eav](https://github.com/sunel/eav) и т.п, которыми вы можете расширить структуру.


> Прошу подумать о реализации зависимостей в формах, если не реализовано (я не нашёл).
При этом нужны зависимости в рейдже полиморфа.
т.е.:
таблица имеет поля: id | name | morphable_id | morphable_type
зависимый селект грузит в себя записи указанной в morphable_type модели.


Для любого отношения необходимо получить данные. Они могут быть в любых отношения в базе данных или вообще **считаться с внешнего источника** (файл/api/etc). Для этого в данный момент мы используем [виджет](https://orchid.software/ru/docs/widget#ajax-widget), в документации существует пример, как его [построить](https://orchid.software/ru/docs/tutorial_profile#sozdanie-ajax-vidzheta-dannykh), при реальном использовании выглядит это так:

```php
Field::tag('relationship')
    ->name('profile.city_id')
    ->required()
    ->title('Город')
    ->handler(CityWidget::class),
```


> в сове это не реализуемо в принципе, ибо проблема в отсутствии данных в том же onEdit / фронтэнде, и даже не патчится путём поиска и прогрузки этих данных где и как -либо, ибо "архитектура"...
надо решить эту тему, ибо решение этого вопроса позволит писать сложные CRM на архитектуре админки.

Не знаю, как это реализовано, но думаю, что какие то варианты существуют.



> данные статик, хранимые не в модели (БД), а именно в php-файле, где-то лежащем, но доступным из моделей, а-ля реляция. возможно решение работать через коллекции.
чтобы не дёргать БД из-за 4-5 статичных строк (однако эти строки требуется редактировать/добавлять/удалять именно из админки)
= повысит, хоть не существенно производительность процессора и не будет жрать неоправданно память при обращении к бд за столь мелкими объёмами данных, кои редко меняются.

Для этого существуют [настройки](https://orchid.software/ru/docs/settings), значения которых кэшируется (в файле/мемкеше/редисе/etc) и обновляются при редактировании.
