### ISSUE TITLE
Prevent regular users to acces Platform cms.

### ISSUE THREAD

**Issue by amirakbulut** [orchidsoftware/platform#665]
I want my regular users and admins to have seperated entry points.

### Expected Behavior
Regular users should only be able to authenticate through the regular /login and /register.
Admin users should only be able to authenticate through Platform's /dashboard.

### Actual Behavior
Regular users and admins can login into both /login and /dashboard.
However, when a regular user logs into /dashboard, the page says "The page you're looking for does not exist".

How do I solve all this?

### Specifications

  - ORCHID Version: Latest Master branch
  - Laravel Version: 5.6.24
  - PHP Version: 7.2.5
  - Database Version: mysql Ver 14.14 Distrib 5.7.21, for Win32 (AMD64)

**Comment by amirakbulut** [comment]
Anyone?

**Comment by tabuna** [comment]
Hi, sorry for the long wait.
Authorization and authentication is handled by laravel. I think this behavior can be implemented with the help of intermediate [middleware](https://laravel.com/docs/5.6/middleware#middleware-groups) groups and changed [authorization](https://laravel.com/docs/5.6/authentication#adding-custom-user-providers)

**Comment by ShamarKellman** [comment]
Just wanted to update for other user who may have this issue. 

After creating your custom guard, you need to override 
- Orchid\Platform\Http\Controllers\Auth\LoginController
- Orchid\Platform\Http\Controllers\Auth\ResetPasswordController
- Orchid\Platform\Http\Controllers\Auth\ForgotPasswordController

in the Login controller `protected function guard()
    {
        return Auth::guard('admin');
    }`

in the  ResetPasswordController, and ForgotPasswordController append the guard to the middleware

You also have to set the `'auth'  => false,` in the `platform.php` config file
