### ISSUE TITLE
Сохранять состояние табов

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#666]
При использовании экрана на котором есть некоторое количество табов, необходимо сохранять их состояние после обновления страницы. (Опасность: Подумать над тем, как показать таб, который находиться в табе, который в табе и т.п.)

**Comment by tabuna** [comment]
Обнаружились какие то проблемы?

**Comment by PSalador** [comment]
Когда сохраняшь он возвращается на таб, но в нем информация из 1-го таба, приходится нажать на любой таб потом опять на текущий.

**Comment by tabuna** [comment]
Не очень понял, что нужно, что бы воспроизвести?
