### ISSUE TITLE
Поле Upload, возможность задавать размеры изображений

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#678]
1) Сейчас в конфиге platform.php можно указать размеры изображений которые дополнительно конвертируются при загрузке.
Возможно ли сделать чтобы в самом поле указывать размеры конвертируемых изображений и нужны они нет. например так.
```
Field::tag('upload')
            ->name('upload')
            ->title('Загрузка изображений')
            ->images([
                'low'    => [
                    'width'   => '100',
                    'height'  => '100',
                    'quality' => '90',
                ],
                'medium' => [
                    'width'   => '600',
                    'height'  => '300',
                    'quality' => '75',
                ],
                'high'   =>'none'
         ]),
```
2) Нужна возможность добавлять дополнительные поля в описание файлов кроме Alt и description.

**Comment by tabuna** [comment]
1. Тогда, что бы узнать какие ресайзы существуют нужно будет прошерстить все файлы.


Предлагаю наделить поле следующими методами:
```php
    /**
     * @return array
     * @throws \Throwable
     */
    public function options(): array
    {
        return [
            Field::tag('upload')
                //default
                ->name('upload')
                ->title('Upload')
                ->help('place for google maps')
                ->value('id')

                //only upload
                ->class(Page::class)
                ->storage('public')
                ->mime('image/png')
                ->maxFileSize(2)
                ->parallelUploads(10)
                ->maxFiles(10)

                //only image
                ->resizeMethod('contain/crop')
                ->resizeQuality(0.75)
                ->resizeMimeType('image/jpeg')
                ->resizeWidth(200)
                ->resizeHeight(200)
        ];
    }
```

**Comment by tabuna** [comment]
По факту это дублирует #399

**Comment by tabuna** [comment]
> как быть в таком случае?

**Не сохранять изображения** на диск, а доставать из кеша нужное разрешение по необходимости, это можно сделать используя метод `getSizeImage`, задокументировать бы [его](https://github.com/orchidsoftware/platform/blob/c75ab278201da2481377cec15818d4b4aa563964/src/Attachment/Models/Attachment.php#L101).


В любом случаи написание явно через:

```php
->images([
                'low'    => [
                    'width'   => '100',
                    'height'  => '100',
                    'quality' => '90',
                ],
                'medium' => [
                    'width'   => '600',
                    'height'  => '300',
                    'quality' => '75',
                ],
                'high'   =>'none'
         ]),
```

Как мне кажется плохая идея. 


Тогда намного лучше будет сделать следующем образом:

Убираем разделение в [конфиге](https://github.com/orchidsoftware/platform/blob/31533177ca4be8d1b51abfdb269717cb9eea20f3/config/attachment.php#L15-L19) attachment (возможно даже лучше вынести его в platform).

https://github.com/orchidsoftware/platform/blob/7759ff729ab38e0f4ee4c39f48d23ddbfa41d4d9/src/Platform/Attachments/File.php#L97


**Убираем всю разницу image/не image и т.п.** 
Накладывая эту проверку уже на необходимый Template _(возможно нужно будет ещё абстрагироваться и создавать AttachInterface/ ImageTemplate / VideoTemplate и т.п.)._

И тогда **будем записывать как**:

```php
->superMethod([
     Orchid\Attachment\Templates\Small::class,
     Orchid\Attachment\Templates\Medium::class,
     Orchid\Attachment\Templates\Large::class
])
```


Единственное не очень понятно как удалять все эти генерации, по условию, что есть файл виде "name.*.jpg" как пример, так как сейчас удаление физического файла обращается к конфигу :

https://github.com/orchidsoftware/platform/blob/31533177ca4be8d1b51abfdb269717cb9eea20f3/src/Attachment/Models/Attachment.php#L151-L153

**Comment by PSalador** [comment]
Если я правильно понял то ` getSizeImage ` создает изображение каких нужно размеров при использовании его. Тогда это в принципе решает проблемы, вед например размер 'small'  нужен чтобы отображать изображение поста на главной, но через некоторое время, когда этот пост уходит с главной уже исчезает потребность, а сам файл остается.

> Единственное не очень понятно как удалять все эти генерации, 

Можно к каждому файлу делать папку с таким же именем, а в неё уже закидывать все генерации - при удалении просто удаляем папку с таким же именем как файл.

**Comment by PSalador** [comment]
Или в базе создать столбец в который добавлять все имена генераций - ` {'low','small','high'} `

**Comment by PSalador** [comment]
Разве сделано?

**Comment by tabuna** [comment]
Добавил параметры:

```php
    /**
     * All attributes that are available to the field.
     *
     * @var array
     */
    public $attributes = [
        'value' => null,
        'multiple' => true,
        'parallelUploads' => 10,
        'maxFileSize' => 9999,
        'maxFiles' => 9999,
        'acceptedFiles' => null,
        'resizeQuality' => 0.8,
        'resizeWidth' => null,
        'resizeHeight' => null,
    ];
```

**Comment by tabuna** [comment]
После #719 больше нет смысла в указании размеров, так как больше это не обрабатывается и предлагается делать cdn самостоятельно
