### ISSUE TITLE
Laravel RouteServiceProvider default namespace override

### ISSUE THREAD

**Issue by Windstep** [orchidsoftware/platform#680]
### Expected Behavior

The expected behaviour is the following: we, for example, using the action($name); method in Blade. Handler should pick namespace from the RouteServiceProvider (\App\Http\Controllers) and assign it to $name.

### Actual Behavior

When we are using Orchid/Platform FoundationServiceProvider it binds some providers in it's **boot** method, so, the Route provider from orchid overrides the $namespace variable from app\RouteServiceProvider, because loaded AFTER it (specification).

### Steps to Reproduce the Problem

  1. Install orchid + laravel, call the action('SomeController@method') in any view.

### Specifications

  - ORCHID Version: 2.2 master (latest)
  - Laravel Version: 5.6 (latest)
  - PHP Version: 7.1.19
  - Database Version: 5.7 mysql.

### Other Notes
![image](https://user-images.githubusercontent.com/13916765/43894733-aae065e4-9bdb-11e8-8ff2-e1ce0961749e.png)

P.S. You can answer on English or Russian

**Comment by tabuna** [comment]
@Windstep  Greetings! Thanks for taking the time to open this issue. :thumbsup:
I was able to reproduce the problem that you describe. Can you make [PR](https://github.com/orchidsoftware/platform/tree/develop)?

**Comment by Windstep** [comment]
@tabuna, In our project we made a decision to remove $namespace protected property from RouteServiceProvider class. So just have to test this, that all of the functions works properly, and before pulling changes.

**Comment by tabuna** [comment]
It was also fixed :hammer: in the development branch. 

I thank all those involved. :clap:
