### ISSUE TITLE
Раскрывающееся верхнее меню в экранах

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#683]
Сейчас в экранах через Links можно в верхнее меню добавлять ссылку, но когда слишком много данных все ссылки не помещаются. 

Необходимо добавить возможность раскрывающегося меню, типа:
![topmenu1](https://user-images.githubusercontent.com/29531264/44107717-846abc20-a022-11e8-81ea-ef4ee8a22f1b.gif)

**Comment by tabuna** [comment]
Добавил.

**Пример кода:**
```php
Link::name('Группа')
    ->icon('icon-user')
    ->group([
        // Link::  ...
        // Link::  ...
        // Link::  ...
        // Link::  ...
    ])
```

**Внешний вид:**
![screenshot-localhost-8000-2018 09 23-02-32-50](https://user-images.githubusercontent.com/5102591/45922594-fce6d600-bed8-11e8-86ce-bfccc9314a5f.png)
