### ISSUE TITLE
Сделать поле в которое можно вкладывать поля.

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#685]
Для поля list нужно поле в которое можно вкладывать поля.
Примерно как поле Field::group(), типа этого:
```
Field::list([
      Field::tag('input')
                ->type('text')
                ->name('name1'),
      Field::tag('datetime')
                ->type('text')
                ->name('datetime'),
])->name('list1');
```

В итоге мы должны получить записи `name` как `list1[][name1]` и  `list1[][datetime]` соответственно

**Comment by PSalador** [comment]
Вот примерная реализация через https://bevacqua.github.io/dragula/
![photo_2018-09-02_17-13-37](https://user-images.githubusercontent.com/29531264/44955241-66775400-aeda-11e8-8af8-075ae9f67e8a.jpg)

**Comment by PSalador** [comment]
js и html файлы.
[list.zip](https://github.com/orchidsoftware/platform/files/2343233/list.zip)

**Comment by Nks** [comment]
Anything new on this option? Maybe better to create one other package to not overhead current package? BTW this logic already using in wordpress in plugin ACF (https://www.advancedcustomfields.com/resources/flexible-content/, https://www.advancedcustomfields.com/resources/repeater/). With this we can give an ability to user build pages based on predefined fields and blocks and sort them as they want. I think this will be good to implement this.

Есть ли какие-то подвижки в решении вопроса? Может быть имеет смысл вынести этот функционал в отдельный пакет чтобы не перегружать основной? Кстати данный вариант логики давно используется в вордпрессе в плагине ACF (https://www.advancedcustomfields.com/resources/flexible-content/, https://www.advancedcustomfields.com/resources/repeater/). Благодаря ему можно давать пользователю самому строить страницы на основе подготовленных блоков и переставлять их так как им хочется. Считаю что было бы очень неплохо реализовать это.

**Comment by tabuna** [comment]
@Nks . As far as I know, nobody is doing this. :weary:
Putting it in a separate package makes sense and I support it. 
Do you want to implement it?

Насколько мне известно, этим никто не занимается. 
Вынесение в отдельный пакет имеет смысл и я поддерживаю это. 
Вы хотите реализовать это?

**Comment by Nks** [comment]
@tabuna So, I started develop this package. Here you can take a look on prototype. https://github.com/Nks/orchid-repeater-field

Work in progress, but here we already have the field based on Field class and it already has everything to start work on this. I'll keep posted about this.

**Comment by Nks** [comment]
Check it out: https://packagist.org/packages/nakukryskin/orchid-repeater-field
I know about issue with the multiple select, but haven't time right now to fix this.

**Comment by PSalador** [comment]
Отлично. То что нужно.
