### ISSUE TITLE
Возможность задавать class в макете таблицы.

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#687]
В макете [таблицы](https://orchid.software/ru/docs/layouts#tablitsa)
добавить возможность устанавливать class строке (` <tr> `) и ячейке (` <td> `).

Например:  чтобы в списке комментариев выделить строки неодобренных комментариев.

**Comment by PSalador** [comment]
Разве сделано?

**Comment by tabuna** [comment]
С `<td>` ещё можно, что либо сделать, а вот с `<tr>` уже будет нагромождено, в том плане, что у нас нет ни параметров, ни методов для этого, то есть мы заранее определяем только `<td>`. 
Если необходимо как то выделить какие то строки (например по условию), то проще создать свой шаблон и использовать его через `Layouts::view('myTemplate')`

**Comment by PSalador** [comment]
Разобрался как сделать <tr>( да и <td>) для определенных нужд:
1) в лайоуте подключить свой шаблон  `$template = 'platform::container.layouts.table';`
2) скопировать `container.layouts.table` 
3) переделать строку с [tr](https://github.com/orchidsoftware/platform/blob/master/resources/views/container/layouts/table.blade.php#L58), там в $datum выводится модель.
Например нужно выделить записи определенного пользователя:
```
@foreach($data as $key => $datum)
                <tr class="@if ($datum->user_id == 1) bg-success @endif">
                    @foreach($fields as $td)
```

Скорее всего, что-то универсальное делать тут не целесообразно, так что закрываю.
