### ISSUE TITLE
Users default migration override

### ISSUE THREAD

**Issue by Windstep** [orchidsoftware/platform#688]
### Expected Behavior
Command `php artisan migrate` is about of doing migration from migrations folder of main project. So if we have migration 00000_create_users_table, we should migrate it to database, even if they are any migrations in packages.

### Actual Behavior
Migration create_users_table of the projects ovewrites the create_users_table migration of the project.

### Steps to Reproduce the Problem

  1. Include orchid
  2. Add for example string column type to default laravel's user migration
  3. php artisan migrate
  4. Look in database.

### Specifications

  - ORCHID Version: dev-master
  - Laravel Version: 5.6
  - PHP Version: 7.1.*
  - Database Version:

**Comment by tabuna** [comment]
We can not automate this in the current stable branch. :disappointed:
 I would be glad if you have suggestions that will work and do not force to see the installation list for the user.

If you need to solve this, run the migration [before](http://orchid.software/en/docs/installation#publish-preferences) installing it from the package:


```php
composer require orchid/platform
artisan migrate
artisan vendor:publish --provider="Orchid\Platform\Providers\FoundationServiceProvider"
artisan vendor:publish --all
artisan migrate
artisan storage:link
artisan orchid:link
```

:gift: But I was able to correct this in the new [artisan command](https://www.youtube.com/watch?v=0eY-WRAE7iA) `orchid:install` for [develop branches.](https://github.com/orchidsoftware/platform/tree/develop)

```php
composer require orchid/platform
php artisan orchid:install
```

-------

:clap: Thank you for taking the time to write about this.

**Comment by Windstep** [comment]
Maybe we can fully remove users table migration from orchid, cos it is included by default? And in files, where we need it just validate that it exists?

**Comment by tabuna** [comment]
Standard migrations have been removed
