### ISSUE TITLE
Можно в Layout, вывести свой View?

### ISSUE THREAD

**Issue by ewgenm** [orchidsoftware/platform#690]
Скажите пожалуйста, как можно в Layout, вывести свой View?
Я попытался так:

>     public function layout() : array
    {
        return [
            Layouts::columns([
                'Левая колонка'=>[RawTableLayout::class],
                'Правая колонка'=>[RawData::class],
            ]),
            view('dashboard.rawTable', $this->query()),
        ];
    }

Получаю
>Method Illuminate\View\View::build does not exist. (View: E:\OSPanel\domains\next.local\vendor\orchid\platform\resources\views\container\layouts\base.blade.php)

**Comment by tabuna** [comment]
Здравствуй @ewgenm, мы добавили такую возможность в [develop](https://github.com/orchidsoftware/platform/tree/develop) ветки:

_Пример использования:_

```php
declare(strict_types=1);

namespace App\Orchid\Screens;

use Orchid\Screen\Screen;
use Orchid\Screen\Layouts;
use Orchid\Platform\Dashboard;

class PlatformScreen extends Screen
{
    /**
     * Display header name.
     *
     * @var string
     */
    public $name = 'platform::common.title';

    /**
     * Display header description.
     *
     * @var string
     */
    public $description = 'platform::common.description';

    /**
     * Query data.
     *
     *
     * @return array
     */
    public function query(): array
    {
        return [
            'status' => Dashboard::checkUpdate(),
        ];
    }

    /**
     * Button commands.
     *
     * @return array
     */
    public function commandBar(): array
    {
        return [];
    }

    /**
     * Views.
     *
     * @return array
     */
    public function layout(): array
    {
        return [
            Layouts::view('platform::partials.update'),
            Layouts::view('platform::partials.welcome'),
        ];
    }
}

```
В шаблоне `view`, уже будут доступны все данные из метода `query`.


-------

**Возможное решение** для того, что бы использовать это в `master`, необходимо унаследовать класс `Orchid\Platform\Screen\Layouts`  и расширить его методом: 


```php
    /**
     * @param string $view
     *
     * @return static
     */
    public static function view(string $view)
    {
        $new = new static;
        $new->active = 'view';
        $new->templates['view'] = $view;
        $new->slug = sha1(serialize($new));
        return $new;
    }
```
