### ISSUE TITLE
Add Order field to Posts model - Добавить поле "Order" в модель "Posts"

### ISSUE THREAD

**Issue by F1-GTR** [orchidsoftware/platform#697]
# Hello!
If I need to load widget content - I can _order_ it only with timestamps or id fields, and after I should exec another sorting to given data using getContent() method (because builtin Field::tag() fields hidden in json field :<)

# Здравствуйте!
Если мне нужно загрузить контент в виджет в определённом порядке - я могу отсортировать его только по полям timestamp и id, и после этого уже дополнительно необходимо сортировать через метод getContent() (Потому что встроенные Field::tag() поля спрятаны в json записи)

**Comment by tabuna** [comment]
Здравствуй @F1-GTR . Спасибо за предложение, но современные реляционные базы данных умеют работать с типом данных json ([1](https://dev.mysql.com/doc/refman/en/json.html), [2](https://www.postgresql.org/docs/9.3/static/functions-json.html), [3](https://www.sqlite.org/json1.html)), так же laravel предоставляет удобные [средства](https://laravel.com/docs/5.7/queries#json-where-clauses).

То есть вы можете добавить сортировку у себя или сортировать и делать выборки по уже существующим полям не посредственно в json.

_Например:_
```php
$post = Post::where('content->options->count','>', 10);

$post = Post::orderBy('content->ru->name','Desc');
```
И другие операции с аналогичным синтаксисом.
