### ISSUE TITLE
develop: Orchid\Platform\Models\User::getFieldsEdit()

### ISSUE THREAD

**Issue by mavsan** [orchidsoftware/platform#698]
Ветка develop, при открытии "Пользователей" (меню система) возникает ошибка: обращение к отсутсвующему методу `Orchid\Platform\Models\User::getFieldsEdit()`. Было удалено 2.10 (видно в истории в PhpStorm, но не видно в истории на github), в коммите 385b24560e99762915d57d78df8d8b72bd4ac05a - есть такой метод, а в коммите 3930dd1310f251dc0d7830b0f2ce6ce2ff2ebe71 - уже нет.

**Comment by tabuna** [comment]
Ох, извини. Но develop на то и develop ;)

Хотел показать, что поля можно задавать непосредственно в модели, что бы не дублировать на каждом экране, а уже после использовать, например:

```php
namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    /**
     * @return \Illuminate\Support\Collection
     */
    public static function getFields() : Collection
    {
        return collect([
            'name' => Field::tag('input')
                ->type('text')
                ->name('user.name')
                ->max(255)
                ->required(),

            'email' => Field::tag('input')
                ->type('email')
                ->name('user.email')
                ->required(),
        ]);
    }
}
```

А затем вызвать в нужных местах и получать список:

```php
// только поле для электронной почты
User::getFields()->only('email');

// всё поля
User::getFields()->all();
```

И в таком духе... Но базовая модель пользователя не подходящее место, что бы показать это, так как её часто меняют, а этот метод скрыт, по этому я убрал его.

Пожалуйста  измените свой собственный Layout где это вызывается 
или опубликуйте файлы заново, с опцией `--force`, это вернёт файлы актуальное состояние (но может удалить ваши изменения!).

**Comment by mavsan** [comment]
Так я чистую поставил (т.е. поставил отдельно laravel, поставил orchid develop, сделал все, что надо, чтобы запустилось), посмотреть, что изменилось и можно-ли пользовать в живом проекте.
Посмотрел вчерашние коммиты - там нет ничего про view, но на всякий случай выполнил команду в консоли `php artisan vendor:publish --provider="Orchid\Platform\Providers\FoundationServiceProvider" --force`, все начало работать. Мистика.
