### ISSUE TITLE
Возможность регистрации пользователей

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#707]
Сейчас нет возможности регистрации пользователей, только через laravel `php artisan make:auth`. 
Это создает неудобства, так как там другой дизайн.
Нужно сделать в /dashboard/login возможность регистрации.
А также возможность добавления пользователя в админке.

**Comment by PSalador** [comment]
Да ещё какая-то проблема если зарегистрироваться через sitename/register то потом пока не почистишь куки не войдешь в dashboard.

**Comment by tabuna** [comment]
> Сейчас нет возможности регистрации пользователей, только через laravel php artisan make:auth.
> Это создает неудобства, так как там другой дизайн.
> 

Думаю так и должно быть, именно для этого существует функция отключения авторизации, что бы пользователи могли настроить вход/регистрацию как им необходимо, например, использовать мобильный телефон или всякие google f2a. Мы по умолчанию не может предусмотреть всех вариантов и именно поэтому предоставляем только простую базовую часть.

> Upd: Проблема из-за того что у нового пользователя нет доступов к админке.

В пользовательском контроллере, который создаётся после выполнения `artisan make:auth`, можно установить любые роли самостоятельно

**Comment by PSalador** [comment]
> Думаю так и должно быть, именно для этого существует функция отключения авторизации,
А есть функция включения авторизации?

> именно поэтому предоставляем только простую базовую часть.
дак базовая часть нужна с возможностью регистрации.

**Comment by tabuna** [comment]
> А есть функция включения авторизации?

Да есть:

```php
    /*
    |--------------------------------------------------------------------------
    | Auth
    |--------------------------------------------------------------------------
    |
    | Available settings
    |
    */
    'auth'  => true,
````


> дак базовая часть нужна с возможностью регистрации.

Для чего? В каких ситуациях она будет лучше `artisan make:auth`?

**Comment by PSalador** [comment]
Например у меня сайт состоит только из админки, и мне нужно добавить пользователя.
Существует 4 способа регистрации пользователей.
1) php artisan make:admin admin admin@admin.com password
2) через artisan make:auth
3) В админке возможность администратору, добавить пользователя.
4) В админке возможность регистрации самому пользователю.
Подробней 
1 пункт. - трудный, нужно каждый раз входить через консоль, а также там проблема с шифрованием паролей.
2 пункт. - вроде норм, но там инородное окошко регистрации
![register](https://user-images.githubusercontent.com/29531264/48188685-eacdd380-e370-11e8-9509-e29ea64b0068.png)
3 пункт - был, но удален.
4 пункт - не было и нет.

Тогда оставить хотя бы 3 пункт.
