### ISSUE TITLE
Menu dropdown bug

### ISSUE THREAD

**Issue by Leshkens** [orchidsoftware/platform#718]
Если у родительского пункта меню есть метод setGroupName(), то его значение появляется в выпадающем.

![ebc96g3qoa](https://user-images.githubusercontent.com/8939383/48280200-c1966b80-e474-11e8-87ea-620a5665c613.gif)
![menu-bug](https://user-images.githubusercontent.com/8939383/48280931-e8ee3800-e476-11e8-8482-92fa1ca87d77.PNG)

Есть метода нет, то все ожидаемо

![ztoeamt9zi](https://user-images.githubusercontent.com/8939383/48280611-e93a0380-e475-11e8-9ddb-31c34fa8c06d.gif)
![menu-bug2](https://user-images.githubusercontent.com/8939383/48280815-9280f980-e476-11e8-9325-b0611691c23f.PNG)

### Specifications

  - ORCHID Version: 3.0.3

**Comment by PSalador** [comment]
Это плохо. Нужно будет поправить.

**Comment by tabuna** [comment]
Было бы замечательно, в следующий раз код вставлять как текст.
Спасибо, что написали о проблеме, обязательно исправим

**Comment by tabuna** [comment]
Исправил в 3.0.5

**Comment by Hrache** [comment]
В документации не смог найти подробную информацыю про элементы меню у которых есть ребетишки, то есть про дроп-дауны. У меня такая ситуацыя, когда мне нужно 3 разных таких дроп-даунов с двумя под элементами с разными раутами, но ничего не выходит:

```
    // Main
    $this->dashboard->menu
      ->add(Menu::MAIN,
        ItemMenu::label('Articles')
          ->slug('articles')
          ->icon('icon-bag')
          ->childs()
      )
      ->add('articles', // slug of the parent
        ItemMenu::label('All articles')->route('platform.articles.list')
      )
      ->add('articles',
        ItemMenu::label('Create one')->route('platform.article.edit')
      );

    $this->dashboard->menu
      ->add(Menu::MAIN,
        ItemMenu::label('Websites')
          ->slug('websites')
          ->icon('icon-bag')
          ->childs()
      )
      ->add('websites', // slug of the parent
        ItemMenu::label('All websites')->route('platform.websites.list')
      )
      ->add('websites',
        ItemMenu::label('Create one')->route('platform.website.edit')
      );

    $this->dashboard->menu
      ->add(Menu::MAIN,
        ItemMenu::label('Comments')
          ->slug('comments')
          ->icon('icon-bag')
          ->childs()
      )
      ->add('comments', // slug of the parent
        ItemMenu::label('All comments')->route('platform.comments.list')
      )
      ->add('comments',
        ItemMenu::label('Create one')->route('platform.comment.edit')
      );
```

https://ibb.co/7WGqvHG
