### ISSUE TITLE
Динамическое создание изображений

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#719]
### Текущее состояние

На текущий момент изображения для разных разрешений создаются автоматически **при загрузке** и хранятся отдельно как отдельная запись в базе данных. Типы и разрешения определяются в файле `config/patform`:

```php
    /*
    |--------------------------------------------------------------------------
    | Attachment
    |--------------------------------------------------------------------------
    |
    | ....
    |
    */
    'attachment' => [
        'small'  => Orchid\Attachment\Templates\Small::class,
        'medium' => Orchid\Attachment\Templates\Medium::class,
        'large'  => Orchid\Attachment\Templates\Large::class,
    ],
```

И обрабатываются с помощью слушателя событий, благодаря этому есть возможность выбирать необходимый тип:

```php
//Возвращает общий адрес изображения с требуемым разрешением изображения
$attachment->url('standart');
```

Это предполагает, что все изображения хранятся на диске постоянно, что явно не требуется

### Предлагаемое изменение

Активно использовать `intervention/imagecache`, который предоставляет готовый функционал.

Настройка осуществляется в `config/imagecache.php`:

```php
return [

    /*
    |--------------------------------------------------------------------------
    | Name of route
    |--------------------------------------------------------------------------
    |
    | Enter the routes name to enable dynamic imagecache manipulation.
    | This handle will define the first part of the URI:
    | 
    | {route}/{template}/{filename}
    | 
    | Examples: "images", "img/cache"
    |
    */

    'route' => 'img/cache',

    /*
    |--------------------------------------------------------------------------
    | Storage paths
    |--------------------------------------------------------------------------
    |
    | The following paths will be searched for the image filename, submited 
    | by URI. 
    | 
    | Define as many directories as you like.
    |
    */

    'paths' => [
        public_path('storage'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Manipulation templates
    |--------------------------------------------------------------------------
    |
    | Here you may specify your own manipulation filter templates.
    | The keys of this array will define which templates 
    | are available in the URI:
    |
    | {route}/{template}/{filename}
    |
    | The values of this array will define which filter class
    | will be applied, by its fully qualified name.
    |
    */

    'templates' => [
        'small'  => Intervention\Image\Templates\Small::class,
        'medium' => Intervention\Image\Templates\Medium::class,
        'large'  => Intervention\Image\Templates\Large::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Image Cache Lifetime
    |--------------------------------------------------------------------------
    |
    | Lifetime in minutes of the images handled by the imagecache route.
    |
    */

    'lifetime' => 43200,

];
```

После определения маршрута и путей (делать это придётся в ручную) будет доступна динамическое создание изображений с необходимыми параметрами:

Например:
```
http://localhost:8000/img/cache/small/images/4999c4acbde2553a25fff98b089a13caec7946f0.png
```

### Заметки

Плюсы:
- Хранение только необходимой информации

Минусы:
- Метод `url()` будет работать иначе
- Будет требоваться ручная настройка
- [Пока не работает для облачных хранилищ (s3,rack,ftp) ](https://github.com/Intervention/image/pull/834)

### Голосование

[![](https://api.gh-polls.com/poll/01CW7BDS9DAPXADRMW3WXH307N/%D0%9F%D1%80%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D0%B5%D0%BC)](https://api.gh-polls.com/poll/01CW7BDS9DAPXADRMW3WXH307N/%D0%9F%D1%80%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D0%B5%D0%BC/vote)
[![](https://api.gh-polls.com/poll/01CW7BDS9DAPXADRMW3WXH307N/%D0%9E%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%20%D0%BA%D0%B0%D0%BA%20%D0%B5%D1%81%D1%82%D1%8C)](https://api.gh-polls.com/poll/01CW7BDS9DAPXADRMW3WXH307N/%D0%9E%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%20%D0%BA%D0%B0%D0%BA%20%D0%B5%D1%81%D1%82%D1%8C/vote)

**Comment by PSalador** [comment]
Я так понимаю, тут можно будет для некоторых изображений делать свои разрешения?
#678

**Comment by tabuna** [comment]
> Я так понимаю, тут можно будет для некоторых изображений делать свои разрешения?

Ох нет, мы всегда будет хранить только оригинал изображения, а изображения в других разрешениях/водяных знаков и т.п. уже будут по требованию и временными

**Comment by tabuna** [comment]
Итог: **Принимаем**
