### ISSUE TITLE
Аватар по умолчанию

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#720]
### Текущее состояние

В данный момент аватар генерируется с помощью пакета `laravolt/avatar`, в одном единственном месте :

```php
    /**
     * @return string
     * @throws \Exception
     */
    public function getAvatar()
    {
        $name = title_case(str_slug($this->getNameTitle(), ' '));

        return AvatarGenerator::create($name)
            //->setBackground('#fff')
            //->setForeground('#363f44')
            ->setBorder(0, '#fff')
            ->toBase64();
    }
```

Изначально это было в качестве эксперимента, но теперь это может быть лишним оверхедем (генерировать на лету), и с выпуском новой версии laravel, ожидать адаптацию.

### Предлагаемое состояние 1

Отдавать статичное svg изображение, подготовлены в основном [репозитории](https://github.com/orchidsoftware/platform/tree/master/public/img/avatars) (16 штук), предлагаю оставить одну и назначить её по умолчанию

```php
    /**
     * @return string
     * @throws \Exception
     */
    public function getAvatar()
    {
        return url()->asset('/orchid/img/avatars/users-1.svg',request()->isSecure());
    }
```

### Предлагаемое состояние 2

Отдавать реальные аватары пользователей от [gravatar](https://ru.gravatar.com/)

```php
    /**
     * @return string
     * @throws \Exception
     */
    public function getAvatar()
    {
        $hash = md5(strtolower(trim($this->email)));

        return "https://www.gravatar.com/avatar/$hash?f=y";
    }
```

По умолчанию это будет реальной заботой и удобством, но значения "по умолчанию" будет сложнее обрабатывать, так как отправка ссылки на изображения к gravatar требует доступа из "вне"

[![](https://api.gh-polls.com/poll/01CW7EDVTCEYME552284Z01N7Y/%D0%9E%D1%81%D1%82%D0%B0%D0%B2%D0%B8%D1%82%D1%8C%20%D0%BA%D0%B0%D0%BA%20%D0%B5%D1%81%D1%82%D1%8C)](https://api.gh-polls.com/poll/01CW7EDVTCEYME552284Z01N7Y/%D0%9E%D1%81%D1%82%D0%B0%D0%B2%D0%B8%D1%82%D1%8C%20%D0%BA%D0%B0%D0%BA%20%D0%B5%D1%81%D1%82%D1%8C/vote)
[![](https://api.gh-polls.com/poll/01CW7EDVTCEYME552284Z01N7Y/%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%20%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%87%D0%BD%D0%BE%D0%B5%20%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5)](https://api.gh-polls.com/poll/01CW7EDVTCEYME552284Z01N7Y/%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%20%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%87%D0%BD%D0%BE%D0%B5%20%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5/vote)
[![](https://api.gh-polls.com/poll/01CW7EDVTCEYME552284Z01N7Y/%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%20Gravatar)](https://api.gh-polls.com/poll/01CW7EDVTCEYME552284Z01N7Y/%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%20Gravatar/vote)

**Comment by tabuna** [comment]
Голосование завершено. #737 Принят и будет выпущен со следующим релизом

**Comment by d1moncom** [comment]
О нет, только не gravitar!  Зачем мусорить ненужным кодом? Кому надо, тот сам себе прикрутит gravatar или что-то еще.

**Comment by tabuna** [comment]
> О нет, только не gravitar! Зачем мусорить ненужным кодом? Кому надо, тот сам себе прикрутит gravatar или что-то еще.

Мы не мусорим ненужным кодом, а используем в качестве заглушки по умолчанию:

```php
    /**
     * @return string
     * @throws \Exception
     */
    public function getAvatar()
    {
        $hash = md5(strtolower(trim($this->email)));

        return "https://www.gravatar.com/avatar/$hash?f=y";
    }
```

Три строчки полезного действия лучше чем пустые значения или аватар по умолчанию для всех.
Каждый может переопределить этот метод в собственной модели. Например:

```php
    /**
     * @return string
     */
    public function getAvatar()
    {
        return url($this->avatar); // вернёт значение поле аватар полном адресе
    }
```

А предыдущие использование laravolt/avatar ведёт к дополнительной зависимости, а так же замедлению генерации страниц (Генерация на лету, base64 и так далее.)

Если у вас есть предложения и вы готовы их реализовать, не стесняйтесь!
