### ISSUE TITLE
Ошибки при редактировании пользователя, модальное окно обновлять страницу

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#728]
- [ ] Имя и email не сохраняются.
- [ ] Пароль не сохраняется
- [ ] Модальное окно при сохранении пароля перегружает страницу, так вроде не должно быть.
- [ ] Пароль скорее всего, будет сохранен не зашифрованным.

**Comment by tabuna** [comment]
Где именно происходят эти проблемы?

**Comment by PSalador** [comment]
/dashboard/users/{id_user}/edit

**Comment by PSalador** [comment]
По 1 пункту [здесь нужно изменить](https://github.com/orchidsoftware/platform/blob/master/install-stubs/Orchid/Screens/User/UserEditScreen.php#L120) на
`->fill($request->get('user'))`
дальше не могу разобраться почему модальное окно стало перезагружать страницу, вроде раньше такого не было, или давно не тестировали это.
Наверно как асинхронно сделали чтобы сохраняло, так и не проверяли этот вариант.

**Comment by tabuna** [comment]
Я изменил некоторые элементы, теперь для асинхронных методов работает DI и можно получать биндинги:

```php
    /**
     * @param User $user
     *
     * @return array
     */
    public function asyncGetUser(User $user) : array
    {
        return [
            'user' => $user,
        ];
    }
```

На текущий момент в модальном окне, нет пароля, это зависит от конфигурации сделанной пользователем.


> Модальное окно при сохранении пароля перегружает страницу, так вроде не должно быть.

Нет это ожидаемое поведение, так как мы не меняем значения в таблице. То есть, если изменить email для пользователя через модальное окно, оно не будет изменено в таблице без обновления страницы
