### ISSUE TITLE
Исключение при создании группы

### ISSUE THREAD

**Issue by Extar93** [orchidsoftware/platform#739]
При создании группы возникает ошибка. В логе 

Illegal string offset 'term' {"userId":4,"email":"***","exception":"[object] (ErrorException(code: 0): Illegal string offset 'term' at /var/www/***/app/Orchid/Screens/Category/CategoryEditScreen.php:89)

Laravel: 5.7
php: 7.2
Nginx, mysql 5.7.24

В дебаг режиме

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db_name`.`term_taxonomy`, CONSTRAINT `term_taxonomy_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `term_taxonomy` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) (SQL: insert into `term_taxonomy` (`term_id`, `taxonomy`, `parent_id`) values (11, category, 0))

В чем может быть проблема и как ее решить ?

**Comment by Extar93** [comment]
Но теперь на рабочем сервере ошибка illegal string offset term, то что в шапке.

**Comment by PSalador** [comment]
Точно такая же ошибка - при создании категории (группы) у которой нет родительской категории(группы)?

**Comment by Extar93** [comment]
Это уже исправилось. Очисткой кеша в laravel.

**Comment by tabuna** [comment]
Если вопрос решён, то можем ли мы закрыть это?

**Comment by Extar93** [comment]
Да

**Comment by tabuna** [comment]
Отлично,  спасибо @PSalador
