### ISSUE TITLE
1071 migration error

### ISSUE THREAD

**Issue by hmzlam** [orchidsoftware/platform#741]
you are using a wrong key length in create_orchid_post_table
`$table->string('slug', '255')->unique();`

the correct way to do it for utf8 is 
`$table->string('slug', '191')->unique();`

**Comment by tabuna** [comment]
Thanks, but where can I read about it?
Am I not entitled to specify any field length in the database?


As I recall it refers [to](https://laravel-news.com/laravel-5-4-key-too-long-error)
```
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long;
   max key length is 767 bytes.
```

That is, for those values where the second parameter is missing, correct me if this is an error

**Comment by hmzlam** [comment]
the problem is that a mysql max object size is 767 , and utf8_mb4 has 4 bytes for every letter, so 191*4=764 the max allowed size,it's a common error in laravel, 

if the second parameter is missing, the laravel users tend to set it in AppServiceProvider like this
 ```
public function boot()
    {
        Schema::defaultStringLength(191); //Solved by increasing StringLength
    }
```
so it's configuration in their project, for me i set it to just 90, because i have an old mysql, and the combined keys will not work either.

the solution is just to leave it to the user project settings, or don't use more than 191 for the second parameter

**Comment by tabuna** [comment]
Oh thank you. I looked at the migration files and it looks like the second argument is used only in one place, let's remove it, and we will not specify it as 191, it will be monotonous

**Comment by tabuna** [comment]
This was changed in the latest release, so I’m closing this issue. If you need to open it again. Thank.
