### ISSUE TITLE
where is the english dashboard

### ISSUE THREAD

**Issue by hmzlam** [orchidsoftware/platform#742]
how to get the english dashboard? 
everything is in russian, i know you have some low quality translation , but how to set it? and which file to translate to get other languages

**Comment by tabuna** [comment]
Oh, we take care to involve as many people as possible to do the translations. You can include them in your configuration file. In the following [way](https://github.com/laravel/laravel/blob/master/config/app.php#L83): `config/app.php`

```php
    /*
    |--------------------------------------------------------------------------
    | Application Locale Configuration
    |--------------------------------------------------------------------------
    |
    | The application locale determines the default locale that will be used
    | by the translation service provider. You are free to set this value
    | to any of the locales which will be supported by the application.
    |
    */
    'locale' => 'en',
```

It is very strange to hear that you see some information in Russian :disappointed:

We store translation files in[ json format](https://github.com/orchidsoftware/platform/tree/master/resources/lang). English is the default language and is the key for further translations.

**Comment by tabuna** [comment]
I think you can close this.
You can open at any time if there are any difficulties.
