### ISSUE TITLE
Unable to generate & populate files

### ISSUE THREAD

**Issue by deknarf** [orchidsoftware/platform#744]
### Expected Behavior
Follow tutorial > Launch application

### Actual Behavior
Follow tutorial > Headache

### Steps to Reproduce the Problem

  1. Follow
  1. The
  1. Tutorial

### Specifications

  - ORCHID Version: **Using version ^3.0 for orchid/platform**
  - Laravel Version: **Laravel Framework 5.7.15**
  - PHP Version: PHP Version => **7.2.12**
  - Database Version: Server version: **10.1.24-MariaDB** | Database client version: **libmysql - 5.1.73**

### Other Notes
This is what happens when I try to install the platform.
I've since edited .env, database.php and a few others, but without luck.

I must add that I have to start all lines with:

> `php -d allow_url_fopen=on`

If I don't, I lack the privileges to execute 95% of the commands.
(`php artisan orchid:install` becomes: `php -d allow_url_fopen=on artisan orchid:install`)
&
(`php composer require orchid/platform` becomes: `php -d allow_url_fopen=on /usr/local/bin/composer require orchid/platform`)

No idea if that is the reason, but either way is it not working for me.

`0/9 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0% < 1 sec Migrating: 2014_10_12_000000_create_users_table

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `reset_password_code` varchar(191) null, `created_at` timestamp null,' at line 1 (SQL: create table `users` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `password` varchar(191) not null, `email` varchar(191) not null, `email_verified_at` timestamp null, `activation_code` varchar(191) null, `locale` varchar(191) null default 'en', `remember_token` varchar(100) null, `activated` tinyint(1) null default '0', `permissions` json null, `reset_password_code` varchar(191) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB)

  at /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `reset_password_code` varchar(191) null, `created_at` timestamp null,' at line 1")
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Database/Connection.php:452

  2   PDO::prepare("create table `users` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `password` varchar(191) not null, `email` varchar(191) not null, `email_verified_at` timestamp null, `activation_code` varchar(191) null, `locale` varchar(191) null default 'en', `remember_token` varchar(100) null, `activated` tinyint(1) null default '0', `permissions` json null, `reset_password_code` varchar(191) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB")
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Database/Connection.php:452

  3   Illuminate\Database\Connection::Illuminate\Database\{closure}("create table `users` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `password` varchar(191) not null, `email` varchar(191) not null, `email_verified_at` timestamp null, `activation_code` varchar(191) null, `locale` varchar(191) null default 'en', `remember_token` varchar(100) null, `activated` tinyint(1) null default '0', `permissions` json null, `reset_password_code` varchar(191) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB", [])
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Database/Connection.php:657

  4   Illuminate\Database\Connection::runQueryCallback("create table `users` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `password` varchar(191) not null, `email` varchar(191) not null, `email_verified_at` timestamp null, `activation_code` varchar(191) null, `locale` varchar(191) null default 'en', `remember_token` varchar(100) null, `activated` tinyint(1) null default '0', `permissions` json null, `reset_password_code` varchar(191) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB", [], Object(Closure))
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624

  5   Illuminate\Database\Connection::run("create table `users` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `password` varchar(191) not null, `email` varchar(191) not null, `email_verified_at` timestamp null, `activation_code` varchar(191) null, `locale` varchar(191) null default 'en', `remember_token` varchar(100) null, `activated` tinyint(1) null default '0', `permissions` json null, `reset_password_code` varchar(191) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB", [], Object(Closure))
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Database/Connection.php:459

  6   Illuminate\Database\Connection::statement("create table `users` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `password` varchar(191) not null, `email` varchar(191) not null, `email_verified_at` timestamp null, `activation_code` varchar(191) null, `locale` varchar(191) null default 'en', `remember_token` varchar(100) null, `activated` tinyint(1) null default '0', `permissions` json null, `reset_password_code` varchar(191) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB")
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php:97

  7   Illuminate\Database\Schema\Blueprint::build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:264

  8   Illuminate\Database\Schema\Builder::build(Object(Illuminate\Database\Schema\Blueprint))
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:165

  9   Illuminate\Database\Schema\Builder::create("users", Object(Closure))
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:223

  10  Illuminate\Support\Facades\Facade::__callStatic("create")
      /home/quale/public_html/tnt/database/migrations/2014_10_12_000000_create_users_table.php:35

  11  CreateUsersTable::up()
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:360

  12  Illuminate\Database\Migrations\Migrator::Illuminate\Database\Migrations\{closure}()
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:367

  13  Illuminate\Database\Migrations\Migrator::runMigration(Object(CreateUsersTable), "up")
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:178

  14  Illuminate\Database\Migrations\Migrator::runUp("/home/quale/public_html/tnt/database/migrations/2014_10_12_000000_create_users_table.php")
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:147

  15  Illuminate\Database\Migrations\Migrator::runPending([])
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:96

  16  Illuminate\Database\Migrations\Migrator::run([])
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:71

  17  Illuminate\Database\Console\Migrations\MigrateCommand::handle()
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

  18  call_user_func_array([])
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

  19  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87

  20  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31

  21  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Container/Container.php:572

  22  Illuminate\Container\Container::call()
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Console/Command.php:183

  23  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
      /home/quale/public_html/tnt/vendor/symfony/console/Command/Command.php:255

  24  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Console/Command.php:170

  25  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Console/Command.php:198

  26  Illuminate\Console\Command::call("migrate", ["migrate"])
      /home/quale/public_html/tnt/vendor/orchid/platform/src/Platform/Commands/InstallCommand.php:98

  27  Orchid\Platform\Commands\InstallCommand::executeCommand("migrate")
      /home/quale/public_html/tnt/vendor/orchid/platform/src/Platform/Commands/InstallCommand.php:60

  28  Orchid\Platform\Commands\InstallCommand::handle()
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

  29  call_user_func_array([])
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

  30  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87

  31  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31

  32  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Container/Container.php:572

  33  Illuminate\Container\Container::call()
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Console/Command.php:183

  34  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /home/quale/public_html/tnt/vendor/symfony/console/Command/Command.php:255

  35  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Console/Command.php:170

  36  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/quale/public_html/tnt/vendor/symfony/console/Application.php:901

  37  Symfony\Component\Console\Application::doRunCommand(Object(Orchid\Platform\Commands\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/quale/public_html/tnt/vendor/symfony/console/Application.php:262

  38  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/quale/public_html/tnt/vendor/symfony/console/Application.php:145

  39  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Console/Application.php:89

  40  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/quale/public_html/tnt/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122

  41  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/quale/public_html/tnt/artisan:37
`

**Comment by PSalador** [comment]
Update version of MariaDB database to at least 10.3.2

**Comment by PSalador** [comment]
The JSON alias was added in [MariaDB 10.2.7. ](https://mariadb.com/kb/en/library/json-data-type/)

**Comment by tabuna** [comment]
Hi, @deknarf , oh this is a very difficult problem that I solve every day.

The `allow_url_fopen` setting is enabled by default in [PHP configurations](http://php.net/manual/en/filesystem.configuration.php)

If you write a manual that covers all the required settings, including the versions, parameters, environment, then I am sure that you would not even want to read it.

I have neither the strength nor the time to describe under 99% of cases, it is better to do under 50%, but it’s good, than to cover in most cases not the necessary material.

Thanks to such cases as this one, users with disabled options will know that they need to be enabled in order to work.

As for the database, currently the Laravel framework does not support 100% MariaDB base.

This is due to the fact that until recently MariaDB and MySQL were fully compatible, but were divided into variations of JSON processing. The necessary patches have already been created in Laravel, but they will be accepted only in the future version 5.8 . 

You can look at this [PR](https://github.com/laravel/framework/pull/25517) or find dozens of issue on this topic.

This has been going on for a very long time ... For example, our research with the same [problem](https://github.com/orchidsoftware/platform/issues/643) As a workaround, I have advised the [package](https://github.com/ybr-nx/laravel-mariadb) that makes JSON workable in MariaDB

If you have any questions or suggestions, please do not hesitate.
