### ISSUE TITLE
Illuminate\Database\QueryException : SQLSTATE[42000] Exception on migrate command

### ISSUE THREAD

**Issue by asimshazad** [orchidsoftware/platform#747]
Getting mysql error on install command

Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null' at line 1

Please have a look below attached picture.
![screen shot 2018-12-13 at 3 19 11 pm](https://user-images.githubusercontent.com/14991207/49932444-d8eccc80-feea-11e8-9eb8-6b7ee41e5c87.png)

**Comment by tabuna** [comment]
Is this no longer a problem? What database are you using and which version?

**Comment by asimshazad** [comment]
I am using MySQL,I converted all the jsonb and json in migration to text and it worked.
