### ISSUE TITLE
Updated Laravel Mix 4.0

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#749]
https://github.com/JeffreyWay/laravel-mix/releases/tag/v4.0.0

**Comment by Sylk** [comment]
@tabuna close this

**Comment by tabuna** [comment]
Hello @Sylk , why should it be closed?
I think this is an urgent [task](https://github.com/orchidsoftware/platform/blob/3a3226fec07ccbfcfa07d8824cfafc183f47ec63/package.json#L32), which can be a great start for the first investment in the project.
