### ISSUE TITLE
Ошибка в документации

### ISSUE THREAD

**Issue by mkswebdev** [orchidsoftware/platform#751]
Здесь:
https://orchid.software/ru/docs/authentication

Сейчас:

Обратите внимание, что его необходимо указывать раньше dashboard
    'middleware' => [
        'public'  => ['web'],
        'private' => ['web', 'platform'],
    ],

Надо:

Обратите внимание, что его необходимо указывать раньше **platform**
    'middleware' => [
        'public'  => ['web'],
        'private' => ['web', **'auth',** 'platform'],
    ],

И здесь:
https://orchid.software/en/docs/authentication

Надо:
Pay attention that this value must be defined before **platform**

    'middleware' => [
        'public'  => ['web'],
        'private' => ['web', 'auth', **'platform'**],
    ],

**Comment by tabuna** [comment]
Обратите внимание, что на каждой странице существует возможность её редактировать:

![screenshot-46 101 147 145-2018 12 20-10-22-27](https://user-images.githubusercontent.com/5102591/50270743-a8a1b280-0443-11e9-9d64-72b3a625002a.png)

Это помогает исправлять неточности сразу же при их обнаружении, тем самым делая проект более качественным и дружелюбным. 

Я исправил эти устаревшие данные, спасибо, что написали.
