### ISSUE TITLE
Failed to render map in blade view. 

### ISSUE THREAD

**Issue by marioperezio** [orchidsoftware/platform#754]
Hello good afternoon, first of all, my apologies if this is not the right place to post this comment, but I can not find the information I need on the website. Does anyone know where to find enough information and examples (please) about this framework? I am trying to show without success the map and the categories and / or taxonomies in the blade views. Let's start with the map!

### Expected Behavior
The map should be displayed in the blade view for a better user experience.

### Actual Behavior
When entering the URL of the view you get an exception error, specifically:
```
ErrorException (E_ERROR)
htmlspecialchars () expects parameter 1 to be string, given array (View: /home/username/public_html/projects/my-projects/resources/views/events/index.blade.php)
```

### Steps to Reproduce the Problem
  1. I have created a new entity class: `php artisan orchid:entity-many Events`
  2. Then in the file `config/platform.php` I enable this new class:
```
[...]
    'many' => [
        \App\Orchid\Entities\Events::class,
    ],
[...]
```
  3. In the `app/Orchid/Entities/Events.php` file, I add the field "MapField":
```
[...]
MapField::make('place')
       ->title('Location on the map')
       ->help('Enter the coordinates, move the pointer or use the search'),
[...]
```
  4. I create the controller and the view, and then I configure the route:
  The code in the `app/Http/Controllers/EventController.php` file is:
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Orchid\Press\Models\Post;

class EventsController extends Controller
{
    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $posts = Post::type('events')
            ->status('publish')
            ->with('attachment')
            ->orderBy('publish_at', 'Desc')
            ->paginate(6);

        return view('events.index', [
            'posts' => $posts
        ]);
    }

    /**
     * @param Post $post
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Post $post)
    {
        return view('events.show', [
            'post' => $post
        ]);
    }
}
```
The code in the `resources/views/events/index.blade.php` file is:
```
[...]
<div>
    {{ $post->getContent('place') }}
</div>
[...]
```
The code in the `routes/web.php` file is:
```
[...]
Route::get('/events','EventsController@index');
Route::get('/events/{events}','EventsController@show')
    ->where('events','^(?!dashboard).*$')
    ->name('events.show');
[...]
```
The code in the `app/providers/RouteServiceProvider.php` file is:
```
<?php
  [...]
  use Orchid\Press\Models\Post;
  [...]
  class RouteServiceProvider extends ServiceProvider
  {
   [...]
       /**
     * Define the routes for the application.
     *
     * @return void
     */
    public function map()
    {
        $this->mapApiRoutes();

        $this->mapWebRoutes();

        //

        Route::bind('events', function ($value) {
            return Post::where('slug', $value)
                ->type('events')
                ->with(['attachment'])
                ->firstOrFail();
        });
    }
   [...]
```
### Specifications

  - ORCHID Version: 3.2.2
  - Laravel Version: 5.7.19
  - PHP Version: 7.2.1
  - Database Version: 10.3.11-MariaDB

### Other Notes
I think this is good software, but it is failing in its documentation (it is not complete, there is not a HOW TO from A to Z). As a student of Software Engineering, my advice is to improve this point a lot, make it understandable to all developers and you will surely find many contributions from the community.

**Comment by tabuna** [comment]
Hello @marioperezio , the error you cited clearly indicates what happened.

What you transmit with the blade actually looks something like this.
```php
$variable = 'loprem...';
```
In blade:
```php
 {{ $variable }}
```
compile file:
```php
echo _e($variable)
```

And there are 2 nuances:

- The first one is told to you right in the error that the argument passed is an **array, not a string**.
- The second is that it is impossible to output an array using the **echo** operator


This brings us closer to exploring the map field itself. It contains coordinates, namely latitude and longitude. You can see it with a dump:

```php
dd( $post->getContent('place') );
```

These coordinates you can transfer directly to your visual presentation (for example, Google maps)

```php
$map = $post->getContent('place');

echo $map['Key name'];
```

I hope I answered your question.

-----

As for taxonometry, we have an [example](https://orchid.software/en/docs/post#categories-and-taxonomy).

Maybe you should learn more about the[ Laravel framework](https://laravel.com) itself, on which this package is based, since the documentation does not cover the explanations that go beyond its borders.

As for the question on the example from A to Z, I am [working](https://github.com/tabuna/book/blob/master/manuscript/chapter5.md) on it, but at the moment it is not the English version.

But in reality, we do not invent magic that would be so difficult to use that a huge paper manual was needed, if you have any suggestions, please deposit your treasure, this will benefit all of us.

**Comment by marioperezio** [comment]
Hello @tabuna, thanks for your message! I found a solution and I hope it is the cleanest. Reviewing the Orchid code, I see that you use the latest version of the Leaflet API for map rendering. Within the core of Orchid are importing the files required by the API. This works very well in the backend of our application, and if we want it to work in the frontend, we must follow the steps of the API documentation. In summary, my solution is as follows (only as a reference for other developers):

++ Step 1. Include the .css files required by Leaflet in the `resources/views/layouts/app.blade.php`:
```
[...]
<head>
    [...]
    {{--Leaflet's CSS--}}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css"
          integrity="sha512- 
puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="crossorigin=""/>
    [...]
</head>
<body>
    [...]
    @stack('scripts')
    [...]
</body>
[...]
```
++ Step 2. Include the `.js` files in the view where we want to show the map, in my case: `resources/views/events/index.blade.php`, also, include a "div" tag with the map identifier. Finally we will initialize the map. The coordinates are taken from the data stored in the database: 
```
[...]
<body>
    [...]

    <div id='map'></div>

    @push('scripts')

        {{--Leaflet's JS--}}
        <script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
            integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="crossorigin="">
       </script>

       <script>
           // Initialize the map ...
          let map = L.map('map', {
              center: [
                  @php
                      $map = $post->getContent('place');
                      echo $map['lat'];
                  @endphp,
                  @php
                      $map = $post->getContent('place');
                      echo $map['lng'];
                  @endphp
              ],
              zoom: 15
          });

          L.tileLayer( 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
              attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
              subdomains: ['a','b','c']
          }).addTo( map );
       </script>

    @endpush
</body>
[...]
```
Well, this is the pragmatic solution that I found, tell me if it is a clean method, if it matches what you think should be done. Thank you.

**Comment by tabuna** [comment]
I think it would be very nice for you to get acquainted with the package building system and the manager. For example Laravel already offers [Mix](https://laravel.com/docs/5.7/mix).

You could also reduce the number of calls using `dot notation`:

```javascript
          let lat = {{  $post->getContent('place.lat')  }} ;
          let lat = {{  $post->getContent('place.lng') }} ;

          let map = L.map('map', {
              center: [ lat, lng ],
              zoom: 15
          });
```

This will make the code more readable.
