### ISSUE TITLE
страница с настройками

### ISSUE THREAD

**Issue by dormadekhin** [orchidsoftware/platform#760]
Добрый день, есть ли готовая реализованная страница с настройками? 
Чтобы добавить туда статическую информацию, телефон и другое
нашел в документации что [настройки ](https://orchid.software/ru/docs/settings), а самой готовой страницы нет, ее нужно создать самому?

**Comment by tabuna** [comment]
Предопределённой страницы с настройками нет, так как нельзя задействовать их для различных возможных вариантов, которые бы удовлетворили всех. Например, некоторые параметры, которые кажутся вам разумными, для других могут показаться бессмысленными.

Сделать новый экран для них, не затратное дело, думаю это не займёт у вас больше 15 минут.

 Я так же знаю о существовании стороннего [расширения](https://github.com/orchidcommunity/XSetting), даже с описанием того, как его [делали](https://github.com/orchidcommunity/XSetting/blob/master/docs/new_package_ru.md), но не могу дать ни каких гарантий на его счёт (@PSalador ping).

-----

У нас так же нет планов по добавлению такой страницы в `app/Orchid/` в качестве примера, но я не против видеть её в ближайшем будущем.

**Comment by tabuna** [comment]
Если появятся вопросы или предложения, откройте эту ветку снова.

**Comment by PSalador** [comment]
Обновил расширение.
