### ISSUE TITLE
Список моделей

### ISSUE THREAD

**Issue by dormadekhin** [orchidsoftware/platform#761]
После создания модели, в интерфейсе она не отображается

**Comment by tabuna** [comment]
Что вы подразумеваете под моделью? Могу предположить, что вы сгенерировали какой либо Entity, но не установили на него права пользователю

**Comment by dormadekhin** [comment]
Имел ввиду то, что в строителе моделей, после нажатия на кнопку "сборка всех моделей", они пропадают из интерфейса строителя моделей

**Comment by tabuna** [comment]
Это нормальная работа сценария. 

Строитель формирует некоторые данные, которые позднее будут преобразованы в объект, тем самым позволяет только создавать, но не редактировать реальные файлы. Так как для этого потребуется достаточно количество ресурсов, помимо парсинга и разложения требуется сохранение предыдущих структур (_Модель может быть унаследована от другой, или иметь различные методы и свойства_), к тому же мы должны обеспечивать совместимость на уровне базы данных, генерируя файлы миграций, что влечёт за собой постоянную слежку за структурой, что тянет ещё и ключи.

Если коротко, то пока ещё не научились.
Это слишком затратные средства, которые к тому же очень хрупки в изменениях.

Его предназначение только помочь на старте.
