### ISSUE TITLE
Поле Select не сохраняет несколько значений

### ISSUE THREAD

**Issue by adxin** [orchidsoftware/platform#763]
Возможно я что то не понимаю, поля плохо расписаны в доках
добавил поле select:
```php
            SelectField::make()
                ->options([
                    'jan'   => 'Январь',
                    'feb' => 'Февраль',
                    'mar' => 'Март',
                    'apr' => 'Апрель',
                    'may' => 'Май',
                    'jun' => 'Июнь',
                    'jul' => 'Июль',
                    'aug' => 'Август',
                    'sep' => 'Сентябрь',
                    'oct' => 'Октябрь',
                    'nov' => 'Ноябрь',
                    'dec' => 'Декабрь',
                ])->multiple()
                ->name('select_months')
                ->title('Выбрать месяцы')
                ->help('...'),
```

Но сохраняется только последний выбранный элемент.

### Specifications

  - ORCHID Version: 3.6.1
  - Laravel Version: 5.7.21
  - PHP Version: 7.2
  - Database Version:  Mysql 5.7

**Comment by tabuna** [comment]
Вы сохраняете только одно значение, потому что только оно отправляется, ваш код сгенерирует следующее <select name=select_months> , хоть поле и является multiple форма отправит только одно значение, это обычное поведение, которое вы можете воспроизвести используя только html. Для того, что бы это работало как вы ожидаете форма должна содержать имя как массив значений select_months[] для этого просто переименуйте аргумент name добавив в конец точку : «select_months.»

**Comment by adxin** [comment]
О благодарю!
