### ISSUE TITLE
Can't use registerResource in package

### ISSUE THREAD

**Issue by Nks** [orchidsoftware/platform#765]
### Expected Behavior
We can add the resource (css, js) from other package to platform with this logic:

```
class ServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot(Dashboard $dashboard)
    {
        $dashboard->registerResource([
'scripts' => [
                mix('/js/repeater.js', 'orchid_repeater')
            ],
            'stylesheets' => [
                mix('css/repeater.css', 'orchid_repeater')
            ]
]);
    }
}
````

### Actual Behavior
If we already have styles and scripts in configuration it will just overwrite resources which added by external package

### Steps to Reproduce the Problem
Here we have `orchid_repeater/js/repeater.js` which added by external package
![image](https://user-images.githubusercontent.com/349293/51673806-03e53880-1fe0-11e9-8dce-68a52633df71.png)

On this endpoint we already have only `js/backend.js` which was added to `config/platform.php`
![image](https://user-images.githubusercontent.com/349293/51673817-08115600-1fe0-11e9-86cf-1ae30b7ba988.png)

### Specifications

  - ORCHID Version: 3.6.1
  - Laravel Version: 5.7.22
  - PHP Version: 7.2.1
  - Database Version: mysql 5.7.23

### Other Notes
Temporary solution:
```
Config::set('platform.resource.scripts', array_merge(config('platform.resource.scripts', []), [ 
             mix('/js/repeater.js', 'orchid_repeater') 
         ])); 
  
         Config::set('platform.resource.stylesheets', array_merge(config('platform.resource.stylesheets', []), [ 
             mix('css/repeater.css', 'orchid_repeater') 
         ])); 
```

**Comment by tabuna** [comment]
Documentation states that it should be like this:

```php
      $dashboard->registerResource('stylesheets','/orchid/repeater.css');
      $dashboard->registerResource('scripts','/orchid/repeater.js');
```

I corrected this behavior so that this would not happen in the [future](https://github.com/orchidsoftware/platform/blob/c8b881798c29585f327416847c2c56f7eb4b916a/tests/Unit/DashboardTest.php#L55-L101)

This will be fixed in 3.6.2.
