### ISSUE TITLE
Multiple select doesn't work

### ISSUE THREAD

**Issue by Nks** [orchidsoftware/platform#766]
It allow you to select multiple values, but not saving it.

Example code:

```
SelectField::make('select_all')
                ->options([
                    'index'   => 'Index',
                    'noindex' => 'No index',
                ])
                ->title('Select tags')
                ->multiple()
                ->help('Allow search bots to index');
```

In the db it saving just this:
```
"select_all": "noindex"}}
```

**Comment by tabuna** [comment]
Added dot notation (#763 and etc)

```php
SelectField::make('select_all.')
                ->options([
                    'index'   => 'Index',
                    'noindex' => 'No index',
                ])
                ->title('Select tags')
                ->multiple()
                ->help('Allow search bots to index');
```

**Comment by tabuna** [comment]
Условно:

```html
<select name="select_all" multiple>
  <option value="1">Пункт 1</option>
  <option value="2">Пункт 2</option>
</select>
```
Не отошлёт 2 значения, хотя поле и является `multiple` ,  в html вы должны записать как:

```html
<select name="select_all[]" multiple>
  <option value="1">Пункт 1</option>
  <option value="2">Пункт 2</option>
</select>
```

То же самое вы должны сделать и с генератором, потому что он старается сгенерировать форму без искажений.

Вы можете записать как `SelectField::make('select_all[]')` или через точку означающий обращение 'SelectField::make('select_all.')'

**Comment by Nks** [comment]
При попытке указать поле с указанием массива получается так:
![image](https://user-images.githubusercontent.com/349293/51691575-15dcd080-200c-11e9-97ba-a1f70241ad07.png)

Если указывать с точкой - все вроде бы норм. 

Неплохо было бы задокументировать.

**Comment by Nks** [comment]
Имхо правильным вариантом было при multiple добавлять [] в любом случае.

**Comment by tabuna** [comment]
> При попытке указать поле с указанием массива получается так:

Так только в entity из-за того, что обработка идёт последовательно, в экранах такого нет. По этому по умолчанию советую точку.

> Имхо правильным вариантом было при multiple добавлять [] в любом случае.

Уже не помню, почему этот вариант не подошёл и больше мы его не рассматривали, теоретически даже сейчас можно поставить обработчик для `multiple`
