### ISSUE TITLE
The Mix manifest does not exist.

### ISSUE THREAD

**Issue by Farhadsaadatpei** [orchidsoftware/platform#768]
### Expected Behavior
Visit /dashboard -> Show dashboard view.

### Actual Behavior
Visit /dashboard -> Exception error.
The Mix manifest does not exist. (View: /home/vagrant/Sites/learn/vendor/orchid/platform/resources/views/layouts/app.blade.php) (View: /home/vagrant/Sites/learn/vendor/orchid/platform/resources/views/layouts/app.blade.php) (View: /home/vagrant/Sites/learn/vendor/orchid/platform/resources/views/layouts/app.blade.php)

### Steps to Reproduce the Problem

  1. Reinstall Orchid, because I saw in Public directory (orchid>public) keep repeating itself, please see screenshot.

Screenshot: 
https://www.photobox.co.uk/my/photo/full?photo_id=501615208167

### Specifications

  - ORCHID Version: 3.6.2
  - Laravel Version: 5.7.22
  - PHP Version: 7.1.19

### Other Notes
I'm using homestead, can't figure a way to solve this. As you mentioned [here](https://github.com/orchidsoftware/platform/issues/663), All folders and files are there. How can I solve this?

**Comment by Farhadsaadatpei** [comment]
I did read that part. and preform the neccessery steps, still no luck. Here is the screenshot.
<img width="825" alt="screen shot 2019-01-27 at 9 02 48 am" src="https://user-images.githubusercontent.com/10551124/51802280-7a6b7b80-2216-11e9-8ac2-73b1fc571f50.png">

**Comment by tabuna** [comment]
Do I understand correctly that this is a symbolic link?

**Comment by tabuna** [comment]
What error do you get when you explicitly access the file?

If you use apache, then make sure that the settings allow links
```bash
Options +Includes +FollowSymLinks
```

**Comment by Farhadsaadatpei** [comment]
I believe so. But the public folder keep getting created when I run `cp -rf vendor/orchid/platform/public public/orchid`

**Comment by Farhadsaadatpei** [comment]
Apache is already follow: 
`Options +Includes +FollowSymLinks`

**Comment by Farhadsaadatpei** [comment]
I try creating it using `php artisan orchid:link`, still 
<img width="715" alt="screen shot 2019-01-27 at 9 43 16 am" src="https://user-images.githubusercontent.com/10551124/51802423-003bf680-2218-11e9-9b22-cc74836afa5e.png">

**Comment by tabuna** [comment]
Oh, damn, I noticed an error, in your screenshot, which says that in the `public` directory there is another `public` directory, so it should not be, it should be called `orchid`

![2019-01-27 17-45-26](https://user-images.githubusercontent.com/5102591/51802444-5a11e000-225b-11e9-9b8c-f92ce688554b.png)

**Comment by Farhadsaadatpei** [comment]
It does call orchid. :/
<img width="413" alt="screen shot 2019-01-27 at 9 48 30 am" src="https://user-images.githubusercontent.com/10551124/51802508-c61f2480-2218-11e9-8e1f-9dbb0e93db73.png">

**Comment by tabuna** [comment]
Hmm, good.

Try to access the file directly, for example:

```
http://your.site:port/orchid/mix-manifest.json
```

What error do you get? Access is denied? Not found?

**Comment by Farhadsaadatpei** [comment]
```
Forbidden
You don't have permission to access /public/orchid/mix-manifest.json on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by tabuna** [comment]
Great, since this is a 403 error, this is handled by the web server.

It is possible that some directories have different access rights or a problem in the configuration (I hope you did not forget to reboot it, after the changes).

Oh, this option is not written in  .htaccess

Since this will add without the current directory, please add it to a higher level.

```apache2
    <VirtualHost *:80>
 
      <Directory "path/to/laravel">
        Options Indexes FollowSymLinks
      </Directory>
      ...
   </VirtualHost>
```

**Comment by tabuna** [comment]
I do not have wide experience with apache2, as I use Nginx,
but I think we found the source of the problem and you can fix it

**Comment by Farhadsaadatpei** [comment]
@tabuna yes make sense now. I just need to figure out a way to access apache for the homestead. which I been having a hard time with lately. but I see your point. Thank you.

**Comment by tabuna** [comment]
Since version 3.8, we no longer use symbolic links.
If you could not set up your apache, now there is no need;)
