### ISSUE TITLE
Select lazyload multiple

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#772]
### Expected Behavior

Add muliple select support with lazy boot:

```php
RelationshipField::make()
    ->name('my_title')
    ->required()
    ->multiple()
    ->title('My title')
    ->handler(AjaxWidget::class);
```

### Other Notes

I think it is worth refusing to use the widget class, but I’m not sure how best to build an alternative. :pensive:
 If anyone has any suggestions please feel free to

**Comment by tabuna** [comment]
New version:

```php
Relation::make('roles.')
   ->fromModel(Role::class, 'name')
   ->title('Select many roles')
   ->multiple(),

Relation::make('role')
    ->fromModel(Role::class, 'name')
    ->title('Select one role'),
```

**Comment by tabuna** [comment]
Example query:

```php
namespace App;

use Illuminate\Database\Eloquent\Model;

class Idea extends Model
{

    /**
     * @param Builder $query
     *
     * @return Builder
     */
    public function scopeActive(Builder $query)
    {
        return $query->where('active', true);
    }
}

```


Field:

```php
Relation::make('idea')
    ->fromModel(Idea::class, 'name')
    ->applyScope('active')
    ->title('Select one idea'),
```

**Comment by PSalador** [comment]
Нужно ещё на основе этого сделать поле состоящее из нескольких селектов.
Примерные варианты:
1) Цитата из чата в телеграмм:

> Подскажите, а есть возможность делать зависимости от поля? Например:
> Есть 2 Select: Category и Subcategory. И в зависимости от выбора в Category, в Subcategory подгружаются разные данные?

2) Выбор адреса:
Первый select - страна, 
второй select - регион,
третий select - город.

3) Выбор элемента модели:
Первый select - выбор модели (категории, посты, страницы) 
второй select - запрос по модели.

**Comment by tabuna** [comment]
> Нужно ещё на основе этого сделать поле состоящее из нескольких селектов.
> Примерные варианты:

Есть отдельный таск, этот закроем и задокументируем
