### ISSUE TITLE
Запуск на windows+homestead 404

### ISSUE THREAD

**Issue by MikhailGennadevic** [orchidsoftware/platform#773]
- ORCHID Version: 3.7
  - Laravel Version: 5.7.22
  - PHP Version: 7.2.9
  - Database Version: 5.7.23

Установил orched на homestead.
Дополнительные команды указанные в конфигурации выполнил.
Все роуты отображаются.
http://orchid.loc/dashboard - при открытие страница 404.
как исправить?

**Comment by tabuna** [comment]
Удостоверьтесь, что адрес перехода и запись в .env файле совпадают

**Comment by MikhailGennadevic** [comment]
После вашего сообщения наконец понял в чем ошибка...

DASHBOARD_DOMAIN=http://orchid.loc/ - лишний слеш
