### ISSUE TITLE
Работа со своими сущностями

### ISSUE THREAD

**Issue by EvvC** [orchidsoftware/platform#776]
Хай. Может кто-нибудь рассказать о преимуществах использования моделей, наследующих Маny / 
 Post, вместо своих моделей? Точнее что придется реализовывать вручную при выборе такого подхода, а что можно подключить трейтами? Например, делаю я класс, наследующий Table для вывода в layout экрана и добавляю колонки в методе fields - TD::set('price', 'Цена')->sort(). Сортировка работать не будет.

**Comment by tabuna** [comment]
Привет @EvvC 

> Может кто-нибудь рассказать о преимуществах использования моделей, наследующих Маny /
Post, вместо своих моделей?

Обычно класс `Post` не наследуются (хотя его можно наследовать и подменять). 

С технической точки зрения моно-модель уступает Вашим собственным по определению, но оно очень выгодно при массовом использовании, например:

-  Существуют очень похожие записи
-  Съхема данных не определена 
- _ААааа, нужно срочно добавить_
- и т.п.


Если вы используете собственные модели/репозитории, то **точно ничего не теряете**, пакет ни диктует, что нужно пользоваться чем то одним - такого нет.

> Точнее что придется реализовывать вручную при выборе такого подхода, а что можно подключить трейтами?

Всё, что умеют `Entity` вы можете построить самостоятельно для своей модели.

> Например, делаю я класс, наследующий Table для вывода в layout экрана и добавляю колонки в методе fields - TD::set('price', 'Цена')->sort(). Сортировка работать не будет.

Тут вы заблуждаетесь есть трейд `Orchid\Platform\Traits\FilterTrait` который позволяет делать всё то же самое со своими [моделями](https://github.com/orchidsoftware/platform/issues/621).

**Comment by EvvC** [comment]
Спасибо за быстрый ответ, что-то подобное было бы уместно в начале раздела "Сущности системы управления" документации, а то немного сбивает с толку фраза
> Сущность является основной частью системы управления содержимым ORCHID

Мне просто недостает списка того, что есть из коробки для работы со своими моделями. То есть для Post есть много всего и сам Post является примером на максималках. И вот классно было бы еще пример обычной модели на таких же "максималках", включая применение на нее FilterTrait

**Comment by tabuna** [comment]
> Спасибо за быстрый ответ, что-то подобное было бы уместно в начале раздела "Сущности системы управления" документации, а то немного сбивает с толку фраза

Документация пишется в свободное время и не профессионалами, но мы стараемся держать её как можно более точной и актуальной, если вы увидели ошибку или можете написать более точное/подходящее выражение, пожалуйста не стесняйтесь:

![screenshot-orchid software-2019 02 07-19-54-13](https://user-images.githubusercontent.com/5102591/52428256-a76f3680-2b12-11e9-935f-dcf56030c5e1.png)
