### ISSUE TITLE
Редактирование UploadField

### ISSUE THREAD

**Issue by EvvC** [orchidsoftware/platform#778]
Привет, в поле UploadField у загруженных файлов есть кнопка редактирования при наведении. 
![image](https://user-images.githubusercontent.com/24358689/52537058-2c588b00-2d73-11e9-8864-e945e7221d3f.png)
Нажатие дает только затемнение экрана, модальное окно не появляется.
listener на них такой 
![image](https://user-images.githubusercontent.com/24358689/52537074-6c1f7280-2d73-11e9-968f-621d145435be.png)

**Comment by tabuna** [comment]
Какую версию orchid вы используете, а так же браузер?

![screenshot-localhost-8000-2019 02 10-21-33-28](https://user-images.githubusercontent.com/5102591/52537801-9f65ff80-2d7b-11e9-83c5-059758600bf6.png)

**Comment by EvvC** [comment]
Orchid 3.8.1
Chrome 71.0.3578.98

**Comment by tabuna** [comment]
Пожалуйста обновитесь до 3.9.0

**Comment by EvvC** [comment]
Модальное окно появляется, все норм. Изменения сохраняются в полях Alternative text и Description. В Display Name не сохраняются

**Comment by tabuna** [comment]
Пожалуйста обновитесь до 3.9.2

**Comment by EvvC** [comment]
Обновился до 3.9.6, модальное окно снова не появляется

**Comment by tabuna** [comment]
@EvvC Хм, изменения не вносились. Не могу воспроизвести проблему.
Возможно это из-за разнице версий bootstrap, в ближайшее время пересоберу с самой версией

**Comment by tabuna** [comment]
Решено.
