### ISSUE TITLE
Screen form send error in 3.9.2

### ISSUE THREAD

**Issue by Leshkens** [orchidsoftware/platform#783]
При вызове метода save у экрана ничего не происходит и в консоли появляется ошибка.

![6wn1fxyr1k](https://user-images.githubusercontent.com/8939383/52626858-ecf67f80-2ed5-11e9-80aa-13105703abbc.gif)

Метод `save` стандартен:
```
public function save(Customer $customer, SaveCustomerRequest $request)
{
     $customer->fill($request->get('customer', []))->save();
     Alert::info(__('Customer was saved'));
     return redirect()->route('platform.customers');
}
```
Подозреваю что дело в маске (inputmask), а именно в опции `removeMaskOnSubmit`.

Вот так выглядит поле:
```
          InputField::make()
                        ->name('customer.phone')
                        ->autocomplete('off')
                        ->required()
                        ->title(__('Main phone number'))
                        ->mask([
                            'removeMaskOnSubmit' => true,
                            'mask' => '+7 (999) 999-99-99',
                            'definitions' => [
                                "7" => [
                                    'validator' => "7"
                                ]
                            ],
                        ]),
```
Скорее всего при отправке через ajax запроса не происходит вызова события `submit`, соответственно маска не удаляется и дальше валидатор на стороне бэкэнда не пропускает номер телефона с маской (т.е с пробелами, скобками и проч.). **Ошибка валидатора, кстати тоже не выводиться.**

Что интересно, в фильтрах вроде как такой проблемы нет.

На 3.9.1, само собой, все в порядке, т.к форма отправляется не через ajax.

### Specifications

  - ORCHID Version: 3.9.2

**Comment by tabuna** [comment]
В **3.9.3** изменил событие на `submit`,
теперь можно любую форму отправлять POST запросом без полной перезагрузки страницы добавив:

```html
    <form 
          data-controller="layouts--form"
          data-action="layouts--form#submit">
    </form>
```
Элементы страницы обновятся автоматически.

----

- Пример с маской - теперь работает правильно
- Ошибки валидатора - отображаются


Спасибо :blush: , не стесняйтесь открывать новые issue в случаи проблемы

**Comment by tabuna** [comment]
К сожалению версия 3.9.3 не принесла изменений с отправкой маски.
Потратив много времени, не нашёл варианта решения, кроме установки ожидания 
в javasrcipt сценарий. Попробуйте 3.9.4
