### ISSUE TITLE
Что не работает после обновления до 3.9.5

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#784]
1. В левом меню (Orchid\Platform\ItemMenu) нет добавления класса типа SetClass - было удобно выделять пункты меню.
2. В Layouts тоже не стало возможности добавлять класс, код:
```
            Layouts::modals([
                'HelpModal' => [
                    HelpModalLayout::class,
                ],
            ])->class('modal-lg'),
```
выдает ошибку `Call to undefined method Orchid\Screen\Layouts::class()`, хотя в шаблоне осталась обработка класса.
Вроде всё остальное норм обновилось.

**Comment by PSalador** [comment]
3. Какие-то проблемы со скриптами - не загружаются файлы, также не обрезается изображение.

**Comment by tabuna** [comment]
@PSalador А с какой версии ты обновился? Изображение не "обрезается" уже очень давно, потому что это работало только с несколькими источниками, в место этого, можно поставить пакет самому и контролировать это.

**Comment by tabuna** [comment]
>  Какие-то проблемы со скриптами - не загружаются файлы

Возможно, что веб-сервер перехватывает вызовы и пытается отдать статику (js/css/fonts/etc), которой нет. Если по адресам, выдаёт 404 - то выполни команду `orchid:link`

**Comment by PSalador** [comment]
> . Если по адресам, выдаёт 404 - то выполни команду `orchid:link`

Что-то нет такой команды
` Command "orchid:link" is not defined.`

**Comment by woodsleaf** [comment]
А почему logout не отрабатывает? В смысле зайти получилось но не выйти )

**Comment by tabuna** [comment]
> А почему logout не отрабатывает? В смысле зайти получилось но не выйти )

Если по кнопки "выход" пользователя перенаправляет на страницу с ошибкой, то страница не перезагружается. Функционал выхода работает.

**Comment by PSalador** [comment]
3. Решено
2. Если не охота возвращать компиляцию атрибутов в Layout - 
( https://github.com/orchidsoftware/platform/blob/3.0.0/src/Screen/Layouts.php#L100 )
то нужно как-то сделать возможность выбирать ширину модульного окна.

**Comment by tabuna** [comment]
Добавлено возможность установки значений размера и названий кнопок:

```php
Layout::modals([
    'exampleModals' => Layout::rows([]),
])
    ->size(Modals::SIZE_LG)
    ->applyButton(self::APPLY_BUTTON)
    ->closeButton(self::CLOSE_BUTTON),
```

Будет доступно с ближайшем релизом
