### ISSUE TITLE
Некорректные ссылки на главной странице админки

### ISSUE THREAD

**Issue by catvlad** [orchidsoftware/platform#786]
https://imgur.com/a/s6pwqun

php artisan orchid:link Выполнено

  - ORCHID Version: 3.9.6
  - Laravel Version: 5.7.19
  - PHP Version: 7.2.15
  - Database Version: 5.7.25

**Comment by tabuna** [comment]
Спасибо @catvlad 

Да приветственный шаблон _(Предполагается, что вы изменение его под себя)_ 
ведёт на одну и туже страницу, я удалил все ссылки и это изменение войдёт в ближайший релиз.

Забавно, что текст "рыба" вас нисколько не смутила. :wink:

**Comment by woodsleaf** [comment]
* ORCHID Version: Currently v3.10.1 
А почему logout не отрабатывает? В смысле зайти получилось но не выйти )
а при заливке на хостинг, в качестве эксперемента, и с логином в dashboard проблема, не отрабатывает кнопка.
Так же заметил что без dev окружения даже до логина не доходит.
