### ISSUE TITLE
Поле PictureField

### ISSUE THREAD

**Issue by EvvC** [orchidsoftware/platform#787]
Версия 3.9.1
1. Не дает повторно загрузить для редактирования одну и ту же картинку. Допустим загружаю для редактирования pic1.jpg, потом сбрасываю или обрезаю, неважно. После этого пытаюсь загрузить этот же файл, ничего не происходит. Загружаю pic2.jpg - норм. Потом снова pic1.jpg - норм.
2. какую роль играет атрибут name?
 ![image](https://user-images.githubusercontent.com/24358689/53096049-43e00280-352f-11e9-8633-91f627b1f9cd.png)
3. вот с этой картинкой у меня проблемы  
![n3](https://user-images.githubusercontent.com/24358689/53096097-6245fe00-352f-11e9-8caa-29de1edc4484.jpg)
как ни обрежь, в поле остается img src="null"
![image](https://user-images.githubusercontent.com/24358689/53096169-91f50600-352f-11e9-859c-f956c75633b4.png)

**Comment by tabuna** [comment]
> 1. Не дает повторно загрузить для редактирования одну и ту же картинку. Допустим загружаю для редактирования pic1.jpg, потом сбрасываю или обрезаю, неважно. После этого пытаюсь загрузить этот же файл, ничего не происходит. Загружаю pic2.jpg - норм. Потом снова pic1.jpg - норм.

Воспроизвёл, баг, будем смотреть.

> 2\. какую роль играет атрибут name?

```html
<input name="Аргумент из метода">
```

Вызывать явно метод `->name($string = 'body')` не обязательно, 
если передавать значение в `->make(($string = 'body')`

Данный метод необходим, если создавать формы заранее, с последующим присвоением имени

3. Очень похоже, что этот null уже приходит, а не формируется

**Comment by EvvC** [comment]
3. Возврат null все же зависит от заданных размеров для этой картинки, больше 1200 х 800 всегда null,
ниже, например, 1198 х 800 вроде всегда возвращает картинку

**Comment by tabuna** [comment]
@EvvC 

> 1. Возврат null все же зависит от заданных размеров для этой картинки, больше 1200 х 800 всегда null,
>    ниже, например, 1198 х 800 вроде всегда возвращает картинку

Ох нет, не могу подтвердить это. 

Попробовав несколько вариантов, что бы воспроизвести, у меня получилось только при сценарии когда **в настройках php.ini выставлено слишком маленькое значение загрузки файла/ POST запроса**, например в 2mb (Обычно это значение по умолчанию), так как изображение генерируется js без сжатия (может в нутри и есть, но по моим наблюдениям не очень эффективное), то размер отправляемого файла, может быть даже выше чем выбранного.

Пожалуйста убедитесь, что ваши настройки корректны.

**Comment by EvvC** [comment]
) вы правы, 2М стояло, сделал побольше и проблема исчезла. Спасибо

**Comment by tabuna** [comment]
> 1. Не дает повторно загрузить для редактирования одну и ту же картинку. Допустим загружаю для редактирования pic1.jpg, потом сбрасываю или обрезаю, неважно. После этого пытаюсь загрузить этот же файл, ничего не происходит. Загружаю pic2.jpg - норм. Потом снова pic1.jpg - норм.

Исправил в master (Можете попробовать?).

Планирую опубликовать с ближайшим релизом

**Comment by EvvC** [comment]
1. Загрузил себе orchid.js из мастера, проверил, без изменений

**Comment by tabuna** [comment]
Эм, не очень понял, что имелось ввиду, надеюсь это был 

```
"orchid/platform":"dev-master"
```
С чистой кэша и т.п. А не копирование файла ;)

**Comment by EvvC** [comment]
🙄 не, просто скопировал бандл, не хотелось все не глядя обновлять. А теперь на чистом проекте стянул мастер, проверил, все же не работает
