### ISSUE TITLE
Laravel Scout with laravel-scout-tntsearch-driver fails to import data

### ISSUE THREAD

**Issue by marioperezio** [orchidsoftware/platform#788]
### Expected Behavior
Laravel Scout must import the data with its indexes and create the post.index database in the storage directory.

### Actual Behavior
I try to configure the Post model using the known configurations (see below), but I always get errors.

### Steps to Reproduce the Problem
Under a clean installation of laravel and orchid, I install the package of TNT Search Driver for Scout using composer, then, I configure the files .env, scout.php and the model Post.php according to the configuration recommendations and import the data with your indexes to create the post.index database.

1. `composer require teamtnt/laravel-scout-tntsearch-driver`
2. .env file. I add `SCOUT_DRIVER=tntsearch`
3. scout.php file. I add:

```
[...]

'tntsearch' => [
    'storage'  => storage_path(), //place where the index files will be stored
    'fuzziness' => env('TNTSEARCH_FUZZINESS', false),
    'fuzzy' => [
        'prefix_length' => 2,
        'max_expansions' => 50,
        'distance' => 2
    ],
    'asYouType' => false,
    'searchBoolean' => env('TNTSEARCH_BOOLEAN', false),
],

[...]

```

4. And finally in the Post.php model (Orchid\Press\Models\Post):

```
namespace Orchid\Press\Models;

use Carbon\Carbon;
use Laravel\Scout\Searchable;
use Orchid\Platform\Models\User;
use Illuminate\Support\Collection;
use Orchid\Support\Facades\Dashboard;
use Orchid\Press\Traits\TaggableTrait;
use Illuminate\Database\Eloquent\Model;
use Orchid\Platform\Traits\AttachTrait;
use Orchid\Platform\Traits\FilterTrait;
use Illuminate\Database\Eloquent\Builder;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Orchid\Platform\Traits\MultiLanguageTrait;
use Orchid\Press\Exceptions\EntityTypeException;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Cviebrock\EloquentSluggable\Services\SlugService;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

/**
 * Class Post.
 */
class Post extends Model
{
    use TaggableTrait,
        SoftDeletes,
        Sluggable,
        MultiLanguageTrait,
        Searchable,
        AttachTrait,
        FilterTrait;

    /**
     * @var bool
     */
    public $asYouType = true;

   [...]

    /**
     * Get the indexable data array for the model.
     *
     * @param $array
     *
     * @return mixed
     */
    public function toSearchableArray($array)
    {
        $array['content']['en']['id'] = $array['id'];

        return $array['content']['en'];
    }

   [...]

```

5. Then: `php artisan scout:import Orchid\\Press\\Models\\Post`
I get the error #1:

```
   Symfony\Component\Debug\Exception\FatalThrowableError  : Too few arguments to function Orchid\Press\Models\Post::toSearchableArray(), 0 passed in /path-to-app-project/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php on line 51 and exactly 1 expected

  at /path-to-app-project/vendor/orchid/platform/src/Press/Models/Post.php:157
    153|      * @param $array
    154|      *
    155|      * @return mixed
    156|      */
  > 157|     public function toSearchableArray($array)
    158|     {
    159|         $array['content']['en']['id'] = $array['id'];
    160| 
    161|         return $array['content']['en'];

  Exception trace:

  1   Orchid\Press\Models\Post::toSearchableArray()
      /path-to-app-project/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php:51

  2   TeamTNT\Scout\Engines\TNTSearchEngine::TeamTNT\Scout\Engines\{closure}(Object(Orchid\Press\Models\Post))
      /path-to-app-project/vendor/laravel/framework/src/Illuminate/Support/Collection.php:419

```

When in the model Post.php I change the code: 

```
    /**
     * Get the indexable data array for the model.
     *
     * @param $array
     *
     * @return mixed
     */
    public function toSearchableArray($array)
    {
        $array['content']['en']['id'] = $array['id'];

        return $array['content']['en'];
    }

```
by:

```
    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray($array)
    {
        $array = $this->toArray();

        // Customize array...

        return $array;
    }
```

I get the error #2:

```
   Symfony\Component\Debug\Exception\FatalThrowableError  : Too few arguments to function Orchid\Press\Models\Post::toSearchableArray(), 0 passed in /path-to-app-project/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php on line 51 and exactly 1 expected

  at /path-to-app-project/vendor/orchid/platform/src/Press/Models/Post.php:155
    151|      * Get the indexable data array for the model.
    152|      *
    153|      * @return array
    154|      */
  > 155|     public function toSearchableArray($array)
    156|     {
    157|         $array = $this->toArray();
    158| 
    159|         // Customize array...

  Exception trace:

  1   Orchid\Press\Models\Post::toSearchableArray()
      /path-to-app-project/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php:51

  2   TeamTNT\Scout\Engines\TNTSearchEngine::TeamTNT\Scout\Engines\{closure}(Object(Orchid\Press\Models\Post))
      /path-to-app-project/vendor/laravel/framework/src/Illuminate/Support/Collection.php:419

```
### Specifications

  - ORCHID Version: 3.9.6
  - Laravel Version: 5.7.27
  - PHP Version: 7.2.15
  - Database Version: 10.3.12-MariaDB

### Other Notes

The error indicates that there are few arguments to work. It is a bit confusing because the `toSearchableArray()` function has been defined according to the recommendations. Any suggestions, thanks.

**Comment by tabuna** [comment]
I just tried to do the same on the latest version of the framework and package.

The package search has been updated, and the documentation says that the entry is incorrect:


**Now the function has no arguments.**
```php
declare(strict_types=1);

namespace App;

use Orchid\Press\Models\Post as OrchidPost;

class Post extends OrchidPost
{
    /**
     * @var bool
     */
    public $asYouType = true;

    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray() : array
    {
        $array = $this->toArray();

        // Customize array...

        return $array;
    }
}
```

Please note that the tnt package should not contain a nested array, it can only work with flat

**Comment by marioperezio** [comment]
Thanks @tabuna, I made the proposed changes, but now I have a different error message:
```
   ErrorException  : mb_strtolower() expects parameter 1 to be string, array given

  at /path-to-app-project/vendor/teamtnt/tntsearch/src/Support/Tokenizer.php:8
     4| class Tokenizer implements TokenizerInterface
     5| {
     6|     public function tokenize($text, $stopwords = [])
     7|     {
  >  8|         $text  = mb_strtolower($text);
     9|         $split = preg_split("/[^\p{L}\p{N}]+/u", $text, -1, PREG_SPLIT_NO_EMPTY);
    10|         return array_diff($split, $stopwords);
    11|     }
    12| }
  Exception trace:

  1   mb_strtolower([])
      /path-to-app-project/vendor/teamtnt/tntsearch/src/Support/Tokenizer.php:8

  2   TeamTNT\TNTSearch\Support\Tokenizer::tokenize([], [])
      /path-to-app-project/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php:444
```
Now, this is an issues already known in the Laravel Scout TNTSearch Driver repository. https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/74#issue-214713730. The import with Laravel Scout works well with other Laravel applications that I have installed, so it seems that there are problems with the relationships between the models or some field of the table posts (Json ???). I still do not know. I'm going to perform other tests and I'll tell you. Any other suggestions?

**Comment by tabuna** [comment]
I told you that this search engine cannot work with multi-level nesting:

```php
// unwork
$model = [
  'id' => 1,
  'options' => [ 
        'color' => 'red',
        'price' => 27.30
    ]  
];


//work
$model = [
  'id' => 1,
  'color' => 'red',
  'price' => 27.30
];
```

You need to either bring the structure to simplicity or choose more complex engines, for example, I use [elasticsearch](https://github.com/ErickTamayo/laravel-scout-elastic) / [2](https://github.com/babenkoivan/scout-elasticsearch-driver). That's the beauty of the Laravel Scout, that it only provides an interface for the engine.

**Comment by marioperezio** [comment]
Hello again, I have not reviewed the guide you have about TNTSearch, but I come using it in other applications with Laravel and wanted to implement it in a project with Orchid for a client, it's not a big project. ElastiSearch is very good and powerful, I agree with you, but it's not justified to use it for these types of projects, it is advisable to install it on a VPS and not on a shared server, the same thing happens with Sphink. For this reason I wanted to use the TNTSearch Driver for Laravel Scout with Orchid. Of course, I agree with you that Laravel Scout is fantastic. Again thanks friend for the suggestion, I think that this issues can be considered closed if you have no other observation.

**Comment by tabuna** [comment]
I hope you understand me. You can use tntsearch, but you should put a one-dimensional array into the index using the provided method, do not worry you will get a regular model.
