### ISSUE TITLE
* ORCHID Version: Currently v3.10.1

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#789]
* ORCHID Version: Currently v3.10.1 
А почему logout не отрабатывает? В смысле зайти получилось но не выйти )
а при заливке на хостинг, в качестве эксперемента, и с логином в dashboard проблема, не отрабатывает кнопка.
Так же заметил что без dev окружения даже до логина не доходит.
Рыба рыбой но аутентификацию лучше бы работала.

_Originally posted by @woodsleaf in https://github.com/orchidsoftware/platform/issues/786#issuecomment-466587143_

**Comment by tabuna** [comment]
Пожалуйста создайте собственную тему.

**Comment by woodsleaf** [comment]
виноват
