### ISSUE TITLE
After install can't access to dashboard

### ISSUE THREAD

**Issue by jmntll** [orchidsoftware/platform#790]
### Expected Behavior
Let me login and access to dashboard

### Actual Behavior
can't login, cant create users

### Steps to Reproduce the Problem

  1. php artisan serve
  1. go to localhost/dashboard
  1. cant access

### Specifications

  - ORCHID Version: 
  - Laravel Version: 5.7.27
  - PHP Version:  7.2.12
  - Database Version: 10.1.37-MariaDB

**Comment by tabuna** [comment]
To solve this problem, more information is required.

**Comment by jmntll** [comment]
### Expected Behavior
Let me login and access to dashboard

### Actual Behavior
can't login, cant create users

### Steps to Reproduce the Problem
1. php artisan serve
2. go to localhost/dashboard
3. cant access

### Specifications
* ORCHID Version:
* Laravel Version: 5.7.27
* PHP Version:  7.2.12
* Database Version: 10.1.37-MariaDB

**Comment by tabuna** [comment]
MariaBD unsupported.
Expected with Laravel 5.8
