### ISSUE TITLE
Доступы пользователей и ролей

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#792]
Сделать чтобы у каждой группы доступов был чекбокс при нажатии на который отмечались все доступы в группе.

**Comment by tabuna** [comment]
Есть предложение как мы можем это сделать не вводя для этого новый тип поля?

**Comment by PSalador** [comment]
Предложений нет, просто замучался тыкать доступы)
Может скрипт какой-нибудь.

**Comment by tabuna** [comment]
Может тогда введём `Layouts` для этого, который отмечал/отменял все значения `checkbox`

**Comment by PSalador** [comment]
Можно так или поле ввести типа CheckBoxGroup.

**Comment by tabuna** [comment]
@PSalador Предлагаю вернутся к этой теме с такой реализацией

```html
  <input type="checkbox" name="users[ ]" value="1">
  <input type="checkbox" name="users[ ]" value="2">
  <input type="checkbox" name="users[ ]" value="3">
```

Поставить событие на двойной клик, который бы делал все значения, где `users[ ]` checked/uncheked соотвественно?

Но так как у нас записаны, перечисление доступов в правах через, явные обращения:
```html
  <input type="checkbox" name="users[rerehgerh]" value="1">
  <input type="checkbox" name="users[qwqwfffdf ]" value="2">
  <input type="checkbox" name="users[prpmodpre ]" value="3">
```

Такой вариант не подойдёт

**Comment by PSalador** [comment]
Почему не подойдет норм.
Можно сделать где все значения, где `users[*]` checked/uncheked

**Comment by tabuna** [comment]
Имеешь ввиду сделать доп.метод который бы принимал аргумент `users[*]` ?
