### ISSUE TITLE
Migration error | Cannot add foreign key

### ISSUE THREAD

**Issue by rezken1** [orchidsoftware/platform#793]
### Expected Behavior

php artisan orchid:install

### Actual Behavior

 Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `role_users` add constraint `role_users_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade on update cascade)

### Steps to Reproduce the Problem

  1. php artisan orchid:install

### Specifications

  - ORCHID Version: 5.8
  - Laravel Version: 3.11
  - PHP Version: 7.2
  - Database Version: MySql 5.7

**Comment by tabuna** [comment]
Are you using InnoDB? We do not set this as default, please check it with you.

**Comment by rezken1** [comment]
Thanks for the information, so i need to downgrade my Mysql version because the use of InnoDB is mandatory since MySQL 5.7

**Comment by tabuna** [comment]
why lower? After all, innodb is recommended since version 5.1, perhaps by default you are using myislam and you just need to change this value.

**Comment by rezken1** [comment]
I am using InnoDB but you said it's not set by default. 

How can i change that ?

**Comment by tabuna** [comment]
Create a new base as follows:
```
CREATE DATABASE "orchid" ENGINE = InnoDB
```

**Comment by rezken1** [comment]
All my tables are already using InnoDB engine

**Comment by mtsunu** [comment]
Laravel 5.8 is using Big INT for user id column.
change the default create users table migration from
`$table->bigIncrements('id');` to `$table->increments('id');`

**Comment by tabuna** [comment]
Thank @mtsunu 

I use "sqlite" for development, so I did not receive such errors. :anguished:
Got the same error when trying to upgrade to production. 
Has released a corrective release.

**Comment by mattdeclaire** [comment]
Ah. I had created my `users` table a long time ago, so `users.id` was still just an unsigned int.
