### ISSUE TITLE
Пользовательские события при установки

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#795]
При установки было бы не плохо дать возможность устанавливать и и сторонние пакеты, что бы не выполнять консольные команды по нескольку раз.

Это можно сделать введя новое событие `InstallEvent`, которое выполнялось в самом конце установки orchid.

**Comment by tabuna** [comment]
```php
<?php

declare(strict_types=1);

namespace Orchid\Platform\Events;

use Illuminate\Console\Command;

/**
 * Class InstallEvent.
 */
class InstallEvent
{
    /**
     * @var Command
     */
    public $command;

    /**
     * InstallEvent constructor.
     *
     * @param Command $command
     */
    public function __construct(Command $command)
    {
        $this->command = $command;
    }
}

```

**Comment by PSalador** [comment]
При установке добавить циферками возможность выбора основных пакетов.
Также на сайте https://orchid.software добавить информацию по пакетам.

**Comment by tabuna** [comment]
@PSalador , что ты имеешь ввиду? Мы же не сможем их установит, это делается через composer

**Comment by PSalador** [comment]
> При установки было бы не плохо дать возможность устанавливать и и сторонние пакеты,

Что-то я не понял, как они будут устанавливаться?

**Comment by tabuna** [comment]
Под этим, я понимал первичную настройку, которая необходима для работы, например выполнение миграций, публикация файлов и т.п
