### ISSUE TITLE
Relationship nullable

### ISSUE THREAD

**Issue by Nks** [orchidsoftware/platform#797]
Not always we need to set the relation for the model. Sometimes it can be null. I think it's better to add allowClear: true to select2 and allow users to clear this. Of course this can be configurable like this:

```
Relationship::make('relation_id')
                ->title(__('Relation'))
                ->horizontal()
                ->nullable()
                ->handler(RelationWidget::class),
```

And after this if we have nullable attribute we can dynamically allow users set the null value for the relationship.

What do you think?

**Comment by tabuna** [comment]
I like your thought. But I think it is worth adhering to a single style, there is not a single field that uses the nlabled, on the contrary, they all declare it required or not.

```php
Relationship::make('relation_id')
                ->title(__('Relation'))
                ->horizontal()
                ->required()
                ->handler(RelationWidget::class),
```

If the required is not set, then we enable the setting. `allowClear: true`

Do you want to add it?
