### ISSUE TITLE
Button field

### ISSUE THREAD

**Issue by Nks** [orchidsoftware/platform#807]
Возможность добавлять кнопки для вызова модальных окон, ссылок и отправки формы на экране за пределами commandBar

**Comment by tabuna** [comment]
Должны ли мы анимировать кнопку при отправки?

**Comment by tabuna** [comment]
```php
Button::make()
    ->title(__('Add Payment'))
    ->method('newPayment')
    ->type(Button::DARK)
    ->modal('addNewPayment')
    ->icon('icon-wallet')
    ->right();
```

Что вы думаете об использовании такого синтаксиса?

**Comment by Nks** [comment]
> Должны ли мы анимировать кнопку при отправки?

Не думаю что это актуально. К тому же кнопка позволяет не только делать отправку, но так же вызывать модальное окно.
