### ISSUE TITLE
loadModalAsync doesn't allow custom text

### ISSUE THREAD

**Issue by Nks** [orchidsoftware/platform#811]
### Expected Behavior

4th parameter must works with custom string too

### Actual Behavior

It works only with content fields

### Steps to Reproduce the Problem

  1. TD::set('title', __('Item'))
                ->loadModalAsync('orderItemModalForm', 'saveOrderItem', 'id', 'Custom Name Of The Field'),

**Comment by tabuna** [comment]
Возможно стоит добавить метод для указания названия модального окна, так как не всегда название колонки отражает суть. Можно брать в зависимости от приоритета, например `$nameModal ?? $title` и т.п. Так как сейчас в примере с пользователями, модальное окно называется `Email`.
