### ISSUE TITLE
Не работают доп. методы у поля datetimer

### ISSUE THREAD

**Issue by Leshkens** [orchidsoftware/platform#816]
Преобразование из bool в строку даёт 1 или 0, но для js скрипта требуется 'true' или 'false'. 
```
public function enableTime(bool $time = true) : self
{
        $this->set('data-fields--datetime-enable-time', (string) $time);

        return $this;
}
```
Предлагаю $time обернуть в var_export(), например.

```
public function enableTime(bool $time = true) : self
{
        $this->set('data-fields--datetime-enable-time', var_export($time, true));

        return $this;
}
```
### Specifications

  - ORCHID Version: v4.3.4

**Comment by tabuna** [comment]
Думаю мы можем изменить это сейчас, но лучше всего написать автору библиотеки

**Comment by tabuna** [comment]
Сделал релиз с исправлением
