### ISSUE TITLE
Групировка entity в dashboard

### ISSUE THREAD

**Issue by aizhar777** [orchidsoftware/platform#825]
Подскажите поведение `groupname`  entity
```php
    /**
     * Menu group name.
     *
     * @var null
     */
    public $groupname = 'Записи';
``` 
У меня есть 4 entity-many у которых `$groupname = 'Записи'`
и 2 entity-single у которых `$groupname = 'Статические страницы'`
и все 6 entity появляются дашборде как отдельная группа Записи или Статические страницы. Почему они не группируются, или я что то не понимаю?)))

![Screenshot](https://user-images.githubusercontent.com/9531609/55275324-54da1b80-5306-11e9-9ad3-86dc896060b0.png)

**Comment by tabuna** [comment]
Да, это это только параметр отвечающий за подпись

**Comment by aizhar777** [comment]
Понятно спасибо
