### ISSUE TITLE
Call to undefined method App\User::hasAccess()

### ISSUE THREAD

**Issue by sidxkick** [orchidsoftware/platform#826]
### Steps to Reproduce the Problem

  1. Install orchid-admin
  2. Created admin user and tried login
  3. Get error Call to undefined method App\User::hasAccess()

### Specifications

  - ORCHID Version: lastest
  - Laravel Version:5.8
  - PHP Version: 7.1
  - Database Version: PostgreSQL 10.3

**Comment by tabuna** [comment]
HI @sidxkick 

When installing, we replace the user model with our [own](https://github.com/orchidsoftware/platform/blob/master/install-stubs/User.stub):

```php
<?php

namespace App;

use Orchid\Platform\Models\User as Authenticatable;

class User extends Authenticatable
{
}
```

Perhaps in your case, the substitution for some reason did not work, 
and you must set the inheritance manually

**Comment by tabuna** [comment]
I close this because of inaction.
Please open when it will be again.

**Comment by RJFares** [comment]
Same happened here, the above solution worked. Maybe it should be documented as a side note?
