### ISSUE TITLE
Migration Problem

### ISSUE THREAD

**Issue by sutharpratik10** [orchidsoftware/platform#835]
### Expected Behavior
Table Migration has to be completed successfully.

### Actual Behavior
Migration gives an error while running command "php artisan orchid/install",
The Error is shown here:- 
--------------------
 Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists (SQL: create table `users` (`id` bigint
 unsigned not null auto_increment primary key, `name` varchar(191) not null, `email` varchar(191) not null, `email_verified_at` timestamp null, `password` varchar(191
) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at D:\Pratik\Work\project ultron\ultron_admin\ultron_admin\orchid\orchid-project\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists")
      D:\Pratik\Work\project ultron\ultron_admin\ultron_admin\orchid\orchid-project\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458

  2   PDOStatement::execute()
      D:\Pratik\Work\project ultron\ultron_admin\ultron_admin\orchid\orchid-project\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458

  Please use the argument -v to see more details.
-----------------------------------------

### Specifications

  - ORCHID Version:4.5.1
  - Laravel Version:2.0
  - PHP Version:7.2
  - Database Version:MySql (V5.1)
![Untitled](https://user-images.githubusercontent.com/10793403/56090760-10cd4600-5ec4-11e9-914a-04529b73b55f.jpg)

**Comment by tabuna** [comment]
Hi, I suspect that it came out in mysql 5.1 version in november 2008, that is, more than 10 years ago, during this time it could be updated, support starts from 5.7.3

I also understand why you specified a version of laravel as 2.0, it also came out many years ago, but I think that you didn’t read it right

As for the error, then most likely the migration from the package and the laravel migration were performed incorrectly, what do you have in the migration table?

There should be an entry about https://github.com/laravel/laravel/blob/master/database/migrations/2014_10_12_000000_create_users_table.php if not, try migration:fresh

**Comment by tabuna** [comment]
I close it due to inactivity. Feel free to open it again.
