### ISSUE TITLE
Can't complete migration

### ISSUE THREAD

**Issue by Nidhishpp** [orchidsoftware/platform#840]
### Expected Behavior
Migration Completed

### Actual Behavior
![image](https://user-images.githubusercontent.com/33666375/56456326-4375b380-6388-11e9-8067-669cb6c70580.png)

### Steps to Reproduce the Problem

  1. composer require orchid/platform
  2. php artisan orchid:install

### Specifications

  - ORCHID Version: 4.6.2
  - Laravel Version: 5.8.*
  - PHP Version: 7
  - Database Version:

**Comment by tabuna** [comment]
I need more information to help you. Please provide data and indicate error.

**Comment by Nidhishpp** [comment]
> I need more information to help you. Please provide data and indicate error.

just updated

**Comment by Nidhishpp** [comment]
![image](https://user-images.githubusercontent.com/33666375/56456368-cd258100-6388-11e9-815e-986ccad985b1.png)

**Comment by tabuna** [comment]
Your database does not support json type. If this mysql please upgrade, support starts from 5.7

**Comment by Nidhishpp** [comment]
Should I update phpmyadmin

**Comment by tabuna** [comment]
phpmyadmin is a graphical client for the database, neither laravel nor orchid use it.

**Comment by Nidhishpp** [comment]
so how can i update it

**Comment by tabuna** [comment]
It is better to learn on profile sites and forums.
