### ISSUE TITLE
Ошибка при переходе по пунктам меню

### ISSUE THREAD

**Issue by maksakoviliya** [orchidsoftware/platform#841]
### Actual Behavior
После установки, при переходе по пунктам меню, а также после авторизации белый экран. 
При обновлении страницы появляется контент.

### Specifications

  - ORCHID Version:  4.6.1
  - Laravel Version: 5.8.3
  - PHP Version: 7.3.2
  - Database Version: 8.0.15

**Comment by tabuna** [comment]
Это скверно, скажите какие статусы ресурсов в браузере?

Был случай, где похожее поведение наблюдалось из-за расширения браузера (прокси) , попробуйте отключить все расширения

**Comment by maksakoviliya** [comment]
Да..Есть vpn. Надо попробовать

**Comment by tabuna** [comment]
> Да..Есть vpn. Но его отключение не помогло

Если изменяете сообщение, то уведомления не приходят.
Можете показать вкладку `network` при попытки загрузить?

**Comment by tabuna** [comment]
Закрою этот вопрос, так как нет обновлений по этой теме.
Не стесняйтесь открывать его снова.
