### ISSUE TITLE
Method Illuminate\View\View::__toString() must not throw an exception

### ISSUE THREAD

**Issue by brahimbim** [orchidsoftware/platform#844]
### Steps to Reproduce the Problem

  1. Create a screen
   
![image](https://user-images.githubusercontent.com/24649160/56607968-a6be4a80-6601-11e9-9606-e2bcf7bb852e.png)

  2. Create layout
    
![image](https://user-images.githubusercontent.com/24649160/56608098-eab14f80-6601-11e9-9cb0-769d554476c7.png)

  3. I get this error 
   
![image](https://user-images.githubusercontent.com/24649160/56608284-52679a80-6602-11e9-9588-a0d9cdc21781.png)

### Specifications

  - ORCHID Version: 4.7.0
  - Laravel Version:  5.8.11
  - PHP Version: 7.2.3
  - Database Version: Mysql 5.7

**Comment by tabuna** [comment]
Hi, personnel - is array or collection ?

**Comment by brahimbim** [comment]
is collection

**Comment by tabuna** [comment]
> is collection

I do not see it, most likely there is one model in the singular:

```php
use App/Personnel;

 // not work
Personnel::find(1);

 // work
Personnel::paginate();
Personnel::limit(10)->get();
```

A table can only display multiple values, because it tries to perform a foreach.

----

If you are sure that several values come, then make sure that the model uses trait:

```php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Orchid\Platform\Traits\MultiLanguageTrait;

class Personnel extends Model
{
    use MultiLanguageTrait;

    //
}
```

**Comment by brahimbim** [comment]
> use MultiLanguageTrait;

thanks for your help
