### ISSUE TITLE
Alert не работает через промежуток времени

### ISSUE THREAD

**Issue by TrenchTown** [orchidsoftware/platform#853]
После возвращения из режима сна, перестают появляться алерты.
Помогает переавторизация в платформе. 

### Specifications
  - Win7
  - Chrome
  - ORCHID Version: 4.7.1
  - Laravel Version: 5,8
  - PHP Version: 7,2

**Comment by Nks** [comment]
Алерты используют стандартную систему сессий php. Можно попробовать увеличить время жизни сессии.

**Comment by tabuna** [comment]
Не уверен, что проблема именно в сессии.
Так как если бы срок её жизни истёк, то пользователя разлогинило бы.

@el-pixellife , можете [попробовать изменить значение](https://github.com/laravel/laravel/blob/master/config/session.php#L23-L33):

```php
    /*
    |--------------------------------------------------------------------------
    | Session Lifetime
    |--------------------------------------------------------------------------
    |
    | Here you may specify the number of minutes that you wish the session
    | to be allowed to remain idle before it expires. If you want them
    | to immediately expire on the browser closing, set that option.
    |
    */
    'lifetime' => env('SESSION_LIFETIME', 120),
```

Наоборот на самое минимальное, например, одну минуту, это даст точное представление, что проблема в использовании сессии, а не в чём либо другом.

**Comment by TrenchTown** [comment]
@tabuna 
Все перепробовал, проблему воспроизвести не удалось.
В чем была причина, не понятно.

**Comment by tabuna** [comment]
@TrenchTown Правильно понимаю, что сейчас всё хорошо?
