### ISSUE TITLE
install orchid platform

### ISSUE THREAD

**Issue by brahimbim** [orchidsoftware/platform#858]
### Expected Behavior

how to install orchid platform without press models ??

**Comment by tabuna** [comment]
Hi @brahimbim 

Although Orchid is not such a big project (judging by the lines of code *) compared to alternatives, at the moment it provides all the possibilities in one package, but that if not a part is required, there are already options:

- Leave everything as it is, just remove the rights for users.
- Disable automatic registration.

If the first option, everything is clear, then the second is not always. Laravel, starting from version 5.5, [allows providers to automatically register](https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518) using ‘extra’ in `composer.json`, but we can disable it:

```json
"extra": {
    "laravel": {
        "dont-discover": [
            "orchid/platform"
        ]
    }
},
```

After that, we can register the required provider from the package, for example, only `Orchid\Platform\Providers\FoundationServiceProvider` in the `config/app.php` configuration file ([and facades](https://github.com/orchidsoftware/platform/blob/master/composer.json#L83-L87)). Then neither the migration nor the parameters from the content management system will be loaded into your application.


We have plans for division into two packages, [you can follow it here](https://github.com/orchidsoftware/platform/pull/857).

If you have other interesting uses or comments, suggestions, it would be nice to discuss them and make the work even more comfortable.
