### ISSUE TITLE
Send data from screen to table layout

### ISSUE THREAD

**Issue by brahimbim** [orchidsoftware/platform#859]
### Steps to Reproduce the Problem

  1. I sent data from screen to table layout
![image](https://user-images.githubusercontent.com/24649160/57586574-2051a600-74e7-11e9-966f-b22bc9506247.png)

  1. I've received data in the layout   
![image](https://user-images.githubusercontent.com/24649160/57586595-64dd4180-74e7-11e9-95f7-f8a269b0aa36.png)

  1.in this table, I want to use Model relationship
![image](https://user-images.githubusercontent.com/24649160/57586628-e503a700-74e7-11e9-8600-d7896a1237fb.png)

### Specifications

  - ORCHID Version: 4.7
  - Laravel Version: 5..8
  - PHP Version: 7.2
  - Database Version: 5.7

**Comment by tabuna** [comment]
Hi @brahimbim 

Please make sure that the `Ticket` has a trade `AsSource`.

```php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Orchid\Screen\Traits\AsSource;

class Ticket extends Model
{
    use AsSource
}
```

**Comment by brahimbim** [comment]
I get an empty field
![image](https://user-images.githubusercontent.com/24649160/57588324-04a7c900-7502-11e9-874c-638d3f41252b.png)

**Comment by tabuna** [comment]
Could you indicate what estat is?  is it an object?  an array? relation?

The screenshot does not let me understand this.

You can also see a test for this, to understand more precisely how it works.

https://github.com/orchidsoftware/platform/blob/master/tests/Unit/Screen/SourceTest.php

**Comment by brahimbim** [comment]
Thank you @tabuna
