### ISSUE TITLE
Chart line doesn't work in the inactive tab

### ISSUE THREAD

**Issue by Nks** [orchidsoftware/platform#861]
### Expected Behavior
Charts showing correctly

### Actual Behavior
When a chart added to not active tab it is not showing

### Steps to Reproduce the Problem

  1. Create a screen with 2 tabs
  1. Add `ChartLineExample::class` to the second tab
  1. Open screen and switch to the tab

### Specifications

  - ORCHID Version: master

### Other Notes

![image](https://user-images.githubusercontent.com/349293/57658028-01860900-75e6-11e9-8cf4-5ce76cd11b2f.png)

**Comment by Nks** [comment]
Assign this on me, I'll fix

**Comment by tabuna** [comment]
This is not the first such problem.  For example maps, the same will not be shown on an inactive tab.  Thanks you

**Comment by Nks** [comment]
Also need check bars and pie charts.
