### ISSUE TITLE
Dynamic Dependent Select using Ajax

### ISSUE THREAD

**Issue by brahimbim** [orchidsoftware/platform#865]
### Expected Behavior
How to use orchid with Ajax for populate dropdown listbox with dynamic data
![image](https://user-images.githubusercontent.com/24649160/57745013-f3ee8300-76ba-11e9-93b7-6c3a1bfcc245.png)

### Specifications

  - ORCHID Version: 4.7.1
  - Laravel Version: 5.8
  - PHP Version:7.3
  - Database Version:5.7

**Comment by tabuna** [comment]
Hi @brahimbim 

Currently, the package does not have such capabilities.

You can get around this by creating a field with a city search.
Another option is to write it explicitly using a JavaScript script.

**Comment by brahimbim** [comment]
thank you for your responses

**Comment by gioacchinopoletto** [comment]
@tabuna: today platform still not having such capabilities?

**Comment by tabuna** [comment]
@gioacchinopoletto You can do this with a listener: https://orchid.software/en/docs/listener/

**Comment by ahmadgx** [comment]
> > @gioacchinopoletto You can do this with a listener: https://orchid.software/en/docs/listener/
> 
> I still can not understand how a listener can be used in this case ? I mean how would you scope or filter dropdown items from a listener ?

its working with me 

class ApplicationKeyEditScreen extends Screen
{
    /**
     * @var ApplicationKey
     */
    public $application_key;

    /**
     * Query data.
     *
     * @param ApplicationKey $application_key
     *
     * @return array
     */
    public function query(ApplicationKey $application_key): array
    {
        return [
            'application_key' => $application_key,
        ];
    }

    /**
     * The name is displayed on the user's screen and in the headers
     */
    public function name(): ?string
    {
        return  $this->application_key->exists ? 'Edit Application key' : 'Creating a new Application key';
    }

    /**
     * Button commands.
     *
     * @return \Orchid\Screen\Action[]
     */
    public function commandBar(): iterable
    {
        return [ ];
    }

    /**
     * Views.
     *
     * @return \Orchid\Screen\Layout[]|string[]
     */
    public function layout(): iterable
    {
        return [
            Layout::rows([

                Select::make('payment')
                    ->title('Payment')
                    ->required()
                    ->class('payment-name')
                    ->options(['' => 'Select Payment','A'=> 'A', 'b' => 'B'] ),
 

            ]), 
                
            PaymentConfigurationListener::class,
        ];
     } 



    /**
     * @param int|null $payment
     *
     * @return string[]
     */
    public function asyncPaymentConfiguration($payment)
    {
        return [
            'payment' => $payment, 
        ];
    }
}

===============================================================================

namespace App\Orchid\Layouts;

use Orchid\Screen\Fields\Matrix;
use Orchid\Support\Facades\Layout;
use Orchid\Screen\Layouts\Listener;

class PaymentConfigurationListener extends Listener
{
    /**
     * List of field names for which values will be listened.
     *
     * @var string[]
     */
    protected $targets = [
        'payment', 
    ];

    /**
     * What screen method should be called
     * as a source for an asynchronous request.
     *
     * The name of the method must
     * begin with the prefix "async"
     *
     * @var string
     */
    protected $asyncMethod = 'asyncPaymentConfiguration';

    /**
     * @return Layout[]
     */
    protected function layouts(): array
    {
        dump($this->query->get('payment'));
        return [
            Layout::rows([ 
                Matrix::make('application_key.configuration')
                    ->title('Configuration')
                    ->required()
                    ->columns([
                        'name',
                        'value',
                    ]),
            ]),
        ];
    }
}

====================================================================

![image](https://user-images.githubusercontent.com/17316605/174264329-742d9479-a52c-45e2-9cf1-ea83ea2dcc17.png)

**Comment by jrushworth** [comment]
OK, have listener working fine but can't see how to populate drop-down with updated results. The above example does not seem to make a request back to the database. Any help would be appreciated.

**Comment by macit-emre** [comment]
You may use Select::make instead of Matrix::make and write your own code like this : 
`
$cityId = $this->query->get('city_id')['city_id'] ?? 0;
$fields[] = Select::make('user.district_id')
            ->fromQuery(District::query()->where('city_id','=',$cityId), 'name')
            ->title(__('District'))
            ->required()
            ->empty('Seçiniz')
            ->autocomplete();`

**Comment by devmania1223** [comment]
How can we do this in Resource component?

**Comment by macit-emre** [comment]
i dont feel resource component the same flexibility neither this platform does not easily encourage custom ajax functions. So if you want to do some, i advice you to use standart screen functions with extended custom fields and custom endpoints. 
This is my own experience by the way.

**Comment by Annikangl** [comment]
In my case, I was able to make Orchid work dynamically with two Select fields, but for the third one, it doesn't work for some reason and returns a 404 error. 

My code that works with two Select fields:

MyScreen.php


`    public function asyncGetModels(int $brandId): iterable
    {
        return [
            'models' => CatalogModel::query()
                ->where('brand_id', $brandId)
                ->pluck('model', 'id'),
        ];
    }`

`    public function layout(): iterable
    {
        return [

            Layout::modal('createCar', [
                Layout::rows([
                    Select::make('brand')
                        ->fromModel(Brand::class, 'title')
                        ->title('Марка')
                        ->required(),
                ]),
                SelectModelListener::class,`



`class SelectModelListener extends Listener
{
    protected $extraVars = [];

    protected $targets = [
        'brand'
    ];

    protected $asyncMethod = 'asyncGetModels';

    protected function layouts(): iterable
    {
        return [
            Layout::rows([
                   Select::make('model')
                       ->options($this->query->has('models') ? $this->query->get('models') : [])
                       ->title('Модель')
                       ->required(),
               ]),

            SelectConfigurationListener::class,
        ];
    }
}`
