### ISSUE TITLE
Поле состоящее из нескольких селектов.

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#869]
Примерные варианты:

Цитата из чата в телеграмм:
Подскажите, а есть возможность делать зависимости от поля? Например:
Есть 2 Select: Category и Subcategory. И в зависимости от выбора в Category, в Subcategory подгружаются разные данные?

Выбор адреса:
Первый select - страна,
второй select - регион,
третий select - город.

Выбор элемента модели:
Первый select - выбор модели (категории, посты, страницы)
второй select - запрос по модели.

**Comment by PSalador** [comment]
На ум приходит такая конструкция:
```php
Relation::make('idea')
    ->fromModel1(Role::class, 'slug')
    ->applyScope1('active')
    ->fromModel2(User::class, 'name')
    ->applyScope2('active')
    ->fromModel3(Idea::class, 'name')
    ->applyScope3('active')
    ->title('Select one idea'),

```

**Comment by PSalador** [comment]
Пришли к такому выводу
```php
Select::make('country')
   ->fromModel(Country::class, 'name')
   ->title('Select Country');

Relation::make('city_id')
    ->title('City')
    ->dependent('country')
    ->fromModel(City::class, 'name')
    ->applyScope('country')
```
где `dependent` будет слушать изменения в том поле которое указано.

Также на основе этого можно будет сделать Conditional fields #774

**Comment by HomaEEE** [comment]
Как использовать Вашу реализацию в проекте? какие правки в модели? пробовал - выдает весь список городов без фильтрации по стране

**Comment by PSalador** [comment]
) это ещё не решенная проблема.

**Comment by 2kodes** [comment]
Any update on this? @PSalador @tabuna 

Would love to have this feature if even as a plugin or extension

**Comment by Nks** [comment]
One of the solution: use your own template with the javascript. I did this with rest api and vue.js+element.ui:
![conditional logic](https://user-images.githubusercontent.com/349293/68022214-c02d0700-fcb4-11e9-9d40-a2c76c3be7df.gif)

**Comment by tabuna** [comment]
Implemented in [7.2](https://github.com/orchidsoftware/platform/releases/tag/7.2.0)
