### ISSUE TITLE
TD filter()  from related model

### ISSUE THREAD

**Issue by brahimbim** [orchidsoftware/platform#870]
Hello, how I can filter from related model 
![image](https://user-images.githubusercontent.com/24649160/58477063-26c85a80-8142-11e9-9b3d-7f37764d5e7a.png)

### Specifications

  - ORCHID Version: 4.7
  - Laravel Version: 5.8
  - PHP Version: 7.2
  - Database Version: 5.7

**Comment by tabuna** [comment]
Hi @brahimbim 

This is not the most appropriate solution, we do not allow the use of HTTP filters for related models.

The best option would be to use a regular filter, where you can already set a modifying query. 

We have no plans to allow filtering, sorting for related models, but we can accept requests to add it.
