### ISSUE TITLE
Ability to use appends fields in Relation field

### ISSUE THREAD

**Issue by Nks** [orchidsoftware/platform#877]
### Expected Behavior
```
Relation::make('categories')
                ->multiple()
                ->title(__('Categories'))
                ->fromModel(Category::class, 'nested_title'),
```

It should return nested_title which appends to the model Category

### Actual Behavior
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nested_title' in 'field list' (SQL: select `nested_title`, `id` from `categories` where `nested_title` like %% limit 10)
```

Relation endpoint returning 500 error

### Specifications

  - ORCHID Version: master
  - Laravel Version: 5.8
  - PHP Version: 7.3
  - Database Version: mysql 5.7

**Comment by tabuna** [comment]
This field is computed. Accordingly, we can not implement a really optimal sql query. 
But we can try to output it, for example:

```php
Relation::make('categories')
    ->multiple()
    ->title(__('Categories'))
    ->fromModel(Category::class, 'title')
    ->displayAppend('nested_title'),
```

This will not be a clean solution, but will output what you want.

**Comment by tabuna** [comment]
I added a rough solution, but I think it requires some discussion and testing.

**Comment by Nks** [comment]
Maybe something like this works too?
In this case we can also show attributes which are not in appends.
Also I'm gonna add `->allowHtml()` as we did for the Relationship.

```
Relation::make('categories')
    ->multiple()
    ->title(__('Categories'))
    ->fromModel(Category::class, function($category) {
         return $category->nested_title;
    });
```

**Comment by tabuna** [comment]
In such processing, the anonymous function will have to be executed on Ajax request, and there is a logical question - how to pass it.  
One option is serialization, but it imposes many restrictions.

**Comment by tabuna** [comment]
Such a decision has already completely entered the system and is now not planning to change. It is necessary to document this

**Comment by tabuna** [comment]
Example:

```php
<?php

declare(strict_types=1);

namespace App;

use Orchid\Platform\Models\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * @return string
     */
    public function getFullAttribute(): string
    {
        return $this->attributes['name'] . ' (' . $this->attributes['email'] . ')';
    }
}

```


Usage:

```php
Relation::make('users.')
    ->fromModel(User::class, 'name')
    ->displayAppend('full')
    ->multiple();
```

Screenshot:
![image](https://user-images.githubusercontent.com/5102591/69579120-efe4db80-0fe2-11ea-8164-0ae5e8e394e9.png)

**Comment by tabuna** [comment]
This is published in 6.7.0

**Comment by kenanchristian** [comment]
Hello, I'm wondering if this feature also available for `Select` with `fromModel` method?

**Comment by Stehos** [comment]
Hi @tabuna  please is there a way to "paginate" fromModel? E.g. I have this code:

```
        $newFields[] = Relation::make('products')
            ->fromModel(Product::class, 'title', 'id')
            ->searchColumns('sku')
            ->displayAppend('orchidTitle')
            ->multiple()
            ->required()
            ->title(__('Products'))
            ->help(__('Select products to be new price applied on'));
```

but it returns only first chunk of searched products and I can not find any other option than is in the first chunk.

thanks.
