### ISSUE TITLE
Некорректные пути на CSS и JS файлы

### ISSUE THREAD

**Issue by vladviolenty** [orchidsoftware/platform#879]
Некорректные пути к js и css файлам админки
![image](https://user-images.githubusercontent.com/10224008/58799433-03078780-860e-11e9-9dd8-8f8c2e9fb544.png)

  - ORCHID Version: 5.0.0
  - Laravel Version: 5.8.17
  - PHP Version: 7.2.17
  - Database Version: mysql 5.7.26

**Comment by vladviolenty** [comment]
Решено с помощью команды

`php artisan orchid:link`

**Comment by tabuna** [comment]
Некоторые веб-серверы перехватывают вызовы к статическим файлам именно для таких случаев и существует эта команда. 

Добавил описание: https://orchid.software/ru/docs/installation/#publikatsiya-staticheskikh-resursov
