### ISSUE TITLE
Js ошибки на странице с примерами

### ISSUE THREAD

**Issue by CodingJediKnight** [orchidsoftware/platform#882]
### Steps to Reproduce the Problem

  1. Свежая установка orchid v5.0. 
  2. Логинимся и смотрим в devtools console браузера
  3. `/dashboard/example` - переходим на страницу и кликаем на таб `Example Tab Rows`
  4. Переходим на любую страницу из меню (именно через клик по ссылке)
  5. Переходим обратно на страницу `/dashboard/example` через меню. 
  6. Наблюдаем ошибки в консоле

### Specifications

  - ORCHID Version: 5.0
  - Laravel Version: 5.8
  - PHP Version: 7.3
  - Database Version: 8

**Comment by tabuna** [comment]
https://github.com/orchidsoftware/platform/blob/master/resources/js/controllers/screen/chart_controller.js#L22

**Comment by tabuna** [comment]
https://github.com/frappe/charts/issues/212#issuecomment-526913080

Теперь это было исправлено, обновлённый релиз выйдет в ближайшее время. Думаю мы можем закрыть это.
