### ISSUE TITLE
Доступ к страницам редактирования роли и пользователя без прав v.5.0.0

### ISSUE THREAD

**Issue by CodingJediKnight** [orchidsoftware/platform#884]
Пользователь без прав `platform.systems.users` и `platform.systems.roles` может зайти по прямой ссылки на "Экран" списков и редактирования пользователей и ролей соответственно.

ORCHID Version: 5.0.0

**Comment by CodingJediKnight** [comment]
Увы после фикса отвалился метод:
```app(App\Orchid\Screens\User\UserEditScreen::class)->switchUserStop()```
Который логинится обратно, после входа под пользователем по кнопке `Войти как пользователь` 🤔

**Comment by tabuna** [comment]
> вы после фикса отвалился метод:
app(App\Orchid\Screens\User\UserEditScreen::class)->switchUserStop()

Вынес этот метод за пределы экрана
