### ISSUE TITLE
Проблемы с функцией TD::set(...)->render()

### ISSUE THREAD

**Issue by CodingJediKnight** [orchidsoftware/platform#886]
https://github.com/orchidsoftware/platform/blob/master/install-stubs/Orchid/Layouts/User/UserListLayout.php#L32 при попытке передать модель юзера `App\Models\User` вместо `Orchid\Platform\Models\User` сваливается ошибка

`Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Argument 1 passed to App\Orchid\Layouts\User\UserListLayout::App\Orchid\Layouts\User\{closure}() must be an instance of App\Models\User, instance of Orchid\Platform\Models\User given, called in ...\vendor\orchid\platform\src\Screen\TD.php on line 162 (View: ...\vendor\orchid\platform\resources\views\layouts\table.blade.php)"`

### Specifications

  - ORCHID Version: 5.0.0
  - Laravel Version: 5.8
  - PHP Version: 7.3
  - Database Version: MySql 8.0

**Comment by tabuna** [comment]
Это нормальное поведение.
В качестве источника выступает именно модель `Orchid\Platform\Models\User` https://github.com/orchidsoftware/platform/blob/master/install-stubs/Orchid/Screens/User/UserListScreen.php#L10
Вы должны изменить сначала там, что бы приходили объекты нужного класса.

**Comment by CodingJediKnight** [comment]
> Это нормальное поведение.
> В качестве источника выступает именно модель `Orchid\Platform\Models\User` https://github.com/orchidsoftware/platform/blob/master/install-stubs/Orchid/Screens/User/UserListScreen.php#L10
> Вы должны изменить сначала там, что бы приходили объекты нужного класса.

Я так и сделал..
