### ISSUE TITLE
User table being overwritten

### ISSUE THREAD

**Issue by ShamarKellman** [orchidsoftware/platform#887]
### Expected Behavior
Using users table for normal users and administrators table for admin users, running `php artisan migrate` uses my user migration.

### Actual Behavior
Running `php artisan migrate` package migration overwrites my users table

### Steps to Reproduce the Problem

  1.create user table migration 
  1. create administrators table migration
  1. run `php artisan migrate`

### Specifications

  - ORCHID Version: 5.0.1
  - Laravel Version: 5.8
  - PHP Version: 7.2.18
  - Database Version: Maria DB 10.2

### Other Notes
- make migrations publishable  
- make UserModel configurable

**Comment by tabuna** [comment]
Have you published the migration files and modified them or created a new migration file?

**Comment by ShamarKellman** [comment]
The package migrations aren't publishable, they load directly from the package.
I am using Laravel's default user migration and my own administrators migration.

I recommend making them publishable. And also making the user model a config variable, so that the roles table wouldn't be tied directly to the users table. So if someone is using a custom model for the panel then the roles would use that model instead of the packages user model.

**Comment by tabuna** [comment]
> I recommend making them publishable. And also making the user model a config variable, so that the roles table wouldn't be tied directly to the users table. So if someone is using a custom model for the panel then the roles would use that model instead of the packages user model.

For this we have a substitution of models, you can specify it for example in the service provider.

Example:

```php
Dashboard::useModel(\Orchid\Platform\Models\User::class,\App\User::class);
```
or

```php
Dashboard::configure([
    'models' => [
        User::class => MyCustom::class,
    ],
]);
```

**Comment by tabuna** [comment]
Hi @ShamarKellman. I added the ability to publish migration files. 

To do this, run:

```bash
php artisan vendor:publish 
    --provider="Orchid\Platform\Providers\FoundationServiceProvider" 
    --tag="migrations"

```

**Comment by tabuna** [comment]
I close this because of inactivity. Please feel free to open again.
