### ISSUE TITLE
Relation field

### ISSUE THREAD

**Issue by brahimbim** [orchidsoftware/platform#893]
### Expected Behavior
My code 
![image](https://user-images.githubusercontent.com/24649160/59557877-0a02a280-8fdd-11e9-8c5f-c8837be150a6.png)

### Actual Behavior
Error 
![image](https://user-images.githubusercontent.com/24649160/59557876-f5260f00-8fdc-11e9-9cd4-19ea46d3f42c.png)

my problem is solved after this update
![image](https://user-images.githubusercontent.com/24649160/59557885-5fd74a80-8fdd-11e9-9c72-e2dbd495fb13.png)

### Specifications

  - ORCHID Version: 5.0.3
  - Laravel Version: 5.8
  - PHP Version: 7.3
  - Database Version: .8.0

**Comment by tabuna** [comment]
Hi @brahimbim. Thank you for paying attention to this issue.
The fix is already released with the release 5.0.5. 
Do you have the opportunity to check it yourself?

**Comment by brahimbim** [comment]
I check release 5.0.5, it's Ok, thanks for your fast respond
