### ISSUE TITLE
Тайтл в Layout::modal перезаписывает скрипт во время открытия

### ISSUE THREAD

**Issue by CodingJediKnight** [orchidsoftware/platform#903]
### Expected Behavior
```
Layout::modal('delete', [
    Layout::rows([]),
])->title('Title')
```
Тайтл модалки должен быть Title

### Actual Behavior
Если указать тайтл еще и у кнопки:
```
Link::name(__('Remove'))
    ->modal('delete')
    ->title('Title 2')
    ->icon('icon-trash')
    ->method('remove')
```
До клика по кнопке, которая открывает модалку тайтл будет 'Title'. При клике он перезаписывается на тайтл кнопки 'Title 2'

### Specifications

  - ORCHID Version: 5.1.2
  - Laravel Version: 5.8
  - PHP Version: 7.3

### Other Notes
Я не уверен, может быть это и верное поведение. Но из-за того, что Layout::modal новая функция, которая заменила Layout::modals, я предположил, что это может быть багом.

**Comment by tabuna** [comment]
@CodingJediKnight 

Это нормальное поведение.

Раньше можно было задать имя модального окна только через `Link`, то есть один объект неявно изменял состояние другого, что было не очень хорошо. Сейчас есть отдельный объект `Modal` и все свойства указываются в нём.

По поводу перезаписи  `Link::title()` был оставлен для обратной совместимости, его изменение происходит в самом конце (на уровне js), по этому он и переопределяет. 

Сама возможность будет оставлена для асинхронных модалок, что бы можно было писать "Редактирование объекта 1/2/3/ и т.д". Но лучше определять заголовок в самом объекте, так будет более понятно
