### ISSUE TITLE
Added Matrix Field

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#910]
**You must add a field to work with json:**

Example model
```php
namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'options' => 'array',
    ];
}
```

Example usage
```php
use App/User;
use Orchid\Screen\Fields\Matrix;

$options = User::find(1)->options;

Matrix::make('options')->value($options)
```

Thus made by Nova
![image](https://user-images.githubusercontent.com/5102591/61061724-77032f80-a405-11e9-9cb5-1cf906d96039.png)

**Extensions:**

Limit on the number of possible lines:
```php
Matrix::make('options')->maxRows(10)
```

**Comment by PSalador** [comment]
А там будет возможность редактировать значения или только удалять?

**Comment by tabuna** [comment]
> А там будет возможность редактировать значения или только удалять?

Yes, editing should be.

**Comment by tabuna** [comment]
I tried this solution and I think we could improve it:

```php
KeyValue::make('options')
```
result:

| key 	| value 	|
|-----	|-------	|
| 1   	| ...   	|
| 2   	| ...   	|
| 3   	| ...   	|


```php
KeyValue::make('options')
    ->columns([
        'Attribute',
        'Value',
        'Units',
    ])
```


| Attribute 	| Value 	| Units 	|
|-----------	|-------	|-------	|
| Color     	| RED   	|       	|
| Width     	| 20    	| cm    	|
| Height    	| 60    	| cm    	|

This will allow you to be more flexible with json.

**Comment by tabuna** [comment]
I think we can add a field definition so that the values are not only in the field:

```php
Matrix::make('users')
    ->title('Users list')
    ->columns(['id', 'name', 'email', 'created_at', 'uses_two_factor_auth'])
    ->fields([
        'id'                   => Input::make()->type('number'),
        'name'                 => TextArea::make(),
        'email'                => Select::make()->fromModel(User::class, 'name'),
        'created_at'           => DateTimer::make()->format('Y-m-d'),
        'uses_two_factor_auth' => CheckBox::make()->placeholder('Включена'),
    ]),
```

**Comment by tabuna** [comment]
I have documented this. I think it’s no longer worth continuing this thread. If you have suggestions or problems, open a new one.
