### ISSUE TITLE
Request online demo

### ISSUE THREAD

**Issue by loverdeveloper** [orchidsoftware/platform#912]

**Comment by tabuna** [comment]
Hi @loverdeveloper 

You have touched on an important topic. Sorry to ignore her for a while.

There are several reasons why there is no online demo right now:

- In the online demo you can only look at the design but don’t try the code, which, as I think, is much more important for the developer.
- Neither backpack, nova have an online demo.
- We removed the demo a few months ago, the VPS was provided to us by DO for free, which was blocked on the territory of Russia, then we brought the site and the demo to servers in the Russian Federation, but stocked up with the fact that many users blocked (in the browser)  the Russian trace by default (FB scandal).

I am not ready to provide good support for this right now. 
If the author or anyone else wants a demo on the Internet, please take responsibility.
