### ISSUE TITLE
request for a comprehensive tutorial

### ISSUE THREAD

**Issue by luigi-iaderosa** [orchidsoftware/platform#914]
hi all, 
I'm struggling with finding a decent  tutorial that could help me in implementing the Update section of any entity, in that I can't find a way to pre-populate a "media" object with pre-existing data (eg. from db/server). 
I've tried in the discussion room on telegram, but I see it's only in russian and I don't speak russian. 
Thank you in advance.

**Comment by tabuna** [comment]
Hi, do not stay out of the way we try to speak English.  In order for me to provide a good tutorial, I need to find out about what update is in question?  All graphic things are in the screens, for example, you can see how the user update is done.

If you have a comprehensive proposal for the manual, then do not hesitate and offer it, it will take a short time to create it.

**Comment by luigi-iaderosa** [comment]
hello, thank you for the quick answer.
What I needed was a way to edit not only text fields (I can already do that, actually it was quite simple),but also picture / upload fields. 
I can use picture / upload fields in insert and easily link the attachment entity to the newly created main entity (in my case, an entity called "news" has a text field and a picture field), unfortunately, I can't find a  way to use them in the "update" section (eg. to display a picture / upload field with the picture saved during the insert phase).

**Comment by tabuna** [comment]
A new attachment tutorial has just been added: https://orchid.software/en/docs/quickstart-files/

Sorry to take so long.
