### ISSUE TITLE
Exposing js/sass files for customization

### ISSUE THREAD

**Issue by mojtabaahn** [orchidsoftware/platform#915]
Hi
I'm wondering if you have plans for exposing js/sass files into resources folder **optionally**, using `--tag=assets`.
after publishing this assets, need to add platform's package.json requirements to root package.json using a single `npm install ...` and then adding webpack.mix.js configurations.

This can be useful for per-project customization of front-end behaviors. 
Currently it needs to be copied and configured by user completely.

**Comment by tabuna** [comment]
Yes it is in the plans

**Comment by mojtabaahn** [comment]
If it is the same routine as I described I can make a PR.

**Comment by tabuna** [comment]
I think we can do the same as laravel does with its presets. For example https://github.com/laravel/ui/blob/master/src/Presets/Bootstrap.php

I will be glad if you do this.

**Comment by tabuna** [comment]
Hi, I returned to this topic again and am ready to work it out more thoroughly.

I think you need to make 2 presets:
- To work as a stimulus.js user, without changing the source code
- And more advanced already with the publication of all source code on js and css


Accordingly, there will be two command `artisan preset orchid` and `artisan preset orchid-source`

**Comment by mojtabaahn** [comment]
I was thinking it is some sort of misleading to call them `presets` since it is actually possible to use them in existing assets and they do not remove all existing assets.

**Comment by tabuna** [comment]
Yes it is, but in reality when the user does: `php artisan vendor:publish` for `view/css/js/etc` he refuses to receive updates, because his files will be used
