### ISSUE TITLE
Override Routes

### ISSUE THREAD

**Issue by yxuko** [orchidsoftware/platform#917]
Hey,
I have being looking for a way to override routes but I cannot find a way to do so without editing the platform
This can be useful in some cases and bring more customization.

**Comment by tabuna** [comment]
Hi @yxuko!  

By default, changeable routes are published to the project.  The remaining routes are more systemic. Tell me which one you would like to redefine and why?

**Comment by yxuko** [comment]
I want to move announcement route to a settings page

**Comment by tabuna** [comment]
Um, but perhaps it is not located in the same place?
Announcements after all are placed on the system page?

**Comment by yxuko** [comment]
I want to override this to redirect it to /settings/annoucement
`$this->router->screen('/announcement', AnnouncementScreen::class)->name('systems.announcement');
`

**Comment by tabuna** [comment]
I do not want to do any special override mechanism. This is the only one screen that the user sees by default and which is hidden in the vendor. I suggest just putting it in a publication with users and roles.

**Comment by yxuko** [comment]
Yeahh you are right I will keep it that way for now.
Thanks for helping :D
