### ISSUE TITLE
Weird behavior with checkboxes in table layout

### ISSUE THREAD

**Issue by mojtabaahn** [orchidsoftware/platform#920]
It used to work well on v5.2 i believe.

### Expected Behavior
By clicking a checkbox or it's label, it has to get toggled.

### Actual Behavior
When having multiple rows on a table, by clicking any checkbox it has a _chance_ to **randomly toggle some previous** checkbox !

### Steps to Reproduce the Problem

  1. Fresh installation of laravel 
  1. Fresh installation of orchid 5.3 | 5.4
  1. Seeding User table by adding `factory(\App\User::class, 20)->create();` to `DatabaseSeeder.php` and running `php artisan db:seed`
 1. Replacing first Column of `UserListLayout.php` with below code

```php
TD::set('id', 'ID')
                ->render(function (User $user){
                    return CheckBox::make('users[]')
                        ->value($user->id)
                        ->placeholder($user->getNameTitle())
                        ->checked(false)
                        ->render();
                }),
```

### Specifications

  - ORCHID Version:5.3 , 5.4
  - Laravel Version: 5.8
  - PHP Version:7.2
  - Database Version: SQlite

 ### Screen capture
![c89bcc10-095c-45ab-946d-84b1ad77f72d](https://user-images.githubusercontent.com/9845317/62050819-43a70a00-b227-11e9-9247-0ed4dae3e7bc.gif)

**Comment by tabuna** [comment]
This is a problem because all your fields have the same name.


https://github.com/orchidsoftware/platform/issues/874

An earlier example 

i will try to solve it as soon as possible

**Comment by tabuna** [comment]
Did you manage to reproduce the problem after the update?

**Comment by mojtabaahn** [comment]
just checking..

**Comment by mojtabaahn** [comment]
Works well, Thanks!
