### ISSUE TITLE
Is this a mariadb related problem?

### ISSUE THREAD

**Issue by hominini** [orchidsoftware/platform#922]
### Expected Behavior
Package installed

### Actual Behavior
 SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null' at line 1 (SQL: alter table `users` add `last_login` timestamp null, add `permissions` json null)

### Steps to Reproduce the Problem

  1.Run php artisan orchid:install

### Specifications

  - ORCHID Version: latest
  - Laravel Version: 5.8
  - PHP Version: 7.3
  - Database Version: Ver 15.1 Distrib 10.1.38-MariaDB, for debian-linux-gnu (x86_64)

### Other Notes
Trying to install orchid in a existing laravel project

**Comment by tabuna** [comment]
Hey @hominini .

Yes, this is a problem with MariaDB.
The package uses the column type "JSON", which is not yet in your version.

From the options offered, this is to update your database version or use package[ laravel-mariadb](https://github.com/ybr-nx/laravel-mariadb).

**Comment by hominini** [comment]
thanks, you know
