### ISSUE TITLE
TextArea not save previously entered value when Redirect::back()->withInput() used

### ISSUE THREAD

**Issue by likemusic** [orchidsoftware/platform#927]
### Expected Behavior
TextArea contains previously entered value.

### Actual Behavior
TextArea is empty for new entity and contains real value for exists entitities.

### Steps to Reproduce the Problem

  1. Use `TextArea::make('')` in layout() return value for screen (inside Layout::rows([])).
  1. In public function createOrUpdate(Product $product, Request $request)  use like:
```
try {
//do some things
throw new \Exception();
} catch (\Exception $e) {
            Alert::error($exception->getMessage());
            return Redirect::back()->withInput();
}
```

### Specifications

  - ORCHID Version: 5.5.0
  - Laravel Version: 5.8.30
  - PHP Version: 7.2.21
  - Database Version: mariadb:10.4

**Comment by tabuna** [comment]
Hi @likemusic . Thanks for paying attention to this.

I prepared a change, you can check if it works for your scenario

**Comment by tabuna** [comment]
It is believed that the problem is resolved.
If you run into this, feel free to reopen issue.
