### ISSUE TITLE
Orchid 5.5 разные проблемки

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#929]
1. Сразу после установки показывает "A new stable version of ORCHID is available. Please update to the latest version." хотя стоит последняя версия.
2. Стартовый экран сделать, может туда добавить текст и ссылку на документацию?
3. В верстке на узких экранах много места под поля.
4. Может Example добавить в доступы чтобы их можно было отключить одним кликом?

**Comment by tee-moore** [comment]
5. Миграция для таблицы Users, метод down удаляет таблицу вместо удаления добавленных полей

**Comment by tabuna** [comment]
1. Поправил, реагировал на созданную 6.0.x-dev ветку
2. Добавил
3. Поработал над адаптивом ещё в 5.5.1, есть какие либо замечания? Что ты хотел бы изменить?
4. Это ведь пример, который может вполне оставаться на стадии разработки и быть удалён когда придёт время выкладывать проект на прод. Надеюсь к тому времени уже не нужно в него смотреть.
