### ISSUE TITLE
Upload field - не работает модалка

### ISSUE THREAD

**Issue by vla-dis** [orchidsoftware/platform#931]
По факту сами файлы загружаются, но нет возможности открыть модалку с редактированием описания для второго файла. 

https://c2n.me/433nTAG
https://c2n.me/433nTUY

### Steps to Reproduce the Problem

  1. Свежая установка
  2. /dashboard/example
  3. Перетащить 2 файла (хоть одновременно, хоть последовательно) в Upload field

### Specifications

  - ORCHID Version: 5.5.2
  - Laravel Version: 5.8
  - PHP Version: 7.3
  - Database Version: 5.7

**Comment by tabuna** [comment]
Привет @vla-dis !
Спасибо, что обратили на это внимание, но [у меня не получилось повторить это](https://drive.google.com/open?id=1ZOpfMWkCPzgYdy68rk2sQH-f37dcrVZ8).
Чем мои действия отличаются от ваших?

**Comment by vla-dis** [comment]
Да, нашел в чем дело.
Если заливать разные файлы то все хорошо. Но если один и тот же, но под разными именами, то вот тогда.
https://drive.google.com/file/d/1ckEbk1ZmikYI8K2FfRXmZcxI820wXuLv/view

**Comment by tabuna** [comment]
Я смог воспроизвести описанную проблему, у меня такое поведение произошло из-за того, что на сервере был указан слишком маленький лимит на загрузку файла:

```
; Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
upload_max_filesize = 20M
```

После увеличения, хэш файла начал считаться хорошо и загрузка происходила успешно, можете ли вы повторить это изменив значение в php.ini ?

**Comment by vla-dis** [comment]
100M задано, с текстовыми доками по ~40 байт та же история. 
Из сопутствующего: 
- в бд создаются две строки, с одинаковыми именами и хэшами
- физически файл в storage создается один

**Comment by tabuna** [comment]
@vla-dis Можешь пожалуйста проверить временный `tmp-dir` и что у пользователя от которого запущен `php` процесс есть права на чтение этой директории?

**Comment by vla-dis** [comment]
Вроде все путем:
$temp = tempnam(sys_get_temp_dir(), 'hello_world');
dd ($temp);

>"/tmp/hello_worldQvguDq"

**Comment by PSalador** [comment]
Думаю что ситуация возникает, из-за того что в БД имя файла генерируется по хешу, и соответственно он файлы с одинаковым хэшем считает за один.

**Comment by tabuna** [comment]
Прошло достаточно много времени, за которое опубликовалось множество релизов.
Если проблема все ещё актуальна, не стесняйтесь и откройте этот issue снова.
