### ISSUE TITLE
Orchid 5.5 migration

### ISSUE THREAD

**Issue by tee-moore** [orchidsoftware/platform#932]
1.Миграция CreateOrchidUsersTable при откате удаляет таблицу users.
2.Может стоит добавить проверку на существование таблиц, т.к. roles, settings,attachments могут уже быть..

**Comment by tabuna** [comment]
> Может стоит добавить проверку на существование таблиц, т.к. roles, settings,attachments могут уже быть..

Как вы предлагаете об этом информировать?

**Comment by tee-moore** [comment]
второй пункт просто к размышлению, у меня эти таблицы есть просто)
в CreateNotificationsTable есть проверка кстати.
возможно просто добавить префикс к названиям таблиц, но тут уже вопрос совместимости будет..

**Comment by tabuna** [comment]
> возможно просто добавить префикс к названиям таблиц, но тут уже вопрос совместимости будет..

Это можно сделать самостоятельно опубликовав миграции, добавить префикс, изменить подключение и т.п.

**Comment by tabuna** [comment]
> Миграция CreateOrchidUsersTable при откате удаляет таблицу users.

Исправил это для всех подключений кроме `sqlite`.

Так как она не поддерживает изменение более одного столбца за миграцию и требует создание новых, что сейчас может сказаться на обратной совместимости, предлагаю оставить это, так как малое количество людей использует `sqlite` в продакшене и исправить для него в следующем мажорном релизе.
