### ISSUE TITLE
Add ability to use turbolinks-cache-control meta tag inside screen as its property

### ISSUE THREAD

**Issue by SKPOmsk** [orchidsoftware/platform#933]
### Proposal

Add ability to manipulate `<meta name="turbolinks-cache-control" content="no-cache">` in screen view from screen implementation as property like:
```
class MyAwesomeScreen extends Screen
{
    public $turbolinkCacheControl = 'no-cache'
    public $name = 'Vendor';
...
```

**Comment by tabuna** [comment]
Hi @SKPOmsk 

What are the benefits of this change?

I can assume that you are having difficulty writing js in a blade representation. This can be solved by wrapping in an event.

```javascript
document.addEventListener("turbolinks:load", function() {
  // ...
})
```

You can also publish view files and change this value.

Now it’s hard for me to imagine why this might be necessary. 

I have plans to add an option for the buttons to disable turbolinks loading as it has problems downloading files 

> (Now it is solved with target = blank)
