### ISSUE TITLE
No FileBag in Request

### ISSUE THREAD

**Issue by yxuko** [orchidsoftware/platform#939]
### Expected Behavior
Upload and Picture should return FileBag in Request so that can be retrieved for attachement via File($request->file('photo')); But It returns NULL

### Actual Behavior
![image](https://user-images.githubusercontent.com/1786317/63965852-62085b80-ca9a-11e9-8ff0-1572e8e9e28a.png)

### Specifications

  - ORCHID Version: 5.5.5
  - Laravel Version: 5.8
  - PHP Version: 7.3.8
  - Database Version: 8.0.16

**Comment by tabuna** [comment]
Direct loading occurs through Ajax. 
Both of these fields return attachment table entries.

You can get around this using:
```php
Input::make('photo')->type('file')
```
But I see no reason to do so? 
Do you want to process the file before downloading it? 
Or why do you want to capture him?

**Comment by yxuko** [comment]
Besides processing I want to capture it so that I can attach it to Attachement

**Comment by tabuna** [comment]
To get attachment:

```php
use Orchid\Attachment\File;

public function upload(Request $request)
{
    $file = new File($request->file('photo'));
    $attachment = $file->load();

}
```
