### ISSUE TITLE
dashboard page: No input file specified. 

### ISSUE THREAD

**Issue by leonpug** [orchidsoftware/platform#942]
### Expected Behavior

show the dashboard page

### Actual Behavior

empty page with text: "No input file specified."

### Specifications

  - ORCHID Version: 5.5.5
  - Laravel Version: 5.8.34
  - PHP Version: 7.3.7
  - Database Version: MySQL 5.7.27

### Other Notes
  - Laravel installation: Homestead/Vagrant on Win10
  - domain: orchid.test
  - php artisan route:list
[route.list.txt](https://github.com/orchidsoftware/platform/files/3562312/route.list.txt)

**Comment by tabuna** [comment]
Hi @leonpug 

The error "No input file specified" is not related to the package. 
This is a problem with your environment.

There are several reasons for the error:
1. You have not set the SCRIPT_FILENAME variable in the nginx config;
2. An invalid root argument was specified in the nginx config;
3. The variable open_basedir in /etc/php7/fpm/php.ini or in the php7-fpm pool config contains a path that does not match the root argument in the nginx config;
4. A user with rights that runs php7-fpm or a specific pool php7-fpm does not have access rights to a directory or file with a php script;

**Comment by leonpug** [comment]
Sorry, my error in Homestead.yaml.
Now it's working.
thanks
