### ISSUE TITLE
Не работают Alert сообщения

### ISSUE THREAD

**Issue by TuxCod** [orchidsoftware/platform#943]
После работы метода не выводять алерт сообщеня.

### Steps to Reproduce the Problem

  1. install ORCHID version 5.5.2
  2. composer update (ORCHID 5.5.5 update)
  3. в Screen по нажатию на кнопку вызывается метод с одержимым
method call: Alert::warning('Запись успешно сохранена.');
return redirect()->route('platform.news.edit');

### Specifications

  - ORCHID Version: 5.5.5
  - Laravel Version:
  - PHP Version:
  - Database Version:

### Other Notes

Если посмотреть состояние сессии перед редиректом то данные в сессии есть, а после редиректа они отсутствуют
method call: Alert::warning('Запись успешно сохранена.');
dd($request->session()->all()); // тут данные есть
return redirect()->route('platform.news.edit');
// на открывшейся странице данные в сессии нет

**Comment by tabuna** [comment]
Привет @TuxCod 

Как мне воспроизвести это?

Попробовал написать:

```php
use Orchid\Support\Facades\Alert;
//...

    public function example()
    {
        Alert::warning('Lorem ipsum...');

        return redirect()->route('platform.main');
    }
```

И на главной странице сообщение отображается

**Comment by TuxCod** [comment]
Я реализовывал пример из документации

https://orchid.software/ru/docs/quickstart-crud/

**Comment by TuxCod** [comment]
Я смог решить данную проблему, изменив 
namespace Orchid\Alert;

flash на put

`public function message($message, $level = self::INFO): self
    {
        $this->session->put('flash_notification.message', $message);
        $this->session->put('flash_notification.level', $level);

        return $this;
    }`

и изменив alert.blade.php добавив

`{{session()->put('flash_notification.message', null)}}`

**Comment by tabuna** [comment]
@TuxCod 

`Flash` - специальная конструкция именно для одноразового [отображения](https://laravel.com/docs/5.8/session#flash-data)

**Comment by TuxCod** [comment]
Да, данная проблема на чистой установке. 
Я думаю это как-то связанно с моим локальным сервером MAMP.

---

Подскажите есть ли возможность использовать множественные поля, например:
есть новость, у новости может быть несколько категорий. 
Предполагается размещение select - выбираем категорию, теперь хотим добавить еще одну категорию, жмем "добавить еще" и отображается еще один select с аналогичным выбором.
