### ISSUE TITLE
php artisan orchid:install fail

### ISSUE THREAD

**Issue by adeguntoro** [orchidsoftware/platform#946]
### Actual Behavior

Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null' at line 1 (SQL: alter table `users` add `last_login` timestamp null, add `permissions` json null)

### Specifications

  - ORCHID Version: 5.5
  - Laravel Version: 5.8.17
  - PHP Version: 7.3.3
  - Database Version: 10.1.38-MariaDB

**Comment by tabuna** [comment]
Your database version does not support a JSON column, please update your database version or use an adapter. 

More:

- https://github.com/orchidsoftware/platform/issues/251
- https://github.com/orchidsoftware/platform/issues/643
- https://github.com/orchidsoftware/platform/issues/922
- https://github.com/orchidsoftware/platform/issues/715#issuecomment-465271265
