### ISSUE TITLE
Missing Link class and Link::name() method

### ISSUE THREAD

**Issue by ab192130** [orchidsoftware/platform#947]
### Expected Behavior
The Create/Update button - Should create a new (update) record and show success alert on a RecordEditScreen.

### Actual Behavior
- Class 'Orchid\Screen\Link' not found

I've tried also **Orchid\Screen\Actions\Link**
- Call to undefined method Orchid\Screen\Actions\Link::name()

### Specifications
  - ORCHID Version: 6.0
  - Laravel Version: 6.0.1
  - PHP Version: 7.2.11
  - Database Version: (mysql) 5.7.24

### Other Notes
It worked earlier in ORCHID v5.5

**Comment by tabuna** [comment]
HI @ab192130 ! We do not have a RecordEditScreen screen.

But I understand what you mean. In version 6, the Link class was divided into 4 separate classes

https://orchid.software/en/docs/screens/#actions

```php
Button::make('Example Button')
    ->method('example')
    ->icon('icon-bag'),

ModalToggle::make('Example Modals')
    ->modal('exampleModal')
    ->method('example')
    ->icon('icon-full-screen'),

Link::make('Website')
    ->href('http://orchid.software')
    ->icon('icon-globe-alt'),

DropDown::make('Example Group Button')
    ->icon('icon-folder-alt')
    ->list([
        Button::make('Example Button')
            ->method('example')
            ->icon('icon-bag'),

        Button::make('Example Button')
            ->method('example')
            ->icon('icon-bag'),
    ]),
```

**Comment by ab192130** [comment]
Hello @tabuna ! Thanks so much. I'm done with this. 
But there is something else. Regarding selection multiple items with Relation Fields.
