### ISSUE TITLE
Update to Orchid 6.0 from 5.x

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/platform#948]
#### Link (Orchid\Screen\Link)
1. Replace `use Orchid\Screen\Link;` on  `use Orchid\Screen\Actions\Link;`
2. Replace `Link::name()` on  `Link::make()`
3. Replace Link on Button `use Orchid\Screen\Actions\Button;` `Link::name('save')->method('save')` on  `Button::make('save')->method('save')
#### Layout (Orchid\Screen\Layouts\Table)
1. Replace function `fields()` on all layouts  on  `columns()`
2. Replace `$data` on `$target`
#### Modal
1. Replace `Link::make('name')->modal('modal')` on  `ModalToggle::make('name')->modal('modal')`
2. Replace `Layout::modals(['modal',[ ModalLayout::class ]])` on  `Layout::modal('modal',[ModalLayout::class])`
3. Replace `use Orchid\Screen\Layouts\Modals;` on `use Orchid\Screen\Layouts\Modal;`

**Comment by tabuna** [comment]
@PSalador I thank you for this work.
