### ISSUE TITLE
There is no error display (ignition) when submitting the form

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#952]
### Expected Behavior

If you submit a form in which there will be an error with the return page, the page should be displayed.

example:
![image](https://user-images.githubusercontent.com/5102591/64943226-d94c3680-d873-11e9-82cd-e9500f3058d3.png)

### Actual Behavior

This worked before implementing ignition.

![image](https://user-images.githubusercontent.com/5102591/64943195-c3d70c80-d873-11e9-926c-4b29a05a0536.png)

### Steps to Reproduce the Problem

  1. Create form
  1. Make a mistake in it
  1. Submit form

### Specifications

  - ORCHID Version: 6.0.*
  - Laravel Version: 6.0.*
  - PHP Version: any
  - Database Version: any

**Comment by tabuna** [comment]
This seems to be due to the ignite page using javascript, and the previous version relied only on html.

When pasted by the current method, any <script> tags are not executed
```javascript
window.history.pushState({ html: error.response.data }, '', error.request.responseURL);
document.documentElement.innerHTML = error.response.data;
```

We can change this behavior with:
```javascript
Turbolinks.clearCache();
document.write(error.response.data);
```

**Comment by tabuna** [comment]
It still takes place if we follow the links and get an error.

After this change, the back buttons in the browser stopped working

**Comment by funtom48** [comment]
@tabuna, fixed
