### ISSUE TITLE
conditional fields

### ISSUE THREAD

**Issue by AaUI-Framework** [orchidsoftware/platform#953]
How can I make conditional fields
(I searched the documentation and I didn't find it)

I am Brazilian, here people and companies have diferent documents for each one (CPF, CNPJ) 
respectively, but only chage the masks and the max numbers,
how can I create a field where I select the type of registration using a radio and exchange the subsequent input

**Comment by tabuna** [comment]
Hi, this is the most popular question.  Dependent and condition fields do not exist yet :)

I can advise you to use javascript to hide or display the field dynamically.


If this is only for forming on the server, then you can use the usual condition when forming the array.

You can also beat the current restriction by breaking the creation of the object into steps, where you will already know in advance who the campaign is in front of you or the person

**Comment by Nks** [comment]
#869

**Comment by tabuna** [comment]
Implemented in [7.2](https://github.com/orchidsoftware/platform/releases/tag/7.2.0)
