### ISSUE TITLE
Async modal bug

### ISSUE THREAD

**Issue by Leshkens** [orchidsoftware/platform#955]
Если на одном экране присутствует более одного **асинхронного** модального окна, то следующие окна при вызове подменяют свое содержимое на содержимое первого.

### Пример:

![GTiuuJQhbx](https://user-images.githubusercontent.com/8939383/65067049-0ea17300-d99f-11e9-9a52-f3941ab6f55f.gif)

### Код:

UserListScreen
```
    public function layout() : array
    {
        return [
            UserListLayout::class,

            Layout::modal('oneAsyncModal', [
                Layout::rows([
                    Input::make('user.name')
                        ->type('text')
                        ->max(255)
                        ->required()
                        ->horizontal()
                        ->title(__('Name'))
                        ->placeholder(__('Name')),
                ])
            ])->async('asyncGetUser'),

            Layout::modal('twoAsyncModal', [
                Layout::rows([
                    Input::make('user.email')
                        ->type('email')
                        ->required()
                        ->horizontal()
                        ->title(__('Email'))
                        ->placeholder(__('Email')),
                ])
            ])->async('asyncGetUser'),
        ];
    }

    public function asyncGetUser(User $user) : array
    {
        return [
            'user' => $user,
        ];
    }
```
UserListLayout
```
            TD::set('name', __('Name'))
                ->loadModalAsync('oneAsyncModal', 'saveUser', 'id', 'name')
                ->sort(),

            TD::set('email', __('Email'))
                ->loadModalAsync('twoAsyncModal', 'saveUser', 'id', 'email')
                ->sort(),
```

### Specifications

  - ORCHID Version: 6.0.2
  - Laravel Version: 6

**Comment by tabuna** [comment]
> Если на одном экране присутствует более одного асинхронного модального окна, то следующие окна при вызове подменяют свое содержимое на содержимое первого.

Немного иначе, для того, что бы экран возвращал только один слой, а не все для него создается некоторое "уникальное значение" на основе его параметров. 

Получилось так, что у `oneAsyncModal` и `twoAsyncModal` хеши полностью совпадали, а так как `oneAsyncModal`  был объявлен раньше именно он и отображался.


Добавил в формирование хеша больше параметров, так что бы учитывалось и их содержимое.


До релиза, могу порекомендовать использовать фиксированы классы вместо анонимных:

```php
Layout::modal('oneAsyncModal', oneAsyncModal::class)
Layout::modal('twoAsyncModal', twoAsyncModal::class)
```

**Comment by Leshkens** [comment]
> До релиза, могу порекомендовать использовать фиксированы классы вместо анонимных:

Использовать как в примере не получится, потому что метод modal вторым аргументом ждет массив.

А вот так:

```
    public function layout() : array
    {
        return [
            UserListLayout::class,

            Layout::modal('oneAsyncModal', [
                OneModalLayout::class
            ])->async('asyncGetUser'),

            Layout::modal('twoAsyncModal', [
                TwoModalLayout::class
            ])->async('asyncGetUser'),
        ];
    }
```
баг все равно присутствует.
