### ISSUE TITLE
Cell render with asynchronous modal window

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#959]
It hurts me when I want to derive my own view and use the asynchronous modal:

```php
TD::set('email')->loadModalAsync('oneAsyncModal', 'saveUser', 'id', 'email');
```

This approach involves only plain text output. If I want to call my own render, then it completely replaces the window call. This is because the `loadModalAsync` method is a private add-on for` render`. The only way out now is to use macros #785

I think we can change the method `loadModalAsync` completely removing the last argument

```php
TD::set('email')
    ->loadModalAsync('oneAsyncModal', 'saveUser', 'id')
    ->render(function (Repository $repository){
        return $repository->get('email');
    })
```

This can cause conflicts, so it’s good to rename the method, and leave depricated for the current one.

```php
TD::set('email')
    ->toggleAsync('oneAsyncModal', 'saveUser', 'id')
    ->render(function (Repository $repository){
        return $repository->get('email');
    })
```

**Comment by 2kodes** [comment]
Yeah i think this is much better
