### ISSUE TITLE
confirm message support

### ISSUE THREAD

**Issue by imnicy** [orchidsoftware/platform#960]
Click Confirmation Message Box on Button or Link?

**Comment by tabuna** [comment]
Hi, there is such an opportunity with the release of corrective release 6.1.2 - 2019-09-20


‘’’php
Button::make(“Delete”)->confirm(“your text”);
‘’’

**Comment by tabuna** [comment]
You can also use modal windows as confirmation

**Comment by imnicy** [comment]
thank you！
