### ISSUE TITLE
Icon prefix for method

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#964]
Currently, the platform contains a package of [icons](https://github.com/orchidsoftware/icons) which have the prefix `icon-`.  
We also define them in code:

```php
ItemMenu::label('Example')->icon('icon-heart');
```

My suggestion is not to duplicate the spelling. 
Thus, the example above can be written as:

```php
ItemMenu::label('Example')->icon('heart');
```

This can cause backward compatibility issues, so it’s acceptable to use both arguments
To do this, you can use the assistant:
```php
public function icon(string $icon) {
     $icon = Str::start($icon, 'icon-');
     //...
}
```

I think this small change is perfect for those who want to contribute. And also reduce irritability when working with code

**Comment by 2kodes** [comment]
What about cases where a person wants to use their custom icons from a different icon set? 

Currently for me I am using [line awesome](https://icons8.com/line-awesome)  and it was quite nice that i could just specify the classes for it without having to configure or change something in the blade or other files
