### ISSUE TITLE
Different routing for the same Screen

### ISSUE THREAD

**Issue by Hrache** [orchidsoftware/platform#966]
Hello, I'm Hratch and nice to meet you.
I've some situation where I decided to use the same screen for (at the moment) two different routes

```
$this->router->screen('comments', CommentsListScreen::class)->name('platform.comments.list');
$this->router->screen('comments/latest', CommentsListScreen::class)->name('platform.comments.latest');
```

In the Screen's constructor I was required to write something like this to be able to load different UIs :

```
parent::__construct($request);
if (Route:: current()->originalParameters() === ['method' => 'latest'])
{
   $this->name = "Latest comments";
   $this->description = "The list of latest comments";
   $this->latest = true;
}
```

I was thinking that route naming will work pretty fine for this which was going to make me write less code even though be without constructor kinda the route name decided everything ... but it didn't work. Is there any shorter solution, because I need to use the same layout the only thing is the query that should prepare different data for passing into the view:

```
'comments' => (
   ($this->latest)?
      Comments::where('updated_at', '>=', $request->user()->last_login)->paginate(25) :
      Comments::paginate(25)
)
```

So as a note there is **$this->latest** means the case where we have this route -> 

```
$this->router->screen('comments/latest', CommentsListScreen::class)->name('platform.comments.latest');
```

Thanks for your attention ...

**Comment by tabuna** [comment]
Hi, you want to separate them by name, but for some reason use the path
Have you tried using something like `Route::currentRouteName()`
This will return the names directly `platform.comments.latest` or `platform.comments.list`


```php
public function query(): array
{
    if(Route::currentRouteName() === 'platform.comments.latest'){
        //...
    }

    return [];
}
```

Also, I can not help but notice that in reality you do not need two screens to do what you want to do. We have http sorting and filtering, as well as individual filters.

You can see them in action on the user list page:

![image](https://user-images.githubusercontent.com/5102591/65545867-f1305400-df1e-11e9-9450-3883eed6fc89.png)

You can also familiarize yourself with this on the [documentation page](https://orchid.software/en/docs/filters/#automatic-http-filtering-and-sorting).

**Comment by Hrache** [comment]
Yes basically I chose this package for a admin from many - it is intuitive and full of functionalities, I did like it, thanks.

So dear **Alexander** the codes I provided is the case when I could realize the goal. I did try what you shown above,  but the whole question was exactly in that that it doesn't work when I use below code

```
(Route::currentRouteName() === 'platform.comments.latest')
```

So I was about, why it doesn't when the urls at the end are different and correspondingly routes must and have different names ? I described it and mentioned about that case ...

**Comment by tabuna** [comment]
Hi, before giving you the code, I created two routes using one screen.  And it worked for me.

**Comment by Hrache** [comment]
So it means if I'll change this
```
if (Route:: current()->originalParameters() === ['method' => 'latest'])
```
into this
```
if (Route::currentRouteName() === 'platform.comments.latest') {
```
it'll work the way I need it to work ?
If in your case it works 100% then I'll post there the content of the files, to make sure you really get what works and what doesn't, because basically I tried it and it didn't work. Here is the mechanism:

- CommentsListScreen
- CommentsListLayout

```
$this->router->screen('comments', CommentsListScreen::class)->name('platform.comments.list');
$this->router->screen('comments/latest', CommentsListScreen::class)->name('platform.comments.latest');
```

**Comment by tabuna** [comment]
That's right, you can change it painlessly.

But you have another problem, the fact is that in this code:

```php
$this->router->screen('comments', CommentsListScreen::class)->name('platform.comments.list');
$this->router->screen('comments/latest', CommentsListScreen::class)->name('platform.comments.latest');
```

`platform.comments.latest` -  will never be executed. Since it is, the previous option gets into the regular expression earlier. To kill yourself, look at the result of the command: `php artisan route:list`

Therefore, you should swap them (Longer route - announced earlier.):

```php
$this->router->screen('comments/latest', CommentsListScreen::class)->name('platform.comments.latest');
$this->router->screen('comments', CommentsListScreen::class)->name('platform.comments.list');
```

**Comment by Hrache** [comment]
Well, lets not to kill anyone, only hunt a fish :) and let me add something to this, I actually didn't debug the OOP code of the router, but by the simplest logic and intuition the order mustn't have any meaning there, because we have unique names for each route and it should work properly.
    The routes are made by their meanings such in my case: I've _comments_ and all other sub pages must contain _comments_ in the route name and in the address string for the friendly URL purpose. So the whole question was why the uniqueness of the routing names aren't working properly, maybe I should ask it from Laravel forum, it really murdered my time ?

**Comment by tabuna** [comment]
Good. This is a package issue.
To understand it, I will give an example of a route:

```php
Route::get('user/{name}', /*...*/)->name('user.name');

Route::get('user/{id}', /*...*/)->name('user.id');
```
The second route will never be completed, 
since the first condition will also satisfy the needs in this form.


Now a little harder:
```php
Route::get('user/{parameters?}', /*...*/)->where('parameters', '.*');
Route::get('user/list', /*...*/);
```
Here, obviously, the first argument is different. 
But the second condition will never be fulfilled either.


The `Router::screen` is very similar to this example.
Since you do not declare on the screen all public methods as available, but you can refer to them.

Under the hood, it looks something like this:
```php
Route::screen('user/list', /*...*/);

// Will be converted to:

Route::any('user/list/{method?}/{parameters?}', /*...*/);
```

I'm sorry you came across this

**Comment by Hrache** [comment]
There is nothing to be sorry for (in this case of course :D)
    Yep, the order somehow plays role in this case, but it isn't normal, maybe some switch in between ordered and not ordered types of routing could be awesome. I changed the order it did work, but wow, I'm still confused honestly.
    And one more time by my opinion Orchid is a nice package, there were like 13 of them I did try 4 or 5 of them, but the Orchid I hope will be the the last choice.
    Thanks **Tabuna** ...
