### ISSUE TITLE
Alert not visible after redirect back

### ISSUE THREAD

**Issue by vdf89** [orchidsoftware/platform#967]
Hello!

**Describe the bug**
The Alert info message is not visible after a redirect back from a Screen.

**To Reproduce**
  1. Create a Screen class;
  2. Define a Button that points to a method;
  3. Define a method that contains a code like this:
`public function sendMessage(Request $request)
    {
        Alert::info('Your e-mail has been sent successfully!');
        return back();
    }`

**Expected behavior**
A redirect to the previous page with a visible Alert message.

**Desktop (please complete the following information):**
 - OS: macOS Sierra
 - Browser: Chrome, Firefox, Safari

**Server (please complete the following information):**
  - Platform Version: 6.1
  - Laravel Version: 6.0.4
  - PHP Version:  7.2.14

Thanks for your attention.
Vincenzo

**Comment by tabuna** [comment]
Hi, we already had some reports of similar behavior (#943, #853).

They all boiled down to an environmental problem 
that their web server for development missed the result.


Please tell me what are you using?

**Comment by vdf89** [comment]
Sorry but I can't speak russian. :)
I am using MAMP 5.3.

**Comment by tabuna** [comment]
Do not worry. Yes, this software does not meet the needs.

I looked in Google the "MAMP session problem" problem 
and this is a fairly common problem since 2014.

I can’t influence this software in any way, so you have to manually change it yourself.

**Comment by vdf89** [comment]
Ok, thank you very much for you support!
