### ISSUE TITLE
Make class function of input field add to existing classes

### ISSUE THREAD

**Issue by 2kodes** [orchidsoftware/platform#969]
**Is your feature request related to a problem? Please describe.**
I added a class `mt` to a checkbox like this 

`CheckBox::make('field')->title('Allow download?')->class('mt-4')`

When the field was rendered only the class I added was in the class attribute. I think the class I added should have been added to the already existing classes for the field.

**Describe the solution you'd like**
1. The new class is appended to the existing class for the field or html element when rendered 
      OR
2. The new class is appended by default but there is an option to specify if it should override the existing class

**Comment by tabuna** [comment]
I don't think adding a default would be a good solution. This causes a mismatch with other methods.

For example:

```php
CheckBox::make('field')
    ->value('Default value')
    ->value('Custom value 2');
```
I expect to receive `Custom value 2`, but not their gluing.

In this case, it would be great to have additional methods like:

```php
CheckBox::make('field')
    ->class('form-control mt-1')
    ->addClass('mt-4')
    ->removeClass('mt-1');
```

As a result of this: `form-control mt-4`

**Comment by tabuna** [comment]
There may be several options for implementation.

- Create and use a trade
- Create a basic concatenation method and use trade / methods
- Or make them magical, by attribute name

**Comment by 2kodes** [comment]
I like `addClass`  since the results will be clear . In this case we can still keep the `class` method for cases when you want to override

**Comment by 2kodes** [comment]
> There may be several options for implementation.
> 
> * Create and use a trade
> * Create a basic concatenation method and use trade / methods
> * Or make them magical, by attribute name

I am not exactly clear on this

**Comment by 2kodes** [comment]
Hello @tabuna , 

Please any update on this??

**Comment by tabuna** [comment]
Hi @2kodes .

This is not a mistake, and accordingly it has a rather low priority. 
I work in my free time, so this may not happen quickly. 
But you can help me by making PR.

Even if you cannot and do not want to do this, we will add it anyway, but you will have to wait;)

**Comment by 2kodes** [comment]
lol.. cool .. no problem.will see if i can make a PR

**Comment by lhoucinecherif** [comment]
Hi,

I made a Workaround for this , you can add your own functions to a Trait like this : 

create an extended class for every Field you want to use  (here is an example with a DateTimer ) : `./app/Orchid/Fields/DateTimer.php`

This class will extend the original Field,  and use our custom Trait  like this : 

```
<?php

namespace  App\Orchid\Fields;

use \App\Orchid\Traits\Field;

class DateTimer extends \Orchid\Screen\Fields\DateTimer
{
    use Field;
}
```

then we create our Trait :  `./app/Orchid/Traits/Field.php` : 

```
<?php
namespace App\Orchid\Traits;

use Illuminate\Support\Str;

trait Field
{
    /**
     * @return static
     */
    public function addClass($classes = null): self
    {
        $class = $this->get('class');

        if ($classes) {
            if (is_array($classes)) {
                $class .= implode(' ', $classes);
            } else {
                $class .= ' ' . $classes;
            }
        }

        return $this->set('class', $class);
    }

    /**
     * @return static
     */
    public function removeClass($classes = null)
    {
        $class = $this->get('class');

        if ($classes) {
            if (is_string($classes)) {
                $classes = array_values(array_filter(Str::of($classes)->trim()->explode(' ')->toArray()));
            }
            $class = Str::remove($classes, $class);
        }

        return $this->set('class', $class);
    }
}

```

finally , we use this new created field (DateTimer) instead of the original one  : 

use `App\Orchid\Fields\DateTimer; `instead of `Orchid\Screen\Fields\DateTimer;`


this is just an example, your can make your own files/folder structure  just use the correct namespaces.
