### ISSUE TITLE
CORS ошибка при попытке редиректа на внешний адрес в методе ModalToggle или Button

### ISSUE THREAD

**Issue by CodingJediKnight** [orchidsoftware/platform#971]
**Describe the bug**
После обновы не могу сделать внешний редирект (`return redirect()->away(...)`) в методе модалки( Пробовал и ModalToggle и Button

**Expected behavior**
Редирект на внешний адрес

**Screenshots**
![image](https://user-images.githubusercontent.com/13077787/65674644-9f3e1a00-e055-11e9-8935-54ffc61a7698.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Latest

**Server (please complete the following information):**
  - Platfrom Version: [e.g. 5.6.3]
  - Laravel Version: 6.0.1
  - PHP Version:  7.3
  - Database:  MySql
  - Database Version:  8

**Comment by tabuna** [comment]
Это проблема возникла из-за использования повсеместного `Ajax`. 
В отправке форм и переходе по ссылкам.

Исправление полностью и без создания новых проблем, может быть очень проблематичным. Например, так же не работает и скачивание файлов с использованием формы.

В теории таких мест не должно быть много, поэтому, предлагаю добавить метод ко всем Actions, который бы отвечал, за отключением `js` обработки.

например:

```php
Button::make('Сказать отчёт')
    ->method('print')
    ->rawRequest();
```


Что вы об этом думаете?

**Comment by tabuna** [comment]
С версии 6.2 добавился метод “rawClick” который отключает обработчики и пример выше - работатает.
