### ISSUE TITLE
Пакет создания форм ОрхидСофтвер

### ISSUE THREAD

**Issue by Hrache** [orchidsoftware/platform#973]
А есть ли у вас отдельный пакет для композера создания форм Орхида ?
Спасибо за внимание.

**Comment by tabuna** [comment]
Hey. You kind of used English.

У нас есть строитель форм, уже внутри основного пакета, пример его работы:

```php
$fields = [
    Input::make('name')->prefix('one'),
    Input::make('name')->prefix('two'),
    Input::make('name')->prefix('three'),
];

$data = new Repository(['name' => 'Alexandr']); 
$builder = new Builder($fields, $data);

$form = $builder->generateForm();
```

**Comment by Hrache** [comment]
Ну прекрасно. Сейчас же попробую. Мне просто очень понравился форм билдер от лакме, потому-что существующие как-то не понятно, что в них есть существенного, а у орхида очень фруктого. У меня в основном база данных, надеюсь все получится. Куль
