### ISSUE TITLE
Вопрос об элементах меню Menu::MAIN

### ISSUE THREAD

**Issue by Hrache** [orchidsoftware/platform#974]
В документации не смог найти подробную информацыю про элементы меню у которых есть ребетишки, то есть про дроп-дауны. У меня такая ситуацыя, когда мне нужно 3 разных таких дроп-даунов с двумя под элементами с разными раутами, но ничего не выходит:

```php
    // Main
    $this->dashboard->menu
      ->add(Menu::MAIN,
        ItemMenu::label('Articles')
          ->slug('articles')
          ->icon('icon-bag')
          ->childs()
      )
      ->add('articles', // slug of the parent
        ItemMenu::label('All articles')->route('platform.articles.list')
      )
      ->add('articles',
        ItemMenu::label('Create one')->route('platform.article.edit')
      );

    $this->dashboard->menu
      ->add(Menu::MAIN,
        ItemMenu::label('Websites')
          ->slug('websites')
          ->icon('icon-bag')
          ->childs()
      )
      ->add('websites', // slug of the parent
        ItemMenu::label('All websites')->route('platform.websites.list')
      )
      ->add('websites',
        ItemMenu::label('Create one')->route('platform.website.edit')
      );

    $this->dashboard->menu
      ->add(Menu::MAIN,
        ItemMenu::label('Comments')
          ->slug('comments')
          ->icon('icon-bag')
          ->childs()
      )
      ->add('comments', // slug of the parent
        ItemMenu::label('All comments')->route('platform.comments.list')
      )
      ->add('comments',
        ItemMenu::label('Create one')->route('platform.comment.edit')
      );
```

https://ibb.co/7WGqvHG

**Comment by tabuna** [comment]
```php
// Main
$this->dashboard->menu
->add(Menu::MAIN,
    ItemMenu::label('Articles')
        ->slug('articles')
        ->icon('icon-bag')
        ->childs()
)
// slug of the parent
->add('articles',
    ItemMenu::label('All articles')
        ->route('platform.articles.list')
)
->add('articles',
    ItemMenu::label('Create one')
        ->slug('create_articles')
        ->route('platform.article.edit')
)->add(Menu::MAIN,
    ItemMenu::label('Websites')
        ->slug('websites')
        ->icon('icon-bag')
        ->childs()
// slug of the parent
)->add('websites',
    ItemMenu::label('All websites')
        ->route('platform.websites.list')
)
->add('websites',
    ItemMenu::label('Create one')
        ->slug('create_website')
        ->route('platform.website.edit')
)->add(Menu::MAIN,
    ItemMenu::label('Comments')
        ->slug('comments')
        ->icon('icon-bag')
        ->childs()
)
// slug of the parent
->add('comments',
    ItemMenu::label('All comments')
        ->route('platform.comments.list')
)
->add('comments',
    ItemMenu::label('Create one')
        ->slug('create_comments')
        ->route('platform.comment.edit')
);
```

**Comment by Hrache** [comment]
No problem, lets on English no difference, cheers ?

and what I did miss in the code, what is the principle of the d-d menus in the orchid, what should be different to make it work, I thought we have quite differences and the slug must appear on the top level element only ?

Thanks ...

**Comment by tabuna** [comment]
Menu items are linear, and their dependency is built dynamically. In order not to indicate uniqueness each time with the help of the `slug` method, it also costs by its name.

That is, there are no elements of the upper or lower level until the builder is called.
Is this a problem for you? Need more info? Do not be shy

**Comment by Hrache** [comment]
Actually I don't shy, I want to be brief. It is actually hard to describe, but I'm about all combinations of the usage of the lets say components in the Orchid, that it was easy to memorize, because we are human beings we are not perfect and the thing we create should be maximal intuitive. As you may noticed few times I was caught on bad intuition and it played negatively on my time am I wrong there, or my intuition is not very good, or it is because of laravel, but I think it is alright,, Orchid is on development whole the time, and nice documentation will be quite exact think, and of course big expectations are always present, such the FormBuilder is, you know if it is nice package then why not universal sub packs for the whole we-site ... and etc.

**Comment by tabuna** [comment]
You just need a little more time to feel at ease using this. As for the sub-packages, we did it 2 years ago and this affected the development very badly.
