### ISSUE TITLE
Form render from view

### ISSUE THREAD

**Issue by vdf89** [orchidsoftware/platform#976]
Hello!

**Describe the bug**
If I put a form in a view, it will be automatically removed. If I put several forms in a view, only the first one will be automatically removed, the others remain.

**To Reproduce**

  1. Create a table (Orchid\Screen\Layouts\Table)
  2. With a TD component, use the function render() and return a view, like this:
`TD::set('actions', 'Actions')
                ->render(function($event) {
                    return view('orchid.tables.actions')
                })
`
  3. In the view, add one or more forms (<form></form>)

**Expected behavior**
All the HTML elements <form> should be present in the final HTML code (they are all available only in the source code, but in the inspector of the browser the first one is removed).

**Comment by tabuna** [comment]
The table is already in the form elemen.

```html
<form ...>
   <!-- ...code...-->
        <table class="Your table">
                 <!-- ...Your code...-->
        </table>
  <!-- ...code...-->
</form
```

It turns out that you want to add several forms to the form. 
This is redundant. You do not need to specify forms in your presentation.

You can add fields (Orchid\Screen\Fields) or buttons (Orchid\Screen\Actions) and they will work.

**Comment by vdf89** [comment]
Ok, but I need to put an icon that if clicked it should send a DELETE request to a controller.
I need that for permitting the user to quickly delete a record by clicking an icon from the table.
I show you what I am doing with the attachment.
![Senza titolo](https://user-images.githubusercontent.com/55792791/65760842-06bf9c80-e11e-11e9-80f1-d1a0604695b4.jpg)
How can I do that?
Thanks.

**Comment by tabuna** [comment]
I do not have your example, for this I will show on a standard screen with a list of users:

![image](https://user-images.githubusercontent.com/5102591/65766999-40e86880-e135-11e9-8e6a-fb64660672ef.png)

code:
```php
TD::set('delete')->render(function (User $user) {
    return Button::make('')
        ->icon('icon-trash')
        ->parameters([
            'id' => $user->id
        ])
        ->method('delete')
        ->render();
}),
```

**Comment by vdf89** [comment]
Thank you very much, it works!

**Comment by vdf89** [comment]
Just one thing: is it possible to add a js confirmation on the click of the button?

**Comment by tabuna** [comment]
> Just one thing: is it possible to add a js confirmation on the click of the button?

```php
TD::set('delete')->render(function (User $user) {
    return Button::make('')
        ->icon('icon-trash')
        ->parameters([
            'id' => $user->id
        ])
        ->confirm('Are you sure you want to delete?')
        ->method('delete')
        ->render();
}),
```

**Comment by vdf89** [comment]
Thank you! I didn't notice of the confirm() method because the documentation is not update: https://orchid.software/en/docs/field/#buttonlink
