### ISSUE TITLE
Different text and value pairs for the select element

### ISSUE THREAD

**Issue by Hrache** [orchidsoftware/platform#980]
Hi there, this is me again and this time I'm wondering to know how to create select form element that was kind of a **fromModel select** and kept the **PRIMARY KEY id** of the table as a value and some table related **title** column as a node text :)?
    Thank you for your attention ...

**Comment by tabuna** [comment]
Have you looked at all the arguments of the method `->fromModel` ?

**Comment by Hrache** [comment]
There are three only in maximum case the Model class, the model value-column, and some 'uuid' in the example which I couldn't turn into a result, maybe it is it ?

**Comment by tabuna** [comment]
Could you figure it out?

**Comment by Hrache** [comment]
Yes, of course,

**Comment by Hrache** [comment]
I can provide some info if you need :)

**Comment by tabuna** [comment]
Usually people write decisions when they find the answer to their question.  In order for the next one to be already

**Comment by Hrache** [comment]
```
Relation::make('foreign_key_table.column')
        ->required()
        ->fromModel(Mother_table::class, 'mother_table_visual_column', 'mother_table_foreign_column')
        ->title('Website')
```
    The third argument name is key, but not foreign_key (e.g.), besides it has no description in the documentation, that is why I didn't guess that there should be the foreign key.
