### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by Hrache** [orchidsoftware/platform#981]
![orchid-sort-issue](https://user-images.githubusercontent.com/49149161/65976333-06f2cb80-e481-11e9-96e0-6ea12fe134a2.gif)

What can be the problem here ?

**Comment by tabuna** [comment]
You have added to your model:

```php
use Filterable;

/**
 * @var
 */
protected $allowedSorts = [
    'id',
    'rank'
];
```

Are you calling him?

```php
Post::filters()->paginate();
```

More details: https://orchid.software/en/docs/filters/#automatic-http-filtering-and-sorting

**Comment by tabuna** [comment]
> So basically ::filters() adds js functionality, right?

No. It only adds url reactions:

```php
http://example.com/demo?filter[id]=1
$model->where('id', '=', 1)

http://example.com/demo?filter[id]=1,2,3,4,5
$model->whereIn('id', [1,2,3,4,5]);

http://example.com/demo?filter[content.ru.name]=dwqdwq
$model->where('content->ru->name', '=', 'dwqdwq');
```

JS processing adds already an indication in the table:

```php
TD::set('rank')->sort();
```
