### ISSUE TITLE
removeMaskOnSubmit dont work

### ISSUE THREAD

**Issue by Leshkens** [orchidsoftware/platform#982]
При отправке инпута с маской и параметром removeMaskOnSubmit маска после сабмита не удаляется. Когда-то уже [была подобная проблема ](https://t.me/orchid_russian_community/12688), но тогда после обновления страницы маска работала корректно, сейчас же работает после возврата назад (без обновления страницы) и повторной отправки.

### Пример:
![uFY2mPqXSQ](https://user-images.githubusercontent.com/8939383/66006142-1563d600-e4c7-11e9-8f8b-f60748d4f942.gif)

### Пример поля:

```
Input::make('phone')
    ->type('text')
    ->mask([
        'mask' => '(999) 999-9999',
        'removeMaskOnSubmit' => true
    ])
    ->title('Phone')
    ->help('Number Phone'),
```

Браузер: Хром 77
Орчид: 6.2.0

**Comment by tabuna** [comment]
Привет @Leshkens 

Да, проблема уже была в #783 
Тогда мы решили её с помощью добавления `setTimeout` и видимо  это больше не работает. 

Я попробовал увеличить ожидание, но это не дало результатов сразу. 
Автор библиотеки говорит, что этот метод не создан для AJAX вызовов: https://github.com/RobinHerbots/Inputmask/issues/1394#issuecomment-260589312

Ни один его совет пока не помог добиться каких либо результатов.

**Comment by Leshkens** [comment]
Привет! @tabuna 

Что насчетg такого решения? (Временного?)

### Orchid\Screen\Fields\Input

```
    public static function make(string $name = null): self
    {
        $input = (new static())->name($name);

        $input->addBeforeRender(function () {
            $mask = $this->get('mask');

            if (is_array($mask)) {
                $this->set('mask', json_encode($mask));

                if (isset($mask['removeMaskOnSubmit'])) {
                    $this->set('remove-mask-on-submit', json_encode($mask['removeMaskOnSubmit']));
                }

            }
        });

        return $input;
    }
```

### input_controller.js

```
connect() {
        const element = this.element.querySelector('input');
        let mask = this.data.get('mask');
        let removeMaskOnSubmit = element.getAttribute('remove-mask-on-submit');

        try {
            mask = JSON.parse(mask);
            removeMaskOnSubmit = JSON.parse(removeMaskOnSubmit);
        } catch (e) {
            // default
        }

        if (mask != '') {
          Inputmask(mask).mask(element);
        }

        if (removeMaskOnSubmit) {
            this.element.closest('form').addEventListener('submit', () => {
                Inputmask.remove(element);
            })
        }

    }
```

Хотя, возможно, лучше искать и выбирать нужные инпуты в form_controller.js

**Comment by tabuna** [comment]
Хм, если это работает, то мы можем просто добавить:

```javascript
this.element.closest('form').addEventListener('submit', () => {
    Inputmask.remove(element);
})
```
Тогда маска будет всегда удалена так?

**Comment by Leshkens** [comment]
> Тогда маска будет всегда удалена так?

Удаляется сразу же после нажатия на баттон (срабатывания события сабмит)

> Часть, что на php мы можем не указывать и взять уже из объекта на js

Угу, сделал так:

![LVHF664Y6i](https://user-images.githubusercontent.com/8939383/66046188-acb84000-e53e-11e9-98f4-266487120aa7.gif)

Надо конечно тестить, но пока не вижу сценириев, чтобы работало что-то не так

**Comment by Leshkens** [comment]
Хотя, хм, есть какой-то случай, когда не удаляется. Еще поковыряю

**Comment by Leshkens** [comment]
Есть есть еще параметр `autoUnmask `в `true`, то удаляется через раз. Не знаю, насколько это критично.

**Comment by tabuna** [comment]
> Есть есть еще параметр autoUnmask в true, то удаляется через раз. Не знаю, насколько это критично.

Эм, а разве `autoUnmask` это не устаревший вариант `removeMaskOnSubmit` ?

**Comment by Leshkens** [comment]
В [документации](https://github.com/RobinHerbots/Inputmask/tree/4.x#autounmask) есть и тот и тот параметр.

> ### autoUnmask
> Automatically unmask the value when retrieved.
> Default: false.
> 
> When setting this option to true the plugin also expects the initial value from the server to be unmasked.

Я так понял он снимает маску при получении значения в форму.

**Comment by Leshkens** [comment]
Если это так, то сценарий когда нужно изначальное значение с маской получить в форме без маски, при этом применить в форме маску и отправить его без маски :D Выглядит довольно странным. Возможно эти параметры изначально друг с другому не ладят.

**Comment by tabuna** [comment]
Опубликован в 6.3.0

**Comment by Leshkens** [comment]
Теперь есть проблема, если есть поле required, то маска удаляется все равно (т.к сабмит срабатывает).

### Пример:
![3U2smtNFbp](https://user-images.githubusercontent.com/8939383/66659739-7759d380-ec5d-11e9-8436-b54d98a73ac7.gif)

**Comment by Leshkens** [comment]
Я так понимаю, достаточно будет сделать проверку `reportValidity()` у формы:

```
        if (mask.removeMaskOnSubmit) {
            this.element.closest('form').addEventListener('submit', () => {
                if (this.element.closest('form').reportValidity()) {
                  Inputmask.remove(element);
                }
            })
        }
```

**Comment by tabuna** [comment]
> Я так понимаю, достаточно будет сделать проверку reportValidity() у формы:

У нас есть метод `novalidate`

```php
Button::make('Remove')
    ->method('remove')
    ->novalidate()
    ->icon('icon-trash');
``` 

Будет ли это работать?

**Comment by tabuna** [comment]
У меня есть предложение, может стоит добавить собственное событие при отправки формы и слушать его?

**Comment by Leshkens** [comment]
> Будет ли это работать?

С `novalidate()` не работает, действительно. Т.к `reportValidity()` при `false` генерирует дочерним элементам событие `invalid`.

> У меня есть предложение, может стоит добавить собственное событие при отправки формы и слушать его?

Да, скорее всего это лучший вариант.

**Comment by tabuna** [comment]
Проверь пожалуйста последний релиз

**Comment by Leshkens** [comment]
> Проверь пожалуйста последний релиз

При обычных переходах маска не удаляется (событие не генерируется?). Удаляется только после принудительной перезагрузки страницы. Видимо как-то с турболинком опять связано.

### Пример: 

![54wWHvXkPW](https://user-images.githubusercontent.com/8939383/66732386-320fee80-ee75-11e9-8519-f747896adb72.gif)

**Comment by Leshkens** [comment]
Если обернуть в `setTimeout()`:
```
        setTimeout(() => {
            const screenEventSubmit = new Event('orchid:screen-submit', {bubbles: false, cancelable: true});
            event.target.dispatchEvent(screenEventSubmit);
        })
```
то все с точностью наоборот. При обычных переходах маска удаляется, при перезагрузке страницы нет.

**Comment by funtom48** [comment]
@tabuna немного потыкав в дебаггер, обнаружил следующее. 
Передача в options input mask-a параметра removeMaskOnSubmit и вызов remove - ломает все. 

При submit формы
 выполнялось следующее: 

`
if (opts.removeMaskOnSubmit) {
                    el.inputmask._valueSet(el.inputmask.unmaskedvalue(), true);
                    setTimeout(function() {
                        writeBuffer(el, getBuffer());
                    }, 0);
                }
`

writeBuffer(el, getBuffer()) вызывался уже после вызванного remove. что ломало все и вся (в консоли ошибка была)

Есть ощущение, что дальше все шло не так из-за этой ошибки. 

P.S.: Далее, при повторном .mask() в writeBuffer input === undefined (почему то) и все шло не так как надо (но могу ошибаться, что из-за этого)



Сейчас я сделал **воттаквот**

не передаю opts.removeMaskOnSubmit. 
сделал autoUnmask: mask.autoUnmask || mask.removeMaskOnSubmit || undefined 
если opts.removeMaskOnSubmit - при нашем сабмите удаляем маску. маска при этом очищается.
в следующий коннект инициализячим ее снова. Ошибок нет. 


Проверьте плз все ли так

#994

**Comment by tabuna** [comment]
@funtom48 Нет не всё в порядке, реализация предполагает, что входным аргументов всегда будет json, что не всегда верно и при таком варианте работать не будет:

```php
Input::make('phone')
    ->type('text')
    ->mask('(999) 999-9999')
    ->title('Phone')
    ->help('Number Phone');
```
