### ISSUE TITLE
Aliases for values in filters

### ISSUE THREAD

**Issue by Leshkens** [orchidsoftware/platform#983]
Обсуждение: [979](https://github.com/orchidsoftware/platform/pull/979)

**Comment by tabuna** [comment]
Думаю имеет смысл не усложнять и сделать, что то вроде:

```php
 /**
  * @return array|string|null
  */
public function alias()
{
      return null;
}
```

Для того, что бы не ломать совместимость с предыдущими версиями по умолчанию, метод возвращает `null`, но так же может `string/array` для отображения. При этом принимает объект `Request`. Тогда изначальный пример мог бы выглядеть примерно так:

```php
/**
 * Human status order
 */
const STATUS  = [
    0 => 'cancelled',
    1 => 'processing',
    2 => 'completed'
];

/**
 * @param Request $request
 *
 * @return string|array|null
 */
public function alias(Request $request)
{
    $code = $request->get('status');

    return self::STATUS[$code];
}
```

Нет нужны подстраиваться, под модели или под конкретные запросы, так как аргументов может быть несколько:

```php
/**
 * @var array
 */
public $parameters = [
    'status',
    'owner',
];
```

 и т.п. при этом они могут быть. @Leshkens Что вы об этом думаете?

**Comment by Leshkens** [comment]
Выглядит неплохо :+1:
