### ISSUE TITLE
Create instances by Laravel service container (using app()->make instead of new $className).

### ISSUE THREAD

**Issue by likemusic** [orchidsoftware/platform#986]
**Describe the bug**
Impossible to inject dependencies by constructor for classes inherited from Orchid classes (for example child class for ListLayout) .

```
Too few arguments to function App\Orchid\Layouts\Product\ProductListLayout::__construct(), 0 passed in /usr/share/nginx/html/vendor/orchid/platform/src/Screen/Layouts/Base.php on line 141 and exactly 1 expected (View: /usr/share/nginx/html/vendor/orchid/platform/resources/views/layouts/base.blade.php)
```

**To Reproduce**

  1. Create class like this:
```
class ProductListLayout extends ListLayout
{
    const DATA_KEY = 'products';

    public function __construct(RouteNameProvider $routeNameProvider)
    {
        parent::__construct($routeNameProvider);
    }
}
```
  1. Open page that used this layout.
 
**Expected behavior**
Page opened without errors. Constructor dependencies injected to class. 

**Additional context**
In my case problem in https://github.com/orchidsoftware/platform/blob/master/src/Screen/Layouts/Base.php#L152

```
 $layout = ! is_object($layout) ? new $layout() : $layout;
```

**Comment by tabuna** [comment]
Hi @likemusic 

I think this is not a bug. But I fully support the idea of doing this!

**Comment by likemusic** [comment]
@tabuna I love your so quick responses for any issues!

What about usage `new` in other places?

![image](https://user-images.githubusercontent.com/603401/66226026-8a5f2780-e6e2-11e9-8e93-6325ffb4c687.png)

**Comment by tabuna** [comment]
Can you help and make a list where this is really needed?

**Comment by likemusic** [comment]
Constructor injection may be needed in any class, i think.

**Comment by tabuna** [comment]
OK.  in that case I will see what can be done

**Comment by tabuna** [comment]
I added creation for filters and for a relationship class. 
Feel free to create a new issue if necessary.
