### ISSUE TITLE
RadioButton не отображает old() значение

### ISSUE THREAD

**Issue by Leshkens** [orchidsoftware/platform#990]
При ошибке валидации на стороне сервера, в радио-баттоне не отображается old() значение (то есть, нужный не становится checked) если в `RadioButtons::options()` в качестве ключей integer или string-числа. Если в качестве ключей делать любые другие строки, то все нормально.

### Пример:
![MKISBM9wBt](https://user-images.githubusercontent.com/8939383/66785046-8955a380-eef5-11e9-9421-e7059adaa227.gif)

### radioButton.blade.php

```
@component($typeForm,get_defined_vars())
    <div data-controller="fields--radiobutton">
        <div class="btn-group btn-group-toggle btn-block no-padder" data-toggle="buttons">

            @foreach($options as $key => $option)
                @php
                    $active = $key === ($value ?? null);
                @endphp

                <label class="btn btn-default @if($active) active @endif"
                       data-action="click->fields--radiobutton#checked"
                >
                    <input @include('platform::partials.fields.attributes', ['attributes' => $attributes])
                           @if($active) checked @endif
                            value="{{ $key }}"
                    >{{ $option }}</label>
            @endforeach
        </div>
    </div>
@endcomponent
```
Здесь  `$value` всегда преобразуется в строку, а т.к числовые строки в качестве ключей в массиве всегда приводятся к int, то в результате строгого сравнения  `$key === $value` получается этот баг.

Решение: преобразовывать `$key`  в `string` или использовать нестрогое сравнение.

  - Platfrom Version: 6.3.2

**Comment by tabuna** [comment]
Думаю мы должны сделать строгое текстовое сравнение

**Comment by tabuna** [comment]
@Leshkens Пожалуйста проверь `build` сборку. Это должно отлично работать сейчас.

**Comment by Leshkens** [comment]
> @Leshkens Пожалуйста проверь `build` сборку. Это должно отлично работать сейчас.

Вроде все хорошо
