### ISSUE TITLE
Migrations doesnt't work. 

### ISSUE THREAD

**Issue by YeisonHunt** [orchidsoftware/platform#992]
![image](https://user-images.githubusercontent.com/20606919/66938310-93b39280-f006-11e9-919b-14fa87d50062.png)

**Comment by tabuna** [comment]
Your database version does not support a JSON column, please update your database version or use an adapter. 

More:

- https://github.com/orchidsoftware/platform/issues/251
- https://github.com/orchidsoftware/platform/issues/643
- https://github.com/orchidsoftware/platform/issues/922
- https://github.com/orchidsoftware/platform/issues/946
- https://github.com/orchidsoftware/platform/issues/715#issuecomment-465271265
