### ISSUE TITLE
Auto Render for TD

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/platform#997]
**Is your feature request related to a problem? Please describe.**

The renderer of cells can take both view and string value.
Therefore, we should indicate forced rendering in our code:

```php
TD::set('id')
    ->render(function (User $user){
        return CheckBox::make('users[]')
            ->value($user->id)
            ->placeholder($user->getNameTitle())
            ->checked(false)
            ->render();
    });
```

**Describe the solution you'd like**
Offer to allow transfer without explicit conversion:

```php
TD::set('id')
    ->render(function (User $user){
        return CheckBox::make('users[]')
            ->value($user->id)
            ->placeholder($user->getNameTitle())
            ->checked(false);
    });
```

In theory, we can solve this at the TD level or by defining `_toString`

**Comment by 2kodes** [comment]
I am curious. Will this support other types of layouts as a return type or only form elements?

**Comment by tabuna** [comment]
Currently supported return of view object and string. Do you want some additional support?

**Comment by 2kodes** [comment]
yes like the row layouts and accordion layouts

**Comment by tabuna** [comment]
This is a bit more complicated, inside the value binders will not work from the table explicitly.
The builder may require the source itself, for example:

```php
TD::set('id')
    ->render(function (User $user) {
        return Layout::rows([
            Input::make('test1'),
            Input::make('test2'),
            Input::make('test3'),
        ])->build(new Repository());
    }),
```
It's hard for me to imagine what this is for, but it is possible through such a challenge.

**Comment by 2kodes** [comment]
interesting... i didnt know that was possible..
I think this will allow for more versatile layouts that do not have to use a custom view but can still utilize orchid's view classes

**Comment by tabuna** [comment]
I had no problems clearly requiring this.  But in custom view or methods / controllers you can use internal builder:

https://github.com/orchidsoftware/platform/issues/973#issuecomment-535467462

**Comment by 2kodes** [comment]
How would one set the source to the build function of the TD using the  method u showed?

**Comment by tabuna** [comment]
> How would one set the source to the build function of the TD using the method u showed?

For example, let's display the user's email address:

```php
TD::set('id')->render(function (User $user) {

    $field = Input::make('email')->prefix($user->id);

    $data = new Repository($user->toArray());
    $builder = new Builder([$field], $data);

    return $builder->generateForm();
}),
```
In this case, we used the form builder explicitly.
Previous case with layers:

```php
TD::set('id')->render(function (User $user) {

    $data = new Repository($user->toArray());

    $layouts = Layout::rows([
        Input::make('email')->prefix($user->id),
    ]);

    return $layouts->build($data);
}),
```

**Comment by 2kodes** [comment]
wow..I am impressed. Nice and clean code too. Will try and blog about this usage. 
Thanks for all the great work on Orchid. I hope more people discover and use it
